### ISSUE TITLE
[2.1.13] Uploads are only by entry number

### ISSUE THREAD

**Issue by djmitche** [geoffhumphrey/brewcompetitiononlineentry#1004]
Version: 2.1.13

Installation URL: http://thoroughbrews.org/kbotb1/

Is your installation hosted on brewcompetition.com or brewcomp.com? no

Description of Issue:

I have uploaded scoresheets, with filenames based on the six-digit judging number.  Per the instructions, *"Be named with a six (6) character judging number (e.g., 000012.pdf, 987654.pdf, 01-012.pdf, abc123.pdf. 123abc.pdf, etc.) that corresponds EXACTLY to the entry's judging number as stored in the system's database."*

After uploading, entrants have complained that they have the wrong scoresheets -- it seems that everyone is seeing a scoresheet for their entry number instead of judging number.

**Comment by geoffhumphrey** [comment]
If you utilized judging numbers as your means of identifying entries to judges, be sure that the "Scoresheet Upload File Names" setting in Website Preferences is 6-Character Judging Number. My suspicion is that yours is set to 6-Digit Entry Number.

**Comment by djmitche** [comment]
Oh.. why is that not on the screen where I upload the scoresheets?  Or at least some mention of it in the instructions?

**Comment by geoffhumphrey** [comment]
Most likely because I missed putting it there. Sometimes things fall through the cracks.
