### ISSUE TITLE
Enhancement: Hiding results in database

### ISSUE THREAD

**Issue by r3dunlop** [geoffhumphrey/brewcompetitiononlineentry#1007]
Version: 2.1.13

Installation URL: truebrewer.truegrist.ca

Is your installation hosted on brewcompetition.com or brewcomp.com? no

Description of Issue: I just discovered that if you have backend access to your competition website, you can **easily** sort out all of the information for a competition that an organizer may want hidden. For example, we host the software as a subdomain on our main website. If our club's webmaster is a judge for a competition and not an organizer, they still technically have access to all of the competition information that they should not have access to. I'm not sure how difficult it would be, but is there some way to obfuscate the results and entry information to a human looking at the DB? If not, does anyone have a suggestion to get around this other than "don't let your webmaster judge"?

**Comment by geoffhumphrey** [comment]
There is a way to obfuscate information in the DB, but not an easy one, and it would be pretty expensive on the server in terms of resource allocation. Not to mention that it would involve a hefty amount of coding to 1) obfuscate the information going into the database, and 2) "un-obfuscate" the information to then be displayed on screen. For functions on the Admin side, like viewing all entries, the resource allocation would severely increase response time.

Unfortunately, the best advice I have you already came up with - "don't let your webmaster judge." Provided you are concerned about total anonymity. Or, more simply, you can have a gentlemen's agreement with your webmaster to keep their hands out of the competition DB.

**Comment by r3dunlop** [comment]
Ok, that makes sense. Thanks for your response!
