### ISSUE TITLE
Enhancement: Increase Table number count high from 75 to 100

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1008]
Version: 2.1.14

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: We want to sort into Table boxes at login. To avoid confusion between the BJCP category number and the Table number, We want to start the table numbers at 51. We have 45 tables so we need table numbers to go higher than 75. Up to 100 or better would work. I can see the 75 value in judging_tables.admin.php at line 290. I have changed it to 100 and it at least shows up to table 100 in the Add a Table dialog. Not sure if there are other places to change but will update this request if I find other needed changes.

Thanks.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Yes, you've found the only place to change. For posterity's sake, here's code to change. 

In /admin/judging_tables.admin.php, the for loop statement on line 290 (v2.1.14) looks like this:
```
for($i=1; $i<=75; $i++) {
```
Change the statement to:
```
for($i=1; $i<=100; $i++) {
```
You can put any number you wish. 100 seems like a reasonable limit.
