### ISSUE TITLE
Upload Scoresheets (entry number)

### ISSUE THREAD

**Issue by admcpd** [geoffhumphrey/brewcompetitiononlineentry#1014]
Hello friend, I have a problem, I have updated the files of the subscribers (named according to the code of each subscriber), but the files do not appear for them to view or download. What do I have to do? Thank you.

**Comment by geoffhumphrey** [comment]
Hello! Be sure that your Scoresheet Upload File Names preference is set to the method you used to name the scoresheets (6 digit judging number or 6 digit entry number). 

Go to Admin > Preferences > Website Preferences to define your methodology.
