### ISSUE TITLE
Enhancement - Add LICENSE file

### ISSUE THREAD

**Issue by jonrhall** [geoffhumphrey/brewcompetitiononlineentry#1015]
Version: N/A
Installation URL: N/A
Is your installation hosted on brewcompetition.com or brewcomp.com? N/A
Description of Issue:
In the README for this project, it states:
> BCOE&M is free and open-source. Hundreds of competitions around the world have utilized BCOE&M since its first release back in 2009.

Would you be able to add a LICENSE file (either MIT/BSD, or some other standard), so that others can be feel more secure in using and modifying this package freely? Doing so in your Readme is admirable, but not legally binding, which is technically what makes a project open source in the first place.

More information here: 
https://opensource.org/licenses

**Comment by jonrhall** [comment]
As a quick follow-up, I bring this up because it's concerning to me that BCOE&M has a copyright notice in its footer:
[See image here](https://i.imgur.com/MWJCzHm.png)
Text:
> BCOE&M 2.1.14 Amateur Competition Edition ©2009-2018

Would it be possible to get some clarification of things here?

**Comment by geoffhumphrey** [comment]
The license can be viewed here: https://www.brewcompetition.com/license

There is a paragraph in the README file that says:
```
This software is free, open source, and is covered under the General Public
License (GPL) from the Open Source Initiative. Therefore, you are permitted to
download the full source code of the software for your own use and customize it
for your own purposes - see http://www.brewcompetition.com/license for more.
```

**Comment by jonrhall** [comment]
Thanks for the clarification Geoff!
