### ISSUE TITLE
2.1.14 - Lost admin privileges

### ISSUE THREAD

**Issue by ecomeaux** [geoffhumphrey/brewcompetitiononlineentry#1018]
Version: 2.1.14

Installation URL: https://bluffcitybrewers.brewcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? Yes

Description of Issue: Upon start of open registration, I had to recreate my profile and no longer have admin access. How do I restore admin privileges?

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Evan, I'm not entirely sure why your admin privs were changed. I have changed them back to top-level. Anyone with top-level admin privs is able to change another user's level, so maybe someone else did? I'll check in on any programming that changes user privs just in case.

**Comment by ecomeaux** [comment]
Thank you Geoff.

As the coordinator I am the top-level admin, but seems like when the system
purged for starting the new comp, my account was purged as well and I had
to created a new account and was not longer admin. How should I purge the
data from the past comp without losing my status?

Evan

**Comment by geoffhumphrey** [comment]
Ah, OK. I'll take a look at the code; that's definitely a bug. It should retain all user privs when performing a reset.

**Comment by geoffhumphrey** [comment]
You can purge entry data at the moment. User data I'd retain until I can isolate the buggy code.

**Comment by ecomeaux** [comment]
Hi Jeff,
Same problem again this year. My account was purged from the brewcomp site after I cleared previous comp info to start the new comp. Had to create my account from scratch & I no longer have admin privileges. Can you help me with this? Thanks!

**Comment by geoffhumphrey** [comment]
I cannot for the life of me fathom why this has happened - again. It seems that your installation is the only one experiencing this among the other 60+ ones on the hosted platform. In any case, I've updated your user status to top-level admin and will be investigating further the issue.

**Comment by graemecoates** [comment]
FWIW I saw this on an instance I host that purged it's DB on 2.1.18 - I
landed up having to truncate the user table and setup a user through the
dB...

Not sure what happened either....

**Comment by ecomeaux** [comment]
Thanks for the help! Somehow I got purged as well during the process.
