### ISSUE TITLE
2.1.14 Admin cannot edit own account info

### ISSUE THREAD

**Issue by oshc** [geoffhumphrey/brewcompetitiononlineentry#1022]
Version: 9th Annual Ocean State Homebrew Competition – BCOE&M 2.1.14 Hosted Amateur Competition Edition 2009-2019

Installation URL: https://oshc.brewcomp.com/

Is your installation hosted on brewcompetition.com or **brewcomp.com?**

Description of Issue: I did a reset of competition info. I still have admin privileges and can login under my account email address and password but cannot edit my own account information or add entries for myself. I can edit other peoples accounts though. I am presuming as a workaround I can create a temp account give it top level admin privileges, delete my current account and then recreate it.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Apologies for the late reply. I've been catching up from the holidays. This is a known issue that will be rectified with the next release.

I just checked your installation and it seems everything has been set up again and you're accepting account registrations. Please let me know if there's anything I can do on my end.
