### ISSUE TITLE
account lock out

### ISSUE THREAD

**Issue by huibertsp** [geoffhumphrey/brewcompetitiononlineentry#1024]
Version:  Scorpion Homebrew Competition – BCOE&M 2.1.14 Hosted Amateur Competition Edition 2009-2019

Installation URL: https://scorpion.brewcompetition.com/

Is your installation hosted on brewcompetition.com or brewcomp.com?

Description of Issue: I cleaned up the website to restart a new comp and my admin account was locked out: phuiberts@gmail.com I have no means to get to my website

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by huibertsp** [comment]
Please upgrade my phuiberts@gmail.com to admin again. I need to make some edits to the site

**Comment by geoffhumphrey** [comment]
No problem. Done. Apologies for the issues. The bug has been identified and corrected - the next version will have the update.

**Comment by huibertsp** [comment]
thank you sir, I am back in
