### ISSUE TITLE
website error "Unknown column 'brewerJudgeBOS' in 'field list'"

### ISSUE THREAD

**Issue by huibertsp** [geoffhumphrey/brewcompetitiononlineentry#1025]
when I go to my website:  https://scorpion.brewcompetition.com/ I get: ""
Version:

Installation URL: https://scorpion.brewcompetition.com

Is your installation hosted on brewcompetition.com or brewcomp.com?
hosten

Description of Issue:

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Are you still experiencing this issue? I was able to access and log into the installation this morning.

**Comment by huibertsp** [comment]
it was fixed few hours later
