### ISSUE TITLE
2.1.16  htaccess apache error after upgrade

### ISSUE THREAD

**Issue by LoganGoesPlaces** [geoffhumphrey/brewcompetitiononlineentry#1028]
Version:  
2.1.16

Installation URL: 
www.unyha.com/comp

Is your installation hosted on brewcompetition.com or brewcomp.com? 
no

Description of Issue:
I just upgraded from 2.1.14 to 2.1.16 and there was a change to htaccess that caused a 500 response and the following error:  
> Either all Options must start with + or -, or no Option may.

The issue was the minus (-) in the following options line 141:
>Options ExecCGI Includes IncludesNOEXEC SymLinksIfOwnerMatch -Indexes

Adding a plus(+) to the added options fixed the issue.

**Comment by LoganGoesPlaces** [comment]
Sorry, found the closed issue.

**Comment by geoffhumphrey** [comment]
Thanks for reporting @LoganGoesPlaces - I'll update the file with the fix for the next release.
