### ISSUE TITLE
2.1.14 - Unable to print Scoresheet labels

### ISSUE THREAD

**Issue by te4336** [geoffhumphrey/brewcompetitiononlineentry#1029]
Version: 2.1.14

Installation URL: http://www.kcbmcomp.com

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: When I click on letter or A4 to print scoresheet labels I get a http error 500. This didn't start until after we upgraded to 2.1.14

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by te4336** [comment]
Just checked most of the other forms and reports and everything works fine. Just the scoresheet labels that won't come up and that throws that error.

**Comment by brouse69** [comment]
I am having the same problems

**Comment by geoffhumphrey** [comment]
Hello @te4336 and @brouse69.

I cannot replicate this issue using version 2.1.17 - the latest version as of today. My suggestion would be to update to 2.1.17 - or, at the very least, replace the /output/labels.output.php file with the one packaged with 2.1.17.

That should alleviate the issue.

**Comment by te4336** [comment]
Thanks Geoff, on a side note is this sent through any type of testing or CI before the new releases are pushed out to make sure all functions are working before pushing a new release out via GA?

**Comment by geoffhumphrey** [comment]
No, unfortunately. It's generally just me making changes and testing in my local environment (Windows/Apache/MariaDB), and web hosting environment (Linux/Apache/MySQL).

**Comment by FDillon00** [comment]
I still have this issue on 2.1.17

**Comment by markalston** [comment]
I believe this error is triggered when using PHP 7.+

There is a bug (at least as far as php 7.x is concerned) in labels.output.php where on line 450 $cicrone is treated as a string and later on line 454 as an array.  

This same issue looks like it has been fixed elsewhere in the labels.output.php file as cicerone is explicitly set as an array in the other locations.
