### ISSUE TITLE
crash in between selecting being a judge and then the page coming up with style selecting

### ISSUE THREAD

**Issue by huibertsp** [geoffhumphrey/brewcompetitiononlineentry#1032]
Version:
https://scorpion.brewcompetition.com

Installation URL:https://scorpion.brewcompetition.com

Is your installation hosted on brewcompetition.com or brewcomp.com?

Description of Issue:
had a user report to me: "The sign up process sort of seems to crash in between selecting being a judge and then the page coming up with style selecting.
It seemed to work out though." 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
I could not replicate this in any of my test environments. Were there any further reports similar to this?

**Comment by huibertsp** [comment]
there were none, just close the ticket. thank you for looking in to this
