### ISSUE TITLE
2.1.15 -Getting error 500 always

### ISSUE THREAD

**Issue by jfreitasneto** [geoffhumphrey/brewcompetitiononlineentry#1034]
Version: 2.1.15

Installation URL: Xampp for MacOS

Is your installation hosted on brewcompetition.com or brewcomp.com?
No

Description of Issue:
I'd followed install steps but Always getting error 500. Install on folder /htdocs/bcoem2115. Trying to access using http://localhost:80/bcoem2115/ 

Is there a way to investigate? Enabling a more detailed log file? 

Thanks 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by jfreitasneto** [comment]
solved!

**Comment by geoffhumphrey** [comment]
Great! Would you mind replying with details how you solved the issue? Will be helpful for the future...
