### ISSUE TITLE
No changes, but blank page.

### ISSUE THREAD

**Issue by MarieAnnick** [geoffhumphrey/brewcompetitiononlineentry#1035]
Version: 2.1.14

Installation URL:
https://ehg.ca/abc

Is your installation hosted on brewcompetition.com or brewcomp.com?
No

Description of Issue:
I attempted to log in to make some updates for the next competition and no changes were made to the page since. The site was working the last time I used it back in October. Now I have the white page of death. 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @MarieAnnick,

Are you still experiencing this issue? In paths.php, if you change the DEBUG constant to TRUE, php's errors will be enabled and shown on screen. If you're still having this issue, please post back what errors are either on screen or in your server log files.

**Comment by MarieAnnick** [comment]
Thanks Geoff, that pointed me in the direction of the problem and resetting
mysql solved the problem. On an unrelated note, now that debugging is on,
I'm getting the message Warning: Base directory
/var/www/abc/classes/htmlpurifier/standalone/HTMLPurifier/DefinitionCache/Serializer
does not exist, please create or change using %Cache.SerializerPath in
/var/www/abc/classes/htmlpurifier/HTMLPurifier.standalone.php on line
15689. Since it isn't causing any issues (that I know of), is this
something I should fix?

Thanks again.

On Mon, Mar 4, 2019 at 1:56 PM Geoff Humphrey <notifications@github.com>
wrote:
>
> Hi @MarieAnnick,
>
> Are you still experiencing this issue? In paths.php, if you change the
DEBUG constant to TRUE, php's errors will be enabled and shown on screen.
If you're still having this issue, please post back what errors are either
on screen or in your server log files.

**Comment by geoffhumphrey** [comment]
Ignoring it should be fine. 

The easiest thing to do would be to make a sub-directory called Serializer in the /classes/htmlpurifier/standalone/HTMLPurifier/DefinitionCache/ directory. That should get rid of the annoying message.

**Comment by MarieAnnick** [comment]
Excellent. Thanks for your help.
