### ISSUE TITLE
Mead and Cider Judge designations do not included in All Participant export 

### ISSUE THREAD

**Issue by buergermeister75** [geoffhumphrey/brewcompetitiononlineentry#1036]
Version: 2.1.14

Installation URL: midwinterhbc.com

Is your installation hosted on brewcompetition.com or brewcomp.com? No.

Description of Issue: Mead Judge and Cider Judge designations are not included on the All Participants csv export. It would be good to include those as two in different fields / cells so folks like us who do their own Judge Name labels have options with mail merge logic. 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hey Bruce. No problem. I'll slate it in for the next version (current version is 2.1.16).

In the meantime, you can use the files in the attached zip to draw that data into the All Participants, Available Judges, and Assigned Judges csv downloads. This is safe for 2.1.14 and further.

There are three files that should be placed in the following folders:
- /includes/db/output_email_export.db.php
- /includes/db/output_participants_export.db.php
- /output/export.output.php

[mead_cider_judge_in_email_exports.zip](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/2928114/mead_cider_judge_in_email_exports.zip)
