### ISSUE TITLE
BCOE&M 2.1.15 - 1st ,2nd and 3rd place beers from every table showing up in BOS Pull Sheets Instead of only 1st Place Beer

### ISSUE THREAD

**Issue by waztros** [geoffhumphrey/brewcompetitiononlineentry#1037]
Version: 2.1.15

Installation URL: https://hvhb.brewcomp.com

Is your installation hosted on brewcompetition.com or brewcomp.com? Yes,  brewcomp.com

Description of Issue: For some reason when I am trying to get BOS pull sheets and Mats it is showing the 1st, 2nd and 3rd place beers going to BOS instead of just the 1st place beer from every table judged.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.
BCOE&M 2.1.15

**Comment by geoffhumphrey** [comment]
The number of places pulled by the pullsheet code depends upon the"BOS Method" defined for each style type. If you go to Admin > Competition Preparation > Style Types, you should see the number of BOS places defined for Beer, Mead, and Cider (or Mead/Cider if combined). 

If you'd like only 1st places to go to the BOS, and thus to pullsheets and mats, change the value to only 1st places.

**Comment by waztros** [comment]
Thanks for the quick response. I was expecting to see the setup in Admin->Preferences->Competition Organization. Thanks for clarifying this.  I got it now. Somehow those setting got changed but I don't know how.

**Comment by geoffhumphrey** [comment]
Agreed that the logical place for this is in Competition Organization preferences. It's on the list for the conversion planned for this fall.

**Comment by waztros** [comment]
Probably a separate bug but for some reason I can currently bring up the "Cider" BOS pull sheet and see the 1st and 2nd place entries that we have entered in so far but when I try to bring of the "Cider" BOS cup mats it does not show any entries. Not sure what is going on there
