### ISSUE TITLE
BCOE&M 2.1.15 - Cider BOS Mats are Blank

### ISSUE THREAD

**Issue by waztros** [geoffhumphrey/brewcompetitiononlineentry#1039]
Version: 
2.1.15

Installation URL:
https://hvhb.brewcomp.com

Is your installation hosted on brewcompetition.com or brewcomp.com?
Yes, brewcomp.com

Description of Issue:
The "BOS Pullsheets"->"Cider - Judging Numbers" shows the entries but not in the "BOS Cup Mats"->"Cider - Judging Numbers". The "Beer" ones are working fine so far. Not sure about the "Meads" yet because we have not entered them into the system.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hmm. That's a new one. Confirmed on your installation.

Let me dig into it and see what's happening.

**Comment by geoffhumphrey** [comment]
Found the issue. The scripting was only looking entries with judging numbers assigned that were integers only - not alphanumeric like your competition's. It's fixed now in your installation - that BOS mat is now being generated.

A fix will be in the next version as well.
