### ISSUE TITLE
[2.1.15] Unable to upload multiple scoresheets

### ISSUE THREAD

**Issue by nschaeffler** [geoffhumphrey/brewcompetitiononlineentry#1042]
Hello!

Version: 2.1.15

Installation URL: https://blitz.brewcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com?  brewcomp.com

Description of Issue:  Cannot upload multiple scoresheets at once.

If you go to Upload Scoresheets and Other Documents

Select Multiple file upload function and then drop a set of files onto the drop-and-drag target, the file icons will have an X over each of them indicating you cannot upload files of that type.

If you try to select from a file selection window, all pdf's are greyed out. Under Firefox, there is an option button. If you click this, a list of supported file types is displayed. pdf is not listed as a supported type of file, only image file formats (jpg, png, ..., etc). 

Under Chrome:
With drop-and-drag, still get an X over the file icons indicating you cannot upload files of that type.
Pdf's are again not selectable via dialog. If you switch filter to "All Files" and still does not work.

Individual pdf uploads work fine.

**Comment by waztros** [comment]
We are having a similar issue using the same version 2.1.15.
https://hvhb.brewcomp.com
The individual upload works maybe 10% of the time.
The multiple upload allows to select the PDF files if you change the extension type. Then it looks like it starts to upload the files but they just disappear with nothing actually being uploaded.
In addition, trying to delete a single upload does not actually delete anything.

**Comment by geoffhumphrey** [comment]
Let me look into this - it appears that the file types accepted have been changed in the dropzone plug-in that facilitates the multiple upload.

Since you're both using hosted accounts, please feel free to zip up all of your PDF files and send them over to me (prost@brewcompetition.com) and I'll upload them via FTP.

**Comment by nschaeffler** [comment]
Geoff,

Thanks for the offer to upload the files. We manually uploaded the files one at a time yesterday so that people would be able to get to them.

Cheers,
Norm Schaeffler
