### ISSUE TITLE
Homebrew Club List Update

### ISSUE THREAD

**Issue by Ravenstein589** [geoffhumphrey/brewcompetitiononlineentry#1044]
Version: 2.1.13

Installation URL: tto2019.rackers.org

Is your installation hosted on brewcompetition.com or brewcomp.com?
No

Description of Issue: This isn't a big deal, but I would like to remedy it at some point and for future builds and possibly the current installation.  The "Green Bay Rackers" are based out of Green Bay, WI.  We have contacted the BJCP about this issue but it goes unresolved.  We would like you to update the code to show that the Rackers are from Green Bay WI and not Kewaunee WI.

Thanks,
Neil Froelich
Organizer TTO 2019

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Sure thing. I'll make the update and it'll be available in the next commit and version. For now, you can simply open the /includes/constants.inc.php file in the text editor of your choice and do a find/replace.

Find: 
``Green Bay Rackers [Kewaunee, WI]``

Replace: 
``Green Bay Rackers [Green Bay, WI]``
