### ISSUE TITLE
Malformed code. 

### ISSUE THREAD

**Issue by FDillon00** [geoffhumphrey/brewcompetitiononlineentry#1045]
Looks like at & was used instead of a  * to comment out a line.

https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/265511c1b922bb0cfd5689bd49ae50fa01987dfa/site/config.php#L38

**Comment by FDillon00** [comment]
Additionally after correcting this line I get raw PHP code on all pages.  
IE: Index.php 
![screenshot](https://user-images.githubusercontent.com/5970995/54554715-1dbd4f00-4983-11e9-8416-d5ccab29ec2f.png)

I host this site. I did an upgrade from 2. 1.11 to 2.1.17
I see this after doing the upgrade to 2.1.17. I can dump my back up back into the directory on my host and it displays just fine. 
Addtionally after dumping in my backup to at least have a functioning site the main "home" doesn't maintain my login. I am logged in and can visit any other page and it will so my name and allow me to navigate my account specific items. However when I click "Home" it says "Log In" and doesn't have my account details. 
url: https://www.lawrencebrewers.org/competition/

This install (2.1.11) has issues with Edit Entry page being empty except for the top nav and title "Edit Entry" for only some users. It also has issue where the required information part of the edit entry form, for those that can see it, is not displaying for some BJCP styles (29 and 30) so those entries are un-completeable. 

So I attempted the upgrade, even thou our entry submission went live a couple days ago. 

I need Edit Entry to work. 
![image](https://user-images.githubusercontent.com/5970995/54555283-675a6980-4984-11e9-8bbb-90cdcbc1ae2b.png)

And required info sections of the form. 
![image](https://user-images.githubusercontent.com/5970995/54555405-ac7e9b80-4984-11e9-9807-f37c23ac7cb5.png)

**Comment by geoffhumphrey** [comment]
Hi @FDillon00 

In the paths.php file, change the the line ``define('DEBUG', FALSE);`` to ``define('DEBUG', TRUE);``

This will allow for php errors to be displayed. Or, check the error_log file in the same server folder you installed BCOE&M.

I've confirmed that the Edit Entry screen is blank. Enabling the errors to be shown on screen will help me help you to troubleshoot.

**Comment by geoffhumphrey** [comment]
As to the original post - since the line in question is within a comment block, php will ignore it and thus it does not affect functionality. It's merely format mistake which I'll correct and get into the next commit and release.

**Comment by FDillon00** [comment]
So turning DEBUG on with the 2.1.17 code?  Not sure how this will help as the php is being "compiled" at all. 

As a far as the black edit entry screen, this is only for some of my users and I am unable to recreate my self, I'll have to coordiate with them. 

I feel that 2.1.17 is my best choice but since Index.php, Entry.php... ect is displaying raw PHP I'm at a loose for what to do.

**Comment by geoffhumphrey** [comment]
Sorry, I was remiss to say that I looked at your installation and registered as a entrant. I do not see any raw php at all when accessing your site when using Chrome and/or Firefox. IE is squirrelly, so I highly suggest NOT using it, but I didn't get any raw php with it, either - despite using version 11 which is waaaay old.

What I did see, however, is that I'm not able to edit the dummy entry I added due to the "blank screen." 

In any case, if you're still getting raw php, I suggest clearing your cache and cookies, restarting your browser, and go from there. If you're still getting it, I'm not sure what the issue would be.

**Comment by FDillon00** [comment]
The raw php is when 2.1.17 code is in place per the upgrade instructions.

**Comment by geoffhumphrey** [comment]
Just noted that you reverted to 2.1.11 on the installation I accessed. Still turning on DEBUG will help in this regard.

Is there a sandbox install I can access?

**Comment by FDillon00** [comment]
No, but debug is now on. It seemed like arrays caused similar issues before, I'll look for brackets

**Comment by FDillon00** [comment]
Tried an install of 2.1.15 ... got a blank white page.
Revert back to 2.1.11
Get the following warnings on my edit page, which shows the form but not the required info parts. 

> Notice: A non well formed numeric value encountered in /homepages/28/d124131446/htdocs/competition/includes/db/styles_special.db.php on line 52

> Warning: Illegal string offset 'M2-C' in /homepages/28/d124131446/htdocs/competition/includes/db/styles_special.db.php on line 150

Warning: Illegal string offset 'M2-D' in /homepages/28/d124131446/htdocs/competition/includes/db/styles_special.db.php on line 150

Warning: Illegal string offset 'M2-E' in /homepages/28/d124131446/htdocs/competition/includes/db/styles_special.db.php on line 150

Warning: Illegal string offset 'M3-A' in /homepages/28/d124131446/htdocs/competition/includes/db/styles_special.db.php on line 150

Warning: Illegal string offset 'M3-B' in /homepages/28/d124131446/htdocs/competition/includes/db/styles_special.db.php on line 150

Warning: Illegal string offset 'M4-B' in /homepages/28/d124131446/htdocs/competition/includes/db/styles_special.db.php on line 150

Warning: Illegal string offset 'M4-C' in /homepages/28/d124131446/htdocs/competition/includes/db/styles_special.db.php on line 150

Warning: Illegal string offset 'C1-E' in /homepages/28/d124131446/htdocs/competition/includes/db/styles_special.db.php on line 300

Warning: Illegal string offset 'C2-A' in /homepages/28/d124131446/htdocs/competition/includes/db/styles_special.db.php on line 300

Warning: Illegal string offset 'C2-B' in /homepages/28/d124131446/htdocs/competition/includes/db/styles_special.db.php on line 300

Warning: Illegal string offset 'C2-E' in /homepages/28/d124131446/htdocs/competition/includes/db/styles_special.db.php on line 300

Warning: Illegal string offset 'C2-F' in /homepages/28/d124131446/htdocs/competition/includes/db/styles_special.db.php on line 300

Warning: Illegal string offset 'C2-D' in /homepages/28/d124131446/htdocs/competition/includes/db/styles_special.db.php on line 396

**Comment by FDillon00** [comment]
Got some that can see the empty Edit page. Error message. 
Fatal error: Uncaught Error: [] operator not supported for strings in /homepages/28/d124131446/htdocs/competition/sections/brew.sec.php:90 
Stack trace: #0 /homepages/28/d124131446/htdocs/competition/index.php(237): include() 
#1 {main} thrown in /homepages/28/d124131446/htdocs/competition/sections/brew.sec.phpon line 90

**Comment by FDillon00** [comment]
I have been able to get 2.1.12 installed and running.  Entry Edit is no longer blank and Required Info form parts now display. 
Free free to close this concerning config.php  issue.  It appears as if this release is where it was introduced.
