### ISSUE TITLE
Scoresheets not pairing

### ISSUE THREAD

**Issue by oshc** [geoffhumphrey/brewcompetitiononlineentry#1049]
Version: 9th Annual Ocean State Homebrew Competition – BCOE&M 2.1.17 Hosted Amateur Competition Edition 2009-2019

Installation URL: https://oshc.brewcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? brewcomp.com

Description of Issue:
We have scanned and uploaded all the scoresheets. The beer scoresheets are downlaodable with no issue. The Cider, Mead and Provisional scoresheets have an issue though - they are not pairing properly. They are titled correctly on my hard drive, i.e. M1-001 but when uploaded they change to m1-001. The capital letter changes to a lower case. I am thinking this is why they are not pairing properly.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hello @oshc - I've found the problem and have fixed it in your installation. Users should now be able to download the mead and cider scoresheets (those that start with an alpha character).

Other hosted sites will be updated in the next few days.

For self hosted sites, employ the following fix in the /sections/brewer_entries.sec.php, /admin/entries.admin.php, and the /admin judging_scores.admin.php files:

Find the line:
``$scoresheet_file_name_judging = $judging_number.".pdf"``

And replace with:
``$scoresheet_file_name_judging = strtolower($judging_number).".pdf"``

**Comment by geoffhumphrey** [comment]
Please note that this issue only applies to judging numbers that contain alpha characters.
