### ISSUE TITLE
2.1.17 - Incorrectly named columns in entry export

### ISSUE THREAD

**Issue by MarsMug** [geoffhumphrey/brewcompetitiononlineentry#1055]
Version:
2.1.17

Description of Issue:
In the All Entries Limited Data and All Entries Limited Data with Brewer Contact Info exports the columns usually called 'Entry Name' and 'Style' are both named 'Name'.

This is not the case with the All Entries All Data export.

**Comment by geoffhumphrey** [comment]
Confirmed. Thanks for your report. A fix for this issue is in the latest master commit will be in the next release.
