### ISSUE TITLE
fail to upload or list logos 2.1.16

### ISSUE THREAD

**Issue by mattwwatson** [geoffhumphrey/brewcompetitiononlineentry#1058]
Version:2.1.16

Installation URL:nswhomebrewing.org/state19

Is your installation hosted on brewcompetition.com or brewcomp.com?
no

Description of Issue:
Uploading of logos does not work - also can't see the list of uploaded logos (when I ftp one) either on the upload screen or the comp prefs/sponsor page - the list is empty. on the upload page the list is not even there. it's like there's an error in php before it gets to showing the list of logos.
I have another site innersydneybrewers.org/brew19 that is the same php version and packages and the same SW version yet it seems to work fine?!?

**Comment by geoffhumphrey** [comment]
This may be a php permission issue (php.ini should have `file_uploads = On`) and/or a chmod permission issue (755). 

Also, make sure the file types you are uploading are jpeg, jpg, gif, or png - I'm pretty sure you've done that, though.

**Comment by mattwwatson** [comment]
Any other ideas? I've got php_info that says file_uploads On, the
directories are actually 777 and the images are jpgs. Whe I hit a page that
needs to list the contents of the image dir, there is some sort of internal
error and the html is truncated at that point, so there is some sort of
problem even reading the dir. Could I be missing some sort of reuquired
package? Is there some way to get server side logging in the request to see
more of what might be going wrong?

Thanks,
Matt

**Comment by mattwwatson** [comment]
My bad - I didn't have the user_* directories on the server!!
