### ISSUE TITLE
"Print Current View" on Available Steward Page Doesn't Work

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#1062]
Version: 2.1.16

Installation URL: seasonal.gtabrews.ca (Self Hosted)

Description of Issue:

After pressing the "Print Current View" button one the Available Stewards page, there is no options like on the Available Judges page.

![image](https://user-images.githubusercontent.com/1551339/58436878-7d2b8f80-8095-11e9-9202-a533f8245c59.png)

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Confirmed in version 2.1.17.  Thanks for your report. A fix for this issue is in the latest commit and will be in the next release.
