### ISSUE TITLE
Issue with _SERVER['DOCUMENT_ROOT'] and unused config setting.

### ISSUE THREAD

**Issue by markalston** [geoffhumphrey/brewcompetitiononlineentry#1066]
We are having issues with sponsor logos in v2.1.17.  This is because we use an alias in our apache setup for our subdirectory and SERVER['DOCUMENT_ROOT'] points to the main document root and not the alias.

This is easly solved in the few places where SERVER['DOCUMENT_ROOT'] shows up by using the paths set in paths.php.

We simply changed sponsors.sec.php and sponsors.admin.php occurances of 
```
$_SERVER['DOCUMENT_ROOT'].$sub_directory.'/user_images/'
```
to 
```
USER_IMAGES
```
and everything worked great.  Seems like using the paths set in that file is a better approach regardless.

Also, there is a setting in config.php $server_root which is not used in any of the php code.  Not sure if  it was removed from the code at some point but it is  fairly confusing when trying to debug issues.  I think that it should be removed from the config file.

**Comment by geoffhumphrey** [comment]
Thanks for reporting @markalston. In the next version, this will be addressed.
