### ISSUE TITLE
Enhancement - Saving Scores

### ISSUE THREAD

**Issue by elronalds** [geoffhumphrey/brewcompetitiononlineentry#1068]
I think it would be great to improve the saving scores with the following changes.  I often fill out the scores as the competition is progressing so I can track the entries, monitor BOS and the overall progress of the competition.

- Have an option for saving the scores on each row instead of scrolling to the bottom.  You could also have an option to auto save the scores using an AJAX call.   Maybe a setting to disable this if it will cause issues.

- Add a screen that lists all tables and I can update the scores from there by searching for a judging number or a specific entry.

Cheers!

**Comment by jimmyorkin** [comment]
I'll add to this. We use barcodes extensively. It would be nice to have a screen similar to the login screen that would let you scan a pull sheet barcode into a judging number field and allow you to enter the score in a score field. It would require putting a barecode on the pullsheet that I played with before. And a new page for entering the scores.

**Comment by geoffhumphrey** [comment]
There are plans in the works to implement an AJAX solution. As of now, the plan is to automatically be save the score onblur (when clicking outside of the text box). Other AJAX-related saving features are also planned when updating data from lists that are potentially very long, such as the admin > entries list.

**Comment by geoffhumphrey** [comment]
Auto-save for score and entry-related updates will be implemented in the next version. See Issue #1070 for further information.
