### ISSUE TITLE
2.1.17 - Scores deleted when saving scores

### ISSUE THREAD

**Issue by elronalds** [geoffhumphrey/brewcompetitiononlineentry#1070]
When using the latest release I am finding that there is a serious bug when saving scores.  As scoresheets are completed we enter the average score into the system.  

So for a given table we are saving the some of the scores and then jumping over to another table to save some of those scores.  Several times yesterday during a comp. with 200+ beers the score entry pages was randomly deleting all the entered scores for a given table.  Sometimes it would just delete some of the scores.

Seems like a serious bug however I'm not sure what is causing it.

**Comment by geoffhumphrey** [comment]
Hi @elronalds - I'm not able to recreate the issue in any of my test environments. Are you still having this issue?

**Comment by elronalds** [comment]
@geoffhumphrey It was happening often on a very large competition that I run each year.  I also recall it occurring last year on an older version of the software.  This year we were running the latest release and it was still happening.

Basically we have over 200 entries across 6-7 tables.  So the tables are large with allot of entries.  As scoresheets are delivered to the data entry person, the table would be loaded and then that score updated.  So there would be allot of switching between tables and only updating some scores in the table.  I was the data entry person so I was saving the scores and they were disappearing.  This is done while the competition is running so that we can announce winners of the categories right at the conclusion of the judging.

I feel like the entry of scores could use an AJAX web request and only save the score for that row.  That would probably help with this issue.  Thoughts?

**Comment by jimmyorkin** [comment]
Could this be an issue where multiple people are entering scores at the same time?

**Comment by heneksj** [comment]
Sounds like a multiple people issue to me too.  Or someone forgetting to update the page.  Yes, only saving the row would probably solve the problem.  

We have that problem on sorting day, but not on comp day.  We would get the results from a table and one person would select the table and enter the results from that table only.  No one else would have any business being in that table.  

But I think I see what happens for you.  Someone is entering the scores on the main scores page, while someone else is entering scores for a particular table.  When someone saves the whole thing, after someone enters scores for one table, that would surely blow away scores.

**Comment by elronalds** [comment]
In my situation I was the only user accessing and entering the scores.  I was entering the scores as sheets arrived at my table, so I would be going in and out of each table very often to add 2-3 scores and then some would get deleted.

I feel like there needs to be some sort of AJAX that runs to auto-save each score as you enter them.  Maybe there could be a warning when updating or clearing an already entered score.

**Comment by geoffhumphrey** [comment]
For version 2.2.0, auto-saving of scores and associated data (mini-BOS, place awarded) as well as BOS scores and places will be implemented; thus not requiring the user to submit ALL of the entered scores from a that screen at once. 

![image](https://user-images.githubusercontent.com/5216502/102699647-8c3bda80-4203-11eb-8040-6ee02c390ccd.png)

Auto-save will likewise be implemented for Administration: Entries associated data (marking as paid or received, adding notes, entering a box location, entering a judging number).

![image](https://user-images.githubusercontent.com/5216502/102699730-3fa4cf00-4204-11eb-9432-8d605e383771.png)
