### ISSUE TITLE
2.1.17 Working Please Stand By Icon

### ISSUE THREAD

**Issue by MarieAnnick** [geoffhumphrey/brewcompetitiononlineentry#1075]
Version: 2.1.17

Installation URL: ehg.ca/abc

Is your installation hosted on brewcompetition.com or brewcomp.com? no

Description of Issue: 
"Working Please Stand By" fa and animation never goes away, even after the document has finished loading. 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
This is an annoyance - apologies for that! By default the "working" overlay disappears after 30 seconds. I've identified a few places where it should not appear (clicking info icons on entry lists, for one). If you would, please let me know where this is happening within the app so I can troubleshoot.

**Comment by MarieAnnick** [comment]
I've done a bit more poking around and it appears to be an issue limited to
certain browsers. In this case, Chromium 66.0.3359.181

There is no overlay, just the spinning icon in the top left corner.

**Comment by geoffhumphrey** [comment]
Hate to ask, but this may be a simple issue of browser caching of css and js files. Does holding your shift key down while refreshing the page and/or clearing cache and cookies make that go away? I'm sure you've thought of it, but I have start there.

**Comment by MarieAnnick** [comment]
Didn't check, unfortunately. I ran an update as I sent the last reply and
that appears to have solved the issue.
 Thanks.
