### ISSUE TITLE
quotation marks in beer names breaks name

### ISSUE THREAD

**Issue by macewank** [geoffhumphrey/brewcompetitiononlineentry#1076]
Version:  2.1.17

Installation URL: https://forwhatitswort.brewcomp.com

Is your installation hosted on brewcompetition.com or brewcomp.com? brewcomp.com

Description of Issue:  entrant submitted beer names that were wrapped in quotes.  the system allows this to happen, however, it does not recognize that the beer has a name and we were unable to mark as received until i went in and edited the quotes out.   It was registering the name as a single quotation mark "  instead of "Beer Name" IPA. 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Thanks for reporting. I'll make sure that quotations are sufficiently scrubbed or escaped in the next release.
