### ISSUE TITLE
2.1.17 - Issue with GoDaddy hosting on new version | Files Download.

### ISSUE THREAD

**Issue by tsukraw** [geoffhumphrey/brewcompetitiononlineentry#1079]
Version: 2.1.17

Installation URL: https://competition.blueoxbrewers.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: Working on loading the new version 2.1.17 on a new GoDaddy Linux Hosting.  After some debugging found that in .htaccess the line "AddHandler application/x-httpd-ea-php70 .php" was added in version 2.1.17.

If this line is present any page you navigate to will try to download vs displaying. 
If you null or remove the line from the .htaccess the pages display properly.

This line was not present in version 2.1.16 should be reviewed if it should maybe be removed?

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
That line was inadvertently (and unknowingly) added by my webhost to my test server's .htaccess file. Unfortunately, it made it into the release 2.1.17 package - it and other extraneous lines were subsequently removed with [this commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/a61b73667f3c6a9a7b29c7fbda123021366e9437#diff-8052c42ab3b8aa06a3f5f788a4ddccc2) and will not be in the next release. 

My advice would be to (obviously) remove the line as you have or replace your .htaccess file [with this one](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/.htaccess).
