### ISSUE TITLE
Viewing required info from Entries listing doesn't work

### ISSUE THREAD

**Issue by diatonic** [geoffhumphrey/brewcompetitiononlineentry#1083]
Version: 2.1.17

Installation URL: https://idbeer.org

Is your installation hosted on brewcompetition.com or brewcomp.com? no

Description of Issue: When viewing the entries list, clicking on the "i" icon to show required info overlays the screen with "Working Please Wait" and the page never recovers. It appears that the information loads behind the overlay but there is no way to hide to overlay at that point.

![issue1](https://user-images.githubusercontent.com/1490527/61997877-e6f7f380-b05c-11e9-8376-fbd9f344c1ff.png)
![issue2](https://user-images.githubusercontent.com/1490527/61997878-e6f7f380-b05c-11e9-972f-c5524ac0e5f6.png)

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @diatonic. This is a known issue and and it has been addressed in the latest commit. A fix will be in place in the next version.
