### ISSUE TITLE
v2.1.11: 404 for home page only. 

### ISSUE THREAD

**Issue by DanielHutt** [geoffhumphrey/brewcompetitiononlineentry#1087]
**Version**: 2.1.11
**Installation URL**: http://brewfest.daytondraft.org/
Is your installation hosted on brewcompetition.com or brewcomp.com? No, hosted on GoDaddy.

**Description of Issue**: 
The home page is throwing a 404 error. We were having troubles with every other page until today when I disabled the search engine friendly URL option. Now all the other navigation links work fine but our home page 404s. If you navigate to "http://brewfest.daytondraft.org/index.php" the URL seems correct. However, the "home" link does not work. Changing the htaccess file to include `RewriteBase brewfest` breaks the site. I can do some more experiments but I'm hitting a dead end.

I believe we are hosted in a subfolder (<root>/brewfest) but all the subfolder options seem to break our installations. I've commented out the `#RewriteBase [subfolder]` line. I also left the site/config.php line `$sub_directory = "";` as default. Changing either of these to include "brewfest" instead of nothing breaks the whole site.

**Comment by diatonic** [comment]
You're not hosted in a subfolder. That is used when the site is at http://example.com/subfolder/ as the root of your BCOE&M site.

I navigated around your site and everything seems to work fine. Links to the homepage don't throw any errors for me.

**Comment by DanielHutt** [comment]
Gotcha. We're good now. Not sure what was going on -- I think it just took a few minutes longer than expected to update fully.

**Comment by graemecoates** [comment]
Watch out for browser caching as well as any PHP opcache you may have in place. Sometimes forcing either cache to reload is required when changing something like this.

**Comment by DanielHutt** [comment]
I'm having this issue consistently now. 
Weirdly enough..
http://www.daytondraft.org/brewfest/ works fine
http://brewfest.daytondraft.org/ does not.

**Comment by DanielHutt** [comment]
Nevermind, it seems like posting about it makes the website fix itself.

**Comment by DanielHutt** [comment]
Alright, this issue has plagued my club long enough -- I think I have more information that might allow me to get some proper help from the community or maintainer. The software has proven super useful in pulling off both of these competitions every year but it's time for me to bust this issue.

First, we have two competitions with two separate installs into sub-folders.  They are sharing a mySQL instance. They are named **Brewfest** and **Saisonfest.** 

The layout of our files on the server are as follows:

Root | Saisonfest Folder
----- | -----------------
![image](https://user-images.githubusercontent.com/1548547/72466825-a8d7c300-37a7-11ea-8cd1-68abe8598809.png) | ![image](https://user-images.githubusercontent.com/1548547/72466948-ea686e00-37a7-11ea-88e0-bbf18cd098bd.png)


Second! We are using GoDaddy to host our install. We would like our users to be able to navigate to `saisonfest.daytondraft.org` to visit the Saisonfest website for registration\information. Here is what the subdomain configuration looks like. 
![image](https://user-images.githubusercontent.com/1548547/72467384-ca857a00-37a8-11ea-9c48-a79e19fbb8bf.png)

And finally, I've tried to update the config.php as well as I could! Here are the contents of the `config.php` file in the Saisonfest install.

```
<?php
$hostname = "Private?";
$username = "Private";
$password = "Private";
$database = "DraftBrewFest";
$database_port = ini_get('mysqli.default_port');
$connection = new mysqli($hostname, $username, $password, $database, $database_port);
mysqli_set_charset($connection,'utf8mb4');
mysqli_query($connection, "SET NAMES 'utf8mb4';");
mysqli_query($connection, "SET CHARACTER SET 'utf8mb4';");
mysqli_query($connection, "SET COLLATION_CONNECTION = 'utf8mb4_unicode_ci';");

$brewing = $connection;	 
$prefix = "saisonfest_";
$installation_id = "saisonfest";
$session_expire_after = 30;
$setup_free_access =  FALSE;
$sub_directory = "/saisonfest";

$base_url = "";
if ((!empty($_SERVER['HTTPS']) && ($_SERVER['HTTPS'] !== "off")) || ($_SERVER['SERVER_PORT'] == 443)) $base_url .= "https://";
else $base_url .= "http://";

$base_url .= $_SERVER['SERVER_NAME'].$sub_directory."/";
$server_root = $_SERVER['SUBDOMAIN_DOCUMENT_ROOT'];
?>
```


Have I missed something? Please help. This issue seems intermittent-ish, given my sporadic reopening of this issue. I have disabled SEF Urls, though enabling them doesn't seem to do anything.  Visiting `www.daytondraft.org` seems to have everything working, although it's fairly hard to verify that and not ideal (as we would like `saisonfest.daytondraft.org` to be the landing page. If that's not the case, I will concede to the technical issues and just remove the subdomain altogether.

Right now, `saisonfest.daytondraft.org` returns this error:
![image](https://user-images.githubusercontent.com/1548547/72467718-8cd52100-37a9-11ea-91c9-965bc5400093.png)

**Comment by DanielHutt** [comment]
I've changed sub_directory to just be empty instead of "/saisonfest" which still results in an error on the homepage.

I've noticed that various subpages (home/info/volunteers/register) return different URL styles (SEF vs not) so I've disabled that setting altogether. Visiting `saisonfest.daytondraft.org` throws an error but the rest of the pages seem fine.

The home page DOES get fixed if you visit `saisonfest.daytondraft.org/index.php`, but I was hoping to avoid putting index at the end...

**Comment by DanielHutt** [comment]
@geoffhumphrey Is there any chance you would have some insight on this issue? My club is trying to launch our competition and this is a big annoyance for all involved at this point.

**Comment by geoffhumphrey** [comment]
This may be a server setting issue. If you are running the site from an Apache server, make make sure that the following is included at the top of your .htaccess file:
```
DirectoryIndex index.php
```
This will change it from your web host's default setting (most likely default.htm or index.html or the like).

**Comment by DanielHutt** [comment]
We're hosting from GoDaddy at the moment -- here is the contents of my .htaccess file under the `/saisonfest` directory. 

```
# No indexing
IndexIgnore *

# Make sure index.php is the default page
DirectoryIndex index.php

RewriteEngine on
# Removed comment for readability on GitHub
# RewriteBase /[subfolder] 
RewriteRule ^$ index.php [L]
RewriteRule ^([A-Za-z0-9-]+)?$ index.php?section=$1 [L]
RewriteRule ^([A-Za-z0-9-]+)/([A-Za-z0-9-]+)/?$ index.php?section=$1&go=$2 [L]
RewriteRule ^([A-Za-z0-9-]+)/([A-Za-z0-9-]+)/([A-Za-z0-9-]+)/?$ index.php?section=$1&go=$2&action=$3 [L]
RewriteRule ^([A-Za-z0-9-]+)/([A-Za-z0-9-]+)/([A-Za-z0-9-]+)/([A-Za-z0-9-]+)/?$ index.php?section=$1&go=$2&action=$3&id=$4 [L]
RewriteRule ^.*user_docs/.*\.pdf$ - [F,NC,L]

# Custom error pages
ErrorDocument 404     /404.php
ErrorDocument 401     /401.php 
ErrorDocument 403     /403.php 
ErrorDocument 404     /404.php 
ErrorDocument 500     /500.html

```

**Comment by geoffhumphrey** [comment]
Ah, GoDaddy. They are their own kind of special. Your configuration looks correct to me.

My advice would be to contact GoDaddy and explain the issue.

**Comment by DanielHutt** [comment]
Thank you, I'll do just that. Sorry to directly tag you, I'm sure you're busy!

**Comment by r-squared** [comment]
@DanielHutt did you ever get a fix from GoDaddy? I'm on Ionos for hosting, but having the same issue with a site that is redirected from a /comp folder to comp.domain.

**Comment by DanielHutt** [comment]
> 
> 
> @DanielHutt did you ever get a fix from GoDaddy? I'm on Ionos for hosting, but having the same issue with a site that is redirected from a /comp folder to comp.domain.

It's been a while, but I'm fairly certain the fix on my end was to overwrite the .htaccess file in the root of the directory with the one in this repo. If that doesn't work, I can send the one I'm using to you because it might have to use the default GoDaddy one. I tried so many things that it's a bit of a blur.

**Comment by r-squared** [comment]
> > @DanielHutt did you ever get a fix from GoDaddy? I'm on Ionos for hosting, but having the same issue with a site that is redirected from a /comp folder to comp.domain.
> 
> @r-squared It's been a while, but I'm fairly certain the fix on my end was to overwrite the .htaccess file in the root of the directory with the one in this repo. If that doesn't work, I can send the one I'm using to you because it might have to use the default GoDaddy one. I tried so many things that it's a bit of a blur.

Thanks, I thought I was using the one from the repo, but I'll double check. If you can send what you've got as well, that would be great. My email is on my profile...

**Comment by r-squared** [comment]
After a bit of digging, and comparing the default .htaccess with the one provided by @DanielHutt (thank you!), the fix was as simple as adding "RewriteBase /" to the default file. 

In other words, without any RewriteBase set, the "RewriteRule ^$ index.php [L]" line does not seem to be applied, breaking the Home link when you are not using a subfolder. All other links (when SEF URLs is disabled) already include index.php, so they work correctly. Also, adding the RewriteBase allowed me to the turn on SEF URLs and those also work as intended now.

The default .htaccess suggests that the the RewriteBase rule is only needed when using a subfolder, but it appears that those instructions should likely be changed to always always uncomment that line, with details on how to modify that line for each of the two cases.
