### ISSUE TITLE
Data Exports: Emails (CSV): Assigned Judges/Stewards Should Only Include Email Addresses

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#1091]
Version:2.1.17

Installation URL: https://brewdrinkrepeat.com/valhalla

Is your installation hosted on brewcompetition.com or brewcomp.com? N

Description of Issue: This section of the data export section is titled "Emails (CSV)" but the resulting file includes a TON of data that is not needed or expected, and the file has to be reformatted in Excel just to get a list of email addresses.

IMO it would be much more useful to include ONLY email addresses, separated by commas (this is the format most email programs are expecting), so we could simply do a quick copy/paste to send a bulk email to all the judges, stewards, etc. like so:

email@address.com, email@address.com, email@address.com, email@address.com

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
@BrewDrinkRepeat, participant email addresses for are available in the format you specify here via a button/modal combination on the Admin > Participants screens - not via a CSV download. Simply select the button on the appropriate view and copy/paste the emails from the comma-separated list.

![image](https://user-images.githubusercontent.com/5216502/65897917-9ad37300-e36d-11e9-9559-5a083b35c048.png)

![image](https://user-images.githubusercontent.com/5216502/65897928-a0c95400-e36d-11e9-8c5a-caaa2c8152fa.png)

Available are:
- All Participant Email Addresses (Admin > Entries and Participants > Manage Participants)
- Participants with Entries Email Addresses (Admin > Entries and Participants > Manage Participants > Participants with Entries)
- Available Judges Email Addresses (Admin > Entries and Participants > Available Judges)
- Available Stewards Email Addresses (Admin > Entries and Participants > Available Stewards)
- Assigned Judges Email Addresses (Admin > Entries and Participants > Assign Judges)
- Assigned Stewards Email Addresses (Admin > Entries and Participants > Assign Stewards)
- Assigned Staff Email Addresses (Admin > Entries and Participants > Assign Staff)

**Comment by geoffhumphrey** [comment]
As far as the expectation that the Email Addresses CSV should only house email addresses, I see your point, but it is not a huge issue, IMHO, to remove the extraneous information via Excel or the like. I will update the label to read Email Addresses and Personal Info (or the like).

**Comment by BrewDrinkRepeat** [comment]
Ahhhh, I did not notice that. Sorry!  ;(

Thanks, as always, for getting back to us so quickly w/ questions, problems… and dumb suggestions!

B.
