### ISSUE TITLE
Multiple scoresheet uploads show checkmarks but no files display for users. When trying single file upload get error message.

### ISSUE THREAD

**Issue by stusiegel** [geoffhumphrey/brewcompetitiononlineentry#1097]
Version: BCOE&M 2.1.10 Amateur Competition Edition 2009-2019

Installation URL: https://azhomebrewers.org/brewcomp/index.php

Is your installation hosted on brewcompetition.com or brewcomp.com? brewcomp

Description of Issue:
On the Admin website page the setting for score sheet upload files is set to Judging Numbers. When I drag and drop the files onto the multiple file upload page each file gets a checkmark then disappears from the screen. When Users login they can't see any of their scoresheets. 
 
If I try to upload a file individually I get an error which states: There was an error. Please try again.

**Comment by stusiegel** [comment]
Our files are numbered like this: 000001.pdf, and 000188.pdf

**Comment by Simon-Haynes** [comment]
I also have this issue, what was the resolution?
