### ISSUE TITLE
Cannot access competition site

### ISSUE THREAD

**Issue by PeterSteinberg** [geoffhumphrey/brewcompetitiononlineentry#1100]
Version: hosted at mhtg.brewcompetition.com

Installation URL: mhtg.brewcompetition.com

Is your installation hosted on brewcompetition.com or brewcomp.com?

Description of Issue:

I've been unable to access any of the hosted sites on brewcompetition.com today, such as our competition mhtg.brewcompetition.com, as well as others that I've tried (becausebeercompetition.brewcompetition.com, yeastwranglers.brewcompetition.com, momashin.brewcompetition.com).

Our competition is coming up in a week and I need access to the data...

**Comment by geoffhumphrey** [comment]
@PeterSteinberg - I was able to access and log into each of the sites you listed. Perhaps the server was down, but I usually get alerts when that happens. I'd advice clearing your browser cache, etc. and trying again.
