### ISSUE TITLE
Enhancement --- Awards Ceremony

### ISSUE THREAD

**Issue by PeterSteinberg** [geoffhumphrey/brewcompetitiononlineentry#1105]
Version:  hsoted

Installation URL:  hosted

Is your installation hosted on brewcompetition.com or brewcomp.com?
  mhtg.brewcompetition.com

Description of Issue:
 If my competition does not have a formal awards ceremony I'd like the awards ceremony paragraph to not be displayed on the competition info page.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
In the current version, if you remove all text and information in all three of the Awards Ceremony related form fields, the section will not be displayed on the competition info page.

![image](https://user-images.githubusercontent.com/5216502/69175348-d0b8ec00-0ac0-11ea-89a1-0a8037fb3ab4.png)

**Comment by PeterSteinberg** [comment]
Thanks, that works.
  Peter
