### ISSUE TITLE
2.1.18 Export of "All Entries" csv does not include "Club" field/column

### ISSUE THREAD

**Issue by rgiaquinta** [geoffhumphrey/brewcompetitiononlineentry#1111]
Version:
2.1.18

Installation URL:
https://motownmash.brewcompetition.com/

Is your installation hosted on brewcompetition.com or brewcomp.com?
yes

Description of Issue:
Export of "All Entries" csv does not include "Club" field/column

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Thanks for your report, @rgiaquinta. A fix for this issue is now in the latest master commit and will be in the next release.
