### ISSUE TITLE
2.1.18 un-assigning judges does not remove them from the tables they are assigned to

### ISSUE THREAD

**Issue by heneksj** [geoffhumphrey/brewcompetitiononlineentry#1113]
Version:
2.1.18

Installation URL: https://turkeyshoot.brewcompetition.com/
Is your installation hosted on brewcompetition.com or brewcomp.com? Yes

Description of Issue:
A Judge tells me he can’t do session two, but I have already assigned him to table in the session, I remove session two from his profile.  But he still is counted there in the judge assignments—he shows up in the judge assignments by table view but is gone in the table assignments page and the judge assignments by name view.  So you can’t remove him at that point.  Now, its a pretty easy problem to solve.  All I got to do is put that session back in his profile, remove him from the table, then re-remove the session from his profile.  But it should have removed him from the assignment when I removed him from the session.  

I am going to call this a bug, but you could argue it is an enhancement.  

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Gotcha. And confirmed. 

I'll put this into the queue. Shouldn't be too difficult to implement as it's a simple check on the backend to delete all assignments for tables that fall into the session that the user isn't available for any longer.

**Comment by geoffhumphrey** [comment]
A fix for this will be in the next version and is available now in the latest master commit. 

When a user or admin changes a judge's or steward's availability for a particular judging session to "No," that judge/steward will likewise be removed from any table they are assigned to in that session. Saves the PITA procedure you outlined in your OP, @heneksj. 

Thanks for the heads up.
