### ISSUE TITLE
enhancement ability to remove extraneous information from entry form

### ISSUE THREAD

**Issue by heneksj** [geoffhumphrey/brewcompetitiononlineentry#1115]
Version:2.1.18 

Installation URL:
https://turkeyshoot.brewcompetition.com/

Is your installation hosted on brewcompetition.com or brewcomp.com?

Description of Issue:
We couldn't care less of the entries recipe.  I say that in the instructions, but some brewers spend a lot of time filling out that information, which we just throw out.  Worse, some might be temped to write in information that is required, instead of entering it online.  I would like to not have those fields even showing on the entry form.  

Also, its a minor point, but we really shouldn't see the item missing/see bottle labels/print buttons on the printed entry form.  

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
In Site Preferences, under the Entries subheading, you can determine whether to show the recipe entry fields or not when users are adding their entries online. However, it looks like your installation's preferences have those fields hidden, so I'm unclear what extraneous information beyond recipe you're referring to as far as the online presentation to users. 

If users are filling out the printed entry sheet by hand and you're throwing them away, my suggestion is not not even have the entry recipe printout be on option for users. You can do this by choosing one of the _Bottle Label Only_ options for the Printed Entry Form and/or Bottle Labels item in Site Preferences. Currently, there are seven options:

![image](https://user-images.githubusercontent.com/5216502/69091089-ce925700-0a06-11ea-82a1-f083bc060878.png)

**Comment by heneksj** [comment]
Ahh, thanks, I didn’t see that one.  That is something that I would have thought would be in the competition preparation section.  That website preferences section got me again this year for another reason. When setting all the dates in the competition preparation section, I apparently didn’t go to the website preference section and set the date/time when the results are to be released.  Actually I swear I did, but on comp day, the results were showing up on the web site, as soon as we put them in.  So when I realized that I had to find the field and fix the date before any BOS judges saw it—not that they really would, but it still was improper.  So I am going to put in an enhancement request that asks to put all that preparation/preference stuff together.  Hope you don’t think I am nit-picking too much.

**Comment by heneksj** [comment]
After reading your response more closely, I realize the problem was in what was printed, not online. I am not sure I want to do away with the entry forms entirely.  Maybe though, half the people don't give them to us anyway. The only reason to have them is when there is a check or cash with the entry, to help associated the money with the right person.  Would any of those other options print a form without the recipe stuff?

**Comment by geoffhumphrey** [comment]
Yes. The Simple Metric and Simple US will print an entry form without any lines for a recipe and bottle labels.

**Comment by geoffhumphrey** [comment]
As of 2.5.0 Beta, all recipe-related data fields have been removed from the add/edit entry function. All printed entry materials that reference recipe-related data have likewise been removed.
