### ISSUE TITLE
RequiredInfo Missing from Provisional Style Bottle Labels

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#1119]
Version: 2.1.18
Installation URL: brewslam.gtabrews.ca
Is your installation hosted on brewcompetition.com or brewcomp.com? Self Hosted
Description of Issue:

Hi @geoffhumphrey ,

During Brew Slam 2019 I noticed several new bugs with the "With Required Info - All Styles (Judging Numbers)" stickers. It's possible they are all related to a single root cause, but I'm creating 3 issues because they appear to be independent to me.

Issue 3)
RequiredInfo Missing from Provisional Style Bottle Labels

Entry Info in Software:
![image](https://user-images.githubusercontent.com/1551339/69101263-2ba10380-0a2d-11ea-9978-4520b8368820.png)

Generated Sticker:
![image](https://user-images.githubusercontent.com/1551339/69101292-407d9700-0a2d-11ea-88cb-15b81c093c93.png)

This sticker should have had a 2nd line containing the text:
lychee and passion fruit 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Thanks for your report. A fix for this issue is in the latest master commit and will be in the next release. Download and replace the /output/labels.output.php file in your installation to implement.
