### ISSUE TITLE
4th character (aka sub-sub style) of StyleID truncated from Bottle Label

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#1121]
Version: 2.1.18
Installation URL: brewslam.gtabrews.ca
Is your installation hosted on brewcompetition.com or brewcomp.com? Self Hosted
Description of Issue:

Hi @geoffhumphrey ,

During Brew Slam 2019 I noticed several new bugs with the "With Required Info - All Styles (Judging Numbers)" stickers. It's possible they are all related to a single root cause, but I'm creating 3 issues because they appear to be independent to me.

### Issue 1)
4th character (aka sub-sub style) of StyleID truncated from Bottle Label

This one is a bit harder to describe, but I attempted to summarize it with the subject. Essentially we have come to rely on the sub-sub-styleID Eg. 27B**7**, because we sometimes split those off into separate Medal Categories for judging. Luckily this wasn't a deal breaker since there is still English text with the sub-sub-style name, but it really caused a ton a confusion for sorting.

**Example 1)** 27A8: Pre-Prohibition Porter 
![image](https://user-images.githubusercontent.com/1551339/69103224-d667f080-0a32-11ea-8b3f-2d376c99c6c0.png)

Bottle Label says 27A: instead of 27A8:
![image](https://user-images.githubusercontent.com/1551339/69103256-eb448400-0a32-11ea-88ad-4e0a65298157.png)

**Example 2)** 21B7: New England IPA
![image](https://user-images.githubusercontent.com/1551339/69103487-83db0400-0a33-11ea-90dd-8a3dc54984b4.png)

Bottle Label says 21B: instead of 21B7:
![image](https://user-images.githubusercontent.com/1551339/69103508-8d646c00-0a33-11ea-8b7b-8b273aa31ae3.png)

Example 3) PRX4: Catharina Sour
![image](https://user-images.githubusercontent.com/1551339/69103551-a9680d80-0a33-11ea-950a-9ad89374cb2d.png)

Bottle Label says PRX: instead of PRX4:
![image](https://user-images.githubusercontent.com/1551339/69103587-cbfa2680-0a33-11ea-93a5-12fb96a5997d.png)

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Thanks for your report. A fix for this issue is in the latest master commit will be in the next release. Download and replace the /output/labels.output.php file in your installation to implement.
![image](https://user-images.githubusercontent.com/5216502/69664636-fe181380-1045-11ea-81e2-d5d07ae2047f.png)

**Comment by ercousin** [comment]
Thanks @geoffhumphrey the preview looks good!

Am I missing something? I don't see any commits since Sept 30th:

![image](https://user-images.githubusercontent.com/1551339/69778700-48e37980-1173-11ea-8350-a1e724384eef.png)
