### ISSUE TITLE
Enhancement - PayPal/Bitcoin donation to BCOE&M author

### ISSUE THREAD

**Issue by grmelacz** [geoffhumphrey/brewcompetitiononlineentry#1122]
Version: 2.1.18

Installation URL: https://soutez.mhmeeting.cz

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: I'd like to send some money we've earned on the competition to Geoff. Could you please provide either Donate button in the software or PayPal/Bitcoin address for a donation? Thanks

**Comment by geoffhumphrey** [comment]
Hello @grmelacz - thank you so much for the offer. And while I certainly don't expect it, I really do appreciate it. You can make your donation via the BCOE&M website at https://www.brewcompetition.com/donation with my sincere thanks.

**Comment by grmelacz** [comment]
Thanks, man. Donation sent. If you're ever in Czech, let me know so we can grab a beer together! Cheers.
