### ISSUE TITLE
Cider Judge label not displaying on Assign Participants as Judges page

### ISSUE THREAD

**Issue by buergermeister75** [geoffhumphrey/brewcompetitiononlineentry#1124]
Version: 2.1.18

Installation URL: https://midwinterhbc.com/competition/

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: Not seeing Certified Cider Judge on the Assigned Participants as Judges page. See attached screen shot. 
![screenshot](https://user-images.githubusercontent.com/15721040/70264086-5d200b80-175d-11ea-9a2a-6c7fbcf7d31e.png)

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Thanks for your report, Bruce. A fix for this issue is in the latest master commit and will be in the next release.
