### ISSUE TITLE
Email, QR, Shipping info issues with hosted BCOE&M 2.1.18

### ISSUE THREAD

**Issue by definiteopinions** [geoffhumphrey/brewcompetitiononlineentry#1125]
Version:  BCOE&M 2.1.18

Installation URL:  https://aotearoa.brewcompetition.com/

Is your installation hosted on brewcompetition.com or brewcomp.com?

Yes

Description of Issue:
Hi there, we found a few issues when doing a dry run to familiarise ourselves with the system:

1.  Confirmation emails, contact emails and password reset emails are not arriving.

2.  Can we change the packing and shipping information?  The USPS information is really not relevant in New Zealand, plus our postal service has different requirements.

3.  The QR code check-in isn't working properly:

    1. Scanning an entry QR code brings you to a login page.
    2. Inputting the correct QR login password just returns a slightly different login page, with a notification at the top saying "Password accepted".
    3. If you login with the qr password again without moving from the page, it allows you to check that entry in.
    4. It then drops you back into the initial login page, with a notification at the top saying "entry number XX is checked in".
    5. Scanning a new QR code sends you back to the initial login at 1, having to repeat the process.

We tested this on 3 different android phones, running chrome or firefox, using google lens and barcode scanner as QR reading apps, all had the same problem.  As far as I can tell the QR reader app is still running in the background, certainly no action has been taken to close them.

Thanks

**Comment by geoffhumphrey** [comment]
Hey there and thanks for reporting. I'm still testing and tracking down potential causes for 1 and 3 in your original post. The second issue has been taken care of for your installation.

For number 1, I've confirmed that emails are being sent via SMTP for the contact form. However, I have noted that confirmation emails are not being sent. I'm working toward rectifying that.

For number 2, I have confirmed that the QR code check-in process is working on iOS using the QR Scanner app version 0.6.4. I have not yet confirmed on Android, but my suggestion would be to try another QR scanning app and trying again.

**Comment by definiteopinions** [comment]
Hi, thanks for the prompt attention.

I tested the contact and password reset emails after you, they both seem to work now.  Haven't checked the confirmation email, so I'll take your word that they're not working.

Could we change the shipping information to the following please?

> 
> Tape the labels onto the bottles using clear packing tape, covering the label completely to prevent it being ripped.  Let your bottles come up to room temperature to help the tape stick.
> 
> Pack your bottles tightly in a sturdy box, line the box with a plastic bag to prevent leaks.  Roll each bottle in bubble wrap, fold the ends over and tape them down.  Put good padding between the bottles, and fill in the gaps at the top and bottom with crumpled paper or packing peanuts.  Tape the box along each edge, and that should do it.

For the QR issue, I tried another 2 android scanner apps in addition to the previous ones.  They behaved the same way, opening a link in the browser and encountering the same problem.  I got a friend with an iPhone to test it using the built-in reader for the camera app and the QR scanner app for iOS.  The same thing happened, except the URI was opened in Safari.

Cheers

**Comment by definiteopinions** [comment]
Hi Geoff, do you have any progress for us?  They're not game-breaking issues, but it would be convenient to be able to use it the way it was meant to be.

Cheers.

**Comment by geoffhumphrey** [comment]
@definiteopinions - checking back in on this issue as I've been diving back into past issues. I've noted that you've opened registration for 2020 - have you experienced the same email issues as described in your original post (emails not arriving)? I sent a message via the contact form at https://aotearoa.brewcompetition.com/index.php?section=contact and can confirm that I received a copy of it to my email, indicating to me that the email scripts are working. Hopefully, that's the case!

**Comment by geoffhumphrey** [comment]
Also, I can confirm that registration and password reset emails are sending - although the comp logo does not come through on the registration email. I'll investigate that.
