### ISSUE TITLE
Optional Info from an entry saves but does not retrieve

### ISSUE THREAD

**Issue by buergermeister75** [geoffhumphrey/brewcompetitiononlineentry#1126]
Version: 2.1.18

Installation URL: Midwinterhbc.com\competition

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: Add an entry for a Keller Bier 7C. Put some info in the Optional Info field and then hit save. Go back into the entry to edit after saving. You may quickly see the Optional Info appear for a split second and then the field appears to be blank. Looks like the info retrieves and then they system defaults blank out the field. Registration is now open for the comp so you can test this on our system if you'd like. 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hey Bruce. Thanks for reporting.

I found the cause in /includes/process/process_brewing.inc.php, To fix, change line 116 to the following:
```
if ((!empty($_POST['brewInfoOptional'])) && (in_array($index, $optional_info_styles))) $brewInfoOptional = $purifier->purify($_POST['brewInfoOptional']);
```

The culprit was an incorrect needle variable in the array search function.
