### ISSUE TITLE
Payment not registering on BCOEM

### ISSUE THREAD

**Issue by joquiroz** [geoffhumphrey/brewcompetitiononlineentry#1127]
Version:
- 2.1.18

Installation URL:
- quaff.org/AFC-2020/

Is your installation hosted on brewcompetition.com or brewcomp.com?
-  No

Description of Issue:
- Payment
Paid with Paypal and clicked the "back to merchant link" and the entry is not marking paid after a few minutes. Tested the error on the installation. Payment marked complete at 11:52 AM and it has not registered on BCOEM 13 minutes later (expectation the handshake will process this in less than two minutes as it usually does)

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by joquiroz** [comment]
Checked the entry now and there is no update to it in terms of payment...

**Comment by geoffhumphrey** [comment]
Hi @joquiroz - Unfortunately, I cannot recreate this issue on my test servers. When I click the "return to..." link and when I simply wait for PayPal to redirect me back the payments were reflected on my account.

If you've paid, chances are QUAFF knows and/or can look it up. My suggestion would be to contact the organizer and/or send proof of payment with your entry bottles. If you've paid, it's simply a matter of an admin of the site to check a box.

**Comment by joquiroz** [comment]
Hey Geoff,

I am the QUAFF admin, I am going to do another test right now for another entry...what can I do to document for you.

**Comment by joquiroz** [comment]
Hey Geoff,

Just recorded the screen for the payment through paypal and the paypal account acknowledged it...

From paypal I went back to BCOEM and the payment is not registered.

[Video of Payment](https://drive.google.com/open?id=1Gfl6I09dkJveYAPicIJ3Uqf2Lue6GgdS)
[Paypal](https://drive.google.com/open?id=1PS3rv_Z1PexhobOCH4gu-6-vDnDeUe5A)
[BCOEM Admin Entries](https://drive.google.com/open?id=156lqIp64I2_5fp0awjE6oDE14adm3TIz)

**Comment by geoffhumphrey** [comment]
Ah, OK. Thanks for taking the time to record the video... After looking at it, it appears that your installation is using the PayPal IPN option - please check Admin Dashboard > Preferences > Website Preferences to verify.

When this option is used, some custom configuration is necessary. Please take a look at the [PayPal IPN set up instructions](https://brewcompetition.com/paypal-ipn) and verify that everything is set up correctly for your installation AND on the PayPal account that is taking payments for your comp.

Alternatively, you can disable the PayPal IPN in your Website Preference and BCOE&M will revert to the traditional method, which, while much improved on PayPal's side, still may not mark 100% of entries as paid.

**Comment by joquiroz** [comment]
Excellent. Thanks. I’ll review when I head back to the office after lunch and close accordingly if this is what happened.

Thanks for the support!

**Comment by joquiroz** [comment]
Excellent, that was it. New Item? I don't think I saw it on the last install. I did review it and thought enabling it was the right option so I left it like that.

**Comment by geoffhumphrey** [comment]
Relatively new. It's been an option since version 2.1.10 (October 2017).

**Comment by joquiroz** [comment]
shoot, wonder how it went under my radar for this long. Just went to my previous install (2.1.14) and it seems that it was disabled as a default.

Cheers, thanks for the quick responses!
