### ISSUE TITLE
Superfluous ) bracket preventing entrant registration on master branch

### ISSUE THREAD

**Issue by quimnut** [geoffhumphrey/brewcompetitiononlineentry#1128]
https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/a3345cc458883b4cd9c91b529eec9f7e6d8adc3a/includes/process/process_users_register.inc.php#L283

Parse error: syntax error, unexpected ')' in /var/www/html/includes/process/process_users_register.inc.php on line 283

**Comment by geoffhumphrey** [comment]
Fixed with [this pull](https://github.com/geoffhumphrey/brewcompetitiononlineentry/pull/1140).
