### ISSUE TITLE
2.1.18 SMTP Send issue/?

### ISSUE THREAD

**Issue by skitzo2000** [geoffhumphrey/brewcompetitiononlineentry#1130]
Version: 2.1.18

Installation URL:  https://198.211.117.144/

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue:
Testing SMTP sending on our site via mailgun.  I'm using the "Test Send" on the website preferences page.  The page takes a really long time to load, and eventually shows the sent message.  But I'm not getting mail.  I set the debug value to 2 in config.mail.php.  On a re-test I reviewed the logs and the only error I'm getting is on the Apache error log: 
 

> [php7:notice] [pid 26555]  PHP Notice:  Undefined index: contestName in /var/www/[OUR COMPSITE]/admin/site_preferences.admin.php on line 772, referer: https://198.211.117.144/index.php?section=admin&go=preferences

I'm not sure if I need to set a flag somewhere else for more verbose output on the page, but I can confirm thru the SMTP server, they are not receiving the request.  Note this is an upgraded installation from last year.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by quimnut** [comment]
No typo in the username? mailgun is working for me. I did have a typo in the username at the beginning and there was nothing logged on the maingun side either.

**Comment by skitzo2000** [comment]
I copy and pasted my info into sendmail as a workaround(needed to go live ASAP).

More than anything was looking for a little better documentation on what the debug function(for mail) is supposed to do, because it didn't seem to trigger any errors at all.

**Comment by quimnut** [comment]
I just rolled my container with the 2.1.18 release and mailgun works. But if I put a wrong password in I also cannot see any meaningful logs on either side.

https://github.com/quimnut/brewcompetition-docker/blob/master/brewcompetition-http-smtp/Dockerfile

**Comment by skitzo2000** [comment]
Yeah I think just some logging added around the new SMTP container would be helpful. maybe there was a typo.
