### ISSUE TITLE
v2.1.18 - character set issue with e-mail

### ISSUE THREAD

**Issue by AdrienM76** [geoffhumphrey/brewcompetitiononlineentry#1132]
Version: 2.1.18

Installation URL: https://bataille.deadyeast.org

Is your installation hosted on brewcompetition.com or brewcomp.com? no

Description of Issue:

I just upgraded from 2.1.17 to 2.1.18, set up SMTP mail. (e-mails weren't getting through otherwise)

However I noticed the 'from' mangling an extended character in our competition name.
The official name of our competition is "Bataille des Bières" but the e-mail came in as from "Bataille des BiÑres" This was both in the from and in the body of the e-mail. The raw source looks like ISO 8859-1 is being used.

So instead of 'small e acute' I'm getting 'capital N tilde'

I'm making the request to use UTF-8 for better standardization.

**Comment by heneksj** [comment]
I’ve noticed that kind of thing too. I believe it was in cute beer names that brewers choose.

**Comment by geoffhumphrey** [comment]
Thanks for your report. A fix for this issue is in the latest master commit and will be in the next release.

**Comment by AdrienM76** [comment]
Awesome, thank you!
