### ISSUE TITLE
Displaying Paid Entries

### ISSUE THREAD

**Issue by oshc** [geoffhumphrey/brewcompetitiononlineentry#1139]
Version: BCOE&M 2.1.18

Installation URL: oshc.brewcomp.com

Is your installation hosted on brewcompetition.com or **brewcomp.com**?

Description of Issue: Is there a way to display only paid entries? Or to display both paid and unpaid? I have concerns of people seeing the entry count hit 500 and then stop entering. I have the paid entry limit set at 500 but the total entry limit set at 600.

Thanks!

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by jangevaare** [comment]
This would be a very useful feature as almost all Canadian competitions have moved to paid entry - based limits this year, and use BCO&E. Cheers!

**Comment by geoffhumphrey** [comment]
Sounds reasonable. The paid limit total will display on the home page when the entries are being accepted as well as on the sidebar that's present on all public (non-admin) pages.

This enhancement is in the latest commit and will be in the next release.
