### ISSUE TITLE
Enhancement - Allow assigning styles to tables without needing entries received

### ISSUE THREAD

**Issue by jmalex** [geoffhumphrey/brewcompetitiononlineentry#1142]
Version: 2.1.17

Installation URL: http://www.keystonehops.com/waroftheworts2020

Is your installation hosted on brewcompetition.com or brewcomp.com? no

Description of Issue:
Currently, in order for a style to be assigned to a table, it must have a received entry in it. It would be nice to set up the styles in tables before entries start coming in. Additionally, late entries will come in and be the first beer of the style. Our competition admins will commonly neglect to add the style to the table after the fact.

**Comment by geoffhumphrey** [comment]
A long time coming, but in the next version, Admins will have the ability to switch into Tables Planning Mode. While in this mode, Admins will be able to define tables and flights along with their associated judge and steward assignments prior to any entry being marked as "received" in the system. This will allow admins to get a lay of the land, so to speak, with regard to table configuration and personnel assignments.

![image](https://user-images.githubusercontent.com/5216502/102699315-eb4c2000-4200-11eb-9d96-99260871a103.png)

Once sorting happens and entries are marked as "received" in the system, Admins should then switch back to the default state, Tables Competition Mode, to review their table configurations, flight assignments, round associations, and personnel assignments in preparation for judging.

![image](https://user-images.githubusercontent.com/5216502/102699329-fef78680-4200-11eb-84bb-4050dccc3346.png)
