### ISSUE TITLE
2.1.18 Troubleshooting code removal

### ISSUE THREAD

**Issue by definiteopinions** [geoffhumphrey/brewcompetitiononlineentry#1151]
Version: 
2.1.18

Installation URL:
https://aotearoa.brewcompetition.com/

Is your installation hosted on brewcompetition.com or brewcomp.com?
Yes

Description of Issue:
Hi Geoff, you fixed some issues for us a while ago. Since then every page has some troubleshooting information at the bottom, like in the screenshot attached.  It doesn't affect the functionality, just looks untidy.  Could you clear it out for us please?

Cheers
![2020-06-18 14_06_56-Window](https://user-images.githubusercontent.com/59522613/84969946-d4534500-b16d-11ea-9758-ddc29e3d3259.png)

**Comment by geoffhumphrey** [comment]
Apologies for the tardy response. I have cleared out the debugging information display from your installation. Best of luck with the competition. I'm glad that New Zealand is able to get back into competitions again. Here in the States, it's still a bit dodgy.
