### ISSUE TITLE
Help Wanted - New Style set display in website preferences

### ISSUE THREAD

**Issue by rocket-pants** [geoffhumphrey/brewcompetitiononlineentry#1153]
Version: 2.1.17

Installation URL:http://competition.wasabc.org/

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue:
Hi, I want to add a new style set to the software for AABC. I've set up the SQL so I can add entries to the styles table via phpmyadmin such as

`INSERT INTO `styles` (`brewStyleNum`, `brewStyle`, `brewStyleCategory`, `brewStyleOG`, `brewStyleOGMax`, `brewStyleFG`, `brewStyleFGMax`, `brewStyleABV`, `brewStyleABVMax`, `brewStyleIBU`, `brewStyleIBUMax`, `brewStyleSRM`, `brewStyleSRMMax`, `brewStyleType`, `brewStyleInfo`, `brewStyleLink`, `brewStyleGroup`, `brewStyleActive`, `brewStyleOwn`, `brewStyleVersion`, `brewStyleReqSpec`, `brewStyleStrength`, `brewStyleCarb`, `brewStyleSweet`, `brewStyleTags`, `brewStyleComEx`, `brewStyleEntry`) VALUES ('01','Light Australian Lager [AABC]','1.LOW ALCOHOL','1.028','1.035','1.004','1.008','2.8','3.5','10','15','2','4','1',' Light-coloured, clean tasting beer. Low flavour levels make off-flavours obvious','http://www.aabc.org.au/docs/AABC2019StyleGuidelines.pdf','1','Y','bcoe','AABC','0','0','0','0','session-strength, amber-color, top-fermented, british-isles, traditional-style, amber-ale-family, malty','Cascade Premium Light',NULL);
`

I can see the entry is added to the styles table but I cannot work out how I can add this to the website preferences field under Entries: Style Set. I can only see BJCP 2008, 2015 and BA style sets. I've played with the brewStyleOwn and brewStyleVersion but no idea what is happening or if there is another step I need to take.  In the past we've added approx 1 million custom styles to BJCP 2015 style set but I would like to elevate what we are doing to include the AABC styles as their own set.

I can send the complete list of AABC 2019 insert statements, or a csv of the details if this help

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
@rocket-pants (awesome name, BTW) - At present, the style sets are hard-coded into the site preferences markup. If you wouldn't mind sending the insert statements and CSV files, I'll be able to get the AABC styles integrated as a style set option for users.

**Comment by rocket-pants** [comment]
Cheers Geoff,

Thanks very much for this. I've attached the csv and insert statement. You'll need to double check that there aren't syntax errors in them as I've not really been able to test myself, however I can add to the styles table sung the insert so they are probably OK to go.

We're running our state comp (West Australian State Amateur Brewing Competition) in August with entries opening in late July, followed by the national comp (AABC) in October. It would be awesome not to have to use the custom categories again this year, but if it can't be done by then at least we'll be set for next year.  

Thanks again

Ed
[AABC 2019 Style_table_insert.sql.txt](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/4835169/AABC.2019.Style_table_insert.sql.txt)
[AABC 2019 styles.csv.txt](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/4835171/AABC.2019.styles.csv.txt)

**Comment by geoffhumphrey** [comment]
Hi Ed. Just to update you - I'm 90% done integrating the AABC guidelines into the code base. The style set will be included as an option for use in the next release, which I'm targeting for 10 July (if not before).

**Comment by rocket-pants** [comment]
Geof, that's amazing. Thank you.

**Comment by mattwwatson** [comment]
Wow, this is awesome. I have added this (but not as a PR, I had to overwrite the bjcp as an option to do it. My code is on the nswbrewcomp branch of my bitbucket repo (https://bitbucket.org/mattw_watson/bcoem/src/nswbrewcomp/) - I use bitbucket (1) cause i use pipelines to automatically update the comp websites we have and (2) I work at Altassian

The changes I made are mostly in the https://bitbucket.org/mattw_watson/bcoem/src/nswbrewcomp/sql/convert_to_aabc.sql file, but there were also some changes I had to make throughout the code which are switchable but depend on you overwriting the database entries for bjcp so YMMV, but it it helps, 

- https://bitbucket.org/mattw_watson/bcoem/src/33cb33ee598daac54a1ae516c7fb94a283703503/site/config.php#lines-58
- https://bitbucket.org/mattw_watson/bcoem/src/nswbrewcomp/sections/brew.sec.php#lines-61
- https://bitbucket.org/mattw_watson/bcoem/src/nswbrewcomp/sections/entry_info.sec.php#lines-231
- https://bitbucket.org/mattw_watson/bcoem/src/nswbrewcomp/lib/common.lib.php#lines-1306
- https://bitbucket.org/mattw_watson/bcoem/src/nswbrewcomp/lib/common.lib.php#lines-1353
- https://bitbucket.org/mattw_watson/bcoem/src/nswbrewcomp/lib/common.lib.php#lines-1417
- https://bitbucket.org/mattw_watson/bcoem/src/nswbrewcomp/lib/common.lib.php#lines-1464
- https://bitbucket.org/mattw_watson/bcoem/src/nswbrewcomp/lib/common.lib.php#lines-1523
- https://bitbucket.org/mattw_watson/bcoem/src/nswbrewcomp/lib/common.lib.php#lines-1561
- https://bitbucket.org/mattw_watson/bcoem/src/nswbrewcomp/lib/common.lib.php#lines-1591
- https://bitbucket.org/mattw_watson/bcoem/src/nswbrewcomp/lib/common.lib.php#lines-1688
- https://bitbucket.org/mattw_watson/bcoem/src/nswbrewcomp/lib/common.lib.php#lines-1689

**Comment by geoffhumphrey** [comment]
@mattwwatson - impressive. A very ingenious way of update the DB and augmenting the PHP code to suit your needs with minimal lines.

Once I'm done with testing, I'll commit the changes and we can compare notes. If you'd like to send the list of clubs along in the meantime, I'll get those added in as well.

**Comment by mattwwatson** [comment]
> I found the clubs in your repo. Assuming they start at line 2295 here.
Thats right - my editor couldn't cope well with the super long line you had so I blew it up into multiple lines...

**Comment by geoffhumphrey** [comment]
The changes to incorporate the style set are in the latest master commit. As you mention @mattwwatson, the goal is to make integration a feature rather than a modification. I'm still testing things, but think it's at least 90% there. 

The styles will be added to the DB if upgrading an install from 2.1.18 or previous. Of course, DB backups are always recommended prior to testing as well as testing in an upgrade environment and a new install. 

**Please note:** When testing in an upgrade environment, the styles that were chosen for any entries present in the DB will NOT be updated.
