### ISSUE TITLE
Waiver not Displaying in Account registration 

### ISSUE THREAD

**Issue by cshinn89** [geoffhumphrey/brewcompetitiononlineentry#1156]
Version:2.1.18

Installation URL:https://njstatefairhomebrew.brewcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? yes

Description of Issue: i'm trying to make the waiver option show up during account registration but cannot find it in the options.
as well currently the  The $setup_free_access variable in config.php is currently still set to TRUE

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @cshinn89 - I've taken care of the $setup_free_access warning. It should not show again. 

Regarding the waiver, there isn't an option to turn it on or off via preferences. It only shows on the [judge](https://njstatefairhomebrew.brewcomp.com/index.php?section=register&go=judge) or [steward](https://njstatefairhomebrew.brewcomp.com/index.php?section=register&go=steward) screens or if a user elects to serve as a judge when editing their account information.

Hope that helps.

**Comment by cshinn89** [comment]
> Hi @cshinn89 - I've taken care of the $setup_free_access warning. It should not show again.
> 
> Regarding the waiver, there isn't an option to turn it on or off via preferences. It only shows on the [judge](https://njstatefairhomebrew.brewcomp.com/index.php?section=register&go=judge) or [steward](https://njstatefairhomebrew.brewcomp.com/index.php?section=register&go=steward) registration screens or if a user elects to serve as a judge when editing their account information.
> 
> Hope that helps.

i thanks for the quick reply, however i've tried creating test accounts and still do not see the waiver checkbox show up.

**Comment by cshinn89** [comment]
@geoffhumphrey upon further investigation i now see that the waiver does not show up at all when registering as a judge. however if you go back into your account info after registering as a judhe or steward it shows as already checked even though the registrant never saw it or checked it themselves. is there any way to fix this so it will appear for the entrant to check themselves?
