### ISSUE TITLE
Entrants can register prior to registration open date

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1157]
Version: 2.1.13

Installation URL: https://limbocomp.org/bcoem

Is your installation hosted on brewcompetition.com or brewcomp.com? no

Description of Issue: Participants are able to register prior to the Account Registration opening date.

The URL: https://limbocomp.org/bcoem/?section=register will allow the participant to register prior to the start date. There is a message at the top of the page that states the registration window but still allow you to register.

I know I am back level on the release but can someone try this on the current release? I could not see an issue with someone describing this behavior in the issues list.

Thanks.

Jimmy

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi Jimmy - well, it looks like you've stumbled upon a back door into registration that I quite literally forgot was there. I had a note to myself to plug it up as far back as version 2.1.9, but, alas, I never did. It's still there in 2.1.18. 

For the next version, I'll definitely be plugging that up. In the meantime, for your installation, adding the following to the index.php file IMMEDIATELY BELOW line 12 will close the door:

```
if (($section == "register") && ($go == "default") && ($registration_open == 0) && ($judge_window_open == 0))  
header(sprintf("Location: %s", $base_url."index.php?section=register&go=entrant"));
```

Upload to your server and you should be good to go.

**Comment by geoffhumphrey** [comment]
A more elegant fix is in the latest master commit and will be included in the next version.
