### ISSUE TITLE
2.1.18 Contact Form not sending emails

### ISSUE THREAD

**Issue by cshinn89** [geoffhumphrey/brewcompetitiononlineentry#1159]
Version:2.1.18

Installation URL:https://njstatefairhomebrew.brewcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? Yes

Description of Issue: when people use the contact form to send organizers emails everything seems to process properly however  no emails are delivered to the organizers
 also as a side note the $setup_free_access variable is still showing as true when logging in
![image](https://user-images.githubusercontent.com/63543974/88065516-b2692b80-cb3a-11ea-99b0-4f1d9820c8ff.png)

**Comment by geoffhumphrey** [comment]
There was a change in the outgoing mail server address from the hosting company (love that they do that without any communication). Anyway, your installation and all other hosted installations on the brewcomp.com domain have been updated and should be mailing as expected now.

For anyone having the same problems outside of a hosted installation, make sure to check the SMTP settings in the /site/config.mail.php file match the ones provided by your hosting company. They must be exact.
