### ISSUE TITLE
2.1.18 Cannot award BOS places

### ISSUE THREAD

**Issue by cshinn89** [geoffhumphrey/brewcompetitiononlineentry#1161]
Version: 2.1.18

Installation URL: https://njstatefairhomebrew.brewcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? yes

Description of Issue:
i'm trying to award the BOS Places and when i go to scoring, manage BOS entries and places, add or update BOS Places for beer it only allows me to award Hon. Men. and not 1st, 2nd, and 3rd plase BOS

![BOS Issue](https://user-images.githubusercontent.com/63543974/90980635-9508f200-e52a-11ea-8f16-254fb3726324.png)

**Comment by stklein** [comment]
I am having this same exact issue. How did you resolve it?
