### ISSUE TITLE
2.1.19 small bug - Can download results before published (after comp has been completed)

### ISSUE THREAD

**Issue by listening2tim** [geoffhumphrey/brewcompetitiononlineentry#1163]
Version:
2.1.19 and

Installation URL:
https://enter.wasabc.org/
*I am using a release a few days before you released prod version of 2.1.19 - had tested and couldn't wait any longer  - sorry.
Perhaps its fixed in full prod  verson?

Is your installation hosted on brewcompetition.com or brewcomp.com? 
No.

Description of Issue:
in settings - set "display winners" after 12th September.  Our competition is done.

if you add
/output/export.output.php?section=results&go=judging_scores&action=default&filter=none&view=html
to the installation URL, after the competition has been completed,  but before the results are published -  someone can download the results before they are released? Some smart person used last years URL, and modified for this years and gained the results.  

If you 'disable' - it does't show when results are posted.  I have renamed the file "export.output.php" so it throws an error if someone tries again -  will rename back just before posting results.
message me if you want to test - I can give you the name of the modified file.

Not sure if there is a way to stop this? Or perhaps you have fixed in the latest version.

Thanks heaps.  

BTW - This version worked great for our Western Australian State Comp!  the AABC style guide lines have made things much easier!
Cheers
Tim

**Comment by geoffhumphrey** [comment]
Hi @listening2tim, thanks for reporting. Some impatient and sneaky people you got there! :)

Anyway, I believe I've plugged the hole you reported in the export.output.php file. Non-admins shouldn't be able to access any CSV downloads at all, so hopefully this will fix the problem. You can [view and download the updated file here](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/output/export.output.php).

**Comment by listening2tim** [comment]
Thanks Geoff !  That has fixed the problem. Thanks again and appreciate your time.
