### ISSUE TITLE
2.1.19-Spammers sending mail using process_contacts.inc.php

### ISSUE THREAD

**Issue by cbwatkins** [geoffhumphrey/brewcompetitiononlineentry#1164]
Version: 2.1.19

Installation URL: domrascup.com

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: Spammers are sending email using our webhost account using the processs_contacts.inc.php file. This was identified in the email headers: X-PHP-Originating-Script: 49727:process_contacts.inc.php

How do we secure the installation to prohibit spammers from sending email using the BCOE&M scripts that we installed?

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by cbwatkins** [comment]
I just turned recaptcha on AFTER this event occurred. With recaptcha turned
off, does this explain how they would have sent spam with our script?

Regards,
Chris Watkins

**Comment by geoffhumphrey** [comment]
Yes, that absolutely explains it. Without reCAPTCHA, automated spambots trolling the internet can use contact forms to send spam email. CAPTCHA and reCAPTCHA were developed specifically to stop them by adding a form element that has to be interacted with by a human and cannot be "duped" by an automatic script.

With reCAPTCHA enabled, you've eliminated the bots, but that won't stop a determined human from using the form to send spam if they care to take the time. These are very few and far between, however. I get a few from Russia every once in a while that are amusing.
