### ISSUE TITLE
2.1.19 - Co-Brewer name doubles and shows up twice

### ISSUE THREAD

**Issue by Beer-Ranger** [geoffhumphrey/brewcompetitiononlineentry#1165]
Version: 
2.1.19

Installation URL:
https://hoppyhalloween.com/comp

Is your installation hosted on brewcompetition.com or brewcomp.com?
No

Description of Issue:
When a value is entered in the Co-Brewer field, it duplicates itself.  Example, if you enter 'John Doe' as the co-brewer and save, then when you inquire, the co-brewer shows as 'John DoeJohn Doe'
This was reported by an entrant adding the co-brewer after he had paid and the bottles received.  It also might have done something to the received value but I can't confirm.
I tried to add the co-brewer as the admin and edit the entry, and got the same issue of doubling the name.
I looked at another entrant who always has a co-brewer and would have put it in when first adding the entry and the name doubling is there too.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
@Beer-Ranger, thanks for reporting. Confirmed. There was some erroneous scripting in the /includes/process/process_brewing.inc.php file that was doubling up co-brewer names. A fix is included in the current master commit and will be included in the next release.

**Comment by AdrienM76** [comment]
Not sure if this is the same thing and is thus fixed in 2.2.0, but our results page shows the text "Co-Brewer:" below every placing beer, even if it doesn't have a co-brewer. (in fact, none of them had a co-brewer) It isn't a big deal, but could be a bit cleaner.
