### ISSUE TITLE
2.1.19 - Website language preference not saved

### ISSUE THREAD

**Issue by grmelacz** [geoffhumphrey/brewcompetitiononlineentry#1168]
Version: 2.1.19

Installation URL: https://soutez.mhmeeting.cz

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue:
The bug is easy to replicate:
1. Log in to admin.
2. Open Website preferences.
3. Set Czech as a default language and save the preferences.
4. Web is displayed in Czech but *only for currently logged in admin* (not for public).
5. Log out.
6. Web is displayed in English again even though Czech is still displayed in Website settings as the language preset.

Currently using workaround mentioned in https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/945#issuecomment-405354087 but would prefer a clean solution instead.

**Comment by geoffhumphrey** [comment]
Hi @grmelacz; thanks for reporting.

A fix for this is in the latest master commit - specifically on the /db/[common.db.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/9e0acb2d0de1a6f4eb3ea5c0c4b568abd137290d/includes/db/common.db.php) file. I removed some coding (originally on lines 301-304) that was unintentionally reverting language display back to US English. 

Also, thanks for your work on the latest [Czech translation](https://gist.github.com/grmelacz/c7d204e6e3823d2d9aa6e2d4a6990b5b). Not only your real efforts, but your work in translating into "real" Czech - something that Google Translate can never do. That translation has also been included in the latest commit. If you look [at that file](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/9e0acb2d0de1a6f4eb3ea5c0c4b568abd137290d/lang/cs/cs-CZ.lang.php), you'll note more items to translate, starting at line 1528. These again were done via Google Translate. Perhaps you'd be able to review them and correct any, um, inconsistencies?

**Comment by grmelacz** [comment]
Hey 
thanks for the quick fix! I've uploaded the 1.2.20 part as a separate gist. I had to rewrite it as it looked more like we're at a court with laywers and all the "judging" around :-) https://gist.github.com/grmelacz/4ee38d99d36c2b2a9dac966942c989a0
