### ISSUE TITLE
2.1.19 - Table Results and All Results reports show that every table has 10 entries

### ISSUE THREAD

**Issue by Beer-Ranger** [geoffhumphrey/brewcompetitiononlineentry#1170]
Version:
2.1.19

Installation URL:
https://hoppyhalloween.com/comp

Is your installation hosted on brewcompetition.com or brewcomp.com?
No

Description of Issue:
In the Reports menu, After Judging, the reports under the Table Results and All Results options indicates 10 entries for every single table and not the correct number.  
The Pullsheets reports do list the correct number of entries for each table.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
@Beer-Ranger thanks for reporting. There was some test code inadvertently left in production. If you remove line 63 in /sections/winners.sec.php that says:
```
$entry_count = 10;
```
...entry counts for each table will display properly. Apologies for any issues this has caused.
