### ISSUE TITLE
2.1.19 - BOS Mead/Cider Not Showing on Results

### ISSUE THREAD

**Issue by Beer-Ranger** [geoffhumphrey/brewcompetitiononlineentry#1172]
Version:
2.1.19

Installation URL:
https://hoppyhalloween.com/comp

Is your installation hosted on brewcompetition.com or brewcomp.com?
No

Description of Issue:
Our competition is set up with Best of Show - Beer and Best of Show - Mead/Cider.
In the Reporting under Before Judging, there are options for BOS Pullsheets and BOS Cup Mats for Beer and separate options for Mead/Cider as I would expect.

Then after scores and places have been entered for both BOSs when running After Judging reports, BOS Results and All Results reports only show the BOS - Beer information and BOS Mead/Cider is missing.
When we publish the results tonight I will add if the BOS Mead/Cider is shown there.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @Beer-Ranger. Thanks for reporting. 

If you haven't already, make sure that BOS for Style? is checked **yes** when you edit the Mead/Cider Style Type in Admin > Competition Preparation > Manage Style Types > Edit Mead/Cider Style Type:

![image](https://user-images.githubusercontent.com/5216502/97509748-bf22ca00-1948-11eb-9ca6-865675369bce.png)

**Comment by geoffhumphrey** [comment]
After further investigation, there was an error in the DB query in the /includes/db/output_results_download_bos.db.php file. Replace the entire line that begins `if ($type == "4)` with this line:

``
if ($type == "4") $query_bos = sprintf("SELECT a.scorePlace, b.brewName, b.brewCategory, b.brewCategorySort, b.brewSubCategory, b.brewStyle, b.brewCoBrewer, c.brewerLastName, c.brewerFirstName, c.brewerCity, c.brewerState, c.brewerCountry, c.brewerBreweryName, c.brewerClubs FROM %s a, %s b, %s c WHERE a.eid = b.id %s AND c.uid = b.brewBrewerID AND (a.scoreType='2' OR a.scoreType='3' OR a.scoreType='4') ORDER BY a.scorePlace", $prefix."judging_scores_bos", $prefix."brewing", $prefix."brewer", $scorePlace);
``

This will also include the Mead/Cider entries for BOS.

This fix is in the latest commit and will be in the next release.
