### ISSUE TITLE
2.1.19 - Can't Add Strength to NEIPA Entry

### ISSUE THREAD

**Issue by Fencer04** [geoffhumphrey/brewcompetitiononlineentry#1174]
Version: 2.1.19

Installation URL: https://libme.brewcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? brewcomp.com

Description of Issue: Can't edit the strength of a NEIPA entry.  When you first visit the page the freeform field is shown but no choice for the strength. If you change the category and then change back to NEIPA the radio buttons for stength appear. When you select and save it doesn't seem to be saved.

**Comment by geoffhumphrey** [comment]
Hi @Fencer04. Thanks for reporting. Confirmed. I've fixed the issue on your hosted instance and entrants/admins should now be able to edit NEIPA (B21-7) entries. 

The fix will also be in place in the next master commit and next release.
