### ISSUE TITLE
QR Scanner Password doesn't work

### ISSUE THREAD

**Issue by rdruckenmiller** [geoffhumphrey/brewcompetitiononlineentry#1176]
Version:

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com?

Description of Issue: When you click the mobile check-in link the password verification doesn't work. Verified the password being used is correct, but it's not being recognized which means mobile check-in isn't possible

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by grmelacz** [comment]
As we're having a competition next week I've just tested this. The function works correctly (version 2.1.19). I've set the password in the admin interface and then launched a browser on my phone. Entered the password and now it says Waiting for a QR code ("Password accepted").

**Comment by prphntm63** [comment]
I had a similar issue - Turns out I was trying to use the "admin" password instead of the "QR" password, which you have to enable and set up on the "Competition Information" screen. 

![image](https://user-images.githubusercontent.com/4017530/100413336-b3581f80-303c-11eb-98b0-4a3079a586e9.png)

**Comment by rdruckenmiller** [comment]
Ah. That makes sense. Thanks!
