### ISSUE TITLE
tinymce v4 CDN deprecation

### ISSUE THREAD

**Issue by prphntm63** [geoffhumphrey/brewcompetitiononlineentry#1181]
Version: 2.1.19

Installation URL: sandbox.cialers.org

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: [tinymce v4 will be deprecated on February 21, 2021](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/). Need to host the package locally or switch to a [3rd party CDN](https://cdnjs.com/libraries/tinymce/4.9.11)

![image](https://user-images.githubusercontent.com/4017530/103194051-ebed5200-48a3-11eb-9e53-d3f454bb673d.png)

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @prphntm63 - thanks for reporting. The next version will update to a 3rd party CDN as you suggest. A future version will upgrade to TinyMCE 5. In the meantime, for current BCOEM versions 2.1.5 and later, replace the TinyMCE js source line in the load_cdn_libraries.inc.php file:
```
<script src="https://cdn.tinymce.com/4/tinymce.min.js"></script>
```

With this:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.9.11/tinymce.min.js"></script>
```
