### ISSUE TITLE
Cider Judge Designation Not Appearing on Administration: Participants, Available Judges

### ISSUE THREAD

**Issue by buergermeister75** [geoffhumphrey/brewcompetitiononlineentry#1182]
Version: 2.1.19

Installation URL: our hosting - Midwinterhbc.com/competition

Is your installation hosted on brewcompetition.com or brewcomp.com? - No

Description of Issue:
Not seeing Cider Judge listed on the Administration: Participants, Available Judges listing. Beer Judge Rank and Mead designations are appearing but not Cider. 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Confirmed. Thanks for your report, @buergermeister75. A fix for this issue is in the latest master commit will be in the next release.
