### ISSUE TITLE
2.2.0 Hosted Beta - Users unable to edit entries once limit is reached

### ISSUE THREAD

**Issue by edfech** [geoffhumphrey/brewcompetitiononlineentry#1183]
Version: 2.2.0

Installation URL: https://yeastwranglers.brewcompetition.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? Yes

Description of Issue: Once brewers have reached their entry limit, it seems like they are unable to edit their entry details. They are given an error stating "You have reached the entry limit. Your entry was not added." Admins can modify entries but it doesn't work for other user permission levels.
![image0 (2)](https://user-images.githubusercontent.com/46381831/104621882-d3c05580-564d-11eb-8ead-f9a9f1e5b39f.jpg)

**Comment by jimmyorkin** [comment]
I think I identified the original problem where an entrant could enter more than the limit. My quick fix caused the same issue described here. 

I think the real fix here needs to look at the intent of the invocation of the process module. Is it an add or edit?

**Comment by edfech** [comment]
Just an edit. Users need to delete their entry then re-enter the info to make modifications if they're at their entry limit but that would cause problems on paid entries.

**Comment by geoffhumphrey** [comment]
Confirmed. A fix is in the latest master commit and will be in the next version. @edfech, I've pushed the fix to your hosted installation.

** Note: this report is for a beta version of 2.2.0 for a hosted user. Title has changed to reflect that.
