### ISSUE TITLE
v2.1.19 - MySQL error when editing admin notes for an entry

### ISSUE THREAD

**Issue by AdrienM76** [geoffhumphrey/brewcompetitiononlineentry#1190]
Version: v2.1.19

Installation URL: https://bataille.deadyeast.org

Is your installation hosted on brewcompetition.com or brewcomp.com? no

Description of Issue:

I received the following error:

```You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's', brewStaffNotes='' WHERE id='15'' at line 1```

When I was attempting to add admin notes to an entry. (I was indicating the place where I picked up the beers, and the place name has an apostrophe which was throwing the error.) After removing all apostrophes in each note field (there were several) the table updated properly without error.

**Comment by geoffhumphrey** [comment]
@AdrienM76, thanks for the heads up. I'll make sure that apostrophes are allowed in the next version when editing staff and admin notes.
