### ISSUE TITLE
Missing Club - MontreAlers

### ISSUE THREAD

**Issue by TheStealth359** [geoffhumphrey/brewcompetitiononlineentry#1194]
Description of Issue:

The MontreAlers homebrew club is missing in constants.inc.php. Please add "MontreAlers" to the club list.

Cheers

**Comment by geoffhumphrey** [comment]
Easy enough. Addition is in the latest commit and will be in the next release. Cheers!

**Comment by TheStealth359** [comment]
@geoffhumphrey Thanks for the quick turnaround. Keep up the good work. Cheers
