### ISSUE TITLE
2.1.19 - Wrong participants' phone numbers in export

### ISSUE THREAD

**Issue by grmelacz** [geoffhumphrey/brewcompetitiononlineentry#1195]
Version: 2.1.19

Installation URL: https://soutez.mhmeeting.cz

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: The participants' phone numbers are correctly saved in the system, but when I perform a data export using Participant Data (CSV) > Winners (e.g. for shipping prizes), the phone numbers are incorrect. There is the same phone number for multiple participants.

<img width="842" alt="Screenshot 2021-02-05 at 9 18 58" src="https://user-images.githubusercontent.com/41264018/107008013-9013c400-6793-11eb-9027-ef875a0ecb23.png">

It may affect other exports too, I didn't check. When I open the user's profile directly, the phone is correct (and differ from other exported users).

**Comment by geoffhumphrey** [comment]
Confirmed. There was some formatting for phone numbers that was mistakenly being called outside of the loop that iterated through each record, resulting in this error. The fix is in the latest master commit and will be part of the next release.

**Comment by grmelacz** [comment]
Great! Thanks for the fix, much appreciated.
