### ISSUE TITLE
Winner display by table shows incorrect number of entries

### ISSUE THREAD

**Issue by julien-gibson** [geoffhumphrey/brewcompetitiononlineentry#1200]
Version: 2.1.19

Installation URL: comps.sabrew.com

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: Winner display on Home page shows 10 entries on both tables, when there were 22 and 14 entries respectively.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.
![image](https://user-images.githubusercontent.com/5753439/108279051-e6d5c080-71cb-11eb-827a-41214cd7e798.png)
![image](https://user-images.githubusercontent.com/5753439/108279105-fc4aea80-71cb-11eb-9a4d-210df0624e10.png)

**Comment by geoffhumphrey** [comment]
Hi @julien-gibson, thanks for reporting. This was a known issue and has been addressed in the latest release. Please see issue #1170 for a fix for 2.1.19 or update to 2.2.0. Thanks!

**Comment by julien-gibson** [comment]
Thanks for the prompt reply Geoff.  Apologies for not doing a more thorough search of the issues

**Comment by geoffhumphrey** [comment]
No worries. Sometimes closed issues get overlooked - I know it's not the first place I think to look as well. Cheers!
