### ISSUE TITLE
BCOE&M 2.1.12 | Warning message related to TinyMCE

### ISSUE THREAD

**Issue by aliciad19363** [geoffhumphrey/brewcompetitiononlineentry#1201]
Version: BCOE&M 2.1.12

Installation URL: https://www.brewdrinkrepeat.com/buzzoff/

Is your installation hosted on brewcompetition.com or brewcomp.com? Not sure

Description of Issue:
I logged onto the site for the first time in several months and when updating competition info I saw this message:
"Your access to TinyMCE will expire on 25 Februrary 2021. Please either contact your administrator or upgrade your account using the instructions available here" [link directed to https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/.] The info in the link was not helpful to me as it appears to be for use by the site administrator. It appears I was able to make the updates but it seems like there is something that needs to be done.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @aliciad19363; this issue has been fixed with release 2.2.0. To fix, please update to the current version or see Issue #1181 for a fix for your installed version.
