### ISSUE TITLE
Label printing amounts, 

### ISSUE THREAD

**Issue by Yatlow** [geoffhumphrey/brewcompetitiononlineentry#1205]
I'm trying to print labels for a participant, the default print amount is 3 stickers, yet we requested 4 bottles for each entry.
how can we adjust the label printing amounts?

**Comment by geoffhumphrey** [comment]
You can adjust the number of bottles required under Admin > Preferences > Competition Organization Preferences. It looks like you've set that number to 3 - change it to 4 and you should be good to go.

**Comment by Yatlow** [comment]
thank you!
