### ISSUE TITLE
Version 2.2.0 - Duplicating Saves in BOS Scoring.

### ISSUE THREAD

**Issue by Fencer04** [geoffhumphrey/brewcompetitiononlineentry#1206]
Version: 2.2.0

Installation URL: https://www.beerhbc.org/NewSite/BCOEM/

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: When selecting Honorable Mention in the BOS scoring area I get the following message next  to the drop down: "Error. Invalid numerical input." It  asks me to click the save button. When I do it double saves the other places that I've already selected.

**Comment by geoffhumphrey** [comment]
Confirmed. Thanks for reporting!

A legacy coding issue is preventing saving honorable mention for any BOS style type - switched in 2.2.0 from storing value in DB as alphanumeric to just numeric and coding was trying to submit alphanumeric "HM" value. To fix, replace the following lines in the /admin/judging_scores_bos.admin.php file:

Line 191, replace with:
```
<td><?php if ($bos_entry_info[10] == "5") echo "HM"; else echo $bos_entry_info[10]; ?></td>
```

Line 281, replace with:
```
<option value="5" <?php if ($bos_entry_info[10] == "5") echo "selected"; ?>><?php echo "Hon. Men."; ?></option>
```
