### ISSUE TITLE
Version 2.2.0 - Decimal scores won't save anymore

### ISSUE THREAD

**Issue by elronalds** [geoffhumphrey/brewcompetitiononlineentry#1210]
Version: 2.2.0

Description of Issue:  When saving scores in the latest release using the new auto save feature, the system won't save decimal scores which was possible in the past.

**Comment by geoffhumphrey** [comment]
Hi @elronalds. Thanks for reporting. 

Confirmed. A fix was included in [this commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/966c65f26575792cdbd4367c8b31f19d52e24355#diff-4847c55a41aee362e5f426e16b549e256f2f4d2c0f2b0e31ed472cc151613547) (specifically, the /ajax/save.ajax.php file) from March and will be in the next release.
