### ISSUE TITLE
Version 2.2.0 - Auto save issue not saving the correct field

### ISSUE THREAD

**Issue by elronalds** [geoffhumphrey/brewcompetitiononlineentry#1211]
Version: 2.2.0

Description of Issue:  I ran a compition on the weekend with a relativly large number of entries (almost 300).  The new auto save feature had a bug around 3 times where the saving progress and tick confirmation UI elements would appear on several entries above the actual entry I was editing and had keyboard focus on.  

Unfortunately I wasn't able to capture a video of this behaviour, however it did happen multiple times during the day.  Refreshing the score entry page then showed that the system had copied the score from above down into the field that I had entered.

**Comment by geoffhumphrey** [comment]
Hmm. Weird. I'll look into possible causes. Try as I might, I'm not able to re-create the issue in my test environments.

**Comment by grmelacz** [comment]
I can confirm this bug. Happened to me with 2.3.1 this weekend. Fortunately, I have a video and also a log of the faulty request.

It happens completly randomly, sometimes when I've opened the same page it worked fine, but sometimes it began to saving the values to a different field. Very dangerous indeed. I've experienced this problem both with Chrome and Safari (recent versions, Win/Mac).

I haven't archived the data yet, so I may help with trying to recreate the situation (e.g. give you access to the live system or send you a DB dump).

Request log:
```
:method: POST
:scheme: https
:authority: soutez.mhmeeting.cz
:path: /ajax/save.ajax.php?action=judging_scores&go=scoreEntry&id=97&rid1=168&rid2=3&rid3=1
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept: */*
Accept-Language: en-us
Accept-Encoding: gzip, deflate, br
Host: soutez.mhmeeting.cz
Origin: https://soutez.mhmeeting.cz
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
Connection: keep-alive
Referer: https://soutez.mhmeeting.cz/index.php?section=admin&&go=judging_scores&action=edit&id=3
Content-Length: 13
Cookie: eff8b79f4f5eeddc362f75402c83c6eb=1e3bb6d6e3328717e4f0b040b05ef4f3
X-Requested-With: XMLHttpRequest


:status: 200
Pragma: no-cache
Content-Type: text/html; charset=UTF-8
Cache-Control: no-store, no-cache, must-revalidate
Date: Sat, 04 Dec 2021 15:49:43 GMT
Content-Encoding: gzip
Content-Length: 123
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Vary: Accept-Encoding
Server: Apache

{"status":"1","query":"UPDATE judging_scores SET scoreEntry=34 WHERE id=106","post":"34","input":"34","error_type":"0"}
```

Video: https://user-images.githubusercontent.com/41264018/144887836-42597ddc-405a-4c3b-955e-b3691083cb7f.mov
