### ISSUE TITLE
Can't login to admin account

### ISSUE THREAD

**Issue by terryn7731** [geoffhumphrey/brewcompetitiononlineentry#1213]
Version:2.2.0

Installation URL:
kotmlmhba.org

Is your installation hosted on brewcompetition.com or brewcomp.com?
no

Description of Issue:
After and upgrade to the latest version I am unable to login to an account with admin privileges. I am getting an error message " You mus log in and have admin privileges to access administration functions". I have tried several different browsers on 2 different PC's with no luck. However, I am able to login from an iPad without an problem. I have checked the account settings in the back-end and tried resetting the password but it hasn't helped. 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
HI @terryn7731. We've hit this issue before and in some cases, it had to do with the .htaccess configuration on the server, and in others, it had to do with how sessions are treated. Take a look here for some suggestions: https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/1123

**Comment by terryn7731** [comment]
You were exactly right- tracked down the problem to a bad .htaccess file
