### ISSUE TITLE
Missing Club - how to add?

### ISSUE THREAD

**Issue by dougvohden** [geoffhumphrey/brewcompetitiononlineentry#1216]
Version:

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com?

Description of Issue:

Our homebrew club  - Keepers of Craft - in Portage MI is not showing up on the dropdown for entry submission.  How can we get it included?   Many thanks....

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @dougvohden. To manually add your club for your installation, you'll need to add it to the ``$club_array``  constant in the /includes/constants.inc.php file. The array variable starts around line 58. Simply add it to the top of the list in quotes with a comma after it (be sure to enclose in **double-quotes** AND **add the comma OUTSIDE** of them), like so:
```
$club_array = array(
    "Keepers of Craft",
    "1.090",
    "#sovai",
    "10 Paces Brewing",
    "1000 IBUS",
    "1337 Brewing Collective",
    "The 1620 Home Brew Club",
    "2 Live Brew",
    // This array HAS 2300+ LINES BELOW HERE, to avoid errors
    // DO NOT copy the array above, just add in your club name at the top of it
";
```
In the meantime, you can direct your members to select OTHER from the drop-down and then manually enter the club name when they register or edit their account information.

I'll add the club to the list for the next release.

**Comment by dougvohden** [comment]
Thanks for adding the club to the array in the next release.   I will see if the organizer of the upcoming company is comfortable appending the array in the meantime.  

 Thanks!
M
  - Doug
