### ISSUE TITLE
Version 2.2.0 - Update timezones for UTC + 8 for Australia

### ISSUE THREAD

**Issue by rocket-pants** [geoffhumphrey/brewcompetitiononlineentry#1219]
Version: 2.2.0

Installation URL: competition.wasabc.org

Is your installation hosted on brewcompetition.com or brewcomp.com?
no

Description of Issue:
The timezone settings under website preferences is incorrect.
Currently has  "GMT + 8 Queensland, Perth, Northern Territory, Western Australia"
when you select this it sets the timezone to AEST (UTC + 10)

Actual timezones are
Queensland UTC+10 (no DST)
Perth / Western Australia UTC + 8 (no DST)
Northern Territory UTC + 9.5 (no DST)

I have not checked any other timezones (other that using Singapore makes it work for me in Perth)

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @rocket-pants, thanks for reporting. Indeed, those are incorrect in the dropdown in the current version. I'll correct them for the next version.
