### ISSUE TITLE
Version 2.1.13, not saving Optional Info for 7C Kellerbier

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1223]
Version: 2.1.13

Installation URL: Limbocomp.org/bcoem

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: Style 7C Kellerbier not saving Optional Info in database. I don't know if this is a problem in the latest version. The quick workaround I tried that worked was changing this statement at line 13 in process_brewing_inc.php:

 if ($_SESSION['prefsStyleSet'] == "BA") $optional_info_styles = array();
        else $optional_info_styles = array("21-B","28-A","30-B","33-A","33-B","34-B","M2-C","M2-D","M2-E","M3-A","M3-B","M4-B","M4-C","7-C","M1-A","M1-B","M1-C","M2-A","M2-B","M4-A","C1-B","C1-C");

I removed the leading zero on the "07-C" element of the array and optional info saves correctly. I don't know if it breaks something else looking for the leading zero.

Please check this on a current version.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @jimmyorkin - indeed, this was an issue with version 2.1.13. It has since been corrected - upgrading to the at least version 2.1.18 should take care of the issue.

**Comment by jimmyorkin** [comment]
Thanks Geoff.
