### ISSUE TITLE
Version 2.2.0 - Payment confirmation email doesn't list entry numbers correctly

### ISSUE THREAD

**Issue by julien-gibson** [geoffhumphrey/brewcompetitiononlineentry#1226]
Version: 2.2.0

Installation URL: enter.sabsosa.com.au

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: In the email that entrants receive after successful PayPal payment, the entry numbers paid for are not displayed, but in their place are 0Array, 0Array, 0Array etc.

I have made the following changes to the block of code starting on line 141 of ppv.php

		`foreach ($b as $key=>$value) {

			$updateSQL = sprintf("UPDATE %s SET brewPaid='1', brewUpdated=NOW( ) WHERE id='%s'",$prefix."brewing",$value);
			mysqli_real_escape_string($connection,$updateSQL);
			$result = mysqli_query($connection,$updateSQL) or die (mysqli_error($connection));

			$display_entry_no[$key] = sprintf("%.06s",$b[$key]);

		}`

Entry numbers are now listed correctly.

Cheers
Julien

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @julien-gibson - thanks for reporting and providing the fix! I've verified that it works and will include it in the next release.
