### ISSUE TITLE
Version 2.2.0 - Entry name containing a "%" character prevents creation of link to scanned PDF of scoresheets

### ISSUE THREAD

**Issue by diatonic** [geoffhumphrey/brewcompetitiononlineentry#1228]
Version: 2.2.0

Installation URL: https://idbeer.org

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue:

We had an entry in our most recent competition named "100% ..." and I had to replace the '%' character with the word "Percent" to get the scoresheet link to appear in the admin view of entries.

**Comment by geoffhumphrey** [comment]
Thanks for reporting @diatonic; I'll look into the issue and try to include a fix for special characters like % in entry names for scoresheet links, etc. I'll post back.
