### ISSUE TITLE
Barcode entry for judging number field can be max length 4 despite judging score sheet uploads expecting 6

### ISSUE THREAD

**Issue by quimnut** [geoffhumphrey/brewcompetitiononlineentry#1232]
Version:
2.2.0 

Installation URL:
https://comp.qabc.org.au

Is your installation hosted on brewcompetition.com or brewcomp.com?
no

Description of Issue:
We had a 4 character form field length on the barcode entry page due to prefsEntryForm using option 2,
"BCOE&M with Barcode/QR Code (Bottle Labels Only)"

https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/56fa7db096a84b000c048ad0fb5a782beccbfcad/admin/barcode_check-in.admin.php#L36

This was unexpected as we'use 6 digit judging numbers to upload the score sheets regardless of bottle labels. As such we had printed 6 digit barcodes with judging numbers for entry check in.

Thanks.

**Comment by geoffhumphrey** [comment]
Confirmed. Thanks for reporting, @quimnut. Apologies for any headaches this caused.

The fix will be to replace the line you referenced above in /admin/barcode_check-in.admin.php to simply:
``
$maxlength = 6;
``
I'll do that for the next version.
