### ISSUE TITLE
Setup Broken at step 7 between v2.3.1 tag and commit aa1ae07

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1251]
Version: v2.3.1 to commit aa1ae070a5f81844a4e418e61f37313ce1b2d4e0

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: I learned git! Pull of current master has a problem at setup step 7, selecting styles. Does not show any styles. Accept button goes to blank screen. backed up to the v2.3.1 tag and Setup completes.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
@jimmyorkin -  Confirmed. A fix has been implemented in the latest commit. Please verify and post back if you have any further issues.
