### ISSUE TITLE
Problem with Custom Style -Mead

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1252]
Version: 2.3.1+ at 3a8ef53 commit

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: First, this is not an issue for me now. I found a better way of doing what I want to do.

I was trying to duplicate some Mead and Cider styles as Custom Styles. So duplicating a Dry Mead in a custom style, I created the style and set the Strength and Carbonation options. This this combination I did not get the Optional Info text entry box. Should I have?

I decided to add the Required Info option. At this point I lost all the attributes like sweet and carbonation and did not get the required info text entry box. This is the problem combination.

I added the sweetness option to the custom style and everything opened up. I did not get an optional text entry but I could have used the required text entry box for optional information by describing what I needed in the Entry information.

Thanks,

Jimmy

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @jimmyorkin. Unfortunately, I'm not able to replicate this issue in my test environments. When adding a custom style (Admin > Competition Preparation > Styles Accepted > Add) and selecting the Mead style type from the drop-down, the four possible options become available. If I select Yes for Required Info, the carbonation, sweetness, and strength options also stay:
![image](https://user-images.githubusercontent.com/5216502/142454090-0fc1848e-087a-4e01-9cec-09124d4b8c93.png)

Perhaps it's a browser issue. Do you have a visual of what you're seeing? Also, if you could, access the browser console to see if there are any errors (using Developer Tools in Chrome, for example), and report them here, that would help with any JS related issues.

**Comment by jimmyorkin** [comment]
Here is what I am seeing. This is the custom style setup:
![image](https://user-images.githubusercontent.com/13592817/142472838-9337a2c8-2f7a-4018-b5d0-70faf93874aa.png)

This is what I see at the entry page. No required info field.
![image](https://user-images.githubusercontent.com/13592817/142474431-d8b968a7-94b5-41f0-8a94-c8813fca7fbe.png)

This is what I see in the console log when I load the Add Entry page:
12:14:49.026 GEThttps://bbo-bcoem/favicon.ico [HTTP/1.1 404 Not Found 0ms]
12:14:49.165 [Exception... "Favicon at "https://bbo-bcoem/favicon.ico" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 253"  data: no] FaviconLoader.jsm:253:22
12:15:04.919 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
12:15:04.919 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
12:15:04.919 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
12:16:06.628 Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
12:16:06.628 Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
12:16:06.628 Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified

If I add sweetness to the configuration:
![image](https://user-images.githubusercontent.com/13592817/142473617-2ab049ef-5011-4fb1-b316-59e414bda101.png)

Here is the entry page. Now I get the required info box and the other attribute buttons.
![image](https://user-images.githubusercontent.com/13592817/142473879-83bdcd36-3b4b-4273-91f7-8a1f6fb93f9d.png)

Here is the console log:
12:20:47.050 GEThttps://bbo-bcoem/favicon.ico
[HTTP/1.1 404 Not Found 0ms]

12:20:47.194 [Exception... "Favicon at "https://bbo-bcoem/favicon.ico" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 253"  data: no] FaviconLoader.jsm:253:22

I am using Firefox.

Let me know what else I can gather for you.

Thanks, Jimmy

**Comment by jimmyorkin** [comment]
That favicon.ico failing to load is because it is trying to load the file from the root, not the sub-directory I have bcoem in.

**Comment by geoffhumphrey** [comment]
Ah, I see. Let me look into it. Totally missed that is was a problem with the Add Entry function.

**Comment by geoffhumphrey** [comment]
@jimmyorkin, check the latest commit. I've completely reworked the JS that dictates which fields are displayed based upon the style's requirements stored in the DB. In my test environment, everything works as expected for all pre-defined and custom styles.
