### ISSUE TITLE
2.3.1 - E-Scoresheet for Mead does not show optional information

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1253]
Version: 2.3.1 commit 3a8ef53

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: Dry Mead M1A Collects Optional Info for things like honey varieties.. The Optional Info is not displayed in the e-scoresheet. I'm looking at the Classic Scoresheet.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Confirmed. I too discovered this a couple of days ago and made a fix. It's in the latest commit.

**Comment by jimmyorkin** [comment]
@geoffhumphrey I am not seeing a fix for this in the latest github commit. Is the fix still in a local workspace?

My plan is to implement the v2.3.x release for the Bluebonnet that opens January 3. Judging starts Jan 24. Just saying I don't need this fix immediately.

**Comment by geoffhumphrey** [comment]
Hi Jimmy... The fix [starts at 294](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/3a8ef53a85eb9673655f10166794414bca4fedec/eval/scoresheet.eval.php#L294) on the /eval/scoresheet.eval.php file in the 3a8ef53a commit.

I'm finalizing 2.3.2 as we speak, planning on releasing by December 1.

**Comment by jimmyorkin** [comment]
Geoff, On line 294 and 297, there are two spaces inside the single quotes inside the brackets indexing $row_entry_info array.

**Comment by geoffhumphrey** [comment]
Just discovered that. Commit 1e004d2e corrects it. Apologies for the confusion.
