### ISSUE TITLE
2.3.2 Alpha - includes tables with no places in winning entries summary

### ISSUE THREAD

**Issue by quimnut** [geoffhumphrey/brewcompetitiononlineentry#1256]
Version:
2.3.2

Installation URL:
https://comps.brisbanebrewersclub.com.au/

Is your installation hosted on brewcompetition.com or brewcomp.com?
no

Description of Issue:
Upgraded install (previously master branch from early September) that was a completed competition, we're a small club so use table based assignments.
Tables that had no overall placing entries show a empty tables in the results page and prezzo.

**Comment by geoffhumphrey** [comment]
Hi @quimnut; thanks for reporting. Confirmed. The latest master commit (aad77c2c) incorporates a fixe for this issue. This is only a bug if a given competition uses tables as their scoring method and does not have any placing entries (1, 2, 3, 4 or HM) for a given table.
