### ISSUE TITLE
2.3.2 Alpha - Admin editing entries fails with Table 'bcoem231.brewer_' doesn't exist message

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1257]
Version: 2.3.1

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: Commit 0cb98da1 breaks the administrator editing of entries. When you click on the pencil while in the Administration: Entries page.

It works ok in the previous commit of ac68c18. The browser window just show the message: Table 'bcoem231.brewer_' doesn't exist. It looks like an underscore is appended to the table name.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @jimmyorkin, thanks for reporting. Confirmed. Commit c77b7b08 and later do feature a fix for this issue, although I'm a bit puzzled why it happened in that commit and not any previous ones. The offending code hasn't been changed in a while. Oh, well - good news is that it's fixed now.
