### ISSUE TITLE
Bottle labels duplicate "Required Info"

### ISSUE THREAD

**Issue by SWBSAV** [geoffhumphrey/brewcompetitiononlineentry#1261]
Version:  2.3.1 Amateur Competition Edition

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com?
No

Description of Issue:
When printing bottle labels, the "Required Info" prints twice

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @SWBSAV, thanks for reporting. Confirmed. This was addressed in a previous commit - 19807371 - and will be in the next release.
