### ISSUE TITLE
2.3.2 - MySQL 8 Strict Mode Issue

### ISSUE THREAD

**Issue by Fencer04** [geoffhumphrey/brewcompetitiononlineentry#1263]
Version: 2.3.2

Installation URL: libme.org/proam

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: Error when registering participant: Truncated incorrect DOUBLE value: 'default'

I believe this is related to me being on MySQL 8 and strict being on by default. Turning off String Mode allows this to work but since this is the default for this installation it should probably work without having to turn it off.

**Comment by markalston** [comment]
This can be fixed without changing anything on the server by adding the following to /site/config.php at the end of all the mysqli_query's after the $connection is set.

`
mysqli_query($connection, "SET sql_mode ='';");
`
