### ISSUE TITLE
2.3.2 Purge participants does keep admin users but they're now invisible

### ISSUE THREAD

**Issue by gene1wood** [geoffhumphrey/brewcompetitiononlineentry#1266]
Version: 2.3.2

Installation URL: https://register.worldcupofbeer.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue:
We purged participants using the `Data Management` : `Purge` : `Participants` feature. The 

https://example.com/index.php?section=admin&go=participants

page now shows no participants, not even the admin users.

I'm still able to login as my admin user however.

In looking through the DB I can't tell where the data should be stored to try to understand what's causing this.

* Does the `users` table contain participants? brewers and staff and admins?
* What about the `brewer` table?
* How does the `staff` table factor in which is a relational table that links to `users`?
* How does the `userLevel` field in `users` relate to the `staff_staff` field in the `staff` table relate to the `brewerStaff` field in the `brewer` table?

**Comment by geoffhumphrey** [comment]
> Does the users table contain participants? brewers and staff and admins?

The users table contains more "sensitive" information like usernames and hashed passwords, as well as account recovery data like tokens and secret questions.

> What about the brewers table?

The brewer table is relational to the users table (uid relates to users: id). It contains participant details including their responses to whether they are _available_ to serve as a judge (brewerJudge), steward (brewerSteward), or staff (brewerStaff). Those three fields only store the user's indication of preference, they aren't used to indicate whether they're actually _assigned_ as one or more of those roles.

> How does the staff table factor in which is a relational table that links to users?

The staff table is relational to the user table (uid relates to users: id). This table is populated with assignments made by Admins (e.g., if the user is assigned into the judge pool, the staff_judge field value for that uid would be 1, if they're assigned as a staff member, the staff_staff field value would be 1, etc.).

> How does the userLevel field in users relate to the staff_staff field in the staff table relate to the brewerStaff field in the brewer table?

The userLevel field does not relate at all to staff_staff or brewerStaff. The userLevel field only indicates whether a participant is an Top-Level Admin (0), Admin (1), or general Participant (2).

**Comment by gene1wood** [comment]
Excellent, thank you for all that detail (I'll see if I can PR that into some help pages)

So what controls whether a given person is displayed in the "participants" web view?

For example, I have my user (same as all the other admins), which in the `users` table has `userLevel` of `0`, and doesn't exist in the `staff` table or `brewer` table.

Is a person only existing in `users` but not `staff` or `brewer` meant to happen or is this the result of purging participants, or is this the result of a bug in purging participants?

**Comment by geoffhumphrey** [comment]
Ah, there's the issue!

From the sound of it, the users table rows for all admins are being retained, but their relational rows in the brewer table are being purged, thus why you aren't seeing them in your list of participants in the UI.

Obviously, that shouldn't be happening. I'll dig into the /includes/process/process_archive.inc.php file to start.

Thanks for reporting this.

**Comment by MarsMug** [comment]
We have the same issue.

Site: https://competitions.londonamateurbrewers.co.uk/labopen
Version: 2.3.2

Affected admin users aren't on the participants list, which means they can't have their roles changed, and also can't add entries or edit any details of their account.

Is there a way to resolve this on the db side? For now the affected users are going to register with new accounts.

**Comment by graemecoates** [comment]
Manually setting up rows in brewer and staff joined to the uids in question should fix this (it worked in testing it for me). Ideally, the archive/purge process shouldn't purge away admin level users from the table user (or their corresponding brewer and staff entries) in any way, which is why we got to this point. 

@geoffhumphrey of note, in this circumstance I noted that, if there wasn't a corresponding brewer row for the logged in user, when using "Add Entry", it returned a seemingly random entrant name in the Brewer Name field - I'm not sure what query it's doing, but it looks wrong in that situation!

Also, in poking around, I noted the field "brewing.brewBrewerID" is relational to "user.id"... assume that was planned, but the nomenclature is confusing....

**Comment by gene1wood** [comment]
To work around the data loss here and to get these users working again I did `INSERT` statements in the `brewer` and `staff` tables to create records for the `uid` of the users that were in the `users` table but missing from `brewer` and `staff`. Once I did this the users affected were working again (as @graemecoates  mentions above)

**Comment by gene1wood** [comment]
One side effect of this corruption, is that any brewers that end up in this corrupted state, if they enter beers in the competition before the corruption is fixed, those brewing entries have no brewer ID and get orphaned.

Problem is, pull sheet reports don't look to see if the entry has a non-null brewerId and so pull sheets get these corrupted entries in them.
