### ISSUE TITLE
v2.2.0 - Any issue with updating while a competition is accepting entries? (but before the comp is in progress)

### ISSUE THREAD

**Issue by AdrienM76** [geoffhumphrey/brewcompetitiononlineentry#1276]
Version:2.2.0

Installation URL: https://bataille.deadyeast.org

Is your installation hosted on brewcompetition.com or brewcomp.com? no

Description of Issue:

We'd like to take advantage of Electronic Score Sheets for our comp on Feb 5th, but are still on version 2.2.0. I just wanted to know if there are any issues with updating to the newest version at this time. Our comp is currently open to entries and we'll be sorting soon. Can I upgrade now? Would it be best to wait till we've marked everything received and entry is closed? Or, should we forgo the new version till our next competition?

Thanks for any guidance.

**Comment by geoffhumphrey** [comment]
Hi @AdrienM76, my advice would be to wait until you have marked everything received and entry is closed to update, just to be safe. Generally, the update is seamless, but there may be a slight chance that an entrant is adding or editing an entry at the exact time you implement the update that may cause some unexpected results.

Of course, definitely make sure to perform a back-up of your DB tables before attempting the upgrade, just in case you need to revert back to 2.2.0.

**Comment by AdrienM76** [comment]
Thanks!
