### ISSUE TITLE
Missing sterilize function in 2.4.0

### ISSUE THREAD

**Issue by quimnut** [geoffhumphrey/brewcompetitiononlineentry#1277]
Version:
2.4.0

Installation URL:
https://comps.brisbanebrewersclub.com.au/

Is your installation hosted on brewcompetition.com or brewcomp.com?
no

Description of Issue:
Upgrade from last tagged release 2.3.2.1

Throwing error;
`PHP Fatal error:  Uncaught Error: Call to undefined function sterilize() in /var/www/html/update/off_schedule_update.php:649\nStack trace:\n#0 /data/bcoem/site/bootstrap.php(132): include()\n#1 /var/www/html/index.php(11): require_once('/data/bcoem/sit...')\n#2 {main}\n  thrown in /var/www/html/update/off_schedule_update.php on line 649`

I see the function is new in some 2.4.0 commits but I cannot see where it is defined.

Thanks

**Comment by geoffhumphrey** [comment]
The sterilize function moved to the /paths.php file. Once you've configured and uploaded, this will not be an issue. I'll update the release notes.

**Comment by GaetanNaulin** [comment]
Hi,
I encountered the same problem.
The sterilize function is not located in the project since the last release (even in paths.php).
Temporary I duplicate the old sterilize function in paths.php.

**Comment by geoffhumphrey** [comment]
Apologies for the confusion here. The updated paths.php file did not make it into the 2.4.0 release on 23 January. The latest release and [master commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/paths.php) corrects this issue.

**Comment by quimnut** [comment]
Looks good, thanks.
