### ISSUE TITLE
Enhancement: Don't Zero Out Judging Numbers When Checking In Entries

### ISSUE THREAD

**Issue by eric-martin** [geoffhumphrey/brewcompetitiononlineentry#1279]
Version: 2.3.0

Installation URL: https://www.kcbmcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? Unknown

Description of Issue:
When scanning entries during sorting, it would be nice not to zero out the existing judging number when left blank. This would allow us to generate judging numbers before sorting but only have to scan in the entry number during sorting.

**Comment by geoffhumphrey** [comment]
Hi @eric-martin, thanks for the suggestion. Seems like a reasonable request.

The function was initially created with using barcoded Judging Numbers in mind, thus the reason for zeroing it out upon submittal. In the latest commit, I've made a small adjustment to the [/includes/process/process_barcode_check_in.inc.php file](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/includes/process/process_barcode_check_in.inc.php) to prevent that from happening. If no Judging Number is present in the POST var (user leaves the field blank in the UI), the script will use the judging number already present in the DB for each entry.

**Comment by eric-martin** [comment]
Thanks @geoffhumphrey! We will look forward to this enhancement in our next comp.
