### ISSUE TITLE
2.4.0 Error Printing Round Labels any size/quantity/format - "FPDF error: Unknown label format:"

### ISSUE THREAD

**Issue by fourums** [geoffhumphrey/brewcompetitiononlineentry#1280]
Version:
2.4.0

Installation URL:
https://ibuopen.brewcompetition.com/

Is your installation hosted on brewcompetition.com or brewcomp.com?
brewcompetition.com

Description of Issue:
When trying to print round label I get the error "FPDF Error: Unknown Label Format"

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by fourums** [comment]
Clicking the Letter size "entry number" and "judging number" links the generated a PDF with 6 numbers on a single 5160 Avery Label, not 1 number on 6 labels. The dropdown options for letter, and A4 size generate blank pdfs not the same errors as the round labels. I can provide the pdf for Judging number letter if you want, let me know. This issues was very inconvenient for our competition check-in process.

**Comment by geoffhumphrey** [comment]
@fourums, this is related to #1281, the other issue you reported. I verified the ability to download labels in all formats for all label types.

> Clicking the Letter size "entry number" and "judging number" links generated a PDF with 6 numbers on a single 5160 Avery Label, not 1 number on 6 labels. 

Yes, this is as intended. These labels are intended to be cut manually into (up to) six individual stickers. This was the first and only option until the round labels were rolled out later.

**Comment by fourums** [comment]
@geoffhumphrey Thanks I see these working as expected now, appreciate it!
