### ISSUE TITLE
2.4.0 Entry Required Info Scoresheet Labels - Generates Blank PDF

### ISSUE THREAD

**Issue by fourums** [geoffhumphrey/brewcompetitiononlineentry#1281]
Version:
2.4.0

Installation URL:
https://ibuopen.brewcompetition.com/

Is your installation hosted on brewcompetition.com or brewcomp.com?
brewcompetition.com

Description of Issue:
Entry Required Info Scoresheet Labels generates a blank pdf regardless of which option(s) are selected.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @fourums, thanks for reporting. I tracked down the issue and implemented a fix for all hosted installations. This should be working as expected now.

For those who are experiencing a similar issue on non-hosted installations with version 2.4.0, incorrect variable declarations in the /includes/url_variables.inc.php file are the culprit. The [corrected url_variables.inc.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/includes/url_variables.inc.php) file is available in the latest commit and is safe to upload to your 2.4.0 installation.
