### ISSUE TITLE
2.3.2 Notes erased if you Edit Entry

### ISSUE THREAD

**Issue by donutbrew** [geoffhumphrey/brewcompetitiononlineentry#1284]
Version:2.3.2

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue:

Admin notes and Staff notes get erased if you change a beer style in the Edit Entries section. 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @donutbrew, thanks for reporting. Confirmed. I tracked down the cause in the /js_includes/add_edit_entry.min.js file. I've fixed it and the [updated code](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/js_includes/add_edit_entry.min.js) is in the latest commit.
