### ISSUE TITLE
Enhancement - Electronic Score Sheets, Option to turn off the timer

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1286]
Version: 2.3.2+

Installation URL: https://bbbrewoff.com/bcoem/

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: I am getting comments from Judges that they do not like the floating timer in the score sheets. They say it gets in the way.

No rush if you want to do something. We are almost done for this year's competition.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
In the next version, judges will be able to expand/collapse the timer with a tap or click. This seemed like a reasonable compromise between the judges/organizers who requested it and those, like yours, that find it's in the way.
