### ISSUE TITLE
BCOE&M v2.4.0 - Entry Count went from 508 to 0 and shows a -508 unconfirmed entries.

### ISSUE THREAD

**Issue by darthtexan** [geoffhumphrey/brewcompetitiononlineentry#1291]
Version:2.4.0

Installation URL: https://rendezbrew.brewcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? Brewcomp

Description of Issue: Our entry count should be at 508, but suddenly changed to 0.  The competition status shows 508 confirmed entries and -508 unconfirmed entries.  Additionally, when you click on the "Manage Entries" option you get the following error message: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE brewBrewerID='default' AND brewPaid='0' AND brewReceived='1'' at line 1"

Our registration is open and filling up quickly, so please assist as quickly as possible.  Thanks.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @darthtexan, thanks for letting me know. You should be good to go now. There was a server-wide change to PHP 8 that happened without my knowledge - BCOE&M is not fully compliant with it as yet. I've set the PHP version back to 7.4 and things appear to be running as expected. Please keep me informed if there are any further issues.

The next version, 2.4.1, should be fully compliant with PHP 8. Continued testing will bear that out.

**Comment by darthtexan** [comment]
Thank you so much!  Appreciate it!

Regards,
