### ISSUE TITLE
Using nulls as arrays (backwards incompatible change in PHP7.4)

### ISSUE THREAD

**Issue by graemecoates** [geoffhumphrey/brewcompetitiononlineentry#1300]
Version:
2.4.0.3

Installation URL:
competitions.londonamateurbrewers.co.uk/brewyourbestipa

Is your installation hosted on brewcompetition.com or brewcomp.com?
No

Description of Issue:

The upgrade from PHP7.3 to PHP7.4 contains the following backwards incompatible change:

https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.non-array-access

As a result, there are several code instances that cause PHP Notices to be thrown. Locations include:
includes/db/mods.db.php on line 28:
do { $mods_display[] = $row_mods['id']; } while ($row_mods = mysqli_fetch_assoc($mods));

sections/sidebar.sec.php on line 345:
if (($row_archive['archiveDisplayWinners'] == "Y") && ($row_archive['archiveStyleSet'] != "")

**Comment by geoffhumphrey** [comment]
Hi @graemecoates - this issue (and issues like it) is currently being worked on. The goal is to have the application fully compatible with both PHP 8 and MySQL 8. I believe the latest master commit does fix both issues you've detailed, but many more are cropping up in testing. That said, please report any you encounter by commenting here. Thanks!
