### ISSUE TITLE
Enhancement - Add "Garden State Homebrewers" to club_array in constants.inc.php

### ISSUE THREAD

**Issue by bobwright011** [geoffhumphrey/brewcompetitiononlineentry#1305]
Version:
2.4.0.3

Installation URL:
https://gshomebrewcomp.com

Is your installation hosted on brewcompetition.com or brewcomp.com?
No

Description of Issue:
Could we please add "Garden State Homebrewers" to the club_array in the constants.inc.php file?  I manually edit it each time for our comp, but it would be nice to have it on other comp sites.
@geoffhumphrey -  Let me know if you want me to fork the file and do the edit for you. I am happy to help.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Will do! I've added it to the $club_array for now and will have that in an upcoming commit. That said, however, I'm looking at providing a function for admins to add any clubs to the list via the UI with the ones in the $club_array as a starting point. Hoping to have that for 2.4.1.
