### ISSUE TITLE
When I try to use the Print Bottle Labels "With Required Info" all I get is a blank PDF

### ISSUE THREAD

**Issue by OriginalDrBeer** [geoffhumphrey/brewcompetitiononlineentry#1306]
Version:Wish I knew

Installation URL:https://www.mashers.org/2022/

Is your installation hosted on brewcompetition.com or brewcomp.com? Not sure

Description of Issue:

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by OriginalDrBeer** [comment]
Hi, Although I am a 35 yr BJCP judge (GM, Former Exam Director, etc)I have not organized a competition in quite a while and I am totally new to this SW. To make matters worse I have pretty much be thrown to the wolves in that the pre-pandemic organizer of our competition who said he'd help out has ghosted me and the SW guru who installed the system started his own brewpub and  basically has few/no cycles available and delayed our being able to access the system by over a month when he ran into installation issues.

Although I am a retired C++ SW programmer (15yrs) and SQL+Apache front end / back end Tech Support Engineer (20yrs) powers that be make it so that I only have organizer level access to the SW. I've accessed the help in the system and at the https://www.brewcompetition.com/ help pages and searched this forum but don't see anyone reporting a similar issue.

So I am not sure if I'm not using the SW properly and/or misunderstanding how it is supposed to work. The last time I organized a comp it was using FileMaker Pro. From what I can glean instead of the way things were once done in that the bottle labels had entrant info but NO pre-assigned number in the system and as an entry was checked in a label with a number was affixed to it and that number then entered into the DB this system seems to use multiple numbers with one being assigned at the time the registrant enters the beer into the SW online and then a separate "judging" number is supposed to be affixed to each entry when the label the entrant printed and put on the bottle has either its QR or Barcode scanned or is somehow otherwise manually entered into the system.

While it seems a little cumbersome to have to have 2 different numbers for each entry since it just seems like another extra piece of data to get mixed up I can work with it. So assuming I have understood that part when I go into "Entries and Participants" and click "Manage" next to "Entries" I see a column named "Entry" with one number and right next to it a column named "Judging" with a different (presumably randomly assigned) number.

So ideally when we go to perform the registration check in what I thought I should be doing is going to the "Entry Sorting" functionality and under the letter format (so I can use the Avery 5160 label sheets we have on hand) choose one of the options below where it says "Entry Numbers" & "Judging Numbers" that read "With Required Info" to pull down the "Number of Labels per Entry" I want to print. We're doing 2 bottles per entry so I was figuring we'd go with 3 so we can attach one label to each bottle and the third to one of the bottle labels just to keep as a hard copy backup.

No matter which of the various "With Required Info" options I choose or what the number of labels I choose I get a pop up to save to PDF and whether I try to print on my Windows Laptop or Chromebook I get the same thing, a one page blank PDF!!

If I hover over the "Entry Numbers" or "Judging Numbers" options above the "With Required Info" a bubble pops up that says "6 numbers per label" and if I choose either of these it does print a PDF which seems to contain either the "Entry Numbers" or "Judging Numbers" (based on which one I chose) along with what seems to be the style category number and subcategory letter next to it in parentheses.

So I'm not sure if I'm using the SW incorrectly (sadly, as someone who wrote a lot of technical  documentation in my day the docs for this leave a lot to be desired and I'd be happy to help but first I need to get a handle on how to actually use the SW) or if it's not working properly....

I apologize that this post is long but our entry deadline is the 13th (already pushed back a week) and competition is the 21st and I'm facing a potential disaster if I can't figure out how to print bottle labels so we can register the entries and the prior pre-pandemic organizers have left me hanging.....

TYVM in advance

**Comment by geoffhumphrey** [comment]
Hello, @OriginalDrBeer - apologies for the tardy reply. Unfortunately, I'm not able to replicate the issue you describe in any of my 2.4.0 testing instances:

> No matter which of the various "With Required Info" options I choose or what the number of labels I choose I get a pop up to save to PDF and whether I try to print on my Windows Laptop or Chromebook I get the same thing, a one page blank PDF!!

FWIW, for this:

> So ideally when we go to perform the registration check in what I thought I should be doing is going to the "Entry Sorting" functionality and under the letter format (so I can use the Avery 5160 label sheets we have on hand) choose one of the options below where it says "Entry Numbers" & "Judging Numbers" that read "With Required Info" to pull down the "Number of Labels per Entry" I want to print. We're doing 2 bottles per entry so I was figuring we'd go with 3 so we can attach one label to each bottle and the third to one of the bottle labels just to keep as a hard copy backup.

The resulting PDF will (should) print each entry or judging number six times on each label - which can then be cut and attached to the bottles. Again, in my test instances, this was working as intended.

Another option will be to use the [Barcode/QR Code Check-in Procedure](https://brewcompetition.com/barcode-check-in), which uses pre-populated [barcode and round bottle labels](https://brewcompetition.com/barcode-labels).

**Comment by magnasaurus** [comment]
I ran into this issue last weekend right before our check-in and sort and fortunately was able to locate the cause but not come up with a proper fix.

The quantity of labels is passed in via the 'sort' parameter but for some reason the value of sort isn't the number of labels requested but rather is the string 'default' which php converts to 0. I should note in my case the command line is correct with 'sort=3'.

Changing line 161 in ./output/labels.output.php from... 
    for($i=0; $i<$sort; $i++) {
to...
    for($i=0; $i<3; $i++) {
allowed me to work around the issue. I hope this helps.

**Comment by OriginalDrBeer** [comment]
Thank you very much! I passed this along to our volunteer sysadmin. 

Our competition is this coming Saturday and we processed our entries last weekend just using labels with entry numbers for the judging numbers. So your work around didn't come in time for this year but we left Cider and Mead out and will hopefully do them in the Fall so if there isn't a formal fix for this by then the work around will be of use to us by then....

**Comment by geoffhumphrey** [comment]
Thank you @magnasaurus for helping out with this! It led me to the root of the cause, a typo in the /includes/url_variables.inc.php file. If you replace that file with [this one](https://raw.githubusercontent.com/geoffhumphrey/brewcompetitiononlineentry/master/includes/url_variables.inc.php) in the includes directory, the requested amount of labels will be generated. Apologies not thinking of this earlier. Sometimes it's the most simple answer that provides a solution.
