### ISSUE TITLE
v2.4.0 - Cannot Add new Participants or Update Existing Participants

### ISSUE THREAD

**Issue by jeffrey-simonds** [geoffhumphrey/brewcompetitiononlineentry#1312]
Version: BCOE&M 2.4.0 (e) mySQL 5.7 PHP 7.4

Installation URL: https://www.mashers.org/2022/

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: When attempting to add and save a new participant or assign existing participants as judges we receive the following error: Truncated incorrect DOUBLE value: 'default'

Our competition is this weekend, Saturday 5/21 so any help would be very much appreciated as we're in a crunch.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @jeffrey-simonds - thanks for reporting. I'm investigating. Please see Issue #1301 for another option as of today.
