### ISSUE TITLE
When printing BJCP report to XML I get a file that says only "No organizer has been designated" but printing it to PDF creates a correct report

### ISSUE THREAD

**Issue by OriginalDrBeer** [geoffhumphrey/brewcompetitiononlineentry#1313]
Version: Not sure but think it's the most recent one

Installation URL:shers.org/2022/

Is your installation hosted on brewcompetition.com or brewcomp.com? No but we're STRONGLY considering it for next year

Description of Issue: When I go into Reports and from the Admin Dashboard and choose "XML" next to the BJCP Points option to print the report as an XML file when I open the file it says only "No organizer has been designated" and has no report in it. I double checked the Competition Info, Manage Contacts and I am definitely listed as "Competition Organizer". If I choose to print to PDF instead it creates a correct report. PDF is a pain though because we kept running into the (previously reported) Truncated Double Value error when trying to add judges in the last days before the competition which forced me to resort to using the "old school" method of an Excel Spreadsheet to do the final judge and steward assignments and I'd really like to have been able to print this out to XML so I could edit it. 

As it stands now I'll have to create my own spreadsheet by cutting and pasting from the PDF and then hand edit that with the last minute changes. :-(

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.
![Competition Contacts](https://user-images.githubusercontent.com/105024214/169707619-5c10de93-e54f-4d6e-a676-fd80315d317a.jpg)
[2022_Noonan_Competition_BJCP_Points_Report .xml.txt](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/8749894/2022_Noonan_Competition_BJCP_Points_Report.xml.txt)

**Comment by geoffhumphrey** [comment]
For that report to populate with the appropriate judge, steward, and staff data, an Organizer needs to be designated in the Admin > Participants > Staff function. I've added a note to the report saying such for the next version.

**Comment by OriginalDrBeer** [comment]
Thanks for the fast reply!
Unfortunately I just tried that and got the dreaded "Truncated incorrect DOUBLE value: 'default'" error :-(. 

Our IT guy did try to apply patches and updates last Tue but it didn't go well and I think he may have backed them out. This is why we're seriously considering going with your hosting it especially because our IT guy now runs a very successful, busy (and awesome) brewpub and his time as our IT guy is limited and although I spent 20 years as a Tech Support Eng (after 20 as a SW Eng) supporting front end client to back end SQL Server and Apache systems (retired from Parametric Technologies in 2015) I'm not really looking to go back to this.

However I would be interested in working with you to improve the documentation. It's pretty terse at the moment and I also did rotations doing SW Testing (in house "alpha" and 1st draft Technical Docs). If you want to contact me please use the contact for Jay Hersh at https://www.mashers.org/2022/ since I don't want to put my email on a public forum and I'll follow up with you.

Cheers,

- Jay
