### ISSUE TITLE
2.4.0 Remove "Best of Show"

### ISSUE THREAD

**Issue by cgspeck** [geoffhumphrey/brewcompetitiononlineentry#1316]
Version: 2.4.0
Installation URL: https://comps.westgatebrewers.org
Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue:

We don't have or use the concept of "Best of Show" in our competitions, yet I am finding references to it in many publicly facing places and reports:

- on the home page after results are posted
- on "Table Results - Winners Only with Scores" report
- on "All Results - All with Scores" report
- on "All Results - Winners Only with Scores" report
- on "All Results - All without Scores" report
- on "All Results - Winners Only without Scores" report
- "Mini-BOS" column when an entrant is viewing their results at `/list`
- other places?

Is there any setting or switch I can use to completely hide public references to "Best of Show" and "Mini-BOS"? It will be _very_ confusing for our participants to see this nomenclature/unused category in various places on the site.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi Chris - you can remove Best of Show from the public facing sections of your installation. Best of Show (BOS) is associated with Style Types (Admin > Competition Preparation > Manage Style Types), and each Style Type can have its BOS enabled or disabled. Disabling BOS for all of them will remove the public-facing references, including the Awards Presentation. This will also remove any BOS reference in the "Table Results" and in the "All Results" reports.

This will not remove the BOS or Mini-BOS references from each participant's Entries list on their My Account page and some reports, but if there's no data associated with BOS, the columns/lines will be blank.

Hope this helps.

**Comment by cgspeck** [comment]
Thanks
