### ISSUE TITLE
2.4.0(e) PayPal Fees not computed Correctly

### ISSUE THREAD

**Issue by cshinn89** [geoffhumphrey/brewcompetitiononlineentry#1317]
Version: 2.4.0(e)

Installation URL:https://njstatefairhomebrew.brewcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? yes

Paypal fees do not seem to be computing correctly resulting in a post fee amount of less than the individual entry fees. for instance a $8 entry fee charges the entrant a total of $8.78 then paypal's fee is $0.80 resulting in a final amount of $7.98.
a entrant adding 5 entries has a fee of $40 and the software computed the total amount of $41.90 then paypal charges $1.95 resulting in a final amount of $39.95 for the competition organizers.
currently paypal fees look like they are 3.49% + $0.49 for standard USD transactions.

**Comment by geoffhumphrey** [comment]
Interesting. The calculations that are being used currently in the code are ``((total to pay * .035) + 0.50)``, rounded to the hundredth place. Results in, as you say, $8.78. But it looks like PayPal isn't exactly doing that according to what you've reported - looks like they're taking out another $0.02 for some reason. 

To get to the correct amount to offset their fees, the formula would need to change to ``((total to pay * .038) + 0.50)`` - upping the percentage to 3.80%. 

According to PayPal's own documentation, the fees have not changed from the 3.49% + $0.49 for USD you cited, so something definitely isn't right here. I'll investigate further.

**Comment by cshinn89** [comment]
I think the issue may be that paypal is calculating it's percentage on the total from BCOEM so the percentage calculation becomes more complicated.  A more accurate way of computing the total would be (entry total + fixed fee) / (1-0.0349) this should calculate the percentage on top of the fixed fee paypal charges and account for it all but i encourage you double check my work. 
For a $8 fee this would be (8 + 0.49) / 0.9651 = 8.80 (rounded to the nearest hundreth) then paypal will take 8.80 * 0.0349 = 0.31 + .49 = 0.80 paypal fee leaving the organizers with the original $8 fee.

**Comment by geoffhumphrey** [comment]
The new way of calculating referenced by @cshinn89 above has been incorporated into the 2.5.0 Beta release.
