### ISSUE TITLE
zip is invalid

### ISSUE THREAD

**Issue by rbranden** [geoffhumphrey/brewcompetitiononlineentry#1321]
2.4Version:

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com?

Description of Issue: Trying to download 2.4 zip.  Zip is invalid

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
The v2.4.0 [zip](https://github.com/geoffhumphrey/brewcompetitiononlineentry/archive/refs/tags/v2.4.0.3.zip) and [tar](https://github.com/geoffhumphrey/brewcompetitiononlineentry/archive/refs/tags/v2.4.0.3.tar.gz) files here on GitHub appear to be downloading properly now. I've extracted both and the file structure is in tact - no errors. Try again?
