### ISSUE TITLE
Version 2.5.0beta: Edit account info advising you can only edit your own info.

### ISSUE THREAD

**Issue by quimnut** [geoffhumphrey/brewcompetitiononlineentry#1325]
**Verify the Following**
Reporting About the Latest Version? Yes
Searched Issue Reports for Bug? Yes

**BCOE&M Info**
Version: 2.5.0beta
Installation URL: https://comp.qabc.org.au/
Hosted Installation? No

**Describe the Bug**
When a non-admin user attempts to edit their account info, they receive the message, 'You can only edit your own profile'

**To Reproduce**
1. Register
2. Attempt to edit your account info
3. See error

**Expected Behavior**
Edit account info dialog

**Screenshots**

**Server Environment**
- PHP Version: 7.2.24
- MySQL Version: 5.7.38
- Other Info: dockerised behind traefik edge router

**Local Environment**
 - OS: ubuntu 18
 - Browser: chrome/ff
 - Browser Version: various

**Additional Context**
Installed from tagged release

**Comment by geoffhumphrey** [comment]
Like Issue #1326, I cannot confirm this on my own test servers, both running Linux / Apache 2.4, which leads me to believe it's an environment issue - most likely having to do with session variables. I'm running PHP version 7.4.28, MySQL version 5.7.23 on one and PHP 8.0.15, MySQL 8.0 on the other.

Looks like you're running an older/deprecated version of PHP (7.2.24). If possible, I would suggest upgrading to the latest stable 7.4 version, [7.4.30](https://www.php.net/distributions/php-7.4.30.tar.gz), or the latest stable 8.0 version, [8.0.21](https://www.php.net/distributions/php-8.0.21.tar.gz).

**Comment by quimnut** [comment]
It's ubuntu 18 lts with updates for the record.

**Comment by quimnut** [comment]
Running 20.04 now, php 7.4.3 and mysql 8.0.29. 

It has resolved this issue. Thanks.
