### ISSUE TITLE
Version 2.5.0 beta: New registrations can't edit account info

### ISSUE THREAD

**Issue by quimnut** [geoffhumphrey/brewcompetitiononlineentry#1328]
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

Version: 2.5.0 beta
Installation URL: https://comp.qabc.org.au/
Hosted Installation? No

After registering, a new user cannot edit their account info until next login.

**To Reproduce**
1. register
2. edit account info
3. See error "You can only edit your own profile"
4. logout / login
5. edit account info
6. see no error

**Expected Behavior**
Able to edit profile after registering

**Server Environment**
- PHP Version: 7.4.3
- MySQL Version: 8.0.29-0ubuntu0.20.04.3
- Other Info: 

**Local Environment**
 - OS: w10
 - Browser: ff, edge
 - Browser Version: latest

**Additional Context**
This only occurs during the registration session.

I see this warning in the logs during registration.
PHP Warning:  session_name(): Cannot change session name when session is active in /var/www/html/includes/process/process_users_register.inc.php on line 380, referer: https://comp.qabc.org.au/register/entrant

This suggests the session_name() behavior changed with php 7.2 https://bugs.php.net/bug.php?id=76358

**Comment by geoffhumphrey** [comment]
Confirmed. Will post back with a fix soon.

**Comment by geoffhumphrey** [comment]
There was an incorrect variable in the /includes/process/process_users_register.inc.php file on [line 161](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/dda3c5eeddf78fab2384f4a61deba7d4fa4b5a6c/includes/process/process_users_register.inc.php#L161). That line should be changed to:
```
'brewerEmail' => $username,
```

Once that's done, users will be able to edit their account information immediately after registration. You can [inspect the change here](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/dda3c5eeddf78fab2384f4a61deba7d4fa4b5a6c/includes/process/process_users_register.inc.php#L161). Note that the session_name and session_start calls have also [been removed](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/dda3c5eeddf78fab2384f4a61deba7d4fa4b5a6c/includes/process/process_users_register.inc.php#L380) to address the warning.

The work-around is just how you described: register, log out, log back in, edit account.
