### ISSUE TITLE
Account registration and entry not opening  version 2.4.0

### ISSUE THREAD

**Issue by afcdmc** [geoffhumphrey/brewcompetitiononlineentry#1333]
Version: 2.40

Installation URL:  https://homebrewerspr.brewcompetition.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? yes

Description of Issue:
 when I put a date to open account registration and entry registration in the dashboard and the site is still closed!! only open for registration is for judges!! I tried inputting yesterday's date and still, registration closed. any ideas?

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.
<img width="731" alt="CleanShot 2022-08-19 at 14 56 16@2x" src="https://user-images.githubusercontent.com/29015103/185688282-40ec923a-6fed-4177-9127-92cbfb8e9d2c.png">
<img width="668" alt="CleanShot 2022-08-19 at 14 56 31@2x" src="https://user-images.githubusercontent.com/29015103/185688300-3593dbae-1ba0-4442-b621-4647cb44bcee.png">

**Comment by geoffhumphrey** [comment]
Hi @afcdmc. In looking at your installation, it looks like your judging session is in the past (May 25, 2022). Once you either remove that judging session or change the date to one that's in the future, the account registration date will open.

Hope that helps.

**Comment by afcdmc** [comment]
> 

Thanks! that was it!! another related topic is there a way to import a past participant's csv exported file?

**Comment by geoffhumphrey** [comment]
Hi Ariel, I just sent an email to you as well. I was able to recover 105 of your participants. Hopefully that will work for you. 

In the future, when you're ready to reset your installation after this competition iteration and want to keep participants, make sure to choose Option 2 when Archiving (Admin > Data Management > Manage Archives - this is only for Hosted accounts) or make sure not to choose "All Purge Functions" from Admin > Data Management > Purge.

Cheers!
