### ISSUE TITLE
Version 2.5.0 (e) Beta: Error When Printing Bottle Labels (HTTP ERROR 500)

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#1334]
**Verify the Following**
Reporting About the Latest Version? **Yes**

Searched Issue Reports for Bug? **Yes**

**BCOE&M Info**
Version: **2.5.0 (e) Beta**
Installation URL: **https://seasonal.gtabrews.ca/**
Hosted Installation? **No**

**Describe the Bug**

When trying to print any of the bottle labels, I get a HTTP ERROR 500 error:

Eg.
https://seasonal.gtabrews.ca/output/labels.output.php?section=admin&go=entries&action=bottle-judging&filter=default&psort=5160

![image](https://user-images.githubusercontent.com/1551339/187043357-e0e2307d-3b8b-4aa8-901f-6956874fc19d.png)

**To Reproduce**

1. Go to 'Entry Sorting' -> 'Print Bottle Labels (PDF)'
2. Tried both of these options:

1) Judging Numbers
2) 'With Required Info - All Styles (Judging Numbers)'
![image](https://user-images.githubusercontent.com/1551339/187043502-6e7438e8-77e3-4923-9f56-35e7e5fe8e38.png)

**Expected Behavior**
I expect a PDF to be generated for print or download

**Screenshots**
(Screenshots above)

**Server Environment**
Environment Info:PHP Version – 7.4.30;MySQL Version – 5.7.39-42-log

Hosted on SiteGround

**Local Environment**
 - OS: Win10
 - Browser: Chrome
 - Browser Version: Version 104.0.5112.102 (Official Build) (64-bit

**Additional Context**
My competition sorting is tomorrow, so I was really hoping to be able to print sorting labels tonight...

@geoffhumphrey have you seen anything like this yet with 2.5.0 Beta?

Has anyone else seen anything like this?

**Comment by ercousin** [comment]
I've been trying to debug, without much progress.

As an experiment... I tried cloning my database, then loading it into a clean install of the latest non-beta version (2.4.0). Unfortunately that doesn't resolve my issue.

This allowed me to print the top labels:
![image](https://user-images.githubusercontent.com/1551339/187044942-a667ff65-10ad-4256-8108-b9f83a010c56.png)

However, this workaround/hack still didn't work to generate correct side labels (aka 'with required info').

The generated PDF is blank:
![image](https://user-images.githubusercontent.com/1551339/187044988-c29fe291-c683-463f-8f17-a90e1d65f015.png)

**Comment by ercousin** [comment]
Okay, I seem to have a workaround now. I was able to get the 'Required Info' labels to generate by re-applying the fix from #1306 on top of 2.4.0

This is a pretty tedious workaround though, since I'm going to have to manually export the MYSQL database from my main install (on 2.5.0 Beta) then re-import to my debug install (on 2.4.0) every time I want to print labels.

**Comment by ercousin** [comment]
Going back to the issue, it seems that not only Sorting Bottle Labels are broken in 2.5.0, I see that a few other PDF generators are broken. I'll summarize below which things work, and which don't to try and help with triage.

**NOTE:** I haven't marked any entries as rec'd yet, since this is pre-sorting.

Name Tags are broken:
![image](https://user-images.githubusercontent.com/1551339/187046011-afc113e2-64a6-443c-a1b8-c8d077b5596d.png)

Scoresheet labels are broken:
![image](https://user-images.githubusercontent.com/1551339/187046025-1395d61e-db4e-489b-9a5b-19d0ddf98cd2.png)

Sign In sheet generates PDF, but it's empty:
![image](https://user-images.githubusercontent.com/1551339/187046133-6b52c2f9-fbec-435c-8a18-14ee52959473.png)

The BJCP Points report seems okay, the judges/organizer names and point values are populated:
![image](https://user-images.githubusercontent.com/1551339/187046192-bf61123c-ab6e-404f-adfd-a689a4493b53.png)

This button generates an empty PDF:
![image](https://user-images.githubusercontent.com/1551339/187046230-9ebbfb0c-144a-4577-9b81-f12dd13874c9.png)

![image](https://user-images.githubusercontent.com/1551339/187046220-461d24db-e52f-459d-95bc-1b6bc6868ef2.png)

The inventory PDF button seems to work:
![image](https://user-images.githubusercontent.com/1551339/187046297-e392c75f-373b-4e36-b9a3-6f6a85033c64.png)

![image](https://user-images.githubusercontent.com/1551339/187046287-fea923ac-02e7-43e2-9e9e-a1791d778ff0.png)


The CSV export functions seem okay to me.

**Comment by geoffhumphrey** [comment]
@ercousin - looking into it. Stay tuned!

**Comment by geoffhumphrey** [comment]
I think I may have isolated the issue. If you would, try this: upload [this updated version of /lib/preflight.lib.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/lib/preflight.lib.php) to your installation. In my test environment, the issues you describe above stem from this one file and a misplaced line of code (ugh).

**Comment by ercousin** [comment]
Unfortunately that updated file doesn't seem to have fixed it.

I dropped it in, and the issue persists.

**Comment by geoffhumphrey** [comment]
Try replacing the /classes/fpdf/ in your installation with the one in the latest master commit.
