### ISSUE TITLE
Version 2.4.0.3: Participants missing edit entry option in actions column

### ISSUE THREAD

**Issue by frazzledpenguin** [geoffhumphrey/brewcompetitiononlineentry#1344]
**Verify the Following**
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

**BCOE&M Info**
Version: 2.4.0.3
Installation URL: registration.proam.beer
Hosted Installation? No

**Describe the Bug**
When a participant logs in and views their entries (hitting URL: index.php?section=list#entries) in the "Actions" column there is only an option to delete. There are no options to edit. Several participants have advised us that this option was there before. I have searched all the past issues (open and closed) and could not find a similar issue. We're running the latest commit (2.4.0.3).

**Comment by geoffhumphrey** [comment]
Hi @frazzledpenguin - one thing to check. Make sure that in Admin > Preferences > Site Preferences that your either a) the Winner Display is set to _Disable_ OR b) if Winner Display is set to _Enable_ that the Winner Display Date/Time is in the **future**. 

My suspicion is that your current settings are Winner Display - _Enable_ and Winner Display Date/Time is sometime in the past.

**Comment by frazzledpenguin** [comment]
Hi @geoffhumphrey, That was exactly the issue! The Winner Display was enabled and the Winner Display Date/Time was in the past. Those were the settings carried over from the previous comp. I didn't clue in that it was tied into these other things.

Thanks again, this issue can be closed.

**Comment by geoffhumphrey** [comment]
Great to hear! FYI - in the next release, there will be a feature in Admin > Competition Preparation that will allow admins to update all competition-related dates from a single screen. It was created for exactly this situation. Something to look forward to for next time.
