### ISSUE TITLE
Version 2.4.0e: BJCP XML Report is Blank

### ISSUE THREAD

**Issue by kmeintsma** [geoffhumphrey/brewcompetitiononlineentry#1349]
XML output for reporting to BJCP is empty. Message states that no organizer has been selected. But there doesn't appear to be anywhere to enter organizer information OTHER than the BJCP competition ID which is in fact entered into the system.

**Comment by geoffhumphrey** [comment]
Hi @kmeintsma, thanks for reporting.

To generate the XML report, an Organizer MUST be designated from the drop-down menu on the Admin > Entries and Participants > Participants > Assign Staff screen. The way to do this isn't clear in messaging when trying to download the XML file without a designated Organizer. That will be corrected in the next release.
