### ISSUE TITLE
Version 2.4.0e: Non-BJCP Judges for BOS

### ISSUE THREAD

**Issue by kmeintsma** [geoffhumphrey/brewcompetitiononlineentry#1351]
When selecting BOS judges, the system refuses to make non-bjcp judges available. They should be included because those points are supposed to be recorded with the BCJP. If the judge later goes through the program the points are retroactively assigned.

**Comment by geoffhumphrey** [comment]
With the relatively recent Mead and Cider judge certifications (independent of beer), allowing for non-BJCP and/or ranked judges to be eligible for BOS assignment in the system makes sense. The scripting for assigning BOS judges was created before those certifications became available. 

The next version will default to listing all assigned judges as eligible for the BOS round, regardless of rank or non-BJCP status. There will be a button to filter out non-ranked judges (BJCP or Cicerone) as an option for admins.
