### ISSUE TITLE
Version 2.4.0: BOS places can't be entered other than Hon. Men.

### ISSUE THREAD

**Issue by czufelt** [geoffhumphrey/brewcompetitiononlineentry#1356]
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

**BCOE&M Info**
Version: 2.4.0
Installation URL: https://www.unyha.com/comp/
Hosted Installation? No

**Describe the Bug**
When trying to enter BOS places only Hon. Men. is listed. You can't select 1st, 2nd or 3rd only Hon. Men.

**To Reproduce**
1. Go to 'Scoring'
2. Click on 'Manage'
3. Using the 'Add or Update' button
4. Click on 'BOS places for beer'
5. Try to select the Place from the drop down. Only Hon. Men. is listed

**Comment by geoffhumphrey** [comment]
Hi @czufelt; before I look into possible programming causes, if you would, please check in your installation's set up:
- Go to Admin > Preferences > Judging Preferences and make sure you have a value entered for the "Maximum Places in BOS Round" item. Most of the time, this is 3 or lower.
- Go to Admin > Competition Preparation > Manage Style Types and make sure that BOS is enabled for each of the style types you have in your competition.

**Comment by czufelt** [comment]
Hi Geoff,

 

The Admin > Preferences > Judging Preferences and make sure you have a value entered for the "Maximum Places in BOS Round" item was not set. I changed that to 3 and now it works.  I also checked the Style Types and those were enabled for BOS. Thank you for your help.

 

Craig

**Comment by czufelt** [comment]
Hi Geoff,

 

One more question; is there an easy way to export the presentation? We’re doing our awards ceremony this weekend and the presentation would be great to display but we won’t have internet access. Have a great day and thanks again for your help,

 

Craig

 

From: Craig Zufelt ***@***.*** 
Sent: Wednesday, September 28, 2022 3:47 PM
To: 'geoffhumphrey/brewcompetitiononlineentry'; 'geoffhumphrey/brewcompetitiononlineentry'
Cc: 'Mention'
Subject: RE: [geoffhumphrey/brewcompetitiononlineentry] Version 2.4.0: BOS places can't be entered other than Hon. Men. (Issue #1356)

 

Hi Geoff,

 

The Admin > Preferences > Judging Preferences and make sure you have a value entered for the "Maximum Places in BOS Round" item was not set. I changed that to 3 and now it works.  I also checked the Style Types and those were enabled for BOS. Thank you for your help.

 

Craig

**Comment by geoffhumphrey** [comment]
Hi Craig,

Yes, you can download the presentation as a web page:
1. In your browser, launch the Awards Presentation (you can do this from the Admin Dashboard).
2. Right-click anywhere on the page (not on an image, though).
3. Select **Save As...**
4. Select your save destination. I'd suggest the Desktop.
5. In the _Save as type_ dropdown, select **Webpage, Complete** (or something similar).
6. Select **Save**.

One caveat - the icons used throughout the presentation do not download properly. The easiest way to have things look good is to eliminate them altogether. This can be done by deleting a single line of code in the .html file you downloaded when you saved the presentation. 

Open the .html file in Notepad and **delete the _entire line_ that contains font-awesome.min.css** - it will be very close to the top of the page. Something like this:
```
<link rel="stylesheet" href="./XXX_files/font-awesome.min.css">
```

After that, it will be good to go for offline use.

**Comment by czufelt** [comment]
Thanks Geoff. I’ll give that a try.
