### ISSUE TITLE
Version 2.4.0.3 - GMail rejecting BCOEM emails due to duplicate headers (non-RFC 5322 compliant mail)

### ISSUE THREAD

**Issue by graemecoates** [geoffhumphrey/brewcompetitiononlineentry#1358]
**Verify the Following**
Reporting About the Latest Version? Yes 

Searched Issue Reports for Bug? Yes or No
*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

**BCOE&M Info**
Version: 2.4.0e (and 2.2.0)
Installation URL: https://competitions.norwichamateurbrewers.co.uk/
Hosted Installation? No

**Describe the Bug**
Gmail mail servers have started to reject mails sent from BCOEM instances (eg password reset mails or contact form emails) with the following rejection code - this is true on 2.4.0e and an older 2.2.0:

*******

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  [username@gmail.com](mailto:kusername@gmail.com)
    host [gmail-smtp-in.l.google.com](http://gmail-smtp-in.l.google.com/) [2a00:1450:400c:c00::1b]
    SMTP error from remote mail server after pipelined end of data:
    550-5.7.1 [2a00:1098:0:86:1000:45:0:1] Our system has detected that this message
    550-5.7.1 is not RFC 5322 compliant: duplicate headers. To reduce the amount of
    550-5.7.1 spam sent to Gmail, this message has been blocked. Please review
    550 5.7.1  RFC 5322 specifications for more information. f6-20020a0560001a8600b0022e6178f42dsi3318786wry.406 - gsmtp

********

GMail isn't informative enough to say which headers are duplicated unfortunately, so I'm not sure what's triggering it?

**To Reproduce**
1. Using a gmail address, request a password reset.
2. Observe bounce.

**Expected Behavior**
Mail delivery successful. 

**Screenshots**

**Server Environment**
- PHP Version: 7.4.30
- MySQL Version: mysql  Ver 15.1 Distrib 10.5.15-MariaDB
- Other Info: Apache 2.4 with daemon mode php-fpm; exim4 running as MTA.

**Local Environment**
 - OS: n/a
 - Browser: n/a
 - Browser Version: N/a

**Additional Context**
Is this related to Issue 1295?

**Comment by geoffhumphrey** [comment]
I'm working through some various configurations from my test servers of the mail() headers without much luck so far. 

In the meantime, if you haven't implemented phpMailer to send emails from your installation via SMTP, I would suggest you do if you're comfortable with customizing some PHP variables. I've successfully tested that emails to reach Gmail addresses if phpMailer is enabled.

Some configuration is required in the /site/[config.mail.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/site/config.mail.php) file. Examples are provided at the top of that file.

To enable phpMailer for BCOEM use, set the following value to 'TRUE' in the /paths.php file and re-upload to your server:
```
define('ENABLE_MAILER', TRUE);
```

I'll keep digging.

**Comment by graemecoates** [comment]
PHPMailer doesn't want to deliver anything on the instance I am using - even after setting the required config in site/config.mail.php (pointing it to 127.0.0.1:25, turning off smtp auth and encryption) and the flag in paths.php, with nothing at all in the exim4 log, or in the PHP error log...

To try and pin down the mail issue, here's the headers from a message that uses mail() that I've stopped in the outbout queue (see below). There are two "To:" headers here. It looks like you're settting the To: header and then mail() sets that based upon the value of $emails that you're passing through to it? 

(example at line 158 and then line 173 of includes/forgot_pasword.inc.php)



Headers of outbound failing message (exim4 -Mvh <message_id>):

212P Received: from norwichamateurbrewers by fuggle.chromosphere.co.uk with local (Exim 4.94.2)
        (envelope-from <norwichamateurbrewers@fuggle.chromosphere.co.uk>)
        id 1oiEAk-004Mlw-Ub; Tue, 11 Oct 2022 13:15:46 +0100
030T To: graeme@chromosphere.co.uk
075  Subject: Norwich Amateur Brewers Hoptober Competition 2022: Password Reset
018  MIME-Version: 1.0
039  Content-type: text/html; charset=utf-8
048T To: Graeme Coates <graeme@chromosphere.co.uk>,
114F From: Norwich Amateur Brewers Hoptober Competition 2022 Server <noreply@competitions.norwichamateurbrewers.co.uk>
058I Message-Id: <E1oiEAk-004Mlw-Ub@fuggle.chromosphere.co.uk>
038  Date: Tue, 11 Oct 2022 13:15:46 +0100

**Comment by graemecoates** [comment]
To confirm, for password reset, commenting out line 158 (and line 67) in includes/forgot_pasword.inc.php resolves the issue so it is a problem with the extra To: header thats being inserted. 

Can we get a patch to remove all instances of this occuring to fix email for GMail users? (which is likely a large number!)

**Comment by geoffhumphrey** [comment]
Ah, great catch! Thanks for providing that information - the fixes were relatively minor and easy to track down based upon what you found.

[This commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/3eb2c89a643522206be13954298fc4cd725270cc) houses all the updates in the affected files. 

I removed the To: header and instead provided a formatted name/email combination (Name <email>) as the first variable in the mail() call.  Tested on Gmail successfully. Hopefully this will work for you!

**Comment by graemecoates** [comment]
Thanks - the commit doesn't look like it will apply against a 2.4.0e release though (there are some substantial changes to the include/process files that this commit touches. I don't want to jump the install to a beta (given it's very close to the competition actually taking place) - is there a way of producing a patch/diff for users on the 2.4.0e release at all? (making a branch at the stable release and producing a commit against that?).

This is a major inconvenience for running competitions when on the stable branch given how many people use gmail hosted email these days...

**Comment by geoffhumphrey** [comment]
My apologies. I spaced that you were running 2.4.0. I'll work on a patch and get it uploaded.

**Comment by geoffhumphrey** [comment]
Hi @graemecoates - you can download the changes by going to [this branch](https://github.com/geoffhumphrey/brewcompetitiononlineentry/tree/2.4.0-mail()-Bug-Fixes). There are five affected files and you can [view the diffs here](https://github.com/geoffhumphrey/brewcompetitiononlineentry/compare/v2.4.0.3...2.4.0-mail()-Bug-Fixes). Hopefully these will work for you.

**Comment by graemecoates** [comment]
Super - thanks @geoffhumphrey - that's perfect and sorted the email issue for 2.4.0.3. Cheers!
