### ISSUE TITLE
2.4.0 - PayPal fee calculation is incorrect

### ISSUE THREAD

**Issue by macewank** [geoffhumphrey/brewcompetitiononlineentry#1361]
Version:

Installation URL: forwhatitswort.brewcomp.com

Is your installation hosted on brewcompetition.com or brewcomp.com?  brewcomp.com

Description of Issue:   Our entry fee is set to $8 and we are only receiving $7.98 per entry.  appears paypal did something with the transaction fees?

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @macewank. Indeed, PayPal did change their fee structure earlier this year. A new calculation will be implemented into the next version to make sure that comps are getting the full amount for PayPal payments. Please see Issue #1317 for a full rundown of the change.
