### ISSUE TITLE
Printing Bottle Labels

### ISSUE THREAD

**Issue by newpotat** [geoffhumphrey/brewcompetitiononlineentry#1363]
Version:

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com?

Description of Issue: We are getting an error message (FPDF error: Unknown label format: 4) when trying to print the bottle labels. 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by wactuary** [comment]
Adding more detail to newpotat report to help with this bug.

Using Hosted Version 2.4.0(e)
https://motownmash.brewcompetition.com/

Trying to print 0.50inch Round labels with Judging Numbers from the Entry Sorting tab of the Admin Dashboard.

Select the number of labels (we need 7 which is not an option, but any selection 1-6 same result) 
Choose number (3), sends to this URL: https://motownmash.brewcompetition.com/output/labels.output.php?section=admin&go=entries&action=bottle-judging-round&filter=default&sort=3&psort=OL32
With output:
FPDF error: Unknown label format: 3

Tried on Chrome, Edge, in Windows and Linux (Chromium) browsers on multiple machines.

**Comment by geoffhumphrey** [comment]
Hi @wactuary and @newpotat - thanks for reporting. There was an outdated file that was calling the FPDF class incorrectly. I've fixed that in your installation and have also increased the available number of labels for each entry to 8 so you can print the 7 per that you need.

You should be good to go now!

**Comment by wactuary** [comment]
I have tested and it looks good.  Thanks for they very fast fix!

**Comment by AdrienM76** [comment]
Geoff,

Any way I can get that fix as well? We host our own instance and I'm getting the same error using v2.4.

**Comment by AdrienM76** [comment]
Nevermind. I eventuall found closed issue #1306 and replaced the url_variables.inc.php file which solved it.
