### ISSUE TITLE
Enhancement: Is v2.5.0 Ready for Production Yet?

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1365]
The Bluebonnet Brewoff is moving to the BJCP 2021 guidelines. Our registration will open on January 2nd 2023. I have my own updates for limiting table entry counts, custom bottle labels, etc, that I apply to the BCOEM base.

My question is, should I use the v2.4.0.3 tag as my base or is v2.5.0-beta tag or the latest commit at a good point to move to production?

Thanks for all the work you do on this project.

Jimmy

**Comment by geoffhumphrey** [comment]
Hi Jimmy - I think it'll be a safe bet use the latest commit as your starting point. I've implemented a code freeze and will not have any more major commits until the release. 

I've been testing the [2.5.0 Beta + latest commit code](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/726fc702f5554623e4c48656babee34371e0ec54) - let's call it Gamma - in the [small competition](https://thebrewhut.brewcompetition.com) I'm running here in Denver. Things are going smoothly so far - no major hiccups. We have about another week until the entry window closes. Judging is on November 19 and I plan to release 2.5.0 shortly thereafter. 

2.5.0 definitely will be available before January 1. 

Cheers!

**Comment by geoffhumphrey** [comment]
BTW, if you'd care to share your custom coding for integration into the core codebase, please fork the repository and make a branch. This way you won't have to keep integrating the changes after every release.

**Comment by jimmyorkin** [comment]
Thanks Geoff. I'll work on making the changes I have made complete enough to move to the mainline. It would make my life easier. My repository is jimmyorkin/brewcompetitiononlineentry. My current latest branch is: bluebonnet-v2.3.2.1-plus. Branch bluebonnet-v2.5.0 will be my new development for this effort.

Jimmy
