### ISSUE TITLE
Informational v2.5.0: PHP8.1, Tiny But Strong fails.

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1366]
**Verify the Following**
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.5.0, latest commit
Installation URL: 
Hosted Installation? No

**Describe the Bug**
I installed the latest commit in my xampp that had PHP8.1 in it. I overshot the PHP release. Discovered Tiny But Strong does not work in PHP8.1. Backed up to PHP8.0 and TBS works. Error was in the TBS code related to assigning the address of $GLOBALS.

Probably need to call out the latest supported version of PHP.

**Comment by geoffhumphrey** [comment]
Thanks for the catch. There is a new version of TBS [available for download](https://www.tinybutstrong.com/download.php) on their website. I'll install it on my PHP 8.1 test server and see if there are any issues.
