### ISSUE TITLE
Version 2.5.0-beta: Fatal error creating competition due to contestEntryCap being defaulted to empty string

### ISSUE THREAD

**Issue by anigeluk** [geoffhumphrey/brewcompetitiononlineentry#1367]
**Verify the Following**
Reporting About the Latest Version? Yes 

Searched Issue Reports for Bug? Yes

**BCOE&M Info**
Version: v2.5.0-beta
Installation URL: 
Hosted Installation? No

**Describe the Bug**
Fatal error creating a competition with no Fee Cap specified 

PHP Fatal error:  Uncaught mysqli_sql_exception: Incorrect integer value: '' for column 'contestEntryCap' at row 1 in /var/www/SITEURLREDACTED/site/MysqliDb.php:1542
Stack trace:
#0 /var/www/SITEURLREDACTED/site/MysqliDb.php(1542): mysqli_stmt->execute()
#1 /var/www/SITEURLREDACTED/site/MysqliDb.php(834): MysqliDb->_buildInsert()
#2 /var/www/SITEURLREDACTED/includes/process/process_comp_info.inc.php(151): MysqliDb->insert()
#3 /var/www/SITEURLREDACTED/includes/process.inc.php(283): include('...')
#4 {main}
 thrown in /var/www/SITEURLREDACTED/site/MysqliDb.php on line 1542, referer: https://www.SITEURLREDACTED/setup.php?section=step4

When creating a competition if you leave the Fee Cap blank at step 4 as instructed for "no limit" 
'Enter the maximum amount for each entrant. Leave blank if no cap. ' 
the site tries to enter an empty string into the integer field in the DB

**To Reproduce**
1. Create a new competition and leave the Fee Cap blank 
2. Submit the form
3. See error

**Expected Behavior**
The setup to continue without an error

**Screenshots**

**Server Environment**
- PHP Version: PHP 8.1.2-1ubuntu2.6
- MySQL Version: Server version: 8.0.31-0ubuntu0.22.04.1
- Other Info: Apache 2

**Local Environment**
 - OS: UBUNTU Jammy
 - Browser: Chrome
 - Browser Version: Current

**Comment by geoffhumphrey** [comment]
Installation tested successfully using the latest master commit running PHP 8.1.12 and MySQL 5.7.23. 

Still need to test with PHP 8.1.X with MySQL 8.0.X.
