### ISSUE TITLE
Version 2.5.0-beta: Fatal error creating a competition due to contestEntryFeePasswordNum

### ISSUE THREAD

**Issue by anigeluk** [geoffhumphrey/brewcompetitiononlineentry#1369]
Verify the Following
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

BCOE&M Info
Version: v2.5.0-beta
Installation URL:
Hosted Installation? No

Describe the Bug
Fatal error creating a competition with no member discount password specified

 PHP Fatal error:  Uncaught mysqli_sql_exception: Data truncated for column 'contestEntryFeePasswordNum' at row 1 in /var/www/SITEURLREDACTED/site/MysqliDb.php:1542
 Stack trace:
 #0 /var/www/SITEURLREDACTED/site/MysqliDb.php(1542): mysqli_stmt->execute()
 #1 /var/www/SITEURLREDACTED/site/MysqliDb.php(834): MysqliDb->_buildInsert()
 #2 /var/www/SITEURLREDACTED/includes/process/process_comp_info.inc.php(155): MysqliDb->insert()
 #3 /var/www/SITEURLREDACTED/includes/process.inc.php(283): include('...')
 #4 {main}
 thrown in /var/www/SITEURLREDACTED/site/MysqliDb.php on line 1542, referer: https://www.SITEURLREDACTED/setup.php?section=step4

When creating a competition if you leave the member discount password blank  at step 4 
the site  hits a fatal error "Data truncated for column 'contestEntryFeePasswordNum'"  

To Reproduce

Create a new competition and leave the member discount password blank
Submit the form
See error
Expected Behavior
The setup to continue without an error

Server Environment

PHP Version: PHP 8.1.2-1ubuntu2.6
MySQL Version: Server version: 8.0.31-0ubuntu0.22.04.1
Other Info: Apache 2
Local Environment

OS: UBUNTU Jammy
Browser: Chrome
Browser Version: Current

**Comment by geoffhumphrey** [comment]
Installation tested successfully using the latest master commit running PHP 8.1.12 and MySQL 5.7.23. 

Still need to test with PHP 8.1.X with MySQL 8.0.X.

**Comment by geoffhumphrey** [comment]
Installation tested successfully using the latest master commit running PHP 8.1.12 and MySQL 8.0.29 (Windows, Apache 2.4.52). Windows 10, Chrome, Edge, FF.
