### ISSUE TITLE
Version: 2.5.0 Error opening judges dashboard for electronic score sheets

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1371]
**Verify the Following**
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.5.0 latest commit 
Installation URL: 
Hosted Installation? No

**Describe the Bug**
Attempting to use electronic scoresheets. When judge attempts to go into their judging dashboard.

Looks like PHP 8.0.23 is enforcing a type mismatch with a fatal error. Here is the error in the php log:

[Mon Nov 07 20:13:40.211349 2022] [php:error] [pid 26180:tid 1844] [client 127.0.0.1:10129] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string - int in E:\\xampp\\htdocs\\bcoem250plus\\eval\\dashboard.eval.php:798\nStack trace:\n#0 E:\\xampp\\htdocs\\bcoem250plus\\eval\\default.eval.php(3): include()\n#1 E:\\xampp\\htdocs\\bcoem250plus\\index.php(302): include('E:\\\\xampp\\\\htdocs...')\n#2 {main}\n  thrown in E:\\xampp\\htdocs\\bcoem250plus\\eval\\dashboard.eval.php on line 798, referer: https://localhost/bcoem250plus/index.php?section=list

This does not occur in an environment with PHP 7.4.3 that I have. 7.4.3 gives this message:
root@ubuntu-2004:/var/log/apache2# [Tue Nov 08 10:22:47.247903 2022] [php7:warn] [pid 3748] [client 192.168.1.11:10802] PHP Warning:  A non-numeric value encountered in /var/www/ubuntu-2004.test/bcoem/eval/dashboard.eval.php on line 798, referer: https://ubuntu-2004.test/bcoem/index.php?section=list
And the dashboard comes up.

**To Reproduce**
Error occurs when a judge goes into their judging dashboard.

**Expected Behavior**
To go into the Judges Dashboard.

**Screenshots**
This is what the judge sees:

![image](https://user-images.githubusercontent.com/13592817/200630785-4658fc95-9aa9-4172-aa62-1e65bc28c5d2.png)

**Server Environment**
- PHP Version: 8.0.23
- MySQL Version: 
- Other Info: [if applicable. Apache, nginx, etc.]

**Local Environment**
 - OS:
 - Browser: 
 - Browser Version:

**Additional Context**

**Comment by geoffhumphrey** [comment]
Looks like PHP 8 is more strict for operands. PHP 7 just ignored things if operands were strings and not integers, but 8 makes it a fatal error. 

Try this on line 798 in /eval/dashboard.eval.php 

```
if ((!empty($row_session_end['judgingDateEnd'])) && (is_numeric($row_session_end['judgingDateEnd'])) && ($totalRows_session_end > 0)) $two_to_end_sess = ($row_session_end['judgingDateEnd'] - 172800);
```

Generally, the judgingDateEnd variable would be an integer (Unix timestamp) - but if that variable is empty, it's treated as a string and not an integer by PHP. By checking if the var is 1) empty and 2) a number in the code above we can avoid the fatal error.

**Comment by jimmyorkin** [comment]
Geoff, That resolves the error I was seeing. Thanks.
