### ISSUE TITLE
Enhancement: .htaccess Options +Indexes

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1377]
Commit 4f5efafd95107734e0537baba9348844e3f66731 back in March of 2019, changed the setting for Indexes in the .htaccess file from minus to plus.

Seems like it should be minus.

Thoughts?

**Comment by geoffhumphrey** [comment]
Hmm. By default, this should be _-Indexes_. However, to be entirely transparent, truly I cannot remember why it was changed. 

Anyway, the line should be:
```
Options +ExecCGI +Includes +IncludesNOEXEC +SymLinksIfOwnerMatch -Indexes
```
This should [disable any directory listing/browsing](https://wpscholar.com/blog/prevent-directory-browsing-with-htaccess/). Of course, check your web host's/web server's configuration documentation for environment-specific settings.
