### ISSUE TITLE
Enhancement: Add Clubs to the Master Club List

### ISSUE THREAD

**Issue by Squelch20** [geoffhumphrey/brewcompetitiononlineentry#1380]
Add the following clubs

1) Master Homebrewer Program
2) Ninja Homebrewers

Change the following Clubs
Woodstock Malt Monkeys ---> North Georgia Malt Monkeys

**Comment by geoffhumphrey** [comment]
See [this commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/02bc3ddc582e233c6a4064d77f3240def67c16d2) for the changes and additions. Updates the /includes/constants.inc.php file.
