### ISSUE TITLE
Version 2.5.0: Add Judging Sessions don't show in manage judging sessions

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1381]
**Verify the Following**
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

**BCOE&M Info**
Version: 2.5.0 latest commit
Hosted Installation? No

**Describe the Bug**
Adding a judging session in initial setup or after setup does not show judging sessions in Manage Judging Sessions. I can see rows in the database in table judging_locations but the manage page does not show any sessions. I also get a message in the Admin Dashboard about No judging sessions specified.

**To Reproduce**
Go to Competition Preparation->Judging Sessions->Manage

- PHP Version: 8.0.23
- MySQL Version: 10.4.25-MariaDB
- Other Info: Apache

I did not see any easy error message in the log. Here is the PHP log:
Wed Dec  7 16:46:30 2022 (22596): Message Cached script 'E:\xampp\htdocs\bcoem250\admin\judging_locations.admin.php'
Wed Dec  7 16:46:57 2022 (22596): Message Cached script 'E:\xampp\htdocs\bcoem250\includes\process.inc.php'
Wed Dec  7 16:46:57 2022 (22596): Message Added key 'E:/xampp/htdocs/bcoem250/includes/process.inc.php'
Wed Dec  7 16:46:57 2022 (22596): Message Cached script 'E:\xampp\htdocs\bcoem250\lib\process.lib.php'
Wed Dec  7 16:46:57 2022 (22596): Message Cached script 'E:\xampp\htdocs\bcoem250\includes\process\process_judging_locations.inc.php'
Wed Dec  7 16:46:57 2022 (22596): Message Cached script 'E:\xampp\htdocs\bcoem250\classes\htmlpurifier\HTMLPurifier.standalone.php'
Wed Dec  7 16:46:57 2022 (22596): Message Added key 'E:\xampp\htdocs\bcoem250\classes\htmlpurifier/HTMLPurifier.standalone.php'
[07-Dec-2022 16:46:57 America/Chicago] PHP Warning:  Base directory E:\xampp\htdocs\bcoem250\classes\htmlpurifier/standalone/HTMLPurifier/DefinitionCache/Serializer does not exist,
                    please create or change using %Cache.SerializerPath in E:\xampp\htdocs\bcoem250\classes\htmlpurifier\HTMLPurifier.standalone.php on line 15688
[07-Dec-2022 16:46:57 America/Chicago] PHP Warning:  Base directory E:\xampp\htdocs\bcoem250\classes\htmlpurifier/standalone/HTMLPurifier/DefinitionCache/Serializer does not exist,
                    please create or change using %Cache.SerializerPath in E:\xampp\htdocs\bcoem250\classes\htmlpurifier\HTMLPurifier.standalone.php on line 15688
[07-Dec-2022 16:46:57 America/Chicago] PHP Warning:  Base directory E:\xampp\htdocs\bcoem250\classes\htmlpurifier/standalone/HTMLPurifier/DefinitionCache/Serializer does not exist,
                    please create or change using %Cache.SerializerPath in E:\xampp\htdocs\bcoem250\classes\htmlpurifier\HTMLPurifier.standalone.php on line 15688

Here is screen snap of the rows in the database.
![image](https://user-images.githubusercontent.com/13592817/206315592-969183a3-a0e1-42b0-a338-6f904958cd83.png)

**Comment by gene1wood** [comment]
I've also encountered this bug.

@jimmyorkin Thank you for the workaround of manually setting the `judgingLocType` column.

**Comment by geoffhumphrey** [comment]
Confirmed and thanks for reporting. This has been addressed and corrected in the latest master commit. Also available in the latest release.
