### ISSUE TITLE
How to PR fixes to the https://www.brewcompetition.com/ website?

### ISSUE THREAD

**Issue by gene1wood** [geoffhumphrey/brewcompetitiononlineentry#1383]
I've looked but don't see the https://www.brewcompetition.com/ website in GitHub. Is it in version control anywhere such that one could PR fixes to it?

I ask as there's a typo on https://www.brewcompetition.com/upgrade-instructions

> Locate the /sites/ sub-folder.

should be

> Locate the /site/ sub-folder.

and

> With your favorite text editor ([Sublime Text](http://www.sublimetext.com/), [Notepad++](https://notepad-plus-plus.org/), even plain ’ol Notepad, etc.), open the the config.php file located in the /sites/ directory.

should be

> With your favorite text editor ([Sublime Text](http://www.sublimetext.com/), [Notepad++](https://notepad-plus-plus.org/), even plain ’ol Notepad, etc.), open the the config.php file located in the /site/ directory.

**Comment by geoffhumphrey** [comment]
The brewcompetition.com site is not in version control here. The best way to report errors, etc. is just like you've done, Gene. Appreciate you pointing these out! The page has been updated.
