### ISSUE TITLE
Version 2.5.0: PayPal Payment Attempt Returns: Things don't appear to be working at the moment. Please try again later.

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1386]
**Verify the Following**
Reporting About the Latest Version? Yes
Searched Issue Reports for Bug? Yes
Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.5.0 Latest Commit
Installation URL:  bcoem.bluebonnetbrewoff.org
Hosted Installation? No

**Describe the Bug**
We are testing before going production in January. When attempting to pay for an entry via PayPal. We get a page from PayPal that says: "Things don't appear to be working at the moment. Please try again later.". I have been retrying to pay this morning and keep getting the same error. I am thinking there may be a problem in the BCOEM handoff to PayPal.

I do not see an error in the PHP error log.

**To Reproduce**
1. Go to entrant account.
2. Click on Pay Entry Fees then click on Pay with PayPal.
3. Click on "I Understand" that I am being handed off to PayPal.
4. See error, PayPal logo and message: Things don't appear to be working at the moment. Please try again later.

**Expected Behavior**
Prompted to log into PayPal
**Screenshots**
![image](https://user-images.githubusercontent.com/13592817/208718763-14772ae8-1b3e-41ae-a339-3a8b022c2d7f.png)

**Server Environment**
- PHP Version: 8,0.25
- MySQL Version: 
- Other Info:

**Comment by geoffhumphrey** [comment]
We've got the latest release running for Biere de Rock (https://bierederock.com) and haven't had any issues with the handoff. I just tested it and things are working normally. This is a live site, however. Are you running in TESTING mode (TESTING is set to TRUE in /paths.php), by chance? If that's the case, I'll look into the hooks into PayPal's sandbox environment.

Otherwise, make sure that your PayPal account email is correct in Admin > Site Preferences. If you're using PayPal IPN that it's also set up correctly.

**Comment by jimmyorkin** [comment]
We just adjusted the IPN URLs as our domain changed and this is a test payment in the production system. Testing mode is off. I need to verify the PayPal account is correct (it used to be but I am not the treasurer). 

I am working on a wireshark decode to see what the handoff looks like. Good to know that it is working for you. I'll focus on the issue as my problem. I also have a PayPal sandbox I can utilize if I need to.

More as I know it.

Thanks, Jimmy

**Comment by jimmyorkin** [comment]
Closing the loop on this issue. The problem was with PayPal. The PayPal account was in "limited" state. PayPal wanted something from account manager. After our treasurer did something to make PayPal happy, everything started working.

So if you get the dreaded PayPal "Things don't appear to be working at the moment. Please try again later" message. Take a look at the PayPal account and make sure everything is good in the account. We saw this message in the PayPal home page:

![image](https://user-images.githubusercontent.com/13592817/209200323-820928c6-3bcf-48c3-85db-e925adb450ab.png)

Geoff, I'll let you close this issue. You might want to tag it with the Good to Know tag.
