### ISSUE TITLE
Version 2.5.0: Weird Internation Stop Symbol and Link in Judges Preferences

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1390]
**Verify the Following**
Reporting About the Latest Version? Yes 

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.5.0(e) 
Installation URL: bcoem.bluebonnetbrewoff.org 
Hosted Installation? No

**Describe the Bug**
Assign judges page shows weird international Stop symbols in the preferences column. We are early in the competition, entry is open. Some of the participants have entered their judging information. The "none specified" link in the preferences column take you to other participants edit account page.

**To Reproduce**
1. Go to Entries, Payments, Participants -> Assign Judges
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/13592817/210849830-0f56d4a7-6192-4968-844f-f30fbd559be9.png)

**Server Environment**
- PHP Version: 8.0.23
- MySQL Version: 
- Other Info: [if applicable. Apache, nginx, etc.]

**Comment by geoffhumphrey** [comment]
Hey Jimmy - thanks for reporting. Check the [this commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/bf7f62c76fe4fc86411665f1704ae6248c717f16) for a fix. Specifically, see line 286-293 in /admin/judging_locations.admin.php file and lines 826*826 in /lib/admin.lib.php files.
