### ISSUE TITLE
Version 2.5.0: The UI presents no way to define the end time of a judging session

### ISSUE THREAD

**Issue by gene1wood** [geoffhumphrey/brewcompetitiononlineentry#1392]
**Verify the Following**
Reporting About the Latest Version? Yes 

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? No (Most of the 19 [good to know](https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+to+know%21%22) issues appear to apply to previous versions)

**BCOE&M Info**
Version: 2.5.0
Installation URL: https://register.worldcupofbeer.com/
Hosted Installation? No

**Describe the Bug**

The UI presents no way to define the end time of a judging session

**To Reproduce**

1. Browse to the Judging Sessions page `/index.php?section=admin&go=judging#`
2. Click `Add a Judging Session` : `/index.php?section=admin&go=judging&action=add`
3. Note how there is a `Session Start Date/Time` field but not a `Session End Date/Time` field
4. Back on the Judging Sessions page, note how the column in the table called `End Date/Time` shows `N/A` for the session you just created

**Expected Behavior**

For there to be a way in the UI to define the end time

**Screenshots**

![Judging session table](https://user-images.githubusercontent.com/1134034/211947708-c743f3f4-8c5b-44e0-b573-e402bf453bbc.png)

![Add judging session](https://user-images.githubusercontent.com/1134034/211947721-1e553d8c-c1dd-4596-85c2-d4b1fb00a65d.png)

**Server Environment**
- PHP Version: 7.4
- MySQL Version: MariaDB 10.6.11
- Other Info: Apache 2.4.41

**Local Environment**
 - OS: Ubuntu 20.04 Focal
 - Browser: Firefox
 - Browser Version: 108.0.1

**Additional Context**

**Comment by geoffhumphrey** [comment]
Hi Gene, there isn't a requirement to provide an end date and time for "Traditional" judging sessions since this type of judging session is generally in-person and not subject to any system-defined access rules. The "Distributed" type must have an ending date/time to serve as a deadline for judges to submit their evaluations for that session.

**Comment by gene1wood** [comment]
Ah got it. Then maybe this could just be a UI change? Ideas could be

* On the "add a session" page ( `/index.php?section=admin&go=judging&action=add` ), have a end time field, greyed out (unusable) with a note indicating that traditional judging sessions don't have end times
* On the  list sessions page ( `/index.php?section=admin&go=judging#` ), if all the sessions are traditional, remove the "end time" column

**Comment by geoffhumphrey** [comment]
Closing this - missed doing so as part of the 2.6.0 release. 

The Session End Date/Time field's visibility is toggled in the UI when a user chooses a Session Type. It appears when "Distributed" is selected and is hidden when "Traditional" is selected. There is also scripting to clear the field when the selection is changed from "Distributed" to "Traditional."
