### ISSUE TITLE
Version 2.5.0: 2021 Guidelines Style 2A does not collect optional regional variations

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1395]
**Verify the Following**
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.5.0
Installation URL: bcoem.bluebonnetbrewoff.org 
Hosted Installation? No

**Describe the Bug**
When creating an entry for 2A International Pale Lager, the guidelines say the entrant can enter regional variation information. BCOEM is not collecting that information for a 2A. 2B and 2C don't have this option.

Low priority for me.

Thanks, Jimmy

**Comment by jimmyorkin** [comment]
I got around to loading the fix. It does get into information into the brewInfo column but the pullsheet does not display it.

**Comment by geoffhumphrey** [comment]
Ah, yes. I'll take a look and get that info on the pullsheets and other appropriate reports.
