### ISSUE TITLE
Version 2.5.0: Setting MAINT to True not not enable maintenance mode 

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1399]
**Verify the Following**
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes 

**BCOE&M Info**
Version:  2.5.0

**Describe the Bug**
Setting MAINT to TRUE in paths.php does not enable maintenance mode.

**To Reproduce**
1. Edit paths.php setting MAINT to TRUE
2. Open browser to BCOEM site.

**Expected Behavior**
When in MAINT mode, see the maintenance.php page.

As a workaround I'll just rename maintenance.php to index.php.

**Comment by geoffhumphrey** [comment]
Hi @jimmyorkin - I tracked down the issue and made some adjustments. Check [this commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/1399) for details.
