### ISSUE TITLE
Version 2.5.0: Password reset showing a green alert box for an error condition

### ISSUE THREAD

**Issue by anigeluk** [geoffhumphrey/brewcompetitiononlineentry#1401]
**Verify the Following**
Reporting About the Latest Version? Yes - well not seeing any change to this functionality in .1 or .2 and with our comp in 2 weeks I don't want to risk updating the entire install. 

Searched Issue Reports for Bug? Yes 

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.5.0
Installation URL:  https://www.nationalhomebrewcompetition.org.uk/
Hosted Installation? No

**Describe the Bug**

Whilst trying to debug why users are not getting password reset emails I tried the process myself and noted that  the system is generating a message saying the answer is wrong (when in my case at least, it definitely matches what is in the DB and I updated it under edit account to make sure), this alert is displayed in green which may be making people think it has succeded when it hasn't 

**To Reproduce**
1. Attempt to reset password
2. Enter email
3. Enter security answer
4. See green message about trying again 

**Expected Behavior**
Expected a red alert to indicate an error condition rather than a green one that normally indicates success

**Screenshots**
![screenshot (57)](https://user-images.githubusercontent.com/2588997/216597215-062b8c75-ce30-4f7b-8ed0-572101c7b0be.png)

**Server Environment**
- PHP Version: libapache2-mod-php8.1/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.10 amd64
- MySQL Version: Server version: 8.0.32-0ubuntu0.22.04.2 (Ubuntu)
- Other Info: Server version: Apache/2.4.52 (Ubuntu)

**Local Environment**
 - OS: Windows 11
 - Browser: Chrome 
 - Browser Version: Current

**Additional Context**

**Comment by geoffhumphrey** [comment]
Hi @anigeluk - I did some digging and audited all the alert conditions. I matched each with their respective Bootstrap alert type to avoid any confusion for users. Updated code is available in [this commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/1401).
