### ISSUE TITLE
Version 2.5.0: Don't apply "Working." loader to links that open in new windows

### ISSUE THREAD

**Issue by mipaca** [geoffhumphrey/brewcompetitiononlineentry#1402]
**Verify the Following**
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.5.0
Installation URL: https://brewedinmn.com/
Hosted Installation? No

**Describe the Bug**
When a link opens in a _blank window the "Working. Please stand by." overlay is shown and the user has to click Esc to make it go away.

**To Reproduce**
1. On the Home page of the installation URL.
2. Click on 'CLICK HERE FOR REGISTRATION INSTRUCTIONS' or '2021 BJCP guidelines', both link to PDFs.
3. See that the Working overlay is shown.

**Expected Behavior**
When a link uses `target="_blank"`, the Working overlay should not be shown.

**Screenshots**
<img width="634" alt="Working overlay" src="https://user-images.githubusercontent.com/4368971/217317703-93d8143b-bd74-4d9d-9e3e-42355f158593.png">

**Server Environment**
- PHP Version: 7.4
- MySQL Version: 5.7.23
- Other Info: Apache

**Local Environment**
 - OS: Mac OS
 - Browser: Chrome
 - Browser Version: 109

**Additional Context**
I reviewed the jQuery for how this is being applied and can see that it is using a not to try to have this not happen with links that use _blank or #. This isn't working for some reason as expected.

**Comment by geoffhumphrey** [comment]
Hi @mipaca - there was a line of jQuery code that was misplaced in the /js_includes/loader_target.min.js file. I've corrected that and retested and now the loader does not show on <a> tags with the target="_blank" attribute. [This commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/80db5f91d67c2603699688778e38b93486984072) has the code changes.

**Comment by mipaca** [comment]
@geoffhumphrey I updated this file in our install and it fixed the issue I reported but may have made it so that the `hide-loader` now gets applied to all links. Checkout the "Contact" link near the bottom of the page which I don't think you were intending to have that class on since it links to an internal page.

**Comment by geoffhumphrey** [comment]
Dang it, you're right! Apologies. I did find the issue, though and believe I've fixed it. Try [this one](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/c7e677d82208556bd224e9c573883c0c95dbe9d9) out and let me know if it works for you. It did for me on my test server. Remember to reload scripts by holding down the shift key when you refresh.

**Comment by mipaca** [comment]
I have loaded the update on the site and it looks good to me.

**Comment by geoffhumphrey** [comment]
One more update was necessary. I added coding to prevent loader from appearing on printing modals generated by Fancybox (reports in Admin, printing bottle labels, etc.). Available in [this commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/4c25f0e55c5fe04fda4db334492fe9189443f5af).

**Comment by mipaca** [comment]
I deployed the updates from the commits and things are working as expected.
