### ISSUE TITLE
Enhancement: Ensure mobile users can view all entry information 

### ISSUE THREAD

**Issue by anigeluk** [geoffhumphrey/brewcompetitiononlineentry#1404]
**Is your enhancement or feature request related to a problem? Please describe.**
Users on mobile devices are unable to see if entries have been received and other actions/information due to the responsive layout removing information. This can be especially confusing where the message about being unable to print entry labels until an entry is marked as paid is still shown, even though there is no way to view the paid status on mobile.

**Describe the solution you'd like**
Enable users to see all the information and actions for an entry, this could be done by switching to a vertical layout per entry, scrolling to the right or popping up the full entry information.

**Describe alternatives you've considered**
Whilst there are options in how to display this info as mentioned above, the current alternative is that folk using mobile have to contact the organiser to see this information or use another device to access the website and not all users have alternative devices

**Additional context**
I've also previously been told that users were unable to see the action item to get their scoresheets as that was also part of the information hidden, but haven't been able to replicate that this year as scoresheets have not been added yet 

Mobile view (modern iPhone)

![image1](https://user-images.githubusercontent.com/2588997/217784186-f2cfeeac-73e4-444e-8fea-eef9a0f1ca7d.jpeg)

Desktop view

![image0](https://user-images.githubusercontent.com/2588997/217784224-44580172-9345-4e3d-a0b8-c45e85da7a10.jpeg)

**Comment by geoffhumphrey** [comment]
It stands to reason that the "hidden" content on mobile (confirmed, paid, received, updated) should be collapsed and added to one of the visible columns. Makes sense to put that information under the entry name. I'll work up a use case and post some screens here.
