### ISSUE TITLE
Version 2.5.0: Custom Styles not available to entrant

### ISSUE THREAD

**Issue by Simon-Haynes** [geoffhumphrey/brewcompetitiononlineentry#1411]
**Verify the Following**
Reporting About the Latest Version? Yes
*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes
*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes
*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**BCOE&M Info**
Version: 2.5.0
Installation URL: https://flatrockbrew.club/comp2023/
Hosted Installation? No

**Describe the Bug**
I have created two custom styles 'Classic Australian-Style Pale Ale' and 'Australian-Style Pale Ale' and both are set and showing as accepted styles in 'Info', both have been set to style category 'Beer'. However, as an entrant I can't select those styles for the entry, only the default ones in the selected style library 'AABC 2022 Styles'.

**To Reproduce**
1. Go to 'Info' and note those styles are accepted.
2. After registering click on 'Add Entry'
3. Select the drop-down list to choose the style and the custom styles are not available.

**Expected Behavior**
The Custom Styles should appear in the drop-down list of styles available when adding an entry.

**Screenshots**

**Server Environment**
- PHP Version: 8.0.22
- MySQL Version: 8.0.28-0ubuntu0.20.04.3
- Other Info: [if applicable. Apache, nginx, etc.]

**Local Environment**
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: 110.0.5481.105

**Additional Context**

**Comment by Simon-Haynes** [comment]
I may have resolved it by deleting the custom style and then re-adding it, although when I edited the custom style it reverted to type .0001 (or similar) and was no longer available again...

**Comment by mattwwatson** [comment]
Same issue on another Au comp - adding custom styles they all get the same brewStyleNum and thus whatever is selected it defaults to the first one. Have to hack the DB to set the brewStyleNum to different values to make it work. It also appears to reset back to 001 for all custom styles occasionally, not sure what this is but some operations in the UI must do this as we've had to hack the db multiple times after the problem re-occurs
