### ISSUE TITLE
Version 2.5.0(e): Blank Report Results by Style

### ISSUE THREAD

**Issue by jswisher** [geoffhumphrey/brewcompetitiononlineentry#1420]
**Verify the Following**
Reporting About the Latest Version? Yes or No
*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes or No
*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes or No
*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**BCOE&M Info**
Version: 2.5.0(e)
Installation URL: https://comp2023.chicohomebrewclub.com
Hosted Installation? Yes 

**Describe the Bug**
After all scores have been entered. When running the reports for results all the reports are blank.

**To Reproduce**
1. Go to Administrator Dashboard
2. Click on Reports
3. Scroll down to Results (By Style)
4. Click any of the All with Scores, Winners Only with Scores, All without Scores, of Winners Only without Scores

**Expected Behavior**
I would expect to see a printable report with all the entries with scored or a report with all the winning entries, but all of the reports are blank.

**Screenshots**
![image](https://user-images.githubusercontent.com/25538894/235497226-d8bb65c9-7966-47e7-a2da-b02e5dce590b.png)

**Server Environment**
- PHP Version:8.0.28
- MySQL Version: 5.7.23-23

**Local Environment**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Browser Version: 112.0.1

**Additional Context**
I am seeing this in the output directory error_log

PHP Warning:  Trying to access array offset on value of type null in /lib/common.lib.php on line 3490
Trying to access array offset on value of type null in /lib/common.lib.php on line 3505

**Comment by geoffhumphrey** [comment]
Hi @jswisher - thanks for reporting. Confirmed. 

I tracked down the issue and have implemented a fix, attached here (for version 2.5.0). That fix will also be in the next version release. Download, unpack, and upload the commin.lib.php file to your installation's /lib/ directory. With that file in place, that should fix this issue.
[common.lib.zip](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/11374664/common.lib.zip)
