### ISSUE TITLE
v2.5.0 - Archive Processing Bug - Archiving data from previous year doesn't archive & display last years winners

### ISSUE THREAD

**Issue by diatonic** [geoffhumphrey/brewcompetitiononlineentry#1421]
Version: 2.5.0.2 (Also happened with testing on 2.4)

Installation URL: https://idbeer.org

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: When archiving data from last year's competition, it does not archive last year's winners. Previous versions did. We show results from 3 earlier year's competitions, but not the most recent one we archived (2022).  As you can see below, we show past winners from 2018-2021, but archiving the 2022 competition results didn't include it. We're preparing for our 2023 competition. 

![image](https://user-images.githubusercontent.com/1490527/236525740-3534943d-41c4-4a09-9733-c6320fc1dd3d.png)

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @diatonic. One thing to check here is whether or not Winner Display is enabled for that archive. You can do that by editing the archive record.

Unfortunately, when I tried to do that on my test server, a processing error occurs. So, for you to edit the archive record, you'll need to download, unpack, and upload the contents of this zip file to the /includes/process/ directory on your installation's server.

[process_archive.inc.zip](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/11409052/process_archive.inc.zip)

Once you've uploaded the file to your installation,  go to Admin > Data Management > Manage Archives. Find the archive on that list and select the pencil icon in the Actions column to edit it. 

Make sure that Winner Display is enabled, like so:

![image](https://user-images.githubusercontent.com/5216502/236535383-55487b10-fa3c-4ed0-a15f-8e2044ceb361.png)

Once enabled, the archive will be available on the Past Winners list you reference in your report above.

If that doesn't work, please let me know.

**Comment by diatonic** [comment]
Thanks, I was able to recover the old site & database & reprocess the archive and it worked. I was then able to import those 2022 tables to the new site and it all looks good. Thanks!
