### ISSUE TITLE
Version 2.5.0 - Change Ninja Brewers to NINJA Brewers in the Clubs Master List

### ISSUE THREAD

**Issue by Cindywho317** [geoffhumphrey/brewcompetitiononlineentry#1423]
Version:

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com?

Description of Issue:

Requesting to change / correct Homebrew club name that is in BCOEM incorrectly.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by Squelch20** [comment]
change Ninja brewers to NINJA Homebrewers

**Comment by Cindywho317** [comment]
Yes, please!  Thank you so much!!!

**Comment by Cindywho317** [comment]
Was also listed as Ninjahomebrewers so if you can change it to NINJA Homebrewers that would be greatly appreciated!!!

**Comment by geoffhumphrey** [comment]
This has been changed [in the latest commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/e16176a1cd91cece795ed00d2c8501163858743a/includes/constants.inc.php#L2467) and will be in the next release. 

Please keep in mind that this change will only be effective if an installation is updated to 2.5.1 once it is released.

**Comment by Cindywho317** [comment]
Thank you!  It’s not NINJA Brewers.  It’s NINJA Homebrewers.

**Comment by geoffhumphrey** [comment]
Yes, that it is! NINJA Homebrewers is what's included as part of the [latest committed code](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/e16176a1cd91cece795ed00d2c8501163858743a/includes/constants.inc.php#L2467).
