### ISSUE TITLE
Enhancement: Make online judging timeout configurable

### ISSUE THREAD

**Issue by jimpdx** [geoffhumphrey/brewcompetitiononlineentry#1425]
When judges are doing online judging they frequently get the 15 minute warning before completing and occasionally lose their entire soresheet, so we would like the option to increase the timeout to 20, 25 or 30 minutes.

**Comment by jimmyorkin** [comment]
I went in and disabled the 15 minute warning all together because I had judges complaining they were losing there edits.

**Comment by geoffhumphrey** [comment]
Hello @jimpdx and thanks for your suggestion. The 15 minute warning when judging is just that - a warning. I does not time out a judge's session (UNLESS the installation has been configured to timeout at 15 minutes). It's a simple modal that is triggered after that amount of time - there is no programmatic association of that warning with any PHP session timers.

To increase the PHP session length for your installation, there is a variable in the /site/config.php file called [$session_expire_after](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/e16176a1cd91cece795ed00d2c8501163858743a/site/config.php#L131) that provides a mechanism to override the server's default PHP session length. For any competition I'm running that is also using electronic scoresheets, I set that variable to 60.

Hope that helps.

**Comment by jimpdx** [comment]
> I went in and disabled the 15 minute warning all together because I had judges complaining they were losing their edits.

Jimmy, where did you change that in the code?

**Comment by geoffhumphrey** [comment]
You can disable the modal by commenting out or removing lines [102-104 in the /eval/warnings.eval.php file](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/e16176a1cd91cece795ed00d2c8501163858743a/eval/warnings.eval.php#L102-L104).

**Comment by jimmyorkin** [comment]
The if statement below near where Geoff said.

// BBO disabling the 15 minute warning popup message  
//  if ((elapsedTime >= 900) && (elapsedTime < 901)) {
//    $("#eval-courtesy-warning-15").modal('show');
//  }

**Comment by geoffhumphrey** [comment]
See Issue #1445 - the 15 minute warning will be re-worked into a less-obtrusive warning for version 2.6.1.
