### ISSUE TITLE
Version 2.5.0(e) - Custom Style Inconsistencies

### ISSUE THREAD

**Issue by kmeintsma** [geoffhumphrey/brewcompetitiononlineentry#1427]
Not clear on why the software sometimes adds numbered or alpha text to custom categories. No obvious logic applies and can't find any editable setting to correct it.

![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/89654205/26672d4a-b145-4e1d-b2ff-d46efe0f5d62)

**Comment by geoffhumphrey** [comment]
This and other custom style-related issues will be addressed in the next version. The latest master commit should include a fix.

**Comment by geoffhumphrey** [comment]
FYI - the next version will allow admins to provide a custom style/sub-style name. Checks will be in place to make sure that the style/sub-style combination is not in use for the competition's style set chosen in Site Preferences. Additionally, if numeric, the style must start at 50.

![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/5216502/6598c880-46bf-498b-954a-16bf58fad5e7)
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/5216502/544052cd-f260-467d-90a4-603fdc2d0979)
