### ISSUE TITLE
Version 2.5.0: Add Homebrew Club to Register of Clubs

### ISSUE THREAD

**Issue by Squelch20** [geoffhumphrey/brewcompetitiononlineentry#1429]
**Verify the Following**
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes 

Reviewed the Good To Know Issue Reports? Yes 

**BCOE&M Info**
Version: 2.5.0
Installation URL: all
Hosted Installation? N/A

**Describe the Bug**
Please add the following club to the club register: Cider, Homebrew, And Mead Production Specialists (CHAMPS)

**Comment by geoffhumphrey** [comment]
Will do. This will be available in the next release.
