### ISSUE TITLE
Enhancement: Separate Admin level for seeing entry info

### ISSUE THREAD

**Issue by wactuary** [geoffhumphrey/brewcompetitiononlineentry#1430]
**Is your enhancement or feature request related to a problem? Please describe.**
Best BJCP practice would be to restrict visibility to entry info, especially the association of Entry Number to Judging Number to the bare minimum.  While in a committee organization structure, there may be many people who should be able to maintain and administer other aspects of the platform, such as updating competition details, managing participant registration info, running various reports, etc.  The Entry/Judging numbers and all info around anonymization should be controlled separately from other site admin permissions.  Specifically, the Judge Coordinator needs to be an admin to map tables and do assignments, but ideally should not have such access to entry info.  The judge table assignment would still need to alert that a judge is ineligible for a certain table due to a conflict, but that is at the flight level and not the individual entry numbers.

**Describe the solution you'd like**
A unique token assigned by Top-Level Admin, separate from Top-Level Admin or Admin that allows a visibility to entry numbers vs judging numbers which can be restricted only to those working in the cellar with need to know.

**Describe alternatives you've considered**
The alternative for us is to allow admin rights to a larger group up until the bottle sort, and then at the time of the sort, remove admin authority from all but the essential staff.  This does not fix the Judge Coordinator, who should then be restricted from judging any flights due to their elevated knowledge level.

**Additional context**
A separate but related request would be a way to easily filter and see a list of all participants with hightened access levels.  I believe currently the only way is to flip through all participants looking for the lock symbol, or search for specific known individuals.

**Comment by cshinn89** [comment]
this would be a great feature as there are many times we need additional Admins but hesitate as not too many people should have full access to the non anonymized entry data

**Comment by geoffhumphrey** [comment]
In the next version, Top-Level Admins will have the option to "Obfuscate Judging Numbers" for any participant whose user level is elevated to Admin or Top-Level Admin:
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/5216502/eb0807ec-4d9e-4f22-ae09-204e9645a7ae)

If that option is checked, that user will not be able to see any judging numbers as well as generate or access any functions/reports that have judging numbers displayed. Participant user levels will have its own column in the Manage Participants list, and any admin level participant who have access to judging numbers will be denoted with an eye icon, those who don't will have an eye icon with a slash through it:
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/5216502/874c1ef2-c8b0-4e98-824d-d5df0348e8d9)

For example, here's the Manage Entries screen for a Admin-level user **without** access to judging numbers:
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/5216502/f0d63e42-b7fa-4c10-a40a-26d5c6207013)

As said above, Admins who **do not** have access to view judging numbers **will not** be able to perform actions or to view/generate any reports/downloads that have that information, including:
- Regenerating Judging Numbers
- Printing bottle labels
- Downloading Pullsheets (Mini-BOS, BOS, Pro-Am), BOS Cup Mats, Judge Inventories, Required Info Labels, 
- Entering scores
- Entry data CSVs

**Comment by wactuary** [comment]
This sounds perfect.  Thanks for the quick implementation.
