### ISSUE TITLE
Version 2.6.0: bcoem_sys Does Not Exist

### ISSUE THREAD

**Issue by larrfish** [geoffhumphrey/brewcompetitiononlineentry#1432]
**Verify the Following**
Reporting About the Latest Version? Yes 

Searched Issue Reports for Bug? Yes 

Reviewed the Good To Know Issue Reports? Yes 

**BCOE&M Info**
Version: latest from master branch
Installation URL: https://petefest.brewbrosco.com/
Hosted Installation? No

**Describe the Bug**
I'm getting an error that says "Table 'brewbros_petefest.bcoem_sys' doesn't exist"

I've installed the software 3 or 4 times in the past by cloning the repo and following the installation guide and it worked like a charm.  I tried this again today with the latest code and I'm getting this error.  It's as if it thinks the tables have been created, but they haven't.

The error_log shows nothing, even when setting DEBUG to TRUE.

I tried setting FORCE_UPDATE to TRUE, but that had no effect.

I'm sure I've missed something simple, but I'm at a loss.  Any pointers on what to do here?

**To Reproduce**
Nothing special here.  I cloned the master branch and then followed the installation guide to the letter.

**Server Environment**
- PHP Version: 8.2
- MySQL Version: 5.7.23
- Other Info: Using bluehost as my hosting environment

**Local Environment**
 - OS:Ubuntu, MacOS
 - Browser: Firefox, Chrome
 - Browser Version:

**Additional Context**

**Comment by AlBrough** [comment]
I have just had issue when I used incorrect version of php. 
Docs state "PHP Version - should be at least 5.4.X but no later than 7.3.X"

**Comment by geoffhumphrey** [comment]
I'll look into it, but I just installed on Bluehost running PHP Version 8.1.21 and MySQL Version 5.7.23. The only variables that are different after looking at your installation is that I used a prefix ([line 107 of /site/config.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/d4b98453b6163c371cfc9c3193b2db0141ff6aa8/site/config.php#L107)), and the PHP version. 

Try with a prefix first, and if that doesn't work, go into your control panel, choose Advanced, then under Software choose Multi-PHP Manager. Change the PHP version of your install to 8.1 and then try the setup process again.

If that still does not work, you can use the fallback installation - included in the package download is a subfolder called “sql” that contains an SQL file called bcoem_baseline_2.6.0.sql. This file contains the complete database structure and dummy data to get you up and running. Complete instructions are at the top of the file. To install the baseline database and dummy data, you will need access to your database via phpMyAdmin or shell access. After that, log in with the credentials supplied, change your Admin information, and then update the competition info.

**Comment by larrfish** [comment]
Thanks Geoff and Al.

It was a PHP version problem.  I moved it back to 8.1 and it worked fine.  I didn't notice the documentation had a max version.  I thought it only had a min version.  My bad.

Thank you very much!
