### ISSUE TITLE
Version 2.6.0: Sponsors Not Displaying in Prescribed Order

### ISSUE THREAD

**Issue by mattwwatson** [geoffhumphrey/brewcompetitiononlineentry#1433]
**Verify the Following**
Reporting About the Latest Version? Yes
*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes
*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes
*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**BCOE&M Info**
Version: 2.6.0 (not filan - is 4ec0530dd8eb6c156f250a5ebd04a5d4b5b200a4
Installation URL:  state2023.nswhomebrewing.org
Hosted Installation? Yes

**Describe the Bug**
We've added Sponsors and assigned Levels to them, but on the sponsor page, the levels are ignored and the sponsor list comes back in raw database order - it should be sorted by level to show the highest first in a way that is controllable by the admin

**Screenshots**

**Server Environment**
- PHP Version: 7.8
- MySQL Version: unsure
- Other Info: [if applicable. Apache, nginx, etc.]

**Comment by hirendu** [comment]
Hi Geoff, I see that #1440 is closed - I understand this is fixed in 2.6.0 - but you mentioned that hosted instances would be updated later. Can you fix/update our instance (castate.brewcompetition.com)?
