### ISSUE TITLE
2.5.0: Bottle labels not generating all entries and out of order

### ISSUE THREAD

**Issue by bexarbrewers** [geoffhumphrey/brewcompetitiononlineentry#1437]
Version:

 5.7.23-23
Installation URL:
accfbexar.brewcomp.com

Is your installation hosted on brewcompetition.com or brewcomp.com?
brewcomp.com

Description of Issue:
The bottle neck labels are not generating all of the entries and they are not in numerical order. 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @bexarbrewers - could you be more specific as to which labels you're using? There are several variations. This will help me try to track down any issues.

By default, bottle labels are sorted first by style number, then by entry/judging number (for both the Entry Numbers and Judging Numbers). This also depends upon when you may have "regenerated" judging numbers. If that happened before you closed entries, there may be some out of order.

**Comment by statsmats** [comment]
Geoff, sent you the same issue via email now jumping in here. We are www.mnstatefair.brewcomp.com and trying to print bottle labels from admin dashboard Print Bottle Labels (PDF), with required Info, number of labels 3. In our instance, it is NOT printing labels for entry 000094 (and a few others) and only printing one label for 282 (which is how I caught this). Also not numerical order but I can get over that.

**Comment by geoffhumphrey** [comment]
@statsmats - in looking at entry 000094, it had some accented characters in the required info description. I replaced the accented characters with their non-accented equivalents and that entry was populated in the PDF. That may be the case for any others that are missing as well. If not, please post here and I'll see about tracking things down further.

**Comment by statsmats** [comment]
Thanks, I'll take a look.

**Comment by statsmats** [comment]
Yes, that fixed the issue. The software should not let you populate the fields with characters that disrupt subsequent operations of the software. Thank you Geoff!
