### ISSUE TITLE
Version 2.2.5.0 (e) PDF's generated from system for bottle labels are missing entries

### ISSUE THREAD

**Issue by statsmats** [geoffhumphrey/brewcompetitiononlineentry#1438]
**Verify the Following**
Reporting About the Latest Version? Yes 

Searched Issue Reports for Bug? Yes - no solution listed

Reviewed the Good To Know Issue Reports?  No

**BCOE&M Info**
Version: 2.2.5.0 (e)
Installation URL: 
Hosted Installation? Yes

PDF's generated from system for bottle labels do not have all entries in database and are missing some of the labels. When trying to print bottle labels from admin dashboard Print Bottle Labels (PDF), with required Info, number of labels 3. In our instance, it is NOT printing labels for entry 000094 (and a few others) and only printing one label for 282 (which is how I caught this). Also not numerical order but I can get over that. 

**Expected Behavior**
Expected labels from ALL entries to be within PDF so I can print for bottle sort TOMORROW MORNING.

**Comment by geoffhumphrey** [comment]
@statsmats, please post the hosted competition URL so I can investigate.

**Comment by statsmats** [comment]
https://www.mnstatefair.brewcomp.com/

Also, if I click the link for "six entries per label" it has all the entries

**Comment by geoffhumphrey** [comment]
Please see my reply in Issue #1437
