### ISSUE TITLE
Version 2.5.0.2 Seach Engine Friendly URLs Not Enabling

### ISSUE THREAD

**Issue by diatonic** [geoffhumphrey/brewcompetitiononlineentry#1441]
Reporting About the Latest Version? Yes - Tested on 2.6 as well with same result

Searched Issue Reports for Bug? Yes 

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: v2.5.0.2
Installation URL: https://idbeer.org
Hosted Installation? No

**Describe the Bug**
Enabling Search Engine Friendly URLs preference does not affect navigation links, but SEF links are working
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/1490527/86ade280-5dfa-4fa4-8245-a23eb8691303)

**To Reproduce**
1. Go to Website Preferences
2. Enable Search Engine Friendly URLs
3. Save Changes
4. Navigation links are not SEF 

**Expected Behavior**
Search Engine Friendly Links in navigation

**Screenshots**
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/1490527/709e140e-17b3-412d-a29f-e33d05cac0b3)

**Server Environment**
- PHP Version: 8.2.5
- MySQL Version: 10.5.16-MariaDB
- Other Info: Apache/2.4.53 (AlmaLinux)

**Local Environment**
 - OS: Windows 11
 - Browser: Edge & Firefox
 - Browser Version: Latest

**Additional Context**
SEF URLs work on the server, but navigation links continue to not use them

**Comment by diatonic** [comment]
Perhaps related to using an unsupported version of php. Saw that the installation instructions state not to use a version newer than 7.3.X.

**Comment by geoffhumphrey** [comment]
Hi @diatonic - thanks for reporting. If you change [lines 164-178 (2.6.0 release) of /lib/common.lib.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/e240ad67ff5b1c4074a1aa88886b8340022ffb90/lib/common.lib.php#L164-L178) to the following, the issue will be resolved:
```
if ($_SESSION['prefsSEF'] == 'Y') {
	$url = $base_url."";
	if ($section != "default") $url .= $section."/";
	if ($go != "default") $url .= $go."/";
	if ($action != "default") $url .= $action."/";
	if ($id != "default") $url .= $id."/";
	return rtrim($url,"/");
}
	
else {
	$url = $base_url."index.php?section=".$section;
	if ($go != "default") $url .= "&amp;go=".$go;
	if ($action != "default") $url .= "&amp;action=".$action;
	if ($id != "default") $url .= "&amp;id=".$id;
	return $url;
}
```

Or, simply download and install the entire [/lib/common.lib.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/lib/common.lib.php) file from the latest commit to your installation.
