### ISSUE TITLE
Version 2.6.0: Unable to Enter Sponsors or Logos

### ISSUE THREAD

**Issue by brown-aaron-g** [geoffhumphrey/brewcompetitiononlineentry#1444]
**Verify the Following**
Reporting About the Latest Version? Yes
*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes
*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes
*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**BCOE&M Info**
Version: 2.6.0
Installation URL: https://headhunters.brewcompetition.com/
Hosted Installation? Yes

**Describe the Bug**
Unable to enter sponsors. When navigating to Admin > Competition Preparation > Manage Sponsors, there's no way to enter a sponsor.

Unable to load logos. When navigating to Admin > Competition Preparation > Upload Logo Images, the logos upload appears to work (both methods), but no logo list is created.

**To Reproduce**
See bug description above.

**Expected Behavior**
Should be able to enter sponsors and logos.

**Screenshots**
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/142061593/9137cd8e-6fff-4bfb-b9a1-8a3f05fcab60)

**Server Environment**
Hosted on brecompetition.com

**Local Environment**
 - OS: Windows 11 Home version 22H2
 - Browser: Chrome
 - Browser Version: Version 115.0.5790.171 (Official Build) (64-bit)
 -Note, also does not work on Firefox 116.0.2 (64-bit)

**Additional Context**
N/A

**Comment by geoffhumphrey** [comment]
Hi @brown-aaron-g - thanks for reporting. A directory was missing on you installation that the scripting was looking for but not finding, thus throwing an error. That directory has been restored with the correct permissions and you can now add your sponsors and logos. Apologies for any confusion.
