### ISSUE TITLE
Version 2.6.0 (e) 15 minute warning Greys out Scoresheet

### ISSUE THREAD

**Issue by cshinn89** [geoffhumphrey/brewcompetitiononlineentry#1445]
**Verify the Following**
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.6.0(e)
Installation URL: https://njstatefairhomebrew.brewcomp.com/
Hosted Installation? Yes

**Describe the Bug**
when judges are entering Scoresheets and the 15 minute warning pops up if they click off of the warning rather than acknowledging it the warning disappears and the whole page greys out and nothing can be selected appearing to lose the whole entry info. this usually happens by mistake i.e. going to save the scoresheet at the exact moment the warning appears therefore erroneously clicking off the warning.

**To Reproduce**
1. Go to fill out a scoresheet
2. when 15 minute judging warning pops up
3. click off of the warning popup box
4. popup disappears and screen goes dark

**Expected Behavior**
either clear popup or do nothing

**Additional Context**
we found through trial and error going back a page and then clicking forward again the judging data is still there but not actually "saved". this is a big issue we had to work through during our judging to not lose scoresheets and many were manually reentered before we found the workaround to the dismay of our judges.

**Comment by geoffhumphrey** [comment]
Hello @cshinn89 - thanks for reporting. Unfortunately, I am not able to replicate the issue on your installation using Chrome, Firefox, and Edge on PC, as well as Safari, Chrome, and Firefox on iOS. 

The cause of this may related to an older browser and/or older hardware running an older browser that isn't capable of running Bootstrap 3.4.1 framework that BCOE&M uses ([see here for supported browsers](https://getbootstrap.com/docs/3.4/getting-started/#support-browsers)).

My advice is to make sure all judges are running the latest version of Chrome on whatever device they're using to do their entry evaluations.

**Comment by cshinn89** [comment]
Hummm that's weird as it happened to 3 different people including myself.  For me i was running the latest version of Chrome

**Comment by AdrienM76** [comment]
We had the same problem a few weeks ago for a judge using the latest Firefox. My workaround was to use the browser's inspector to turn off the overlay entirely so he could continue judging.

**Comment by geoffhumphrey** [comment]
So, thinking about this - would a less intrusive warning like the one below be more preferrable? This way we're not reliant upon a modal which can break the experience.

![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/5216502/851c59a5-a142-45dc-9805-3f8fb50383af)
