### ISSUE TITLE
Version 2.6.0(e) Participant State for Address cannot be updated

### ISSUE THREAD

**Issue by cshinn89** [geoffhumphrey/brewcompetitiononlineentry#1446]
Verify the Following
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

BCOE&M Info
Version: 2.6.0(e)
Installation URL: https://njstatefairhomebrew.brewcomp.com/
Hosted Installation? Yes

**Describe the Bug**
when a participant or admin is updating someone's address all fields are updated except the State

**To Reproduce**
1. Go to Edit account info
2. Update State/ province field
3. Click on Edit Account Info
4. State/ province reverts to previous selected state

**Expected Behavior**
Updated info should update and save

**Comment by geoffhumphrey** [comment]
Confirmed, and thanks for reporting @cshinn89. A fix is in place in the latest master commit, and will be available in the next release. Specifically, you can replace the [/includes/process/process_brewer_info.inc.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/235c1e93e2e6365ab69e5130691ae09d675866c1#diff-43eba6442479463d21d6ff1c6e5e112daec42e88b36ed8c8d394eaf3d3bc2d0a) file on your server with this one.
