### ISSUE TITLE
Enhancement: Display Non-Judging Sessions As Prominently as Judging Sessions

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#1451]
**Is your enhancement or feature request related to a problem? Please describe.**
I had previously filed #873 (Need ability to track entry sorting volunteers/sessions) and this feature was added in v2.5.0 release.

Trying it out now with  v2.6.0.1 and I find it fairly difficult to find the Non-Judging Sessions compared to the Judging Sessions.

![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/1551339/fbc8fdda-f347-4be7-8500-8d405ee76a77)

**Describe the solution you'd like**
I would like to request that the Non-Judging Sessions get displayed in the right side column with similar formatting as Judging Sessions. Perhaps just below judging sessions.

![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/1551339/1f9f07b0-b883-4d4f-bc54-3baf030b1b19)

**Comment by geoffhumphrey** [comment]
Sounds reasonable and thanks for the suggestion. If there are Non-Judging sessions, the next version display them in their own section, just below Judging Sessions public-facing pages sidebar, like this:

![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/5216502/65cdc90f-4c1b-4f33-a78a-5d15b503488e)
