### ISSUE TITLE
Version 2.6.0: Contact Form Not Redirecting Inquiries 

### ISSUE THREAD

**Issue by shappy118** [geoffhumphrey/brewcompetitiononlineentry#1453]
**Verify the Following**
Reporting About the Latest Version? Yes 
*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may 

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.6.0
Installation URL: https://nerhbc.brewcomp.com/
Hosted Installation? Yes

**Describe the Bug**
It appears that when a participant goes to our contact page to submit a question, the email is not being forwarded to the email addresses associated with each contact member. Especially 'Jill Crawford - Competition Coordinator' 

**To Reproduce**
1. Go to 'Contact'
2. Click on 'Jill Crawford'
3. Type in question
4. Hit submit

**Expected Behavior**
An email to appear in the appropriate inbox, in this case, shappy118@gmail.com 

**Screenshots**
n/a

**Local Environment**
 - OS: Mac OS
 - Browser: Google Chrome
 - Browser Version: Version 115.0.5790.170 (Official Build) (arm64)

**Additional Context**
Really appreciate the help! If there is anything I can do to troubleshoot on my end, do let me know and thank you!

**Comment by geoffhumphrey** [comment]
I'll look into the issue, but in the meantime, I would suggest using another email address that is NOT a Gmail address - apologies if this is a hassle, but it may be the most expedient. 

I've been 'round and 'round with getting the email generation system to play nice with Gmail, and was successful for a while, but it appears that things are being rejected again and I'll need to get to the bottom of why.

**Comment by geoffhumphrey** [comment]
Hi @shappy118 - I checked your installation and there was a configuration error in the email script. I just tested it now and the email went through to my Gmail address. Test it on your end and let me know if it works!

Thanks.

**Comment by shappy118** [comment]
Looks like we are set thank you so much!
