### ISSUE TITLE
Enhancement: Improve Clarity of BOS Cup Mats

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#1455]
Re-filing an enhancement request for the unfixed issue from #875 , I don't think my comment on that one was not seen.

> Hi @geoffhumphrey
I don't think this one was resolved, we are still seeing the same issue in Brew Slam 2019.

Here's an example of one square:
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/1551339/331e954c-5f3c-43d4-bfe6-ada9c7d0a1a6)

Is there any case where users want the BJCP Category ("1: Standard American Beer") to be more prominent than their self created table names (Table 1: Light Lager)? Could we just get rid of the BJCP Category from cup maps, or make a setting to select "Table Name" vs "BJCP Category Name" in big letters?

We always have to spend 10 minutes crossing these out in black sharpie before we can start BOS. Otherwise out BOS judges get confused and start using the wrong text to describe the entry they are describing.

My suggestion is:

- Make the Table Name the most prominent (first line, largest font size). Eg. 'Table 1: Light Lager'
- Do not list the BJCP Category (E.g. 1: Standard American Beer). If a competition is following the BJCP Categories for grouping their styles into tables, then they can just name their tables after the Categories.
- Keep the subcategory/style as-is

**Comment by ercousin** [comment]
Another example where BJCP Category gets confusing is when we have split the category across multiple tables. In that case judges first see the name '21: IPA' for two of the BOS entries, then have to look to the bottom of the square to know which table it actually came from.

![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/1551339/d4c5d0ab-9fcd-476a-bda7-21a999ac07ba)

**Comment by geoffhumphrey** [comment]
To save you some headache come BOS, replace [lines 148-155 of the /output/bos_mat.output.php file](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/f1adf48284fd128b4b8651bf14c03bbf3f91081f/output/bos_mat.output.php#L148-L155) with the following:
```
else {
     $output .= '<h3 style="padding:0 0 5px 0;margin:0;">';
     $output .= check_table_name($row_scores['scoreTable'],$judging_tables_db_table);
     $output .= '</h3>';
     $output .= '<h4 style="padding:0 0 5px 0;margin:0;">';
     $output .= '<em>'.$style.': '.$row_scores['brewStyle'].'</em>';
     $output .= '</h4>';
}
```

Then, erase or comment out [lines 187-188 in the same file](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/f1adf48284fd128b4b8651bf14c03bbf3f91081f/output/bos_mat.output.php#L187-L188):
```
//$output .= '<p><small><strong>'.check_table_name($row_scores['scoreTable'],$judging_tables_db_table).'</strong></small></p>';
//$output .= '</section>';
```

This will result in squares that look like this:

![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/5216502/27e5d0a5-75e5-4add-8fd5-d486cafc2d1c)

For convenience, I've made the above changes and put them in this zip. Simply unpack and upload the contained file to your installation's /output/ folder.
[bos_mat.output.zip](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/12525336/bos_mat.output.zip)

Hope that helps!

**Comment by geoffhumphrey** [comment]
Incorporated into version 2.6.1 - see [release tag v2.6.1.1](https://github.com/geoffhumphrey/brewcompetitiononlineentry/tree/v2.6.1.1).

**Comment by ercousin** [comment]
Thank you! Looking forward to incorporating this into my upcoming judging weekend in late Oct!
