### ISSUE TITLE
Version 2.6.1(e): Unable to view or print evaluations. Getting an SQL error (attached). Likely this will prevent the entrants from seeing their scoresheets when results are published. 

### ISSUE THREAD

**Issue by kmeintsma** [geoffhumphrey/brewcompetitiononlineentry#1467]
**Verify the Following**
Reporting About the Latest Version? Yes or No
*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes or No
*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes or No
*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**BCOE&M Info**
Version: 
Installation URL: 
Hosted Installation? Yes or No

**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Server Environment**
- PHP Version:
- MySQL Version: 
- Other Info: [if applicable. Apache, nginx, etc.]

**Local Environment**
 - OS:
 - Browser: 
 - Browser Version:

**Additional Context**

**Comment by kmeintsma** [comment]
The EDIT query works however (but not helpful for entrants).

**Comment by kmeintsma** [comment]
I neglected the attachment - sorry about that.

This bug is the one that will have the most impact from an entrant standpoint. The other big bug is the one preventing marking of mini-bos and placement as it will directly affect the operation of the competition (which is underway now).

Additional environment information:
    PHP Version – 7.4.33;
    MariaDB Version – 5.5.5-10.6.15-MariaDB-1:10.6.15+maria~ubu2204
    
    
![Evaluations SQL Error preventing view or printing](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/89654205/e9367ad4-2f31-4fcf-8f31-66e2c282e405)

**Comment by geoffhumphrey** [comment]
Unfortunately, I could not replicate the scoresheet viewing/downloading issue in any of my test environments (php 7/8 running MySQL 5.5 or MariaDB 10.4) using multiple browsers. The screenshot is from the Admin > Scoring > Entry Evaluations dashboard and it worked for me for all scoresheet output types (full, structured, checklist).

In any case, I would replace the following files in the /eval/ folder:
- checklist_output.evalphp
- scoresheet_output.eval.php
- structured_output.eval.php

**Comment by daveroyer** [comment]
I run the back end for Kevin with this comp. I updated the files you
suggested in your last from the latest in the git repo and we still have
the issue.

We are getting this in the logs when trying to view the scoresheet :

[Thu Sep 21 20:42:17.751399 2023] [proxy_fcgi:error] [pid 3497194:tid
140444532983360] [client 97.116.114.15:0] AH01071: Got error 'PHP message:
PHP Notice:  Trying to access array offset on value of type null in
/home/valkyrieshorn/webapps/valkyrieshorn_home/eval/db.eval.php on line 6',
referer:
https://comp.valkyrieshorn.com/index.php?section=evaluation&go=default&filter=default&view=admin

My eval/db.eval.php file matches the current version in git.

Not sure if above helps or not but that's the only log being generated on
the button click.

**Comment by geoffhumphrey** [comment]
Looking at that line, it appears that the `$row_eval['evalJudgeInfo']` variable is missing (relational to the id in the 'brewer' db table), which is passed from the previous query's results. This indicates to me that there's some info missing in the record in the 'evaluation' table.

Couple of things to check. 
- Make sure the entire contents of your installation's /eval/ directory match what is in the current version on git. The current version has just been updated today.
- Check the 'evaluation' db table for any records that have a non-numerical or missing value in the evalJudgeInfo column. If so, you may need to match up the Judge's name with their id in the 'brewer' table and update it in the 'evaluation' table.

As a stopgap, you can change line 7 in the /eval/eval.db.php file to:
```
$judge = mysqli_query($connection,$query_judge);
```
This will let the script run and not die when MySQL throws an error. If the judge's information is missing, then that is the indication that the `$row_eval['evalJudgeInfo']` variable is missing.

**Comment by wactuary** [comment]
I am seeing this as an admin trying to look at a scoresheet through the Scoring - Manage Entry Evaluations page, looking at entry m2-004 in our hosted come (motownmash.brewcompetition.com), which was flagged by the system for having scores out of range.  After I got this error, I started trying to view other scoresheets and I got a blank white square where the scoresheet would normally be visible.

**Comment by geoffhumphrey** [comment]
[This commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/f580a854cf43467fab6f34a52ab303a7a0529669#diff-81cf35ae9ba9c8122c1b2fb1bd6f28150c375a95876fb43a710fcfec6fba0e17) should resolve this issue. I was able to replicate it today. Apologies for the delay.
