### ISSUE TITLE
Version 2.6.1(e): During entry evaluations the running total is not working. Once an evaluation has been saved it completes the total. 

### ISSUE THREAD

**Issue by kmeintsma** [geoffhumphrey/brewcompetitiononlineentry#1468]
**Verify the Following**
Reporting About the Latest Version? Yes or No
*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes or No
*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes or No
*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**BCOE&M Info**
Version: 
Installation URL: 
Hosted Installation? Yes or No

**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Server Environment**
- PHP Version:
- MySQL Version: 
- Other Info: [if applicable. Apache, nginx, etc.]

**Local Environment**
 - OS:
 - Browser: 
 - Browser Version:

**Additional Context**

**Comment by geoffhumphrey** [comment]
Similar to #1466, there's a reference to a test environment file. Replace [line 583 in the /eval/scoresheet.eval.php file](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/cc1eab3bafbd7966d1db3a94819c6395faf16555/eval/scoresheet.eval.php#L583) with this line:
```
<script src="<?php echo $base_url;?>js_includes/eval_checks.min.js"></script>
```
This will alleviate the issue. I will be updating the 2.6.1 release with this code soon.
