### ISSUE TITLE
Version 2.6.1(e): Checkbox not appearing when adding judge to a table for Head Judge and mini-BOS Judge

### ISSUE THREAD

**Issue by wactuary** [geoffhumphrey/brewcompetitiononlineentry#1470]
Reporting About the Latest Version? Yes 

Searched Issue Reports for Bug? Yes 

Reviewed the Good To Know Issue Reports? Yes 

**BCOE&M Info**
Version: 2.6.1(e)
Installation URL: https://motownmash.brewcompetition.com/
Hosted Installation? Yes

**Describe the Bug**
I found when adding judges to a table that I wasn't given the option to identify a head judge or enable them as mini-BOS.  I had to re-open the table assignment where the boxes re-appeared and I could make the selections.

**To Reproduce**
1. Create a Distributed Judging Session and have more than 1 round (I had 3, have not tested other numbers)
2. Create Tables and assign some tables to the distributed judging session
3. Assign the table to Round 2 or Round 3 (did not find the issue for any Round 1 tables)
4. On the Tables list, click to add judges and assign a judge.

Expected behavior is the boxes to select would appear for Head and mini-BOS, but they are not visible.

Workaround
1.  Click Save Table
2.  Go back to edit the judges for that table
3. Now the judges are marked as selected and the checkboxes appear (but unchecked)
4. Check as needed and resave

Obviously I've found a workaround by re-editing and re-saving.  I did not check if this happened for in person sessions as those have only 1 round in our comp.

**Comment by wactuary** [comment]
Further searching, I found #1283 which appears to be the same issue from version 2.4.0.  Initial comment was that it is by design, but the use case is the same, unrelated tables associated in Round 1/Round 2, and with different judge pairings, so the Head Judge from Round 1 should not carry over into higher rounds.  Perhaps this is a mis-application of the intended use for multiple rounds in a session, but it is more intuitive than having multiple virtual sessions for people to need to opt into.  Also if truly intended behavior then I wouldn't expect the boxes to become available again when going back to edit the table, so it still feels like a display glitch.

**Comment by geoffhumphrey** [comment]
Confirmed. The JS scripting was not receiving the correct input, and thus not firing the command, creating the display glitch. I believe I've fixed the issue. If you update the /admin/judging_assign.admin.php file with [the one in this commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/f0dcbe4054ff6b655c8cefebf4d56320ffb9c88d), the issue should be resolved.
