### ISSUE TITLE
Version 2.6.1: Entrants unable to download PDF scoresheets

### ISSUE THREAD

**Issue by brown-aaron-g** [geoffhumphrey/brewcompetitiononlineentry#1472]
**Verify the Following**
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.6.1
Installation URL: https://headhunters.brewcompetition.com/
Hosted Installation? Yes

**Describe the Bug**
When entrants click on PDF icon to download their scoresheets, they are met with the following error: "Your scoresheets could not be properly generated. Please contact the organizers of the competition."

**To Reproduce**
See above.

**Server Environment**
- PHP Version:
- MySQL Version: 
- Other Info: [if applicable. Apache, nginx, etc.]

**Local Environment**
 - OS: Windows 10
 - Browser: Chrome (116.0.5845.188 ) and Firefox (117.0.1)

**Additional Context**
Several users have experienced the same issue. I'm able to download PDFs with my admin account. Error exists weather PDF was uploaded using the batch or single file uploader.

**Comment by 003401E8** [comment]
It's not just you. I had someone reach out to me as a competition coordinator with the same issue.
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/71900912/7037e3a3-862a-46c5-b376-5e6ecea8480b)

It seems to have been caused after the update 
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/71900912/9702aa2a-6b47-4c06-a604-5e191ae0adc1)

**Comment by 003401E8** [comment]
I completely agree with you and wasn't trying to be sarcastic or anything. I only had one person reach out to me so I think everyone else downloaded theirs before the update, but I came here to provide supporting evidence of your report.

**Comment by geoffhumphrey** [comment]
Hey all... I'm looking into the issue this morning and will have a fix in place later today. Stay tuned!

**Comment by brown-aaron-g** [comment]
> I completely agree with you and wasn't trying to be sarcastic or anything. I only had one person reach out to me so I think everyone else downloaded theirs before the update, but I came here to provide supporting evidence of your report.

All good! I didn't take it as sarcasm at all.

**Comment by geoffhumphrey** [comment]
Tracked down the issue and have deployed the fix on all hosted installations. 

For non-hosted installations running versions 2.6.1 ([2.1.6.5 build](https://github.com/geoffhumphrey/brewcompetitiononlineentry/tree/2.6.1.5) or previous), replace the /sections/brewer_entries.sec.php with [this one](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/sections/brewer_entries.sec.php).
