### ISSUE TITLE
Enhancement: CoA points system for Heavy Medal / Heavy Medal Club

### ISSUE THREAD

**Issue by Squelch20** [geoffhumphrey/brewcompetitiononlineentry#1476]
Addition of the ability to score points for wins that align to the Master Homebrewer Program's Circuit of America Points system

(https://opferm.cialers.org/user_images/distinguished.png)

**Comment by geoffhumphrey** [comment]
This will be added to the core code starting with 2.6.2. Admins can choose to use the CoA formula or the points system that is currently used.
