### ISSUE TITLE
Scoresheets not available to participants

### ISSUE THREAD

**Issue by mattbcba** [geoffhumphrey/brewcompetitiononlineentry#1478]
PHP Version – 7.4.33;
MariaDB Version – 5.5.5-10.6.14-MariaDB-cll-lve

Hosted

URL: (https://bcba.brewingcompetitions.com)

After an update in the summer my install switched itself from Pro Mode to Amateur Mode, then after the server migration went back to pro mode. The issue I'm having is that the participants who registered when in amateur mode are unable to view their scoresheets. Furthermore when I edit the accounts to add an organization it doesn't show up on their account. I've tried on safari and chrome.

**Comment by geoffhumphrey** [comment]
Hi @mattbcba, thanks for reporting.

I've made a change for hosted installations to allow Admins of Pro installations to add an Organization name to any user by editing their account info from the Admin > Manage Participants screen. 

In looking deeper into your installation - both before migration and after - it appears that no PDF scoresheets were uploaded to either server nor were any Electronic Scoresheets added to the database. Thus why your participants aren't seeing their scoresheets. 

Your preferences indicate that the Scoresheet Unique Identifier you're using is the 6-digit Entry Number. My advice is to make sure that the scoresheets PDFs you presumably have locally should each be named with the 6-digit Entry Number. Then, simply upload them via your installations Admin > Scoring > Upload Scoresheets function. Once that's done, your entrants will be able to download them from their My Account page.

Please reach out if you have any questions.

**Comment by mattbcba** [comment]
Hi Geoff

It worked last Thursday but I've lost the ability to add an organization name. It seems to be the key to making the scoresheets viewable.

**Comment by geoffhumphrey** [comment]
Hi Matt, my mistake. The code allowing to do that was overwritten. It's now fixed and you're able to add org names to individual accounts as an Admin.
