### ISSUE TITLE
Version 2.6.2: Issue #1458 Not Fixed by 2.6.2

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#1481]
Hi Geoff,

I commented on #1458 but I don't know how to re-open the issue.

https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/1458#issuecomment-1807245190

I tried the new release and I'm still not able to edit profiles to fix Province. Whenever I try to edit to correct province and save, it doesn't save the value.

Thanks,
Eric

**Comment by geoffhumphrey** [comment]
Eric, I'm so sorry to day that I'm truly, unabashedly, frustratingly flummoxed by the continued issues with Canadian states you've experienced within the application. On the surface, it's a simple text field to save into a variable character SQL column. Should be straight-forward, right? I cannot to this day re-create the issues you've described. Sigh.

There was a variable I used called `$state` used when processing registration and/or adding/editing a participant's info. That same variable named is used in a couple third-party classes, which **may** have introduced a conflict. I've changed the `$state` variable in the user add/edit processing in the hopes that it will work for you. It's in [this commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/63ec90684b4e691f10bdbabba836582e6ff8bfe8) and will be included in the next version.

Fingers crossed.

**Comment by ercousin** [comment]
Hey Geoff,

I installed 2.7.0 on top of my old brewslam.gtabrews.ca database from 2023 which contained this issue.

Unfortunately it doesn't seem to resolve it :(

Proof I got the new version:
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/1551339/b31b8aa3-1456-43f8-9043-acb2b3b13022)

What I'm trying to fix:
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/1551339/7155e553-1bdb-491b-9118-923c4b1a9b55)

When I go to edit that profile to try and save "ON" as State/Province, it shows as not-selected:
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/1551339/172dc4e2-7c10-4ddc-ad99-f0ebf79de6ee)

I change it to Ontario, hit save, but it still displays as Toronto, MT...

When I go into PhpMyAdmin, I can see MT there as well:
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/1551339/737eee91-d2b6-4dd1-afe8-b59b1abf0472)

I'm able to edit it to ON, and it sticks...
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/1551339/ea5ed08e-a178-4949-9153-362bae59fd12)

**Comment by ercousin** [comment]
I guess at this point, we may need to see if this can be replicated on a fresh install for a new competition.
