### ISSUE TITLE
Main website at https://brewingcompetitions.com/ is showing PHP errors on the page

### ISSUE THREAD

**Issue by gene1wood** [geoffhumphrey/brewcompetitiononlineentry#1485]
Browse to

https://brewingcompetitions.com/

And you'll see it's showing PHP errors

![errors on main page of BCOE M site](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/1134034/17980d89-9639-4339-bf1e-20cbefd94949)

**Comment by geoffhumphrey** [comment]
Thanks for the heads up. I've adjusted the settings.
