### ISSUE TITLE
Version 2.6.2 (e) : "Extra Info" says 0 characters used even though text is in the field.

### ISSUE THREAD

**Issue by Port16-MAS** [geoffhumphrey/brewcompetitiononlineentry#1488]
**Verify the Following**
Reporting About the Latest Version? Yes
Searched Issue Reports for Bug? Yes
Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.6.2 (e) 
Installation URL: https://petefest.brewbrosco.com
Hosted Installation? Yes

**Describe the Bug**
Entry info doesn't show correct character count in "Extra Info"

**To Reproduce**
1. Go to Admin dashboard > Entries and Participants > Manage Entries
2. Click on an entry that has Required Info
3. Scroll down to Required Info field
4. Text field description lists "65 character limit - use keywords and abbreviations if space is limited. Characters used: 0" even though there is text in the field. If you type in the field, the count is updated, but saving and returning to the entry shows the same message, 0 characters.

**Expected Behavior**
Character count to be accurate.

**Screenshots**
![Before Edit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/154395321/8a9bc331-930f-4aed-9634-9f0d7266e052)
![Edited then Saved](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/154395321/249bea81-af65-41ee-8268-d8e64ed7f245)
![Reviewing entry after edit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/154395321/d3f683a5-6fba-41ed-a427-60a6eab26852)

**Server Environment**
- PHP Version – 8.1.26;
- MySQL Version – 5.7.23-23
- Apache: 2.4.58

12/20/23 - Update - Added version information.

**Local Environment**
 - OS: Windows 11
 - Browser: Firefox, Edge
 - Browser Version: FireFox 121.0 (64-bit) - Edge 120.0.2210.77 (Official build) (64-bit)

**Additional Context**
When the entries were created, the install was at version 2.6.0 (e) and then we upgraded. The entry in question was listed as a "unconfirmed" entry, I don't know the date and time it was entered, but after the upgrade it's no longer displayed as unconfirmed. Side note: Geoff, thanks so much for making this software available. Love it!

**Comment by geoffhumphrey** [comment]
Thanks for reporting and the eagle eye! Luckily, it was a quick and simple fix that is now available in [this commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/4be5bfe54f280881361cf5e3664dcb7ca1610b5f). Applied to both the Required Info field and the Brewer's Specifics field on the add/edit entry screens for both Admins and Participants.

**Comment by Port16-MAS** [comment]
You are on fire! Thanks for that, and I hope your recovery is going well.

Cheers!
Mike Scott
