### ISSUE TITLE
Unable to apply discount code

### ISSUE THREAD

**Issue by Port16-MAS** [geoffhumphrey/brewcompetitiononlineentry#1491]
**Verify the Following**
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes
There are two issues for this bug in previous versions of the software. 
#22 and #342 - both are closed

Reviewed the Good To Know Issue Reports? Yes

BCOE&M Info
Version: 2.6.2.1 / 2.6.2 (e)
Installation URL: https://petefest.brewbrosco.com/
Hosted Installation? Yes

**Describe the Bug**
When entering a discount fee, clicking "verify" brings you to a blank page. With server debugging on, the following error is displayed.

`Fatal error: Uncaught TypeError: hash_equals(): Argument #2 ($user_string) must be of type string, null given in /home3/brewbros/public_html/competitions-petefest/includes/process.inc.php:92 Stack trace: #0 /home3/brewbros/public_html/competitions-petefest/includes/process.inc.php(92): hash_equals('d804bdf237bff60...', NULL) #1 {main} thrown in /home3/brewbros/public_html/competitions-petefest/includes/process.inc.php on line 92`

**To Reproduce**
1. Log into site, when you have unpaid entries.
2. Click on profile > Pay Entry Fees
3. Enter Discount Code in field and press verify
4. See blank page.

**Expected Behavior**
Discounted entry fee would be applied.

**Screenshots**

Server Environment
    PHP Version – 8.1.26;
    MySQL Version – 5.7.23-23
    Apache: 2.4.58

**Local Environment**
 - OS: Windows 11
 - Browser: Firefox
 - Browser Version: 121.0 64 bit

**Additional Context**
Verified the discount code is correct.

**Comment by Port16-MAS** [comment]
We had another site, running 2.5.0, and the discount code works as expected. We upgraded it to the latest version, and now it has the issue as well.

**Comment by geoffhumphrey** [comment]
I've isolated the issue and have implemented a fix in [this commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/cefed53dfa220677a5d827559d479887cd828a62). Replace the /sections/pay.sec.php file on your server with the one in the commit and you'll be good to go.

**Comment by Port16-MAS** [comment]
Confirmed that the issue is resolved with that commit. Thank you @geoffhumphrey !
