### ISSUE TITLE
Update bad link in PayPal IPN documentation page

### ISSUE THREAD

**Issue by gene1wood** [geoffhumphrey/brewcompetitiononlineentry#1492]
Please updated this webpage

https://brewingcompetitions.com/paypal-ipn

as the page link describing how to setup "Auto Return" is a now out of date PayPal document page with incorrect instructions and links to PayPal domain names that no longer exist.

Please change the link from

https://www.paypal.com/cgi-bin/webscr?cmd=p/mer/express_return_summary-outside

to

https://www.paypal.com/us/cshelp/article/how-do-i-use-paypals-auto-return-feature-HELP197

which contains the current correct instructions.

**Comment by geoffhumphrey** [comment]
Thanks for the heads up. Done!
