### ISSUE TITLE
Change subdomain name on hosted competitions

### ISSUE THREAD

**Issue by hirendu** [geoffhumphrey/brewcompetitiononlineentry#1496]
We have a slight change in name of our competition but the hosted comp still has subdomain based on old name. Can we update the subdomain name? 

(Sent by email also but again - requesting here for tracking/followup).

**Comment by geoffhumphrey** [comment]
Hi Hirendu, apologies, I was out of the country for most of last month and have been recovering from surgery the last couple of weeks. Needless to say, I'm a bit behind the eight ball at the moment. I did get your email and will get your subdomain changed in the next couple of days with redirects in place for the old subdomain.
