### ISSUE TITLE
Enhancement: Missing Club - Garner Ale Society

### ISSUE THREAD

**Issue by zane329** [geoffhumphrey/brewcompetitiononlineentry#1497]
'Garner Ale Society' homebrew club is missing from the Club dropdown list.

Please add to software so the club is an option.

Thanks.

**Comment by geoffhumphrey** [comment]
No problem. That will be included in the next release. 

In the meantime, it's relatively easy to add a club to the `$club_array` in /includes/constants.inc.php if you're comfortable.

Download and open that file locally with your favorite text editor and find the $club_array variable. In the latest release, it starts at line 153. It'll look like this at the beginning of the array:

``
$club_array = array(
 "1.090",  "#sovai",  "10 Paces Brewing",
``
... and so on (the array has over 2000 clubs).

Add your club name before `"1.090",` like this:
``
$club_array = array(
"Garner Ale Society",  "1.090",  "#sovai",  "10 Paces Brewing",
``

Be sure it's enclosed in double quotations and has a following comma outlise the quotation marks (commas separate the array's data in PHP). Upload the updated file to the BCOE&M /includes/ directory on your server. It'll be available to your users immediately.

A future release will allow Admins to add clubs via the UI.

**Comment by geoffhumphrey** [comment]
FYI - one thing I forgot to mention. As of version 2.6.0, Admins are able to add clubs to the list via the UI. Go to Admin Dashboard > Competition Preparation > Edit Competition Info. Look for the Additional Club Names label under the General heading. 

Search for the club.
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/5216502/b1abfcd6-1c76-4902-82ed-d0117220ca66)

If it's not found, you can add it to the list for your installation.
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/5216502/a60b1a85-f16b-4642-8744-d048c0f8adea)
