### ISSUE TITLE
 CAPTCHA was not successful

### ISSUE THREAD

**Issue by donutbrew** [geoffhumphrey/brewcompetitiononlineentry#1498]
**Verify the Following**
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes 

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.6.2
Hosted Installation? No

**Describe the Bug**

Forms that use reCAPTCHA are not working--they time out and the site reports " CAPTCHA was not successful. Please try again" in a warning banner at top. I've used this setup for several years (same domain, same paths, same Google reCAPTCHA settings). However, I did recently update to 2.6.2.

Looking at the Google reCAPTCHA dashboard, I don't see that the requests are coming in, and at the top of the dashboard is this message:

> We detected that your site is not verifying reCAPTCHA solutions. This is required for the proper use of reCAPTCHA on your site. Please see [our developer site](https://developers.google.com/recaptcha/docs/verify#api-request) for more information.

I'll continue looking in to it and post a solution if I find one, but wondering if anyone else has seen this.

**Comment by geoffhumphrey** [comment]
I just tested on one test and one production site each running 2.6.2.1 and the CAPTCHA is working as expected. When getting  key pair from Google, make sure you are getting a keys pair that is from the V3 Dashboard (NOT Enterprise) and its type is checkbox.

**Comment by donutbrew** [comment]
Yeah, that's what I've got.

However, I think I resolved it. Over the last few months, doing a couple of PHP updates, I think `allow_url_include` got set to Off in `php.ini`. I switched that on and restarted the server, and everything is working now.
