### ISSUE TITLE
Version 2.6.2.1+6b80f0d7: Sponsor logos with ampersand (&) in file name are not handled correctly

### ISSUE THREAD

**Issue by peterurbanec** [geoffhumphrey/brewcompetitiononlineentry#1501]
**Verify the Following**
Reporting About the Latest Version? Yes
Searched Issue Reports for Bug? Yes
Reviewed the Good To Know Issue Reports? No

**BCOE&M Info**
Version: 2.6.2.1 (master at 6b80f0d7)
Hosted Installation? No

**Describe the Bug**
When a sponsor logo image with ampersand in the file name is uploaded, it is not correctly handled in some places. For example, it is not possible to delete the file. The logo also does not display correctly when it is associated with a sponsor.

**To Reproduce**
1. Go to 'Administration: Upload Images'
2. Upload a file named 'hop&grain.png'
3. Go to 'Administration: Sponsors'
4. Assign the logo file named 'hop&grain.png' to one of the sponsors
5. Go to Sponsors
6. The sponsor entry shows a blank space where the logo should appear
7. Go back to 'Administration: Upload Images'
8. Click on the delete icon for the logo file named 'hop&grain.png'
9. Click Yes to confirm deletion
10. The logo file named 'hop&grain.png' was not deleted

**Expected Behavior**
1. Uploaded logo should be visible next to the sponsor.
2. It should be possible to delete the uploaded file.

**Comment by peterurbanec** [comment]
BTW: GitHub auto-added the `enhancement` label, where it should have been `bug`, when creating this issue.

**Comment by geoffhumphrey** [comment]
Hi @peterurbanec and thanks for reporting. I've confirmed the issue. Hopefully, [this commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/4a5ec0fd523e593414d9a2cb86bb5b5ed03d5f52) addresses the issue you've described. It has when I've tested in my dev environments.

This fix will be included in the next version.
