### ISSUE TITLE
Enhancement: Brewer Club Match - Accent Insensitive Search

### ISSUE THREAD

**Issue by tmack8001** [geoffhumphrey/brewcompetitiononlineentry#1504]
**Reviewed the Release Notes?**
Please review the complete [Release Notes](https://brewingcompetitions.com/release-notes) on [brewingcompetitions.com](https://brewingcompetitions.com) *prior* to making your request. Your enhancement may have already been incorporated into the core code.

**Is your enhancement or feature request related to a problem? Please describe.**
When club members search for "The Bru Club" our club entry doesn't show up as it is spelled with a punctuated letter, "The Brü Club"

**Describe the solution you'd like:**
When filtering a list, it is best to filter the list by stripping out any extra character punctuation (not everyone knows the way to type punctuated characters : umlauts, accents, etc).

<img width="957" alt="image" src="https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/2158627/84ea9df3-d242-41e1-a2c0-c1bd1b7c6ef1">
<img width="961" alt="image" src="https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/2158627/c12190fc-0091-4fed-bb13-fd1ad97beec4">

**Comment by tmack8001** [comment]
I checked the underlying implementation to see what would it take to do this since the filtering is performed client-side via bootstrap-select logic.

There was a PR in bootstrap-select that performs the expected logic via `data-live-search-normalize="true"` - https://github.com/snapappointments/bootstrap-select/pull/1686

The version that is currently pinned in BCOEM is v 1.12.0 whereas the logic desired was released in v1.13.4 back in 2018 ([source](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.4))

**Comment by geoffhumphrey** [comment]
Confirmed - and thanks for reporting and doing some further research. The next version will update to Bootstrap Select 1.13.18 and add the `data-live-search-normalize="true"` specification to each dropdown that employs the function.

**Comment by tmack8001** [comment]
Ah awesome @geoffhumphrey !
Was going to dive in and try to provide this fix myself, but didn't have the time yet. Appreciate the assistance.
