### ISSUE TITLE
How To: Need to add an admin to the comp

### ISSUE THREAD

**Issue by MikeMalsed** [geoffhumphrey/brewcompetitiononlineentry#1505]
Version:2.5.0 (don't want to upgrade until after the competition

Installation URL: brewcomp.beerme.club

Is your installation hosted? No - we host it

Description of Issue: I need to add an admin. Right now it's me, and I need to add another as I'm transitioning someone else in to assist / take over. I've made him Organizer, but I don't see where I can make him admin.

I also need our Treasurer to be able to see the list of Entries so she can click Paid when payment comes through (we don't use PayPal so we have to manually do it) but cannot see how to do this either.

Point me in the right direction?

Thanks

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title (e.g. "2.1.18 - ").

**Comment by geoffhumphrey** [comment]
Hi @MikeMalsed - to make anyone an admin, log in as an Admin yourself and then go to Admin Dashboard > Entries and Participants > Manage Participants. In the Actions column of the participant you want to make an Admin, select the lock icon. You can then choose to make the participant a Top Level Admin or simply an Admin.

**Comment by MikeMalsed** [comment]
Thank you sir – that worked perfectly!

Micheal Malsed
Asst Director for Student Technology Services
Information Technology Services
Claremont McKenna College
Adams 203
Claremont, CA 91711
Phone:(909)607-4547 Fax:(909)621-8661
***@***.******@***.***>
