### ISSUE TITLE
Enhancement: Add UI improvements to disabled submit buttons indicating which fields haven't been filled in

### ISSUE THREAD

**Issue by gene1wood** [geoffhumphrey/brewcompetitiononlineentry#1506]
**Is your enhancement or feature request related to a problem? Please describe.**

We've encountered the following scenario each year :

* A competition entrant goes to fill out a form on the BCOE&M site. Examples would be the steward registration page or the edit profile page
* As the user goes through the longer, multi-page forms, they overlook one of the many fields, leaving it unfilled out. Examples would be [the drop off location in the registration page](https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/1278#issuecomment-1021544162) or the "Entry Delivery" field in the "Edit Account Info" form.
* The user gets to the bottom of the form and finds that the submit button is disabled

The button is disabled because a required field hasn't been filled in.

![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/1134034/f48de1e6-a701-4e83-947c-61242c0c72e5)

At this point there are a few different UI challenges that cause user's to get stuck

1. There's no visual indicator to differentiate all the required fields from the optional fields. The textbox fields have the star icon on the right side of the field (which I'm assuming means they're required), but the other field types, like required drop-downs, don't have a visual indicator that it's required
2. Many forms are multiple pages long and so the unfilled in field might not even be displayed when the user encounters the disabled submit button
3. The button the user clicks at the bottom of some forms to submit or save their changes is labeled in a confusing way. On the "Edit Account Info" page, the button to submit or save changes says "Edit Account Info" causing the user to be unsure what to do next since they're already editing the account info
4. There's no message indicating why the submit button is disabled

**Describe the solution you'd like:**

Here are some features that would mitigate this UI confusion that users get stuck by

1. If the star icon is meant to indicate that a field is required, update the UI to add that star to all required fields, not just text boxes that are required fields
2. Add a tooltip to the star icon that shows a message indicating what the star means
3. Instead disabling the submit button, change the function of clicking the submit button when a required field hasn't been filled in, to 
   * Focusing the view on the required field that isn't filled in so that the page scrolls up to that field
   * Adding style markup to visually indicate that the field is missing information like surrounding the field in red
4. Add a dynamic `title` attribute or just an error message to the disabled submit `button` element that enumerates the required fields that haven't been filled in.
5. Change the submit button text on forms to say something like "Submit" or "Save"

**Describe alternatives you've considered:**

So far, the only alternative we've found is that I zoom with the user and screen share and look with them through the fields to help them find the required field that they've forgotten to fill in.

**Additional context:**

I encountered this problem in 2022 and reported it here #1278 where these types of UI improvements would have enabled me and the user to identify the cause of the problem (instead of bugging you about it)

**Comment by geoffhumphrey** [comment]
Some enhancements here will be partially addressed in the next version and some will be put into consideration for v3.0.0, coming later this year, which will feature a totally reworked UI for public and non-Admin-related areas of the application. 

For the next release...

To make required fields exceedingly obvious, a star icon will be added to the labels of all required fields in the add/edit account, and add/edit entry forms. For example, on the registration and edit account screen:

![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/5216502/9432846c-610e-49e4-a4c0-3cda01ac47a7)

And on the add/edit entry screen:

![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/5216502/ad8cd11b-710a-4dd9-a86c-e77fa14bb3c3)

There will also be an alert present below the submit button on both forms informing the user when one or more of the required fields does not have a value, not selected, etc. Like so:

![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/5216502/efcc74f3-56c6-470d-9b5a-44145aeddf75)

This alert will be removed and the button enabled once all required fields have been filled out.

For other required fields on other forms, such as the Contact page, a tooltip will be added indicating that the star indicates a required field.

Hopefully, both of these in tandem should alleviate the issues you've experiened - perhaps staving off any future Zoom calls with entrants.

**Comment by gene1wood** [comment]
@geoffhumphrey That sounds great, thanks so much for these additions! (Indeed in the 3 weeks since I opened this, our judge coordinator pointed another user to me who was stuck/confused about the edit/submit button being disabled)
