### ISSUE TITLE
Version 2.6.2 (e): Some non-English characters stored and displayed in HTML encoded format

### ISSUE THREAD

**Issue by gradys** [geoffhumphrey/brewcompetitiononlineentry#1507]
**BCOE&M Info**
Version: 2.6.2 (e)
Installation URL:  https://soutez.cech-pivo.cz/korbel
Hosted Installation? No

**Describe the Bug**
Non-English characters (used for example in Entry Name) are not displayed correctly.

*Note:* Entries are displayed correctly after being manually edited directly in database.

**To Reproduce**
1. Add new Entry (index.php?section=brew&go=entries&action=add)
2. Use national characters in form fields (for example in Entry Name)
3. Saved Entry is displayed incorrectly

**Screenshots**
Use Czech national characters in Entry Name
![01](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/7261188/ee0267ad-cabd-49b4-85f4-27209caab7b9)

After saving the form, some non-English characters are displayed as HTML Encoded(?)
![02](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/7261188/e9ee98cb-8497-480d-a875-ff57d831b588)

The same wrong result seen in administration (index.php?section=admin&go=entries)
![03](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/7261188/b99dad9f-27dc-45a9-bc31-a035e2411cec)

Incorrect string is stored in database
![04](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/7261188/3fa471a1-ccbc-4f48-bdc3-72f1d1487f8b)

**Server Environment**
- PHP Version: 7.4.33
- MySQL Version: 5.5.5-10.3.39-MariaDB

**Local Environment**
 - OS: Windows (various versions)
 - Browser: various browsers and versions

**Comment by geoffhumphrey** [comment]
I'm actually going to flag this as a bug that was inadvertantly introduced with version 2.6. To fix immediately, you can simply replaces lines [106 and 107 in the /includes/process/process_brewing.inc.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/38955052cf1960fab735566f8dc814088bfb666b/includes/process/process_brewing.inc.php#L106C3-L107C72) file with:

```
$brewName = sterilize($_POST['brewName']); 
$brewName = $purifier->purify($brewName);
```
This will apply the sanitization functions prior to the HTML purifier doing its thing. With that, the HTML won't be encoded.

I'll be cleaning this up across the application for the next version, but this should help with the problem you've discribed.

**Comment by gradys** [comment]
Hi Geoff,
thank you for the quick fix, it's working.

Martin


P.S. For the reference - I had to update BREWING table as well.

`update <BREWING>" set brewName = HTML_Decode(brewName);`

Where HTML_Decode function is defined like this (more characters can be added for example from this site: https://www.w3schools.com/charsets/ref_utf_latin_extended_a.asp):

```
DELIMITER $$
CREATE FUNCTION HTML_Decode(X TEXT) RETURNS text CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci
    DETERMINISTIC
BEGIN 

    DECLARE TextString text ; 
    SET TextString = X ; 

    IF INSTR( X , '&Aacute;' ) 
    THEN SET TextString = REPLACE(TextString, '&Aacute;','Á') ; 
    END IF ; 

    IF INSTR( X , '&Eacute;' ) 
    THEN SET TextString = REPLACE(TextString, '&Eacute;','É') ; 
    END IF ; 

    IF INSTR( X , '&Iacute;' ) 
    THEN SET TextString = REPLACE(TextString, '&Iacute;','Í') ; 
    END IF ; 

    IF INSTR( X , '&Oacute;' ) 
    THEN SET TextString = REPLACE(TextString, '&Oacute;','Ó') ; 
    END IF ; 

    IF INSTR( X , '&Scaron;' ) 
    THEN SET TextString = REPLACE(TextString, '&Scaron;','Š') ; 
    END IF ;

    IF INSTR( X , '&Uacute;' ) 
    THEN SET TextString = REPLACE(TextString, '&Uacute;','Ú') ; 
    END IF ; 

    IF INSTR( X , '&Yacute;' ) 
    THEN SET TextString = REPLACE(TextString, '&Yacute;','Ý') ; 
    END IF ; 

    IF INSTR( X , '&aacute;' ) 
    THEN SET TextString = REPLACE(TextString, '&aacute;','á') ; 
    END IF ; 

    IF INSTR( X , '&eacute;' ) 
    THEN SET TextString = REPLACE(TextString, '&eacute;','é') ; 
    END IF ; 

    IF INSTR( X , '&iacute;' ) 
    THEN SET TextString = REPLACE(TextString, '&iacute;','í') ; 
    END IF ; 

    IF INSTR( X , '&oacute;' ) 
    THEN SET TextString = REPLACE(TextString, '&oacute;','ó') ; 
    END IF ; 

    IF INSTR( X , '&scaron;' ) 
    THEN SET TextString = REPLACE(TextString, '&scaron;','š') ; 
    END IF ; 

    IF INSTR( X , '&uacute;' ) 
    THEN SET TextString = REPLACE(TextString, '&uacute;','ú') ; 
    END IF ; 

    IF INSTR( X , '&yacute;' ) 
    THEN SET TextString = REPLACE(TextString, '&yacute;','ý') ; 
    END IF ; 

    RETURN TextString ; 

    END$$
DELIMITER ;
```
