### ISSUE TITLE
Version 2.X.X: Data Export - All Entries

### ISSUE THREAD

**Issue by darthtexan** [geoffhumphrey/brewcompetitiononlineentry#1514]
For Lunar Rendezbrew (https://rendezbrew.brewingcompetitions.com), the Data Export to Excel is providing bad data.  Our organizers have tried all three of the All Entries exports to Excel for planning tables & reviewing missing information.  But those Excel reports have incorrect data from what is in the system.

For example, the table set up has all subcategories assigned to tables.  But the download shows seven or eight with no table assigned.  Also, the other table assignments do not match what in in the BCOEM listing.   We need this to be accurate so after sorting day, we can run reports to confirm table assignments and work through judging assignments.

Thanks.

**Comment by geoffhumphrey** [comment]
Hi @darthtexan - this has been fixed for all hosted competitions. There was a corrupted function that was preventing export of some data points into the CSV file.

This issue does not affect other, non-hosted installations.
