### ISSUE TITLE
Version 2.7.0: Windows detects trojan in .tar.gz and .zip release files

### ISSUE THREAD

**Issue by prphntm63** [geoffhumphrey/brewcompetitiononlineentry#1517]
**Verify the Following**
Reporting About the Latest Version? Yes
*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes
*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes
*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**BCOE&M Info**
Version: 2.7.0
Installation URL: N/A
Hosted Installation? N/A

**Describe the Bug**
Windows identifies a trojan in the latest release zip/tar

**To Reproduce**
1. Dowload the .tar.gz or .zip from releases section for 2.7.0
2. Windows identifies the file as containing `Wacatac.B!ml` trojan

**Expected Behavior**
Users should be able to download and unzip the release on Windows

**Screenshots**
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/4017530/2494a36c-6704-4379-a06f-f1d4fe8a2a18)

**Server Environment**
- PHP Version: N/A
- MySQL Version: N/A
- Other Info: N/A

**Local Environment**
 - OS: Windows
 - Browser: N/A
 - Browser Version: N/A

**Additional Context**
Reported from MHP thread on Facebook

**Comment by geoffhumphrey** [comment]
I've deleted, shredded, obliterated, and eviciserated the original 400.php file and rebuilt it from scratch. It's in the new master commit. 

I've put the commit's zip file through virustotal.com as well as Windows locally through Avast and Windows Defender and it came out clean.

![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/5216502/6eff5e64-6c8e-42de-9a5e-68921bcb7fc9)

@prphntm63, if you wouldn't mind running [the master commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/archive/refs/heads/master.zip) through the regimen you followed before, I'd appreciate it.  

If things are good, I will rebuild the 2.7.0 release.

**Comment by prphntm63** [comment]
Looks great now. Thanks @geoffhumphrey!
