### ISSUE TITLE
Enhancement: "Print Bottle Labels" on user account screen is sometimes confusing

### ISSUE THREAD

**Issue by r-squared** [geoffhumphrey/brewcompetitiononlineentry#1519]
**Is your enhancement or feature request related to a problem? Please describe.**
Every year I receive at least one question about not being able to print labels where the issue that turns out to be they did not realize they had to select their entries. While there is a tooltip next to selection boxes, there is nothing obvious to the brewer that the button availability is tied to the selection boxes, so they never hover and read the tooltip.

**Describe the solution you'd like:**
One of two options would likely make this more obvious or at least reduce confusion.
1) Default to having all entries selected on page load. Most brewers are likely printing labels for all items anyways.
2) Renaming button to "Print Selected Bottle Labels" makes it more obvious that they need to select the entries.

**Comment by geoffhumphrey** [comment]
Ah, yes. You are correct. This is what I get for the lack of coffee I had today. The latest commit makes the switch and corrects the display.
