### ISSUE TITLE
Enhancement: Update Problematic/Fair/Good indicator based on portion of sheet filled

### ISSUE THREAD

**Issue by wactuary** [geoffhumphrey/brewcompetitiononlineentry#1522]
**Is your enhancement or feature request related to a problem? Please describe.**
While entering a scoresheet, when you first populate Aroma score, there is an indicator that starts with "Problematic" because the total score is below 13.  Then as you add more sections, Aroma, Flavor, it starts to rise and is never useful until scoring is complete.  Also when finished, the indicator does not say there is a missing score, which would be helpful.  You have the hint of "I thought this beer was Excellent, why do my scores say only Very Good" and you look up to find the missing section, but this could be more direct.

**Describe the solution you'd like:**
I would like this status indicator to show where the beer is tracking as you progress.  If you provide a 8/12 aroma, you have given 66% of the points, tracking toward a Very Good (33pts).  As you progress and add 3 for Aroma, that's 11/15, so ~37, still Very Good, you add Flavor, Mouthfeel and finally as you add Overall Impression, it's telling you how this beer is tracking.  To give an indicator that the scoring isn't complete, you could say "of 12" and "of 15" as you add more sections, or provide some other visual indicator of completeness.

**Describe alternatives you've considered:**
An alternate approach to showing you still have an empty section could be with color coding.  This isn't ideal from an accessibility perspective for those who are color blind.  Or at least not if you use red/green.

**Comment by geoffhumphrey** [comment]
In the next version, there will be "...some other visual indicator[s] of completeness" as requested above. There will be visual indicators that a part of the scoresheet has been scored. If Aroma has a score, for example, a green checkmark will replace the red X under the calculated score, like so:

![image](https://github.com/user-attachments/assets/42af211c-26b2-48f5-9eb2-d0aab43bc696)

This visual indicator will be sticky as the user moves through the scoresheet. When they provide a score for all of the other factors like appearance, flavor, etc. the will have a quick reference to see whether they have missed a score or not. All checkmarks indicate all scored areas are present:

![image](https://github.com/user-attachments/assets/e2327a7b-f0ef-4cf8-a677-ebb118013643)

Additionally, there a checkmark will appear by the section header when a score is indicated, like so:

![image](https://github.com/user-attachments/assets/84e7b529-8e70-493f-80cd-af61c800c5ab)

**Comment by wactuary** [comment]
I like your new approach.  Thanks for addressing this.
