### ISSUE TITLE
Alphanumeric AHA MemberId

### ISSUE THREAD

**Issue by tmack8001** [geoffhumphrey/brewcompetitiononlineentry#1524]
**Verify the Following**
Reporting About the Latest Version? Yes 

Searched Issue Reports for Bug? Yes related to closed bug https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/1413

Reviewed the Good To Know Issue Reports? Yes 

**Describe the Bug**
AHA Numbers now seemingly support non numeric values, but BCOEM restricts to numerical leading to failures when someone has an alpha numerical AHA Member ID.

**Additional Context**
It seems that AHA made a change recently (within the last year) to start returning member IDs with alpha numeric values. This was reported to me within the discord server for MHP and adding an Issue to track that for the brewer that reported it. My specific AHA Id from several years ago is numerical.

**Comment by geoffhumphrey** [comment]
To address this now, you'll need to have access to your installation's database to change the brewerAHA column datatype from its current one (INT) to a string type that will accept alphanumeric/symbol combinations. VARCHAR fits the bill here with a 255 character for future proofing. 

So, the SQL command would look like this:

``
ALTER TABLE `brewer` CHANGE `brewerAHA` `brewerAHA` VARCHAR(255) NULL DEFAULT NULL;
``

Be sure to add the prefix before "brewer" if you have one defined.

Then, [line 66 in the /sections/brewer_form_1.sec.php file](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/efa7f83c36523506a1dd7f21c59109dd0c9b010a/sections/brewer_form_1.sec.php#L66) will need to be altered, instructing the browser to accept alphanumeric input on the AHA Number text box (via the pattern attribute):

``
<input class="form-control" name="brewerAHA" id="brewerAHA" type="text" pattern="[A-Za-z0-9]+" placeholder="" data-error="<?php echo $brew_text_019; ?>" value="<?php if ($action == "edit") echo $row_brewer['brewerAHA']; ?>" placeholder="">
``

The above will be done for the next release.

**Comment by jkmarut** [comment]
If the alphanumeric AHA ID issue was supposedly fixed in 2.7.1, I can confirm that the problem is still occurring in the field with 2.7.2.

Just tried to signup for a comp, still seeing the same issue with my AHA ID which starts with a letter.
