### ISSUE TITLE
Version 2.6.2: Required Information does not print on bottle label when there is an apostrophe in text

### ISSUE THREAD

**Issue by MarsMug** [geoffhumphrey/brewcompetitiononlineentry#1526]
**Verify the Following**
Reporting About the Latest Version? No, have checked bug reports
*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes
*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes
*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**BCOE&M Info**
Version: 2.6.2
Installation URL: https://competitions.londonamateurbrewers.co.uk/labopen/
Hosted Installation? No

**Describe the Bug**
For entries that have 'Required Information', if there is an apostrophe ' character in the text then Required Information does not appear on the bottle label. Other characters do not seem to be affected.

**To Reproduce**
1. Add entry that has required information.
2. Add description that includes an apostrophe (e.g. Here's my entry)
3. Attempt to print label for entry

**Expected Behavior**
Required information should appear on bottle label

**Screenshots**
![bug1](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/38494103/fe4009cd-f1a1-43f3-b4ea-34a98acf91cf)
![bug2](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/38494103/fcb1599c-c3c9-4d17-9468-e4d46da25330)

**Server Environment**
Unknown

**Local Environment**
Unknown

**Additional Context**

**Comment by geoffhumphrey** [comment]
Apostrophes do affect the display of Required Information for the multiple bottle labels per page options (via Site Preferences).

In the next version, the bottle label options that print a single entry per page will be deprecated in favor of the multiple bottle labels per page options. General feedback is that the one entry per page options are unnecessarily wasteful and somewhat annoying for entrants.
