### ISSUE TITLE
Update Failed 2.5.0 to 2.7.0.1

### ISSUE THREAD

**Issue by TheStealth359** [geoffhumphrey/brewcompetitiononlineentry#1532]
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.7.0.1 (trying to update from 2.5.0)
Installation URL: montrealers.ca/malt
Hosted Installation? No

**Describe the Bug**
I tried to upgrade from 2.5.0 as per instructions (like I have done in the past). However, the home page gives me HTTP ERROR 500. I tried update.php and click yes and I also get HTTP ERROR 500.

**Expected Behavior**
A successful update.

**Screenshots**

**Server Environment**
- PHP Version: 8.1.6
- MySQL Version: 8.1.6
- Other Info: LiteSpeed V8.0.1

**Comment by grmelacz** [comment]
Got the same problem. Running 2.6.0, trying to upgrade to latest stable version.

Got this error:
`Got error 'PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Duplicate column name 'styleTypeEntryLimit' in [path]/site/MysqliDb.php:588\\nStack trace:\\n#0 [path]/site/MysqliDb.php(588): mysqli_stmt->execute()\\n#1 [path]/update/off_schedule_update.php(4010): MysqliDb->rawQuery('ALTER TABLE 'st...')\\n#2 [path]/site/bootstrap.php(67): include('/data/web/virtu...')\\n#3 [path]/index.php(11): require_once('/data/web/virtu...')\\n#4 {main}\\n  thrown in [path]/site/MysqliDb.php on line 588'AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Duplicate column name 'styleTypeEntryLimit' in [path]/site/MysqliDb.php:588\\nStack trace:\\n#0 [path]/site/MysqliDb.php(588): mysqli_stmt->execute()\\n#1 [path]/update/off_schedule_update.php(4010): MysqliDb->rawQuery('ALTER TABLE 'st...')\\n#2 [path]/site/bootstrap.php(67): include('/data/web/virtu...')\\n#3 [path]/index.php(11): require_once('/data/web/virtu...')\\n#4 {main}\\n  thrown in [path]/site/MysqliDb.php on line 588'`

**Comment by geoffhumphrey** [comment]
If you replace line 4009 in /update/off_schedule_update.php to the following, things should work properly:
```
$sql = sprintf("ALTER TABLE `%s` ADD `styleTypeEntryLimit` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;", $prefix."style_types_".$suffix);
```
The lack of the ``$suffix`` variable was throwing the error.

**Comment by jlawless1** [comment]
Hi @geoffhumphrey. I have some new information regarding this error. I was upgrading from Release 2.1.19

Running debug mode I got the following error (Fatal error from debug is posted below):

> line 1996 in MysqliDb.php is looking for the column 'update_summary' in the 'bcoem_sys' table.

I don't know when this column was supposed to have been added, but I went ahead and added this column manually with sql, `ALTER TABLE bcoem_sys ADD COLUMN update_summary VARCHAR(255);`

That corrected my issue. 

`Fatal error: Uncaught mysqli_sql_exception: Unknown column 'update_summary' in 'field list' in /home4/musicco9/public_html/MCBO/site/MysqliDb.php:1996 Stack trace: #0 /home4/musicco9/public_html/MCBO/site/MysqliDb.php(1996): mysqli->prepare('UPDATE bcoem_sy...') #1 /home4/musicco9/public_html/MCBO/site/MysqliDb.php(1602): MysqliDb->_prepareQuery() #2 /home4/musicco9/public_html/MCBO/site/MysqliDb.php(927): MysqliDb->_buildQuery(NULL, Array) #3 /home4/musicco9/public_html/MCBO/update/off_schedule_update.php(26): MysqliDb->update('bcoem_sys', Array) #4 /home4/musicco9/public_html/MCBO/site/bootstrap.php(67): include('/home4/musicco9...') #5 /home4/musicco9/public_html/MCBO/index.php(11): require_once('/home4/musicco9...') #6 {main} thrown in /home4/musicco9/public_html/MCBO/site/MysqliDb.php on line 1996`

**Comment by markalston** [comment]
Adding a note that both those issues (the missing update_summary column and the need to add $suffix to the off_schedule_update.php file) were needed when upgrading from 2.4 to 2.7
