### ISSUE TITLE
Version 2.6.0: Neither QR or Barcodes printing on entry paperwork

### ISSUE THREAD

**Issue by AdrienM76** [geoffhumphrey/brewcompetitiononlineentry#1533]
**Verify the Following**
Reporting About the Latest Version? No
We've already started accepting entries, so I'm hesitant to upgrade at this time. (as well, I see open issues of being unable to upgrade/install the latest)

Searched Issue Reports for Bug? Yes
I see it was reported and fixed for 2.6.2, but nothing with respect to 2.6.0

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.6.0
Installation URL: https://bbbbthekgb.org
Hosted Installation? No

**Describe the Bug**
Neither QR or barcodes print on entry bottle labels. It does not matter if the brewer tries to print, or if an admin does.

**To Reproduce**
1. Go to Admin Dashboard > Entries & Participants > Entries > Manage
2. Click on "Print the Entry Forms for..." action button for any entry

**Expected Behavior**
The QR & barcodes print on the label

**Screenshots**
![Screen Shot 2024-06-11 at 12 35 17 PM](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/19876193/de641214-029c-40aa-93cc-169022de331e)

**Server Environment**
- PHP Version: 8.36
- MySQL Version: 5.7.23-23
- Other Info: Apache

**Local Environment**
 - OS: Multiple (but I'm using: MacOS Montery 12.7.5)
 - Browser: Multiple (tested with Safari, Firefox Nightly, Vivaldi)
 - Browser Version: Multiple (tested with Safari 17.5, Firefox Nightly 129.01a, Vivaldi 6.7.3329.39-stable)

**Additional Context**
This worked fine in January using the same version for a different competition, though on a different host and server. I personally don't have access to the hosting account for *this* installation, but can work with the person who does to resolve the issue.

**Comment by AdrienM76** [comment]
Side question - I clicked to file a bug report, not an enhancement, but it still automatically got the enhancement label. (which it says I added, though I did not) I guess that would explain why I'm seeing that label on almost all new issues as being added by the reporter.

**Comment by geoffhumphrey** [comment]
Hi @AdrienM76. This was fixed in version 2.7.0 (see #1493); so if you update, the issue will be resolved.
