### ISSUE TITLE
All Bugs are getting the Enhancement label automatically

### ISSUE THREAD

**Issue by AdrienM76** [geoffhumphrey/brewcompetitiononlineentry#1536]
It seems regardless of if I choose Enhancement or Bug, the "enhancement" label is being added automatically 'allegedly' by the reporter. I noticed this oddity reading over some previous issues before filing one, and can confirm it happened to me as well.

**Comment by AdrienM76** [comment]
And indeed, this very issue was filed by clicking 'bug report' yet, it got the enhancement label automatically.

**Comment by AdrienM76** [comment]
I should add the caveat, that at least bugs filed by the Geoff, are getting the "bug" label rather than "enhancement".

**Comment by geoffhumphrey** [comment]
Thanks for alerting me to this, @AdrienM76. Bug reports won't be labeled as "enhancement" going further. I didn't opt to put a "bug" label on every bug report since I prefer to verify that the report is truly a bug that needs addressing.
