### ISSUE TITLE
AHA Membership ID not being accepted Version 2.5.0.0 

### ISSUE THREAD

**Issue by NCBeerGuys** [geoffhumphrey/brewcompetitiononlineentry#1542]
**Verify the Following**
Reporting About the Latest Version? Yes or No
*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes or No
*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes or No
*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**BCOE&M Info**
Version: BCOE&M 2.5.0
Installation URL: 
Hosted Installation? Yes or No

**Describe the Bug**
A new user tried to enter their AHA Member number and it didn't accept it - field was blank after accepting user info. Two admins tried to add his AHA number and it wouldn't take it (screen showed it was processing and went back to user directory - went back to check and field was blank. I tried to enter my AHA Member number and, after verifying, the field now has a zero. 

**To Reproduce**
1. Go to Manage Participants. Select David Crowder and EDIT 
2. Scroll down to AHA Member and enter 900357979.
3. Click "Edit Account Info" button. Odd the button changes to ghosted color after entering the ID PLUS the cursor shows it cannot be clicked but it allows the transaction. There are no errors on the page?
4. Screen changes to "Working, Please Stand By"
5. Go back and verify if the change was accepted - the AHA Member field is empty

**Expected Behavior**
The user AHA number should be applied and visible in the AHA Member field. 

**Screenshots**

**Server Environment**
- PHP Version:
- MySQL Version: 
- Other Info: [if applicable. Apache, nginx, etc.]

**Local Environment**
 - OS:
 - Browser: 
 - Browser Version:

**Additional Context**

**Comment by geoffhumphrey** [comment]
This is fixed in the latest version.
