### ISSUE TITLE
Version 2.7.0 (e) - The system DELETED entries over the weekend!!!! 

### ISSUE THREAD

**Issue by statsmats** [geoffhumphrey/brewcompetitiononlineentry#1549]
Version:  2.7.0 (e)
Installation URL: 
Hosted Installation? Yes

**Describe the Bug**
**Participants are beginning to email me that they are missing entries. I have confirmed this and not sure if it is only a set of specific styles or random?**

Help!

**Comment by geoffhumphrey** [comment]
Check your site preferences and verify that the Automatically Purge Unconfirmed Entries and Perform Data Clean Up option is disabled.

![image](https://github.com/user-attachments/assets/b2448ba7-9459-4b0f-8d7c-c1a974a8eabe)

In later versions (past 2.1.0 or so, I believe), the default setting is "disabled." 

No records should be automatically deleted unless you specifically enable the data clean up function. If enabled, the function will automatically purge any entries flagged as unconfirmed or that require special ingredients but do not have any 24 hours after entry as well as any data clean-up functions. 

If this option is disabled, however, please note that any Top-Level Admin has the option to manually purge entries that meet certain criteria at any time via Admin Dashboard > Data Management:

![image](https://github.com/user-attachments/assets/43c2aa23-ca0a-4767-8465-9832930e5d4d)

**Comment by statsmats** [comment]
Hi Geoff,

The automatic purge WAS set to enable (now disabled). Not sure why/how but
not something I enabled and did not have the problem last year.

So...I will instruct those participants with missing entries to re-enter.

Would the system purge an entry after labels are printed?

Dave

**Comment by geoffhumphrey** [comment]
Yes since there's no flag that informs the system that labels have been printed. To keep things consistent, anyone who has to re-enter should also print new bottle labels since their entry numbers will be different.
