### ISSUE TITLE
Code 39 barcode

### ISSUE THREAD

**Issue by rommel109g** [geoffhumphrey/brewcompetitiononlineentry#1551]
Version: 2.7

Hello , i am working on programming my Brother QL-820NWB label printer to automatically print a judging number label when the entry barcode is scanned.

to do so i need to download an excel spreadsheet into the printer with the data.

the issue is i have downloaded all available code 39 fonts i can find on the internet but none of them correspond to the one your software prints out.

can you provide a download link to the same code 39 fonts that you software uses?    or email me a copy ?

**Comment by geoffhumphrey** [comment]
See response in Issue #1555.
