### ISSUE TITLE
Verison V2.7.1 Can't add entries

### ISSUE THREAD

**Issue by mdgann** [geoffhumphrey/brewcompetitiononlineentry#1553]
**BCOE&M Info**
Version: 2.7.1
Installation URL: 2manybeers.com/commercial
Hosted Installation? No

**Describe the Bug**
Participant's can't add an entry. 

**To Reproduce**
When I setup the site, I created a test user and I was able to add an entry. After I received a problem report, I logged back on as my test user and tried to add another entry. After filling out the entry form and clicking on "Add Entry +" button, I'm taken back to the "My Account" page and the header shows "Your email address has been updated" and there is no added entry:

![AddEntry](https://github.com/user-attachments/assets/a345545b-16f9-41fe-85c2-145969378612)

**Server Environment**
- PHP Version: 7.3.33
- MySQL Version: not sure
- Other Info: [if applicable. Apache, nginx, etc.]

**Local Environment**
 - OS: Windows 10 Pro
 - Browser: Microsoft Edge
 - Browser Version: V127.0.2651.74

**Additional Context**
The site is now open to the public for entries, hoping to resolve this as soon as possible.

**Comment by mdgann** [comment]
Hi - 

Any suggestions? I have a live competition and we can't make entries?

Is it possible to downgrade to a previous version (2.7.0.1) without affecting the current configuration?

**Comment by geoffhumphrey** [comment]
I've tried to replicate the issue but haven't been able to on any of my test installations running [this codebase](https://github.com/geoffhumphrey/brewcompetitiononlineentry/archive/refs/heads/master.zip). I would suggest replacing your entire codebase on the server with what's contained in the zip.

If the issue persists, it may be a session issue on the server.

**Comment by mdgann** [comment]
Hi Geoff - 

I did that and I am experiencing the same issue. 

If I give you access to the server is there anyway you can help troubleshoot this issue? I can compensate you for your time. 

I appreciate the help. If you have other ideas I can try please let me know.

**Comment by mdgann** [comment]
I changed hosting providers and was able to get the system operational. [https://commercial.beers4amadire.com]

There must be an issue with the old provider, I didn't have time to troubleshoot further, but clearly the V2.7.1 woks as expected. 

Thanks for the help on this. 

Mike
