### ISSUE TITLE
Version 2.6.2: Published results twice, now winners not showing and tables have zero entries received

### ISSUE THREAD

**Issue by Simon-Haynes** [geoffhumphrey/brewcompetitiononlineentry#1554]
**BEFORE Posting a Bug Report, Verify and Respond Yes or No to the Following**

Reporting About the Latest Version? No

*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes

*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes

*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**Your Intallation's BCOE&M Info**
- Version: 2.6.2
- Installation URL: https://pro-am24.nswhomebrewing.org/
- Hosted Installation? No

**Describe the Bug**

Not exactly sure how this happened, but once judging was finished and all scores entered, I brought the 'Preferences > Website > Winner Display Date/Time' forward to display the results immediately. This worked, but I realised that two of the placings needed to be changed. I pushed the 'Preferences > Website > Winner Display Date/Time' back to the future and changed the placings in the relevant tables. I then brought the date forward again to display the results immediately and the winners were not displayed? Returning to the tables I found that they now had zero entries received (see attached) although the correct number of entries scored. Clicking the trophy symbol to update the scores takes me to the table with no entries visible (see attached)

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Server Environment**
- PHP Version: 8.3.8
- MySQL Version: mysqlnd 8.3.8
- Other Info: [if applicable. Apache, nginx, etc.]

**Local Environment**
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: 127.0.6533.89
 - 
![ReceivedEntriesZero](https://github.com/user-attachments/assets/3c13c358-e4f1-4c8c-85a6-08c3d7cf7e90)
![TablesEmpty](https://github.com/user-attachments/assets/ef7bdf1d-adea-43cf-89fa-a93166f374c5)

**Additional Context**

**Comment by geoffhumphrey** [comment]
Confirmed - and apologies for the issue. There was legacy code still in place that should have been removed when ability to designate a custom style's sub-style number/letter was added. This only applies when updating preferences, as @Simon-Haynes experienced.
