### ISSUE TITLE
Is possible to change the entry number 

### ISSUE THREAD

**Issue by ACCNRes** [geoffhumphrey/brewcompetitiononlineentry#1558]
Version: 2.7.0

Installation URL: https://bjcp.accnr.eu/

Is your installation hosted? Yes shelf hosted

Description of Issue:
Is possible to change the entry number (Not the judging numbers). To keep a correlative order of entry?
![Captura de pantalla (171)](https://github.com/user-attachments/assets/06e7981f-59f1-4278-90be-de0cf048510f)

**Comment by geoffhumphrey** [comment]
There is not via the user interface. The Entry Numbers are generated automatically by the MySQL database. You can change the randomly generated Judging Numbers to be the same as the entry numbers via the Admin Actions dropdown - which it looks like you've discovered how to do. 

Entrants do not see the Judging Number - they only see the Entry Number. My advice would be to wait until you closed the entry window (once all entries have been input into the system) and then run the Regenerate Judging Numbers function. This will guarantee that all entry numbers and judging numbers are the same.

**Comment by ACCNRes** [comment]
Oh I see for the moment I will do as you say.
But for future versions i think it would be a good idea to be editable (Especially when you have to delete a entry).
I mean for Cellar Stewards is easier to have a correlative guidance I mean:
Participant 1 xxxx. zzzz. Is gonna send entries with entry number 1 and 2 
Participant 2 xxxx. zzzz. Is gonna send entries with entry number 3 and 4
But you have to delete entry 2. And you want rename the entries form participant number 2 to entries 2 and 3 after that deletion.

**Comment by r-squared** [comment]
> Participant 1 xxxx. zzzz. Is gonna send entries with entry number 1 and 2
> Participant 2 xxxx. zzzz. Is gonna send entries with entry number 3 and 4
> But you have to delete entry 2. And you want rename the entries form participant number 2 to entries 2 and 3 after that deletion

But what happens if participant 2 has already printed their labels and boxed everything up for shipping? Their labels say it's entries 3 and 4, but the system now has them as entries 2 and 3.

And often entry deletions are done by the participants themselves when they realize their brew won't actually be ready in time. You could have 150 entries registered and then get entry 5 deleted and you then want to renumber the other 145 entries?

**Comment by ACCNRes** [comment]
Yeah that makes a sense. 
👍
