### ISSUE TITLE
Version Aug 11 Master (f228310): Participant Able to Add Entries Before Registration Opens

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#1559]
**BEFORE Posting a Bug Report, Verify and Respond Yes or No to the Following**

Reporting About the Latest Version? Yes

*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes

*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes

*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**Your Intallation's BCOE&M Info**
- Version: Aug 11 Master (f228310)
- Installation URL: https://brewslam.gtabrews.ca/
- Hosted Installation? No

**Describe the Bug**

Even though entry registration is not opened yet, entrants have been able to add and pay for entries.

**To Reproduce**
Use Aug 11 Master (f228310)

**Expected Behavior**

Entrants should not be able to add or pay for entries yet

**Screenshots**

![image](https://github.com/user-attachments/assets/91bba9a5-46e8-4901-941e-25091d5844ba)

![image](https://github.com/user-attachments/assets/5a395b6f-0bb8-45e5-9e08-10b236ab13e3)

![image](https://github.com/user-attachments/assets/2cce1955-0869-40ed-91f3-cbf74999ab52)

![image](https://github.com/user-attachments/assets/1f67066c-1068-440e-8fd8-d100795b7cf4)

**Server Environment**
Environment Info:PHP Version – 7.3.33;MySQL Version – 8.0.36-28

**Local Environment**
 - OS: Windows
 - Browser: Chrome
 - Browser Version:

**Additional Context**

**Comment by geoffhumphrey** [comment]
That commit is 3 behind the latest one - I'd suggest updating [to the latest commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/archive/refs/heads/master.zip). I'm not able to replicate the issue with that codebase. 

Of course, I have to say that the commits are not ready for prime time and can't be guaranteed to work for any production installation.

**Comment by hirendu** [comment]
Hi Geoff - I see in above a functionality to increment entry limit on a specific date. How come we do not see that functionality on chc.brewingcompetitions.com?

**Comment by geoffhumphrey** [comment]
I did confirm that was possible if the user "backdoors" into the Add Entry screen by using a direct link URL. With the latest commit, this hole has been plugged.

**Comment by ercousin** [comment]
Thanks Geoff!

I installed the 2.7.1 release and the "Add Entry" buttons I was seeing in the user profiles before entry registration open are gone now, so I expect the issue is resolved :)
