### ISSUE TITLE
Version 2.X.X: Data exports not working (Firefox) Hosted site - chc.brewingcompetitions.com 

### ISSUE THREAD

**Issue by hirendu** [geoffhumphrey/brewcompetitiononlineentry#1560]
**BEFORE Posting a Bug Report, Verify and Respond Yes or No to the Following**

Reporting About the Latest Version? Yes 

*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes

*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes

*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**Your Intallation's BCOE&M Info**
- Version: 2.7.0 (e) 
- Installation URL: https://chc.brewingcompetitions.com/includes/output.inc.php?section=export-emails
- Hosted Installation? Yes

**Describe the Bug**

When we try to do data export  - nothing happens. 

clear and concise description of what the bug is.

**To Reproduce**
1. Go to https://chc.brewingcompetitions.com/includes/output.inc.php?section=export-emails

**Expected Behavior**

We expected the file to download. 

**Screenshots**

**Server Environment**
- PHP Version: Hosted
- MySQL Version: 
- Other Info: [if applicable. Apache, nginx, etc.]

**Local Environment**
 - OS:
 - Browser: 
 - Browser Version:

**Additional Context**

**Comment by geoffhumphrey** [comment]
I'll look into this but I suspect it had to do with the incorrect codebase that was deployed for your hosted installation. I'll attempt to grab the necessary data from a backup of the DB.

**Comment by hirendu** [comment]
Hi Geoff,

Super thanks! Note that last comp ended first week of November - so any 
DB backup after that (Say Nov. 10th, 2023) would be good enough.

Thanks again.

- Hirendu
