### ISSUE TITLE
Version 2.X.X: Participant information can not be saved unless a state from EACH of USA, Canada and Australia is selected

### ISSUE THREAD

**Issue by hirendu** [geoffhumphrey/brewcompetitiononlineentry#1561]
**BEFORE Posting a Bug Report, Verify and Respond Yes or No to the Following**

Reporting About the Latest Version? Yes or No

Yes (Hosted version) 

*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes or No

Yes

*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes or No

*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**Your Intallation's BCOE&M Info**
- Version: 2.7.0 (e)
- Installation URL: chc.brewingcompetitions.com 
- Hosted Installation? Yes 

**Describe the Bug**

Edit/Save of participant info is not allowed unless a state from THREE dropdown is selected. USA, Canada and Australia (?) 

**To Reproduce**

**Expected Behavior**

Only state from selected country (USA in this case) should be needed to be selected. 

**Screenshots**

**Server Environment**
- PHP Version:
- MySQL Version: 
- Other Info: [if applicable. Apache, nginx, etc.]

**Local Environment**
 - OS:
 - Browser: 
 - Browser Version:

**Additional Context**

**Comment by geoffhumphrey** [comment]
This has been fixed. It only affected this particular hosted installation - out of date files were being used. Once updated, things worked as expected.
