### ISSUE TITLE
Enhancement: Color combination on mobile is almost unreadable. 

### ISSUE THREAD

**Issue by hirendu** [geoffhumphrey/brewcompetitiononlineentry#1562]
See attached attempt at "Register" on a mobile phone. The color combination on the menu makes it almost impossible to read. 
![Screenshot_20240823-083534](https://github.com/user-attachments/assets/474fbf71-2aad-4277-9872-949c2e73b315)

**Comment by geoffhumphrey** [comment]
Thanks for reporting. I'll see what can be done about it to incorporate into the next release - in the meantime, I'd suggest changing your theme if this continues to be an issue.

**Comment by hirendu** [comment]
Thanks for the suggestion - interestingly, changing the local browser theme from Dark to Light or Vice versa made no difference on Firefox.

**Comment by r-squared** [comment]
It's the site theme under website preferences causing this, not browser theme.

**Comment by hirendu** [comment]
Got it - I changed it to Blue-Gray and the problem is gone! Thanks!!

**Comment by geoffhumphrey** [comment]
I'm inclined to deprecate that particular theme and the other green-dominated theme anyway in the next release. I haven't looked at either in a loooooong time -- I think it's been 8 years -- and there are some glaring accessibility/contrast related issues in both that I really can't believe haven't surfaced until today (which indicates to me that neither of them are used much). Plus, they're not very well designed and, well, dated. 

The grey and blue-grey themes will remain. 

Version 3.0 will feature a totally reworked, modern design of all non-Admin screens that will meet accessibility standards. Here's a few screenshots of the work-in-progress prototype. Please note that colors have not been finalized - those here are the default Bootstrap 5 ones.

![image](https://github.com/user-attachments/assets/38df5a3d-2738-4c5e-9eb2-f57a2514bb37)

![image](https://github.com/user-attachments/assets/56487821-d374-4cf8-add8-23861979c106)

![image](https://github.com/user-attachments/assets/7f46c615-ac47-4ea7-9971-ce9a476d4bb0)

![image](https://github.com/user-attachments/assets/78bf894b-77f8-49ea-b704-95f439ad6b71)

![image](https://github.com/user-attachments/assets/6e29c633-84a9-48a1-a96a-d5eef32d2d6c)

Once 2.7.1 is released, I'll turn my attention back to V3.
