### ISSUE TITLE
Version 2.7.0: Co-Brewer field empty on edit, after entering and saving Co-Brewer.

### ISSUE THREAD

**Issue by zomble** [geoffhumphrey/brewcompetitiononlineentry#1563]
Reporting About the Latest Version? Yes.

Searched Issue Reports for Bug? Yes. Found a recent enhancement related to Co-Brewer though.

Reviewed the Good To Know Issue Reports? Yes. None appeared to be relavant.

**Your Intallation's BCOE&M Info**

- Version: 2.7.0
- Installation URL: https://comp.qabc.org.au/ & https://comp.tunsofanarchy.com/
- Hosted Installation? Dunno.

Not my installations though, just doing entries and I noticed this.

A clear and concise description of what the bug is:

Co-Brewer is blank/empty when editing an entry where the Co-Brewer was set.

**To Reproduce**
1. Go to Add an Entry.
2. Fill out the entry as per normal, but set the Co-Brewer to any value, like someones name.
3. Submit the entry as per normal.
4. Edit the entry.
5. See that the Co-Brewer field is empty.

Alternatively:

1. Edit an entry, set the Co-Brewer.
2. Edit it again, see that the Co-Brewer field is empty.

**Expected Behavior**

The entries Co-Brewer is the value entered on creation or on previous editing.

Seems minor, unsure if the value is being saved or not, and if it's just not showing on edit. Cheers!

**Comment by geoffhumphrey** [comment]
Hi @zomble - thanks for reporting. Confirmed.

 I tracked the issue down to code that wasn't taking into account the you don't have a shipping deadline date specified in your competition info. I've fixed the issue on yours and all hosted installations. 

This only affected the display of the date, not enforcement of the entry edit deadline date you specified.

**Comment by geoffhumphrey** [comment]
Apologies. I commented on this issue incorrectly. I've deleted that comment.

**Comment by geoffhumphrey** [comment]
Hi @zomble - thanks for reporting. Confirmed.

The /includes/process/process_brewing.inc.php file was missing a line that processed the $_POST variable from the form. If you replace that file with [the one in the latest master commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/includes/process/process_brewing.inc.php) (the change is inserted at line 134), co-brewer input will be processed and stored.

**Comment by quimnut** [comment]
I host both of those :) shanks.

**Comment by zomble** [comment]
Cheers! Co-Brewer saved and is showing on edit!
