### ISSUE TITLE
Version 2.7.0(e): Entry Edit Deadline display not respecting competition date settings

### ISSUE THREAD

**Issue by insaneblaine** [geoffhumphrey/brewcompetitiononlineentry#1564]
**BEFORE Posting a Bug Report, Verify and Respond Yes or No to the Following**

Reporting About the Latest Version? Yes

*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes

*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes

*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**Your Intallation's BCOE&M Info**
- Version: 2.7.0 (e)
- Installation URL: https://motownmash.brewingcompetitions.com/
- Hosted Installation? Yes

**Describe the Bug**
On the account page of a competition entrant who has entries, the Entry Edit Deadline is incorrectly displaying as "Wednesday, December 31, 1969 7:00 PM, EST"

I have tried both setting this to an explicit date and leaving it blank in the competition settings. Neither have had an impact. See attached screen shots. 
<img width="900" alt="Screenshot 2024-08-28 at 12 23 04 PM" src="https://github.com/user-attachments/assets/188e4ec0-9fdc-46e6-a586-237f178cb4aa">
<img width="1035" alt="Screenshot 2024-08-28 at 12 17 33 PM" src="https://github.com/user-attachments/assets/4599032b-cdf6-45f7-8f4d-4ab87a2363a9">
<img width="1037" alt="Screenshot 2024-08-28 at 12 15 06 PM" src="https://github.com/user-attachments/assets/a7f633ea-2548-4bbb-879e-e29abbda929d">

**Comment by geoffhumphrey** [comment]
Hi @insaneblaine - thanks for reporting. Confirmed.

I tracked the issue down to code that wasn't taking into account the you don't have a shipping deadline date specified in your competition info. I've fixed the issue on all hosted installations. For anyone else, please specify a shipping deadline and a drop-off deadline in your and the display will be correct.

**PLEASE NOTE:** This only affected the display of the date, not enforcement of the entry edit deadline date you specified.
