### ISSUE TITLE
Version 2.7.0: Organizer Judge ID missing - in BJCP Section of XML file

### ISSUE THREAD

**Issue by hirendu** [geoffhumphrey/brewcompetitiononlineentry#1566]
BJCP Section of XML report - if missing judge ID - should flag to the comp organizer to fix before submitting to BJCP. I have noticed this a few times - this happens primarily for Comp Organizer. 

Attaching one of the comp report received where organizer Judge ID was missing (Didn't let me attach XML file - so just pasting part of the report with problem): 
.........
<BJCPpoints>
		<JudgeData>
			<JudgeName>David Little</JudgeName>
			<JudgeID></JudgeID>
			<JudgeRole>Organizer</JudgeRole>
			<JudgePts>0.0</JudgePts>
			<NonJudgePts>3.0</NonJudgePts>
		</JudgeData>
.......

**Comment by hirendu** [comment]
Hi Geoff - to add further to this. The Organizer reported is NOT a BJCP judge. So to some extent not having BJCP ID is OK but he should have been in non-BJCP section and not in BJCP section. So still something to look into. BTW - I have received other reports with similar issues from BCOE&M.

**Comment by geoffhumphrey** [comment]
OK - thanks @hirendu. I'll look into it!

**Comment by geoffhumphrey** [comment]
I put in some logic that determines whether an Organizer has a BJCP ID in the system. If so, their information is added to the `<BJCPpoints>` section of the XML output. If not, their information is added to the `<NonBJCP>` section. 

All hosted competitions have been updated with this change. Non-hosted installations should download the [/output/export.output.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/output/export.output.php) file and upload it to their webserver.
