### ISSUE TITLE
Version 2.7.1 - Upgrade results in - Unknown column 'prefsUserEntryLimitDates' in 'field list'

### ISSUE THREAD

**Issue by Beer-Ranger** [geoffhumphrey/brewcompetitiononlineentry#1567]
**BEFORE Posting a Bug Report, Verify and Respond Yes or No to the Following**

Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

**Your Intallation's BCOE&M Info**
- Version:  2.7.1
- Installation URL: https://hoppyhalloween.com/comp/
- Hosted Installation? No

Upgraded install to version 2.7.1 and when I go to the installation URL it just shows the following message:
Unknown column 'prefsUserEntryLimitDates' in 'field list'

**Expected Behavior**

Software opens and updates to v2.7.1

**Comment by geoffhumphrey** [comment]
I ran into this issue when testing when I neglected to replace the files in the /sites/ folder. I didn't want to overwrite my config.php and config.mail.php files, so I skipped the entire folder when uploading to the server. 

Make sure you replace all of the other files in the /sites/ folder and things should update as expected.

**Comment by geoffhumphrey** [comment]
Forgot to mention that you may need to do a force update. Change the FORCE_UPDATE variable in paths.php to TRUE. It's on line 110.

``` define('FORCE_UPDATE', TRUE); ```

Upload to your server and access index.php.

If that doesn't work, you may need to add the prefsUserEntryLimitDates row manually via phpMyAdmin or shell access. Run this command:

``` ALTER TABLE `preferences` ADD `prefsUserEntryLimitDates` MEDIUMTEXT NULL DEFAULT NULL AFTER `prefsUSCLExLimit`; ```

If you have a prefix for your DB tables, make sure to add it before "preferences."

**Comment by geoffhumphrey** [comment]
Also, change the FORCE_UPDATE back to FALSE after you run it once or it will run every time the browser is refreshed.

**Comment by Beer-Ranger** [comment]
Forcing the update fixed it for me and I did change it back to FALSE.

Thank you for the support.

**Comment by geoffhumphrey** [comment]
Awesome! Glad I could help.
