### ISSUE TITLE
Version 2.6.2: Entry Name Doesn't Support Special Characters (Ä, ö, ü, etc)

### ISSUE THREAD

**Issue by tmack8001** [geoffhumphrey/brewcompetitiononlineentry#1568]
**BEFORE Posting a Bug Report, Verify and Respond Yes or No to the Following**

Reporting About the Latest Version? No

*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes

*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes

*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**Your Installation's BCOE&M Info**
- Version: 2.6.2
- Installation URL: https://kotm.lmbrewers.beer/
- Hosted Installation? Unknown - this isn't my BCOE&M installation - just a competitor

**Describe the Bug**

Entries with a special character letter don't render as the special character but the escaped version of them. In this specific competition that means "Avg Br&uuml; Alt In All It's Just Another Bier In The Hall" was rendered for "Avg Brü; Alt In All It's Just Another Bier In The Hall".

**Expected Behavior**

With a entry name containing Ä, ö, ü or other similar extra accented letter the rendered results of those entries should also contain those letters - Clubs support these extra letters so should names of people and entries alike (and styles of course).

**Screenshots**
<img width="888" alt="image" src="https://github.com/user-attachments/assets/2c9dcdd3-cba2-4f18-9c15-f52266430b8d">

**Comment by geoffhumphrey** [comment]
Support for special characters for entry names is available in v2.7.0 or later.

![image](https://github.com/user-attachments/assets/a71f5f7a-fe73-41ef-9a1f-7cd81d587bf0)
