### ISSUE TITLE
Not all Winner entries Styles are displayed in Homepage!

### ISSUE THREAD

**Issue by afcdmc** [geoffhumphrey/brewcompetitiononlineentry#1569]
**BEFORE Posting a Bug Report, Verify and Respond Yes or No to the Following**

Reporting About the Latest Version? Yes or No

*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes or No

*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes or No

*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**Your Intallation's BCOE&M Info**
- Version:  2.7.1
- Installation URL:  https://homebrewerspr.brewingcompetitions.com
- Hosted Installation? Yes or No - Yes

**Describe the Bug**

Not all Winner Entries Styles are displayed in Homepage!  in the Tables and evaluation pages the scores are visible but not in the Homepage!!  When I create a report all the styles are in there!!

**To Reproduce**

**Expected Behavior**

View all the Styles in the competition displayed in the Home Page

**Screenshots**
![CleanShot 2024-09-08 at 13 28 36@2x](https://github.com/user-attachments/assets/4fbd8189-d9e1-4126-9bc9-7af13cfa68c0)
![CleanShot 2024-09-08 at 13 29 15@2x](https://github.com/user-attachments/assets/74043c69-a374-4d18-8b75-b17a3f904185)

**Server Environment**
- PHP Version:
- MySQL Version: 
- Other Info: [if applicable. Apache, nginx, etc.]

**Local Environment**
 - OS:
 - Browser: 
 - Browser Version:

**Additional Context**

**Comment by geoffhumphrey** [comment]
Confirmed. Bug affects BOS winner display of both "By Category" and "By Sub-Category" methods.

A fix is provided in the latest master commit and  will be available in the next release.
