### ISSUE TITLE
Version 2.7.1: Judges, Stewards (and Staff) able to register without picking any sessions

### ISSUE THREAD

**Issue by hirendu** [geoffhumphrey/brewcompetitiononlineentry#1571]
This could potentially be an enhancement. 

We had a number of participants sign up to "Judge" or "Steward" or "Staff" without picking any related sessions. 

This means we have to reach out to them individually to find out what sessions they are available for adding a lot of extra effort/time on the part of organizers. 

I would expect that if one volunteers to judge - there should be an error if they did not pick any judging session (same for others). 

Again - this could be an enhancement and not a bug; but from organizer's point of view, this is important.

**Comment by geoffhumphrey** [comment]
This will be a part of the next release.
