### ISSUE TITLE
Order of entries on Printed Pullsheets does not match Order of entries on Judging Dashboard Version 2.7.1(e): 

### ISSUE THREAD

**Issue by insaneblaine** [geoffhumphrey/brewcompetitiononlineentry#1577]
**BEFORE Posting a Bug Report, Verify and Respond Yes or No to the Following**

Reporting About the Latest Version? Yes

*If you are not running the most current version in your environment, please update prior to reporting your bug. Your issue may have already been addressed.*

Searched Issue Reports for Bug? Yes 

*Please search open *and* closed issues for issues similar to yours. Your bug may already have a posted solution.*

Reviewed the Good To Know Issue Reports? Yes

*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**Your Intallation's BCOE&M Info**
- Version: 2.7.1 (e)
- Installation URL: https://motownmash.brewingcompetitions.com/ 
- Hosted Installation? Yes

**Describe the Bug**

The order in which entries are displayed on printed competition pullsheets does not always match the order in which the entries display for judges in their judging dashboard. This creates confusion when the judges are working with Stewards off of printed pullsheets and the pullsheets do not match what the judges use to enter evaluations. We saw this lead to multiple cases where judges accidentally entered evaluations for the wrong entry.

**To Reproduce**
Print a pullsheet for a table and compare to the judging dashboard for the same table. See attached examples from the fruit beer table. 

**Expected Behavior**

 the entry order on the judge dashboard should always match exactly with the order on printed pullsheets
**Screenshots**

**Server Environment**
- PHP Version:
- MySQL Version: 
- Other Info: [if applicable. Apache, nginx, etc.]

**Local Environment**
 - OS:
 - Browser: 
 - Browser Version:

**Additional Context**

[Judging Dashboard.pdf](https://github.com/user-attachments/files/17300581/Judging.Dashboard.pdf)
[Fruit Beers.pdf](https://github.com/user-attachments/files/17300582/Fruit.Beers.pdf)

**Comment by geoffhumphrey** [comment]
Hi @insaneblaine - thanks for reporting. Confirmed. The two outputs mentioned here will be aligned in the next version. 

Judging Dashboard view:

![image](https://github.com/user-attachments/assets/aba839c7-5a7d-4677-967c-fdfc7c208b3e)

Pullsheet:

![image](https://github.com/user-attachments/assets/51916a93-80d9-4480-80d3-ce4d86539887)
