### ISSUE TITLE
Version 2.7.1 - Hosted - Judges can not register/signup/update sessions (URGENT) 

### ISSUE THREAD

**Issue by hirendu** [geoffhumphrey/brewcompetitiononlineentry#1578]
Emailed you separately as well. 

For https://chc.brewingcompetitions.com

If you sign in as a non-admin judge - only "Staff" option is available. So the judges are not able to signup (entry registration is closed because we reached entry count - but judge registration and selection of sessions etc. should be open till Nov 3rd). 

It works fine if one logs in as admin. So to recreate this - you should login as one of the other users. I reset password for one of the users (see attachment) - you can reset it again and log in as him to see the issue. This is URGENT because we are trying to get judges to sign up. 

PS - Actually decided to not attach PDF because it has some private information of the person (address etc).  Please email me for login/password to test this out.

**Comment by geoffhumphrey** [comment]
I cannot recreate this issue, unfortunately. In my attempt to do so I did NOT reset the user's password as you've suggested - I did not feel comfortable doing so. Instead, here's what I did:
- Created a new user as an admin (non-judge - you'll see it as G.H. Humphrey)
- Accessed the new user's account via another browser.
- On the Edit Account screen, I was able to sign up to be a judge. I did, but didn't indicate any availability.
- Logged out of the non-admin account.
- Via the Admin account on the other browser, I assigned the account as a judge via Admin > Entries and Participants > Assign Judges. 
- Logged back into the non-admin account with the other browser, selected Edit Account Info, and was able to indicate availability.
- Checked the Admin account and verified the availability change on the  Admin > Entries and Participants > Assign Judges   screen.

So, there's not a programmatic way to deal with this that I can see. I did note that the user in question was already assigned to the judge pool, hence why I went through the procedure above. 

At this time, my suggestion would be to "unassign" the user from the judge pool and then have them clear all cache/cookies or use another browser to log in and indicate their availability. Or, update their availability on your end as an admin.

**Comment by hirendu** [comment]
Thank Geoff - we figured out this was happening when judges are assigned to a table. Once a judge is assigned to even a single table - the judges are not able to edit their sessions or add availability for more judging sessions. Maybe only the judging sessions where the judge is assigned a table to should be locked and not the entire judging section?
