### ISSUE TITLE
Version 2.7.1: URGENT - Can't import Reports to BJCP IT - Potential Syntax error

### ISSUE THREAD

**Issue by hirendu** [geoffhumphrey/brewcompetitiononlineentry#1579]
NonBJCP judges are not being imported from 2.7.1. This was working fine till 2.7.0. 

I tried to debug this but can't figure out exact location of issue. I am going to hold processing of 2.7.1 reports till we know what is going on. I can email you the report which works and which does not work but not posting it here for privacy reasons.  

Edit: Found the issue </ NonBJCP > is missing from file since some time.

**Comment by hirendu** [comment]
Found the same issue in one of 2.7.0 comps - "Aotearoa Home Brewing Classic"

**Comment by hirendu** [comment]
Another comp from 2.7.0 - "Vicbrew 2024" has same issue. https://comps.vicbrew.org/

**Comment by hirendu** [comment]
Found the issue - </NonBJCP> is missing..

**Comment by geoffhumphrey** [comment]
This is fixed in the latest commit and will be available in the next version. All hosted sites have been updated with the fix.

Interesting - it seems that that particular end tag was always missing. I'm assuming the XML parser you're using now is now a bit more strict.
