### ISSUE TITLE
Pullsheets only printing one page

### ISSUE THREAD

**Issue by GoogleCodeExporter** [geoffhumphrey/brewcompetitiononlineentry#307]
```
What steps will reproduce the problem?
1. Print the pullsheet for a larger flight (in this case, 50 entries - it's a 
single-style competition)


What is the expected output? What do you see instead?
I expect to get as many pages as necessary. Instead, only page 1 prints (and 
the last entry is cutoff at the bottom, as if BCOEMS things that a single page 
is tall enough to print the entire list)

What version of the product are you using? On what operating system?
BCOE&M 1.3.0.2
Firefox 23.0.1
Max OS X 10.8.4
```

Original issue reported on code.google.com by `br...@brewdrinkrepeat.com` on 22 Sep 2013 at 2:24

**Comment by geoffhumphrey** [comment]
A solution to this has not been easy to find. All tests with automatic printing via Firefox have not been optimal from an output point of view - the resulting pages have aesthetic issues or simply do not work. For the next release, an alert will be placed in the Admin area detailing a work-around for Firefox users. As stated previously, tests in Chrome and IE work as expected.
