### ISSUE TITLE
Automatic registration confirmation email

### ISSUE THREAD

**Issue by GoogleCodeExporter** [geoffhumphrey/brewcompetitiononlineentry#378]
```
It would be nice to have an option to automatically send an email to entrants 
as soon as tehy register. That way they have something in their posession to 
remember whay email address they used to register. Also it is good to give some 
extra feedback.




```

Original issue reported on code.google.com by `cpa...@gmail.com` on 14 Feb 2014 at 5:03

**Comment by geoffhumphrey** [comment]
There will need to be some sort of check to see if sendmail is enabled from environment to environment. A simple "test email function" that generates and sends an email to the admin currently logged into the site can be implemented easily and just-in-time on the website preferences page.
