### ISSUE TITLE
Enter scored by table - sometime doesn't follow pullsheet

### ISSUE THREAD

**Issue by GoogleCodeExporter** [geoffhumphrey/brewcompetitiononlineentry#413]
```
On a few tables today, the enter scores screen is not in the same order as the 
pullsheet (making it more time-consuming to enter the scores). They are not in 
any order we can determine (i.e. not numerical by entry# oe judging#), but they 
don't match the pullsheet either.

```

Original issue reported on code.google.com by `br...@brewdrinkrepeat.com` on 17 May 2014 at 4:24

**Comment by geoffhumphrey** [comment]
The sort order will be the same for both pull sheets and on screen scoring data entry in the next version, 1.3.1.0.

**Comment by markalston** [comment]
Not fixed. Still broken for 1.3.1 if you print pull sheets using entry id instead of judging number.  Looks like the sort is forced to be style then brewJudgingNumber on the score entry page even when our pull sheets are sorted by style then entry id.   

Also pullsheets with special ingredients are sorted by style then special ingredient notes then entry number. 

Using latest version as of 8/8/2015

**Comment by markalston** [comment]
Line 230 in judging_scores.admin.php forces the sorting to be by style and then brewJudgingNumber.  This is a problem for us using entry id instead of brew judging number.  I changed the line to:
 
"aaSorting": [[2,'asc'],[0,'asc']],

**Comment by markalston** [comment]
The problem with the special ingredients sorting comes via the javascript dataTables aaSorting on the column with the style/substyle stuff.  The javascript code is sorting on that whole column which is including the special ingredients/classic style info (pullsheets.php). 

It looks like the best solution would be to set aaSorting to an empty array

 "aaSorting": []

as per https://stackoverflow.com/questions/4964388/is-there-a-way-to-disable-initial-sorting-for-jquery-datatables to disable the initial javascript sort and then use the database query in output_pullsheets_entries.db.php to do the actual sorting properly.
