### ISSUE TITLE
2015 - 2008 style mix up in some display tables

### ISSUE THREAD

**Issue by j031** [geoffhumphrey/brewcompetitiononlineentry#461]
These two test entries were added as 2015 style name from dropdown but then displayed on the admin entry form as 2008 style name.

How admin add entry looked for test 1:
![image](https://cloud.githubusercontent.com/assets/9260986/8094498/1dbe4cfe-0f8d-11e5-9d6e-01c7c8717b3a.png)

How admin view Entry looked for test 1 and 2:
![image](https://cloud.githubusercontent.com/assets/9260986/8107075/3a93d55e-100c-11e5-9821-153bc8f18896.png)

Test 1 should should show czech lager
Test 2 should show kolsch

instead they are showing the 2008 names.

**Comment by j031** [comment]
As a follow up, it appears that the 2008 styles are hard coded in the files style_convert.inc.php and in the functions.inc.php style_convert Function.  Now that there are two styles it seems like these need to be pulled from the database instead of hard coded.  

I'm trying to change but it is difficult for me to understand all of the cases in the functions.inc.php style_convert function.  German Fest Stein Challenge is going live on Friday and we are using the 2015 styles.

**Comment by j031** [comment]
Additional update, I've found queries to the style table that don't include the style year but look up based on category.  If category appears in both 2008 and 2015 then the 2008 is printed.

In process_brewing.inc.php I've changed a couple of lines that look like:
$query_style_name = "SELECT * FROM $styles_db_table WHERE brewStyleGroup='$styleFix' AND brewStyleNum='$style[1]'";

To include the style year like this:
$query_style_name = "SELECT * FROM $styles_db_table WHERE brewStyleGroup='$styleFix' AND brewStyleNum='$style[1]' AND brewStyleVersion='$_SESSION['prefsStyleSet']'";

I've not had a chance to search through the code to see if this occurs anywhere else.

**Comment by geoffhumphrey** [comment]
Joel,

Those two particular files are not used anymore in the codebase. I will
remove them to make sure that there's no confusion.

   - functions.inc.php has been replaced with common.lib.php
   - style_convert.inc.php code is obsolete and was integrated into the
   common.lib.php a few releases ago

Thanks,

Geoff



Geoff

===============================

Geoff Humphrey
Sr. Instructional Designer, DIRECTV
LinkedIn Profile: http://goo.gl/FPEZk0
Website: http://www.zkdigital.com
Portfolio: http://goo.gl/ls4pTe

*No animals were hurt in the sending of this email. Just a few minorly
inconvenienced electrons.*

**Comment by j031** [comment]
Thanks,  Did you see that I submitted a fix via git hub about another file that added filters to the queries for the entries page so that the site correctly queried by 2008 or 2015 styles?
