### ISSUE TITLE
Navigation Links don't work in 1.3.1.0

### ISSUE THREAD

**Issue by schmidtkvn** [geoffhumphrey/brewcompetitiononlineentry#463]
This is a brand new installation of the beta build.
For example when I click on 'Rules' at the top of the page I am navigated to /rules, which isn't valid. I am able to manually navigate to /index.php?section=rules 

Similar issues with other links including Entry Info, Volunteer Info, Contact, and "Info and List of Entries".

**Comment by geoffhumphrey** [comment]
This has to do with the "search engine friendly" option available via Admin > Preferences > Site Preferences. The default value is "No," however, it appears as though your installation has it as "Yes," but your server isn't set up to process search engine friendly url rules via .htaccess. To remedy, navigate to /index.php?section=login, log in as an top-level admin, and update your preferences.
