### ISSUE TITLE
Error with setting BOS places

### ISSUE THREAD

**Issue by j031** [geoffhumphrey/brewcompetitiononlineentry#468]
The site gets an error when trying to set BOS places.

I clicked on Enter/Edit BOS Entries and Places - Beer.  Then the site comes up saying it can't find the table name.  

I think it is similar to issue #465 but this time it appears to be missing an include or the include is displaying an invalid table name.

I just entered BOS through the database as a work arround.

**Comment by markalston** [comment]
Same bug as 471. I put the fix into the comments for that bug.
