### ISSUE TITLE
Unable to enter BOS places.

### ISSUE THREAD

**Issue by j031** [geoffhumphrey/brewcompetitiononlineentry#471]
We get a sql table error when trying to set BOS places.  You can see the url and error below.  Looks similar to the pull sheets printing issue.

url: index.php?section=admin&go=judging_scores_bos&action=enter&filter=1

Table 'brewing_' doesn't exist

**Comment by markalston** [comment]
We get the same error here.  The bug is in lib/admin.lib.php.

if you change the line in function bos_entry_info from:

        if ($filter == "default") $filter = ""; else $filter = "_".$filter;

to:

        if ($filter == "" || $filter == "default") $filter = ""; else $filter = "_".$filter;

it works.

Not sure where $filter is set though and when/if it is ever set to default.  However, this fixes it for us.

**Comment by markalston** [comment]
Actually, looks like the true bug is on line 211 of judging_scores_bos.admin.php.
the call to bos_entry_info():

            $bos_entry_info = bos_entry_info($row_enter_bos['eid'], "default");

seems to be missing the value for filter.

Changing that line to:
 
           $bos_entry_info = bos_entry_info($row_enter_bos['eid'], "default", "default");

fixes the bug as well and is probably the proper fix.
