### ISSUE TITLE
entry registration window start date restriction and inconsistency

### ISSUE THREAD

**Issue by rivesborland** [geoffhumphrey/brewcompetitiononlineentry#472]
I noticed what I think is both a restriction and inconsistency in the software that I am not crazy about.

There are the following deadlines that you specify under the "competition info" setup
Entry and Registration
1) Entry Window Open Date: Required The date/time that entrants will be able to add entries to the system. Also the date that drop-off and mail-in locations will begin receiving entries.
2) Entry Window Close Date: Required The final date/time entrants will be able to add entries to the system. Also the date that drop-off and mail-in locations will stop receiving entries.
3) General Registration Open Date: Required The date/time the system will automatically open registrations. Make this date prior to the entry window date for pre-registration purposes.
4) General Registration Close Date: Required The date/time the system will automatically close registrations.
5) Judge/Steward Registration Open Date: Required The date/time the system will automatically open judge/steward registrations. This date can be prior to both the entry window open and registration open dates.
6) Judge/Steward Registration Close Date: Required The date/time the system will automatically close judge/steward registrations. This date can be after to both the entry window close and registration close dates.

So for the number 1 date it is both the date the site will let entrants start imputing entries and the date it lists as when they can start dropping them off. But what if you want to let them start registering entries online before the drop-off locations will physically accept entries?

Also, this date appears to be not even used consistently, depending on whether you look under the "home" page or the "entry info" page. For example, right now I have entry window set to 8/28 and general registration set to 8/5. Well, on the home page it states "
Entries

Participants will be able to add their entry data via this website and entries will be accepted at drop-off and shipping locations between Friday, August 28, 2015 at 12:00 PM, PDT and Saturday, September 12, 2015 at 12:00 PM, PDT."

but under the "entry info" page it states"
Registration Window

You will be able to register your entries beginning Wednesday, August 5, 2015 at 12:00 PM, PDT through Thursday, September 24, 2015 at 11:59 PM, PDT."

so there seems to be an inconsistency in when they say you will be able to register the entries online. It appears to be the entry window date (number 1) that actually controls when you actually have the option to input entries. Have others experienced the same issue and how should I deal with it?

**Comment by geoffhumphrey** [comment]
Clarity in nomenclature has been added to public pages you mention. Also, registered users are able to add entries into the system now after the registration window has closed.
