### ISSUE TITLE
Beers dropping off

### ISSUE THREAD

**Issue by robertetheredge** [geoffhumphrey/brewcompetitiononlineentry#475]
We have had many reports of beer entries disappearing.  It happened to me also.  I entered 3 beers, checked back in a few days and only one of my beers was listed.  This is a SERIOUS problem. How do we resolve this?

**Comment by geoffhumphrey** [comment]
If you upgrade to 1.3.1.0, this bug has been fixed. Additionally, there is an option in Preferences to "turn off" automatic purging of entries. Admin > Defining Preferences > Site Preferences - choose "No" to Automatically Purge Unconfirmed Entries.

**Comment by robertetheredge** [comment]
Thanks for your email.

Can we upgrade with out harming our existing data?
We are in the middle of a competition.

**Comment by geoffhumphrey** [comment]
Yes, you can update without impact to existing data. The major changes happen in the styles DB table as well as a couple of additions to the Site Preferences table. Be sure to download the release today, as there were issues previously (that are now fixed) with custom styles.
