### ISSUE TITLE
25B Saison should require strength and color - 2015 guidelines

### ISSUE THREAD

**Issue by whenyeastattack** [geoffhumphrey/brewcompetitiononlineentry#476]
We're using 1.3.1.0.  According to the new guidlines for 25B. Saison: "The entrant must specify the strength (table, standard, super) and the color (pale, dark)."

Those entering saisons in our competition have pointed out that it does not ask them to enter this information.  25B should have a ♦ next to it, as well as another field for entering color.  ♠ could probably be used here for the user to enter their color.

**Comment by geoffhumphrey** [comment]
Noted. Thank you for the information. A fix will be in the next bug fix release. In the mean time, you can force the program to require special ingredients/more information by opening phpMyAdmin or shell access and running the following MySQL command (make sure your DB name and the styles DB table name match up to your environment):

UPDATE  `YOURDBNAME`.`styles` SET  `brewStyleReqSpec` =  '1' WHERE  `id` =178;

**Comment by whenyeastattack** [comment]
Thanks!  Will do.
