### ISSUE TITLE
Style can no longer be edited after an entry is submitted

### ISSUE THREAD

**Issue by yeastnerd** [geoffhumphrey/brewcompetitiononlineentry#477]
We just upgraded to the final version of 1.3.1.0 from the previous beta. Prior to the upgrade, participants were able to edit a previously submitted entry and modify its style. After completing the upgrade, the same "Edit an Entry" page does not allow entry style to be modified after it has been created. The only entry in the brewStyle selection box is the originally submitted style.

I attempted a clean install of the official 1.3.1.0 release starting from an empty database and encountered  the same behavior: after submitting an entry, its style cannot be modified.

**Comment by geoffhumphrey** [comment]
There appears to be a piece of code in the /includes/db/styles.db.php file that is causing this behavior. If you comment out or remove lines 13 through 16 it will take care of the problem. Those lines read:

`if ($view != "default") {
		$explodies = explode("-",$view);
		$query_styles .= sprintf(" AND brewStyleGroup='%s' AND brewStyleNum='%s'",$explodies[0],$explodies[1]);
	}
`
I'll investigate further if removing this code has any other ramifications and post here if so.

**Comment by yeastnerd** [comment]
That seemed to work. Commenting out the lines you indicated allows me to edit the style of a previously submitted entry.

Thanks!

**Comment by geoffhumphrey** [comment]
The latest commit has code that fixes this issue.

**Comment by yeastnerd** [comment]
Awesome. Thanks!
