### ISSUE TITLE
no optional special ingredients box

### ISSUE THREAD

**Issue by rivesborland** [geoffhumphrey/brewcompetitiononlineentry#478]
The ability should exist to have and optional special ingredients box for entries in styles such as Pyment, where listing the honey and grape variety is optional. Per the 2015 guidelines:
"Entrants MUST specify carbonation level, strength, and sweetness. Entrants MAY specify honey varieties. Entrants MAY specify the varieties of grape used; if specified, a varietal character will be expected."
currently if you do not check the "Spec. Ing. Req?" column under the categories accepted setup page, there will no box at all, not even an optional one. It is currently only possibly to set it for no box, or mandatory, but not optional. I'd like to give entrants the ability to specify grape variety, but not require it.

**Comment by geoffhumphrey** [comment]
The latest code commit features changes to the code that will display the Brewer's Specifics field that can be used to enter optional specifics about an entry (e.g., hop variety used, honey variety, etc.). It is NOT a required field and warning nomenclature has been added to make sure that entrants know that anything they specify will be considered by judges.
