### ISSUE TITLE
QR Codes - Enhancement request?

### ISSUE THREAD

**Issue by XeonNAS** [geoffhumphrey/brewcompetitiononlineentry#479]
More of an enhancement request than an issue, but could QR codes be an alternative to bar codes, several advantages of QR codes in that it can contain a lot more data. Configuration of the QR code generation should allow an administrator to determine what information gets included in the QR code, with say the minimum being entry id.

There should be an option the use the QR code to print instead of a bottle label, entrants then just affix the QR code to their bottle and organisers/stewards simply use a smart phone to scan entries.

Cheers

John

**Comment by geoffhumphrey** [comment]
This will be incorporated into the next version, 2.1.0. Here's the scenario to utilize:
- Admins will set a unique QR Code Log On password for their installation via the Competition Preparation > Competition Info screen...

![screen shot 2016-03-10 at 9 15 24 am](https://cloud.githubusercontent.com/assets/5216502/13675851/afcadbc2-e6a0-11e5-8e2c-ff7bcb3bee82.png)
- All barcode-enabled bottle labels will also feature a QR code as well...
![screen shot 2016-03-10 at 9 11 21 am](https://cloud.githubusercontent.com/assets/5216502/13675959/1619d40a-e6a1-11e5-8430-37f72976cb7d.png)
- On sorting day, staff with mobile devices, using a barcode app, scan a bottle label's QR code. This launch to a special login page upon the first scan...
![2016-03-10 09 20 14](https://cloud.githubusercontent.com/assets/5216502/13676089/9b355ce0-e6a1-11e5-849b-30f4c7dd76b7.png)
- After log in and on each subsequent scan, the entries are checked in to the software...
![2016-03-10 09 21 03](https://cloud.githubusercontent.com/assets/5216502/13676129/c373cd72-e6a1-11e5-806e-b6844388d827.png)
