### ISSUE TITLE
Entries being lost even with Auto Purge set to No

### ISSUE THREAD

**Issue by beerinfinity** [geoffhumphrey/brewcompetitiononlineentry#481]
We are running V1.3.1.0 on http://www.statecollegehomebrewclub.com/phoc and have 'Automatically Purge Unconfirmed Entries' set to "No" yet we are still encountering Entries being purged from the system. Any ideas what is causing this and how to resolve please?

**Comment by beerinfinity** [comment]
Just to add that we are using the BJCP 2015 settings rather than 2008.

**Comment by geoffhumphrey** [comment]
Investigating. For now, keep the purge functions turned off and also comment out lines 66, 69, and 72 of the /sites/bootstrap.php file.

**Comment by beerinfinity** [comment]
Geoff

We have not had any more occurrences so wonder if a purge was still scheduled then ran after the setting was changed but did not affect subsequent entries?

Best wishes,
Phil
