### ISSUE TITLE
Judge Registration Screen Showing Times in Wrong Time Zone

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#482]
For some reason the judging times have started showing in MDT, but only on the judge registration screen. Is this a bug, or is there a setting buried somewhere that can cause this?

Judging times showing as MDT
![image](https://cloud.githubusercontent.com/assets/1551339/9825746/723f6fe2-58a3-11e5-925c-44aef48d58d4.png)

Home page showing proper judging times in EDT
![image](https://cloud.githubusercontent.com/assets/1551339/9825765/9fb1c588-58a3-11e5-8a45-2589f1e03839.png)

**Comment by geoffhumphrey** [comment]
Unfortunately, I cannot replicate this issue in my test environment. I'll investigate, but it could be a local server setting.

**Comment by ercousin** [comment]
We're you able to replicate it?

Or was it just closed because you couldn't replicate?

**Comment by geoffhumphrey** [comment]
I couldn't replicate it; apologies
