### ISSUE TITLE
Reset Password Fails

### ISSUE THREAD

**Issue by vortexofhate** [geoffhumphrey/brewcompetitiononlineentry#487]
When a user attempts to reset their password, they get the error "There is no email address in the system that matches the one you entered."  There is of course an email address for that one.

I was originally on 1.3.10 BETA and upgraded to the final release.  This happens on new users that create an account on the FINAL and existing users from the BETA.

**Comment by geoffhumphrey** [comment]
Verified. Will be fixed in next commit and release.
