### ISSUE TITLE
Wrong Judging Number Showing Up

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#489]
Hi.

I am seeing the wrong judging number being assigned to certain entries. For example I am seeing 23-001 being assigned to a 21B, 23-004 to a 10A, 23-006 to a 22B, and several other errors. I have attached a picture.

![bcoe m wrong judging number](https://cloud.githubusercontent.com/assets/1551339/9884750/7dab2e66-5baf-11e5-9c7b-9ece7134ba66.png)

**Comment by geoffhumphrey** [comment]
Unfortunately, I cannot replicate this issue (it's one that's been a pain for a while in the field, but the coding tests OK). 

This issue can easily be resolved by regenerating all judging numbers prior to sorting. Admin Dashboard > Sorting Received Entries > Regenerate > Entry Judging Numbers.

**Comment by ercousin** [comment]
Perhaps add instructions about regenerating judging numbers to the help? I searched for almost an hour for help before submitting this ticket.
