### ISSUE TITLE
judge and steward availability no longer displaying in edit participant info page

### ISSUE THREAD

**Issue by rivesborland** [geoffhumphrey/brewcompetitiononlineentry#490]
I used to have the ability to edit the judge and steward availability in the participant info page and flag them as available for particular locations a few days ago, as shown at the bottom of the first image below (taken from the site help, but looked the same for me). Now when I go to edit a participant's info or add a new participant those radio buttons and pull down menus to not appear at all, as shown in the second image. I did not change any settings. The only thing that changed was that we had the first prelim round of judging and that date passed. I was able to assign judges for the first prelim fine, but now I can't assign any judges at all so it is really messing up progress on the competition since we need to make more assignments before this weekend. Help!
![judge_avail](https://cloud.githubusercontent.com/assets/13674364/9942786/dcb2aeec-5d31-11e5-90e3-02920e63ca76.png)
![current_edit_info](https://cloud.githubusercontent.com/assets/13674364/9942787/ddbf6d98-5d31-11e5-9dae-ffa8f1221686.png)

**Comment by BrewGyver** [comment]
I've got the exact same issue. It's making reassigning judges a huge pain. The only workaround I've found is deleting the Judge and then signing up again with a new password (that I know). Then I can log in and change the availability.

**Comment by rivesborland** [comment]
Yeah it was very annoying. We loaded the very latest version of the code
(had same version number but diff showed there were changes) and that
seemed to fix the issue for us.

**Comment by BrewGyver** [comment]
Ah. Good. I was wondering if that would fix it. Might give it a try after a
backup.

**Comment by SaltCityBrew** [comment]
I'm having this exact same issue. We loaded the latest version of 1.3.2 and we still have this issue. I can't assign judges to any tables because they all show "no defined availability" and in their info page there is no way to select available locations. We only have 1 location and 1 time so you would think it would default...Judging starts in the morning and I guess I'll just have to assign everything by hand.

**Comment by geoffhumphrey** [comment]
There will be a fix in place for 2.1.0 that, if there's only one judging location, will automatically assign judges and stewards to that location. Additionally, there will be more robust checking of judge/steward assigned locations if 1) a location is changed, and 2) if a location is deleted. Admins will be alerted if these kind of changes happen.

**Comment by SaltCityBrew** [comment]
I found a temporary fix by adding a second location, which then populated the user info page with the option to select which one. However, after the initial work around, I'm not back to square one. I had a few judges to add last minute, but even adding a 3rd or 4th location wasn't giving the same results. I now don't have any way to assign judges to the tables they judged, which means I don't have a way to get the judges the points that they earned.
