### ISSUE TITLE
Custom Style assigned number 1A

### ISSUE THREAD

**Issue by schmidtkvn** [geoffhumphrey/brewcompetitiononlineentry#491]
I defined a custom style for my competition and was surprised to see it assigned category 01A. Then When I went to assign it to a table it shows up as "1A American Light Lager" rather than my custom category name.

**Comment by tehchriso** [comment]
For what it's worth, our competition uses 30A and 31A for our custom category numbers in order to prevent any confusion (whether on the part of the software or the humans).

**Comment by schmidtkvn** [comment]
In the 2015 style guidelines 30A is 'Spice, Herb, or Vegetable Beer', 31A is 'Alternative Grain Beer'. I had both in my recent competition. 
I have included a screenshot showing my custom 'Pancake Stout' category being listed at 1A.
![screenshot from 2015-09-23 09 28 38](https://cloud.githubusercontent.com/assets/13227820/10051258/80093136-61d5-11e5-8c2a-3fe6ebbe4a27.png)

**Comment by tehchriso** [comment]
Whoops, I didn't even think about 2015 guidelines, we are still using 2008 this year.

In that case, next year we will plan to skip forward to using 50, 51, 52, etc. - or you could even use 99, 98, 97 instead.

As to why it does what it does, I will leave that to the professionals. As you can see from the issues I have posted, I am far from fully understanding the inner workings of this software.
