### ISSUE TITLE
Verb missing in "Entries" section

### ISSUE THREAD

**Issue by dogunter** [geoffhumphrey/brewcompetitiononlineentry#492]
The main page displays the start of a paragraph under the "Entries" section that is missing a verb.  Here is how it appears now

"You will be able to your entries into the system..."

while is should probably read

"You will be able to add your entries into the system..."

The fix is to add the verb to line 93 of the file sections/reg_open_sec.php

**Comment by geoffhumphrey** [comment]
This has been fixed with the latest commit and will be included in the next release. Thanks for reporting!

**Comment by XeonNAS** [comment]
Thanks for posting where the fix goes, was just searching for it!
