### ISSUE TITLE
No styles available to assign to tables upon 2nd year of competition

### ISSUE THREAD

**Issue by tehchriso** [geoffhumphrey/brewcompetitiononlineentry#495]
Describe the problem?

This is our second year running a competition, and in June, before registration opened, we used the Archive feature to make a backup of the 2014 data and clear the tables before we began registering 2015 entries. 

Now, in September, entry registration is closed, and we are ready to set up tables and styles. Upon visiting Administration -> Tables, it reports that "All style categories with entries have been assigned to tables." Therefore I can create tables, but cannot assign any categories to them

What is the expected output? What do you see instead?

Expected result is to create new tables, and click the checkbox to assign styles to them. Instead, we see "No data" as shown below.
![image](https://cloud.githubusercontent.com/assets/14573859/9994005/b72ac27e-6040-11e5-8e31-5d7ddc2f5fe6.png)

What version of the product are you using?

ver. 1.3.0.4

Please provide any additional information below.

I also had an issue where random participants were pre-assigned as stewards - presumably this was due to matching up the 2014 user_id number to a 2015 participant. In that case, I was able to go into phpMyAdmin, find the table, and manually edit each assigned steward to '0', at which point I was able to use the regular BCOE&M interface to assign new stewards.

However in this case it is not immediately apparent to me how, or where in the database, the categories are assigned to tables -- and I am hesitant to start manually editing the 2014 data to see if it fixes the new issue... in the hope that I can still preserve that data!

**Comment by geoffhumphrey** [comment]
If you upgrade your installation to the latest version, by downloading and installing the latest commit here from GitHub (click the Download Zip button on the right) this should not be an issue.
