### ISSUE TITLE
Export All non-paid entries email addresses produces blank CSV

### ISSUE THREAD

**Issue by whenyeastattack** [geoffhumphrey/brewcompetitiononlineentry#497]
Our competition has 231 paid, 69 unpaid entries.  When I use Admin -> Exporting -> Email Addresses (CSV Files) -> All Non-Paid Entries, I get a CSV file that looks like this:

"First Name","Last Name",Email,Category,"Sub Category","Entry Number","Judging Number","Brew Name","Special Ingredients",Sweetness,Carb,Strength
,,,,0000,,,,,

Exporting all paid entries produces a valid CSV file, as does Admin -> Exporting -> CSV Files -> All Non-Paid Entries.

**Comment by geoffhumphrey** [comment]
This has been fixed with the latest commit and will be included in the next release. Thanks for reporting!
