### ISSUE TITLE
$_SERVER['QUERY_STRING'] used dangerously

### ISSUE THREAD

**Issue by scoates** [geoffhumphrey/brewcompetitiononlineentry#499]
All [instances of `$_SERVER['QUERY_STRING']`](https://github.com/geoffhumphrey/brewcompetitiononlineentry/search?utf8=%E2%9C%93&q=%24_SERVER[%27QUERY_STRING%27]) in [participants.admin.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/admin/participants.admin.php) and [entries.admin.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/admin/entries.admin.php) are used dangerously.

(they need to be escaped on output; `QUERY_STRING` is user-supplied)

**Comment by graemecoates** [comment]
Reflective XSS. Nice :(

**Comment by geoffhumphrey** [comment]
This has been fixed with the latest commit and will be included in the next release. Thanks for reporting!
