### ISSUE TITLE
Hops Use and IBU swapped on insert

### ISSUE THREAD

**Issue by beer-dev** [geoffhumphrey/brewcompetitiononlineentry#500]
When entering a new brewing entry, the values for hops "Use" and "IBU" are swapped during the insert.  Editing the entry brings up the Use value in the IBU entry and with no Use selection. 

This appears to be due to the order of the column names and values being inconsistent in the insert statement in includes/process/process_brewing.inc.php.  On lines 180-181, Use precedes IBU:

> `                                $brewHopsUse,`
> `                                $brewHopsIBU,`

while on lines 284-285, IBU precedes Use:

> `			for($i=1; $i<=20; $i++) { $insertSQL .= GetSQLValueString($_POST['brewHops'.$i.'IBU'],"text").","; }`
> `					for($i=1; $i<=20; $i++) { $insertSQL .= GetSQLValueString($_POST['brewHops'.$i.'Use'],"text").","; }`

This creates an insert statement similar to the following: 
`INSERT INTO table ( ..., brewHopsUse1, brewHopsUse2, ..., brewHopsIBU1, brewHopsIBU2, ... ) VALUES ( ..., brewHopsIBU1, brewHopsIBU2, ..., brewHopsUse1, brewHopsUse2, ...)`

Once inserted, displaying the brewing entry either by editing the entry or by printing the entry shows the values swapped.  Once corrected via the Edit page, the values are displayed correctly, which seems ito indicate the issue is with the insert statement and not the update or display of the values.

This was experienced in a deployed application based on version 1.3.1.0.

The solution would appear to be as easy as making sure the order of the brewHopsUse and brewHopsIBU values are consistent throughout the file.

**Comment by geoffhumphrey** [comment]
This has been fixed with the latest commit and will be included in the next release. Thanks for reporting!
