### ISSUE TITLE
Stewarding Availability Not Showing on My Info page.

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#501]
Stewarding availability indicated in the profile sign up isn't showing up in the Profile page.

![stewardingavailability](https://cloud.githubusercontent.com/assets/1551339/10239916/0ce34dac-68a3-11e5-8867-c059c1305557.png)

![missingstewardingavailability](https://cloud.githubusercontent.com/assets/1551339/10239918/0fe576f6-68a3-11e5-8f60-f2a8b9241c0e.png)

**Comment by geoffhumphrey** [comment]
Sorry, another one that I cannot replicate. If you download the latest commit, that's the codebase I'm using for testing.
