### ISSUE TITLE
Mead / Cider judging #'s

### ISSUE THREAD

**Issue by PeterSteinberg** [geoffhumphrey/brewcompetitiononlineentry#508]
Mead's and Ciders seem to get assigned judging numbers 38xxx, 39xxx, ..., 43xxx instead of M1xxx, M2xxx, M3xcxx, M4xxx, C1xxx, C2xxx.

I would like at least the option of having these categories judging numbers reflect their BJCP category code.

**Comment by geoffhumphrey** [comment]
Unfortunately, having the alphanumeric numbering system messed with back end functions relating to judging numbers. Judging numbers for meads and ciders are still unique, but the alphanumeric system the BJCP implemented in 2015's guidelines really threw a wrench into the way judging numbers were assigned and displayed - hence the use of simple numbers starting with "style" 38.
