### ISSUE TITLE
Unable to give place by category when two categories at a table

### ISSUE THREAD

**Issue by dogunter** [geoffhumphrey/brewcompetitiononlineentry#509]
We have assigned two categories to a single table (Meads M3 and M4). When it comes time to enter the scores for the table, we are only allowed to give 1st place to one entry. We would like to give first place to one M4 entry and first place to one M3 entry.

How can this be done?

**Comment by buergermeister75** [comment]
You'll need to create a table for M3 and another for M4 in the system.  A physical table with 4 legs or a physical location at the judging event is not the same thing as a table in the system.  We do this all the time for our competitions. We'll have sets of judges sit side by side at the same physical table, but they actually judge two different tables.
