### ISSUE TITLE
Volunteer Registration still allowed after set end date

### ISSUE THREAD

**Issue by rcthomas69** [geoffhumphrey/brewcompetitiononlineentry#513]
System is still allowing new judges and stewards to register after the end date set in Competition Info.  bigbeers.brewcomp.com

**Comment by j031** [comment]
Have you verified the dates in the menu Admin -> Preparing -> Edit -> Competition Info
![2016-01-03 09_39_05-clipboard](https://cloud.githubusercontent.com/assets/9260986/12079418/ee3fdeca-b1fd-11e5-83b8-71f1e9d7e2d3.png)

There should be options for competition and judge / steward registration windows.
![2016-01-03 09_40_57-2015 german fest stein challenge organized by beer barons of milwaukee _ adminis](https://cloud.githubusercontent.com/assets/9260986/12079421/2cda0a7a-b1fe-11e5-920c-2e2bb892ad54.png)

**Comment by rcthomas69** [comment]
Yes.  The close date was originally 12/31 at 11:59AM, and one judge let me know that it blocked them that day.  However there was one judge to register at 5 PM on the 31st, and I was (and still am) able to create a new registration then choose judge options.



 

 

Note the time in the shot below for this test judge I just created.

 

 

 



 

Thank you,

Ryan Thomas

**Comment by geoffhumphrey** [comment]
Hey Ryan, I see. It looks like there's a "backdoor" to the registration function via the volunteers page and/or entering the URL directly. I'll make sure to close that for the next version. Thanks for reporting.
