### ISSUE TITLE
Can't upload logo on latest commit

### ISSUE THREAD

**Issue by torreyj** [geoffhumphrey/brewcompetitiononlineentry#514]
When uploading logo from admin, I get this error:

Not Found

The requested URL /admin/includes/upload.inc.php was not found on this server.

**Comment by geoffhumphrey** [comment]
Upload has been proving to be a bit of a challenge. The issues haven't been resolved yet. It's next on the list.

**Comment by geoffhumphrey** [comment]
The latest v 2.0.0 commit features logo image upload capability. Give it a whirl...

**Comment by torreyj** [comment]
Awesome! Thanks.  I was just about to add another issue ticket. I has to switch back to that last version for my competition because when it went live with this last build, I was getting an Competition Was Full error. I'll send another issue with more details.

**Comment by geoffhumphrey** [comment]
I would not advise using any of the v 2.0.0 code for a production or live competition. There are still a lot of bugs that may crop up that will most likely irk your users (and generate some interesting emails to you). 2.0.0 is close, but not production ready...

**Comment by torreyj** [comment]
Yep, found that out :)  It's ok, it was fun messing with it.  Thanks for your work on this.
