### ISSUE TITLE
Bootstrap styles for nav and foot are fixed, can't update items (latest commit)

### ISSUE THREAD

**Issue by torreyj** [geoffhumphrey/brewcompetitiononlineentry#515]
Can't update items (plus site looks off) because the bootstrap styles are hiding the update buttons and pushing down the nav and hiding the flash. 

navbar navbar-inverse navbar-fixed-bottom bcoem-footer

it works when you remove position:fixed on the styles above.

**Comment by geoffhumphrey** [comment]
What environment are you testing the commits on? I've had no issue with desktops, laptops, tablets and phones I've used for testing.

**Comment by torreyj** [comment]
Sorry, after further testing this morning, it's the bootstrap styles I'm pretty sure.  I just added padding-top: 60px and padding-bottom:80px to the body tag and it fixed it. I'm testing on a mac, with Firefox and Chrome. The top and bottom and pinching off content. 
![screenshot-ibuopen com 2016-01-14 09-02-00](https://cloud.githubusercontent.com/assets/6643464/12327715/9de97730-ba9d-11e5-9e7d-4316e8cbcab0.png)
![screenshot-ibuopen com 2016-01-14 09-00-54](https://cloud.githubusercontent.com/assets/6643464/12327714/9de94e54-ba9d-11e5-9df7-9af5b980ecfb.png)
![screenshot-ibuopen com 2016-01-14 08-59-10](https://cloud.githubusercontent.com/assets/6643464/12327716/9dee6240-ba9d-11e5-9795-0440e119693d.png)
![screenshot-ibuopen com 2016-01-14 08-57-00](https://cloud.githubusercontent.com/assets/6643464/12327717/9df042cc-ba9d-11e5-80a4-739aa479ba0a.png)

**Comment by torreyj** [comment]
I'm testing on a mac, using Firefox and Chrome.

**Comment by torreyj** [comment]
If you can't fix it, let me know. I'll try later tonight, and add a pull request. But it should be a pretty easy fix.

**Comment by geoffhumphrey** [comment]
Ah. Looks to me like the /css/default.min.css isn't being loaded. There are style Bootstrap overrides in that file that correct this issue. Check the /sites/bootstrap.php around line 126. It should be:

`$theme = $base_url."css/".$_SESSION['prefsTheme'].".min.css";`

Then, check index.php around line 117. It should be:

`<link rel="stylesheet" type="text/css" href="<?php echo $theme; ?>" />`

Hopefully that will fix the issue. Here's the way it's supposed to look
![screen shot 2016-01-14 at 8 29 37 am](https://cloud.githubusercontent.com/assets/5216502/12328532/00fa1c4e-ba99-11e5-9c30-9c46eb905bc0.png)

**Comment by torreyj** [comment]
Figured it out. Those are the values that I have, but I noticed, it's grabbing 'prefsTheme' from the database, at the moment mine is 'lambicus' from my old site (I updated from last years version), then there should be a lambicus.min.css file correct? But there isn't one. The only file I see in the css directory is the default.min.css.  So I changed my theme to "default" in the database and it worked. Just add the other theme css files, and this should work.  Thanks

**Comment by geoffhumphrey** [comment]
The bruxellensis and claussenii themes for v 2.0.0 have yet to be developed. They will come last as I'm still tweaking the CSS in default, which will serve as a base for other themes. For now, like torreyj said, make sure your theme is BCOE&M Default when setting your preferences when testing commits prior to 2.0.0 release.
