### ISSUE TITLE
Unable to edit the style of an entry

### ISSUE THREAD

**Issue by johnrm** [geoffhumphrey/brewcompetitiononlineentry#516]
Once a beer is submitted it is not possible to edit the style.
(On reflection, a beer may be deemed close to one style than another)

**Comment by geoffhumphrey** [comment]
Hello John. A bit more information would be helpful here. Please specify the version you are currently experiencing this issue with. I know that this issue was fixed with the 1.3.2.0 release (see Issue #477).

**Comment by jimpdx** [comment]
I am seeing the same thing on 1.3.2.0. After a user has created an entry, when you (or even an admin) goes back to "Edit" that entry, you can not select a different category. I have had to create a NEW entry a few times then delete the old one, which is not ideal.
