### ISSUE TITLE
Special Ingredients box missing when entering a custom style

### ISSUE THREAD

**Issue by johnrm** [geoffhumphrey/brewcompetitiononlineentry#517]
While creating an entry, 'Specific Type, Special Ingredients and/or Classic Style' entry box does not show initially for a Custom style.
User must submit their entry, then wait for the error, at which point the box appears and they can then enter this additional information.

**Comment by geoffhumphrey** [comment]
In the latest version (and a couple versions back if I'm not mistaken), when you set up a custom category, there is an option to require special ingredients. If that flag is set, the special ingredients entry box will show when the user chooses the custom style.
