### ISSUE TITLE
 Adding entries is not available. The competition entry limit has been reached.

### ISSUE THREAD

**Issue by torreyj** [geoffhumphrey/brewcompetitiononlineentry#518]
Users trying to enter in entries got this error on the first day the competition started" Adding entries is not available. The competition entry limit has been reached."  Admin could enter in stuff, but normal entry users got this error. I switch back to last version so it didn't interrupt the comp, but just want to get this in for other users.  Thanks

**Comment by geoffhumphrey** [comment]
Thanks for reporting. There are some logic errors that will cause this behavior. The next commit will have a fix in place.

**Comment by dregalia** [comment]
Thanks, I just downloaded and installed this today.. It's still happening.  I ended up limiting the number of entries to 10000, just to make sure there are no more problems.  I would double check/test it again.  I am using the 2.0 software that is available on the site.  Thanks!

**Comment by geoffhumphrey** [comment]
I'll check the code and test again. Please know that the 2.0 version is not production ready; I would not be confident using it for a live competition until its official release, which is targeted for the end of the month.

**Comment by dregalia** [comment]
That's fine, we're in testing mode as well.  If anything comes up, we'll let you know what and where.  I'm looking forward to the new version.  I just wish there was a way to create multiple events without having to recycle the users.

**Comment by dregalia** [comment]
Awesome!  Thanks
