### ISSUE TITLE
Entry date

### ISSUE THREAD

**Issue by PeterSteinberg** [geoffhumphrey/brewcompetitiononlineentry#521]
I would like to have separate dates for when people can add entries and when the shipping / dropoff locations will accept them.

Right now the Entry Window dates states "The date/time that entrants will be able to add entries to the system. Also the date that drop-off and mail-in locations will begin receiving entries."

**Comment by geoffhumphrey** [comment]
Just in time Peter! As it happens, I'm working on that functionality now. For v2.0.0, admins will be able to specify shipping and drop-off windows separately from the entry registration window.

**Comment by dducrest** [comment]
Woo hoo!
