### ISSUE TITLE
"Specific Type" requirement missing for 9A, 10C, 24C

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#522]
Hopefully this issue report isn't too late for v2.0.0 since this is kind of major...

9A (Doppelbock), 10C (Weizenbock), 24C (Biere De Garde) require colour to be specified by brewer. 

Pale vs Dark

To double check which styles require a description from brewer just search for "Entry Instructions" in the 2015 guidelines.

Currently only these show as required:

Required for the following categories: 07C  21B  23F  25B  27A  28A  28B  28C  29A  29B  29C  30A  30B  30C  31A  31B  32A  32B  33A  33B  34A  34B  34C

Using 1.3.2.0
Using 2015 Guidelines

**Comment by geoffhumphrey** [comment]
This will be included in 2.0.0; it is not part of the latest commit, however. Thanks for the heads up.

**Comment by geoffhumphrey** [comment]
Also applies to Kellerbier (7C) for color, Saison (25B) for strength and color.

**Comment by ercousin** [comment]
Yes it does, but 7C and 25B were already included on the list, it was just 9A, 10C, and 24C that were missed.

**Comment by ercousin** [comment]
I filed a separate report for a related issue to fix the drop down menu and legend. This one (adding 9A, 10C, 24C to "required" list) is higher priority though since it could make or break an entry.

https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/524
