### ISSUE TITLE
"Brewers Specifics" field is confusing for entrants

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#523]
I'm not sure what the intended use of the "Brewer's Specifics" field is since it shows up for every style, including the ones where information isn't required of the brewer. The issue is that it also shows up for styles where information is required of the brewer and can confuse them into putting their entry info into the wrong box, or splitting their info two boxes.

Can you add an option to disable this field from the entry creation page? Also I think setting it to off by default would be wise.

Using 1.3.2.0

![image](https://cloud.githubusercontent.com/assets/1551339/12558246/9eae2a2c-c35c-11e5-8bc3-b3f75de7db44.png)

**Comment by jimpdx** [comment]
We discovered this past weekend that participants were treating this like the "Special Ingredients" section. But since we were not printing out the "Brewer's Specifics" section it was not visible during judging. I assume the field was intended to be part of the RECIPE section and if I am correct, it should display within the recipe section if configured to display at all.

**Comment by ercousin** [comment]
Yes, I anticipate this "extra" field is going to cause a lot of issues for judging until it is removed...

**Comment by geoffhumphrey** [comment]
The Brewer's Specific field has been provided as an option for every entry by request as an extra field that entrants can use to delineate anything other than special ingredients, classic style, strength, color, etc. I will make sure that the supporting text is very clear that special ingredients, etc. should NOT be included in this field. Here's a screenshot for 2.0.0:

![screen shot 2016-01-25 at 10 37 23 am](https://cloud.githubusercontent.com/assets/5216502/12558972/aab74ed2-c34f-11e5-8f6d-2aa51551deff.png)

**Comment by jimpdx** [comment]
Looks great @geoffhumphrey - let me know if you need help with CSS or other UI testing

**Comment by ercousin** [comment]
I agree that it is clear to people like us that are conscientious enough to read the text and have experience entrering. It has still been a source of confusion for new entrants and people that don't pay close attention.

It would be a big help if we could turn it off with an option. Most competitions do not provide judges with this kind of info anyway.

**Comment by ercousin** [comment]
Also, that red text doesn't seem to show up when 2015 guidelines are set. This is what I see in 1.3.2.0 with 2015.

![image](https://cloud.githubusercontent.com/assets/1551339/12559107/107ca53a-c361-11e5-9783-63eb75142a34.png)

**Comment by jimpdx** [comment]
@ercousin the screenshot he is showing is from version 2.0.0.0 - you won't see the same text or formatting in 1.3.2.0

**Comment by jimpdx** [comment]
@geoffhumphrey looking more closely at your screenshot, I think it is misleading to indicate that "Brewer's Specifics" would be evaluated by judges. We print entry/judging numbers and special ingredients only onto the bottles. I don't think any of the standard label templates are include Brewer's Specifics. A fellow organizer thought (as I now do) that the field is more "recipe" related, in which case the text beneath the field is quite misleading.
