### ISSUE TITLE
Only "spade" shows up in style drop down, diamond/club/heart and missing

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#524]
There is a legend showing what type of info is require for each style, however in the drop down menu only spade shows up.

♠ = Specific Type, Special Ingredients and/or Classic Style Required
♦ = Strength Required
♣ = Carbonation Level Required
♥ = Sweetness Level Required

For example: 25B (Saison) should have a diamond next to it in the drop down list, instead it has a spade.

I would also recommend amending the diamond to say:

♦ = Strength and/or Color Required

That would help simplify things since Saison would only require ♦ and no ♠.

♠ would only be needed on the specialty styles (27A  28A  28B  28C  29A  29B  29C  30A  30B  30C  31A  31B  32A  32B  33A  33B  34A  34B  34C).

♦ would be specified for 07C  9A  10C  24C  25B

♠♦ would be specified for 21B  (since it requires strength + type)

♠♣♥ would be specified for 23F  (since it requires fruit type, carbonation, and sweetness level)

I hope this helps and can make it into v2.0.0

This is on v1.3.2.0
Using 2015 Guidelines

![image](https://cloud.githubusercontent.com/assets/1551339/12558357/1b0dbc9a-c35d-11e5-94e2-00fc1b8196d7.png)

![image](https://cloud.githubusercontent.com/assets/1551339/12558393/4510aec6-c35d-11e5-873e-6805fbb5ed0e.png)

**Comment by jimpdx** [comment]
"Strength" is also required for Specialty IPA, which I reported earlier.

**Comment by ercousin** [comment]
Yes, following the breakdown I laid out above will fix all current issues (unless I missed something):

♠ would only be needed on the specialty styles (27A 28A 28B 28C 29A 29B 29C 30A 30B 30C 31A 31B 32A 32B 33A 33B 34A 34B 34C).

♦ would be specified for 07C 9A 10C 24C 25B

♠♦ would be specified for 21B (since it requires strength + type)

♠♣♥ would be specified for 23F (since it requires fruit type, carbonation, and sweetness level)
