### ISSUE TITLE
Judging/Stewarding Location Availability Only Shows Up When Multiple Rounds Defined

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#525]
I have a competition with only 1 round, 1 judging location (very small comp). When I went to assign judges to tables I noticed that none of them were available for the one round.

I tried to create a dummy judge entry and noticed that it never asked me availability so everyone who signed up had no availability defined.

Can you change the functionality to always have these text boxes show up? Or just set availability to yes when only 1 round defined.

I had to create a second dummy judging location (also with only 1 round) to get the text boxes to show up.

Before adding 2nd round:
![image](https://cloud.githubusercontent.com/assets/1551339/12585000/163ee1ce-c418-11e5-9490-cbb1c4cefc8e.png)

After adding 2nd round:
![image](https://cloud.githubusercontent.com/assets/1551339/12585123/96de5c2e-c418-11e5-96e9-4fa3d91de89b.png)

Judging location list after adding 2nd round:
![image](https://cloud.githubusercontent.com/assets/1551339/12585070/6ac3eb68-c418-11e5-9f93-e1b61d8c9e71.png)

**Comment by geoffhumphrey** [comment]
This is a bug that was reported to me directly (forgot to log it here) and will be fixed. Essentially, when only one location is available, all judges will be automatically associated with it. Will be in place for 2.0.0.

**Comment by ercousin** [comment]
Perfect! Noticed it today, just wanted to make sure it made it into 2.0.0!

Thanks for all your work Geoff!
