### ISSUE TITLE
Unable to put postal code in 2.0.0

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#526]
Checking out to 2.0.0 software, unable to enter a postal code, only accepts numbers not letters. Please make sure this field accepts letters too.

For example: "A1A 1A1"

http://v2.brewcomp.com/register/judge

**Comment by geoffhumphrey** [comment]
Looking at the code, the text field had a type of "number" - I'll change it to accept alphanumeric for the next commit. Good catch!
