### ISSUE TITLE
Unable to add an entry in 2.0.0 sandbox

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#527]
I imagine you are already aware of this one... but after registering (with a fake postal code of "12" since postal codes aren't accepted), I'm unable to add an entry. The screen is blank.

![image](https://cloud.githubusercontent.com/assets/1551339/12729285/f26401f4-c8f3-11e5-8eb2-e05f73e04b8c.png)

**Comment by geoffhumphrey** [comment]
Interesting - can't imagine how the two are connected. I'll look into it.

**Comment by ercousin** [comment]
I mentioned postal code just in case. Should "Add An Entry" be working in the sandbox?

**Comment by geoffhumphrey** [comment]
Figured it out... Had to do with an incorrect figuring of the total limit of entries. Fix will be in place in the next commit and the sandbox has been updated.
