### ISSUE TITLE
Competition info edit page is broken

### ISSUE THREAD

**Issue by RussellXIP** [geoffhumphrey/brewcompetitiononlineentry#530]
Below Logo File name, nothing is rendered and there is no button to update.  In viewing source, the HTML is just truncated:

```
<div class="form-group"><!-- Form Group NOT REQUIRED Text Input -->
    <label for="contestHostWebsite" class="col-lg-2 col-md-3 col-sm-4 col-xs-12 control-label">Host Website Address</label>
    <div class="col-lg-6 col-md-6 col-sm-8 col-xs-12">
        <!-- Input Here -->
        <input class="form-control" id="contestHostWebsite" name="contestHostWebsite" type="text" maxlength="255" value="http://strangebrew.org/" placeholder="http://www.yoursite.com">
    </div>
</div><!-- ./Form Group -->

<div class="form-group"><!-- Form Group NOT REQUIRED Select -->
    <label for="contestLogo" class="col-lg-2 col-md-3 col-sm-4 col-xs-12 control-label">Logo File Name</label>
    <div class="col-lg-6 col-md-6 col-sm-8 col-xs-12">
    <!-- Input Here -->
    <select class="selectpicker" data-width="auto"  name="contestLogo" id="contestLogo">

```       
<img width="883" alt="screen shot 2016-02-06 at 11 01 40 am" src="https://cloud.githubusercontent.com/assets/8182468/12868729/66c8f100-ccc1-11e5-8cc1-84fea21136f6.png">

**Comment by geoffhumphrey** [comment]
Hi Russell, a couple of things to make sure of...

- Make sure you have a user_images folder on your server in the root folder of your installation. The very earliest release of 2.0.0 did not have this folder in for some reason. I fixed that and updated with the release, but if you downloaded the source code in the first couple of hours after release this folder was missing. 
- If that folder is in place, make sure that there are images in it.

If the those are in place already, please post back here and I'll dig further into the code to see what's happening.

**Comment by RussellXIP** [comment]
Hi Geoff,

The folder is there and there is a sample_logo.png file in it.  The file
folder permissions are:

drwxr-xr-x  2 strangk9 strangk9  4096 Feb  5 16:22 *user_images*/

[image: Inline image 1]

**Comment by geoffhumphrey** [comment]
OK. Make sure the permissions are at least read/write for all users (766 or 777) for the user_images folder - forgot to mention that.

**Comment by RussellXIP** [comment]
Ok, I updated the folder permissions but same result.

**Comment by geoffhumphrey** [comment]
Looks like the point of failure is either the call to a function called directory_contents_dropdown, or  the path defined in the USER_IMAGES global variable defined in root/paths.php is incorrect for your environment. To know if this is the problem, we need to know what that variable is being defined as.

If you would, create a new file in notepad, copy the code below into it, save it as filepaths.php, upload it to the root of your installation, and browse to it. Copy and paste the resulting page here and we'll see if there's something amiss with the file path definitions.

```
<?php 

include('paths.php');

echo (ROOT)."<br>";
echo (ADMIN)."<br>";
echo (CLASSES)."<br>";
echo (CONFIG)."<br>";
echo (DB)."<br>";
echo (IMAGES)."<br>";
echo (INCLUDES)."<br>";
echo (LIB)."<br>";
echo (MODS)."<br>";
echo (PROCESS)."<br>";
echo (SECTIONS)."<br>";
echo (COMPONENTS)."<br>";
echo (TEMPLATES)."<br>";
echo (SETUP)."<br>";
echo (UPDATE)."<br>";
echo (OUTPUT)."<br>";
echo (USER_IMAGES)."<br>";

?>
```

**Comment by geoffhumphrey** [comment]
Also, make sure you have the admin.lib.php file in the /lib/ directory. The function that is called is housed in that file. 

Post any error log files that are in your /admin/ directory as well. That will help to pinpoint the problem.

**Comment by RussellXIP** [comment]
I confirmed that the admin.lib.php is there.  Here is the result from the
code snipped you provided:

/home1/strangk9/public_html/slurp2/
/home1/strangk9/public_html/slurp2/admin/
/home1/strangk9/public_html/slurp2/classes/
/home1/strangk9/public_html/slurp2/site/
/home1/strangk9/public_html/slurp2/includes/db/
/home1/strangk9/public_html/slurp2/images/
/home1/strangk9/public_html/slurp2/includes/
/home1/strangk9/public_html/slurp2/lib/
/home1/strangk9/public_html/slurp2/mods/
/home1/strangk9/public_html/slurp2/includes/process/
/home1/strangk9/public_html/slurp2/sections/
/home1/strangk9/public_html/slurp2/components/
/home1/strangk9/public_html/slurp2/templates/
/home1/strangk9/public_html/slurp2/setup/
/home1/strangk9/public_html/slurp2/update/
/home1/strangk9/public_html/slurp2/output/
/home1/strangk9/public_html/slurp2/user_images/

**Comment by RussellXIP** [comment]
I didn't see any log files in the admin directory.  Here is a screen shot.
<img width="623" alt="screen shot 2016-02-06 at 11 50 46 am" src="https://cloud.githubusercontent.com/assets/8182468/12868985/e54cedd2-ccc7-11e5-8c06-411ad98dfd45.png">

**Comment by geoffhumphrey** [comment]
Hmm. I have to say I'm at a loss at the moment, but it looks like the point of failure is the function since the path variables are OK and permissions are good. One more thing to check for problem solving - navigate to the image upload function and post a screenshot. There should be a list of images in the directory right below the upload box.

**Comment by RussellXIP** [comment]
The image upload page seems to work.  Interestingly, the link to upload images wasn't listed under the Competition Preparation main window but only under the Admin menu on the left.  See attached screen shots
<img width="1000" alt="screen shot 2016-02-06 at 12 02 59 pm" src="https://cloud.githubusercontent.com/assets/8182468/12869072/e9ef8352-ccc9-11e5-8a29-2693df23c524.png">
<img width="652" alt="screen shot 2016-02-06 at 12 03 51 pm" src="https://cloud.githubusercontent.com/assets/8182468/12869074/ee01d10c-ccc9-11e5-88f6-d8294ab44197.png">
<img width="303" alt="screen shot 2016-02-06 at 12 04 05 pm" src="https://cloud.githubusercontent.com/assets/8182468/12869075/f11cb6c2-ccc9-11e5-9b93-98bb9814aeba.png">

**Comment by RussellXIP** [comment]
I put a print statement inside the directory_contents_dropdown function inside admin.lib.php at the top and it doesn't appear on the page so the call stack is quietly dying before it ever calls that function, it appears.

**Comment by RussellXIP** [comment]
My bad, it is being output, it's just hidden by the open <select> tag.  I'll keep troubleshooting...

**Comment by geoffhumphrey** [comment]
OK. You may want to comment out line 109 on the /admin/competition_info.admin.php file just to see if the rest of the page renders.

**Comment by RussellXIP** [comment]
Ok, it's dying on this call: 		

$finfo = finfo_open(FILEINFO_MIME_TYPE);

**Comment by RussellXIP** [comment]
Commenting out line 109 does allow the rest of the page to render.

**Comment by geoffhumphrey** [comment]
For now, I would comment out the following code in the function; it's really not needed:
```
$filetype_ok = FALSE;
		
		$finfo = finfo_open(FILEINFO_MIME_TYPE);
    	$mime_type = finfo_file($finfo, $directory.$file);
		switch ($mime_type) {
			case "image/jpeg": $filetype_ok = TRUE; break;
			case "image/png":  $filetype_ok = TRUE; break;
			case "image/gif":  $filetype_ok = TRUE; break;
		}
```
Add this just below:

```
$filetype_ok = TRUE;
```
The entire function should look like this:
```
function directory_contents_dropdown($directory,$file_name_selected) {
	
	$handle = opendir($directory);
	$filelist[] = "";
	
	while ($file = readdir($handle)) {
		/*
		$filetype_ok = FALSE;
		
		$finfo = finfo_open(FILEINFO_MIME_TYPE);
    	$mime_type = finfo_file($finfo, $directory.$file);
		switch ($mime_type) {
			case "image/jpeg": $filetype_ok = TRUE; break;
			case "image/png":  $filetype_ok = TRUE; break;
			case "image/gif":  $filetype_ok = TRUE; break;
		}
	   */
	   $filetype_ok = TRUE;
	   
	   if ((!is_dir($file)) && (!is_link($file)) && ($filetype_ok)) {
			$filelist[] .= $file;
	   }
	   
	}
	
	sort($filelist, SORT_NATURAL | SORT_FLAG_CASE);
	
	$return = "";
	foreach ($filelist as $filename) {
		$selected = "";
		if ($file_name_selected == $filename) $selected = " selected";
		$return .= "<option value=\"".$filename."\"".$selected.">";
		$return .= $filename;
		$return .= "</option>";
	}
	
	return $return;
}
```

Hopefully this will clear up the issue...

**Comment by RussellXIP** [comment]
Yes, it looks like that cleans it up! I appreciate the rapid response and quick resolution!

Would you like me to log a different issue for the Image upload link not being in the Competition Preparation list of admin links for the dashboard view?

**Comment by geoffhumphrey** [comment]
You thinking it should be like this?
![adminmenu2](https://cloud.githubusercontent.com/assets/5216502/12869249/26873ca8-ccd7-11e5-9dca-f53f33ef3521.PNG)

**Comment by RussellXIP** [comment]
Yes, that looks good!  Since it's a top level function on the Admin pop out menu on the right side, I was just expecting to find the link in the Comp Prep list also.

**Comment by geoffhumphrey** [comment]
No problem. I'll be included in the next commit as well as a fix for the problem child in the function we identified.

**Comment by RussellXIP** [comment]
Cool. Thanks again for the fantastic support!
