### ISSUE TITLE
Upgrade or new install - no help available?

### ISSUE THREAD

**Issue by XeonNAS** [geoffhumphrey/brewcompetitiononlineentry#533]
Just looked around for any help on upgrading from an earlier  version to 2.0, does not appear to be anything available yet?

John

**Comment by geoffhumphrey** [comment]
Hi John,
Check here:
- http://www.brewcompetition.com/install-instructions
- http://www.brewcompetition.com/upgrade-instructions

**Comment by XeonNAS** [comment]
Excellent, thanks
