### ISSUE TITLE
The installed version (2.0.0.0) is the same as the version for upgrade. No updates are necessary.

### ISSUE THREAD

**Issue by XeonNAS** [geoffhumphrey/brewcompetitiononlineentry#534]
Installed new files, after logging in the above message appears, no links on the page work as they all link back to the update.php page, which produces the same message.

Cheers 

John

**Comment by geoffhumphrey** [comment]
This may occur if you installed one of the commit packages, pre-release. Even if you didn't install any pre-release commits, the update function checks the "system" DB table for the installed version. Change the version value in that table to 1.3.2.0 or whatever version you may have had installed; post back whether that worked. In the meantime, I'll see if there's any weird going on in the update function code.

**Comment by XeonNAS** [comment]
Yeah that did it perfect!
