### ISSUE TITLE
mysql_connect deprecation warning for php5.5+

### ISSUE THREAD

**Issue by graemecoates** [geoffhumphrey/brewcompetitiononlineentry#535]
The use of mysql_connect is deprecated from php5.5 onwards, and is removed in php7 - currently (BCOEM 2.0.0) its use in site/config.php throws warnings as such. This needs to be converted to mysqli_connect for the future (unsure of knock-on affects if any here?).

**Comment by geoffhumphrey** [comment]
The next version, 2.1.0, will have updated mysql connection programming. It's a pretty big undertaking, hence the push-off until the next version, which is planned for release at the end of March, 2016.

Cheers.

**Comment by geoffhumphrey** [comment]
@graemecoates - update on this as of today. I have converted all of the code to mysqli in the 2.1.0 branch. Currently in the midst of testing all functions.
