### ISSUE TITLE
DataTables warning

### ISSUE THREAD

**Issue by wireden** [geoffhumphrey/brewcompetitiononlineentry#537]
Not sure where this is coming from but when you first load the home page in Chrome this message appears. I can not see that it is stopping in functionality or creating any problems.

The error started after judging was complete and awards are posting.

Error:
DataTables warning: table id=sortable37499745811 - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

Site:
http://www.hgbrew.com/hgb/bcoem/

Preformed all DB maintenance from the Admin Dash board.

**Comment by geoffhumphrey** [comment]
Thanks for reporting. I'll grab a look at the code and post back if I find any anomalies. Since there are multiple DataTables that are dynamically rendered on the page by php, there may be some "confusion" with the DataTables script initialization for each table being rendered. Stay tuned.

**Comment by wireden** [comment]
Updated to 2.0.1 new error below.

DataTables warning: table id=sortableH8O9K1038J9379414G7I7 - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

**Comment by geoffhumphrey** [comment]
Weird. Thought that would take care of it. I'll keep looking and trying
different things...

Thanks for letting me know.

On Fri, Feb 12, 2016 at 9:35 AM, wireden <notifications@github.com> wrote:

> Updated to 2.0.1 new error below.
>
> DataTables warning: table id=sortableH8O9K1038J9379414G7I7 - Cannot
> reinitialise DataTable. For more information about this error, please see
> http://datatables.net/tn/3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/537#issuecomment-183400093>
> .
>



-- 
-------------------------------
Geoff Humphrey
