### ISSUE TITLE
DataTables warning Reference Issue: #537

### ISSUE THREAD

**Issue by wireden** [geoffhumphrey/brewcompetitiononlineentry#542]
Reference Issue: #537

Updated to 2.0.1 new error below.

DataTables warning: table id=sortableH8O9K1038J9379414G7I7 - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

site: http://www.hgbrew.com/hgb/bcoem

**Comment by geoffhumphrey** [comment]
To be clear for anyone else, the warning pops up, but the tables on the winners page render just fine. Back to the drawing board to figure this one out! Thanks for reporting...

**Comment by wireden** [comment]
Thanks. I think the redesign of the front end is wonderful.

Matt
