### ISSUE TITLE
IE Edge issues with Admin Access

### ISSUE THREAD

**Issue by marckw** [geoffhumphrey/brewcompetitiononlineentry#548]
Not sure this is an application issues as much as a browser issue however, when using IE Edge (25.10586.0.0), any attempts to logon with an elevated account (userLevel 0 & 1) displays:
**You must log in and have admin privileges to access the XXXXXXXX administration functions. **

Performing password reset prompts:
**Your verification question does not match what is in the database. Please try again. **
when verifying secret question regardless if the answer is correct or not.

**Comment by geoffhumphrey** [comment]
Thanks for reporting @marckw; I will test the issue with Edge on my Windows 10 machine and see if there's anything that can be fixed. In the interim, this isn't an issue with the latest versions of both Chrome, Safari, and Firefox for Windows, Mac, iOS and Android.

**Comment by geoffhumphrey** [comment]
@marckw, I wasn't able to recreate the issues you reported with the latest version of IE Edge running on Windows 10 accessing my testing server. If anyone else is experiencing these issue, please post here with your version of IE Edge, Windows Version, and webserver environment if possible.
