### ISSUE TITLE
Barcode Check-In Function Not Updating Judging Numbers

### ISSUE THREAD

**Issue by geoffhumphrey** [geoffhumphrey/brewcompetitiononlineentry#549]
When attempting to use a barcode scanner to enter the entries it doesn't replace the system generated judging number. Fixed in latest commit...

**Comment by BrewDrinkRepeat** [comment]
I'm trying to scan in entries right now, version 2.0.1, and none of the new judging numbers (scanned from the barcodes via the Checking With Barcode Scanner page) are being entered into the database.

Is there new code I can copy into my install that will correct this?

**Comment by geoffhumphrey** [comment]
The latest commit from the master branch should fix this, if memory serves me correctly. 

======================
Geoff

**Comment by BrewDrinkRepeat** [comment]
Please pardon my lack of knowledge about Github / branches / forks / etc. Do I download all the files and re-upload to my server, or is there a specific file / set of files I can grab that represent "the latest commit"?

Sorry... I know just enough about all of this to be dangerous.  :)

**Comment by geoffhumphrey** [comment]
No worries. Download this zip, expand it locally, and upload all folders EXCEPT the /site/ folder to replace the files currently on the server. That will get you up to date.

https://github.com/geoffhumphrey/brewcompetitiononlineentry/archive/master.zip

Hope that helps!

======================
Geoff

**Comment by BrewDrinkRepeat** [comment]
Awesome, thank you SOOOOO much! Downloading now, I'll report back if I run into any problems!

**Comment by BrewDrinkRepeat** [comment]
Looks like it's working perfectly (and nothing else got broken in the process, at least not that I've seen!).

Thanks!!!!

A view of the fun:
https://www.instagram.com/p/BFC6ms4BucH/?taken-by=brewdrinkrepeat
