### ISSUE TITLE
How to control # of bottle labels in PDFs?

### ISSUE THREAD

**Issue by dducrest** [geoffhumphrey/brewcompetitiononlineentry#550]
I cannot find where I can change the number of labels that are printed per entry.

Currently, my site is printing four, but I'm running a 1-round with BOS competition which requires two bottles. Can I change this setting?

**Comment by geoffhumphrey** [comment]
@dducrest - unfortunately, the number of printed bottle labels is fixed at four. A possible enhancement would be give admins the ability to define the number in a future release. Four was chosen for a couple of factors: 1) that's the number that would fit on a single page, 2) most comps require between 2 and 4 bottles.

**Comment by dducrest** [comment]
Gotcha.

Just an FYI, people were weirded out when they saw 4 labels.  So there is a segment of the general population to consider

**Comment by geoffhumphrey** [comment]
@dducrest, do you think it would be beneficial to add the "bottle submission rules" to the bottle labels print out? I'm thinking it can't hurt and it serves as a not-so-subtle reminder to check the bottle submission rules.

**Comment by dducrest** [comment]
That would probably accomplish part of the intended goal.

Might be possible to separate the Recipe receipt from the Labels so that
they can be printed as needed.



On Tue, Mar 8, 2016 at 3:18 PM, geoffhumphrey <notifications@github.com>
wrote:

> @dducrest <https://github.com/dducrest>, do you think it would be
> beneficial to add the "bottle submission rules" to the bottle labels print
> out? I'm thinking it can't hurt and it serves as a not-so-subtle reminder
> to check the bottle submission rules.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/550#issuecomment-193951144>
> .
>



-- 
David Ducrest
dducrest@gmail.com

**Comment by geoffhumphrey** [comment]
Will be addressed in version 2.1.14. See issue #857 for more info.
