### ISSUE TITLE
Setup process fails if site is https only

### ISSUE THREAD

**Issue by anigeluk** [geoffhumphrey/brewcompetitiononlineentry#552]
The config defaults to using http for the base_url meaning all forms and ajax requests fail if your site is using https only and redirecting http traffic to https. It also means, if you server supports both https and http then you get sent back to http even if you were previously accessing via https.

I would suggest setting the protocol part of the URL programmatically based on checking the value of $_SERVER['HTTPS'] which can be used to check if the site has been requested via https as it is not immediately obvious what the issue is unless you know what you are looking for.

**Comment by geoffhumphrey** [comment]
Great suggestion. I'll make sure the check is incorporated into the next version.

**Comment by geoffhumphrey** [comment]
@anigeluk if you would, please replace the $base_url variable in your config file on or about line 163 (the $base_url section) with the following and let me know if it worked for you...

`$base_url = "";`
`if ((!empty($_SERVER['HTTPS']) && ($_SERVER['HTTPS'] !== "off")) || ($_SERVER['SERVER_PORT'] == 443)) $base_url .= "https://"; `
`else $base_url .= "http://"; `
`$base_url .= $_SERVER['SERVER_NAME'].$sub_directory."/";`

Thank you!
