### ISSUE TITLE
Feature Request: Admin can reset passwords or generate a reset token for participants

### ISSUE THREAD

**Issue by dducrest** [geoffhumphrey/brewcompetitiononlineentry#553]
Story:
Several of my participants are reporting that they aren't receiving the password reset email.
Some may be a problem with spam filter, but regardless they turn to me(the admin) for help and I don't have the power to do anything except use the form to send request another reset link.

Idea:
I'd like a feature to generate a reset password link or token that I can forward to the user via a secure channel.

Is there any other way that I reset a password?

**Comment by j031** [comment]
In past versions of the software, I've done the following.  But they both seem labor intensive and I agree it would be nice for the admin user to be able do this.

**Editing the MySQL user tables**
1.  Create a dummy account with a known password
2.  Then copy the hashed password from the dummy account  
3.  Paste into the users password field and let the user know the password

**Temporarily change the users email in MySQL**
1. Change the locked out users email address to an address you control in the user table
    * You shouldn't use an email already in use, as that needs to be unique per user.
2. Request the reset
3. Reset the password 
4. Change the email address back to the users
5. Send it to the user

**Comment by geoffhumphrey** [comment]
I agree it would be easier for an admin to be able to reset a password for an entrant. @j031, David is on a hosted account and does not have access to the backend of his installation... thus his frustration. I will put the ability for an admin to reset a user's password in the queue for 2.1.0.

**Comment by dducrest** [comment]
Thanks guys!

**Comment by geoffhumphrey** [comment]
As an additional measure and/or quick look up, I'll add the ability for admins to "look up" the question/answer combination for any participant, accessed via the Admin > Participants view. If the admin clicks on the question mark icon that's part of any record, a modal will display the user's secret question/answer combination:

![screen shot 2016-03-08 at 12 53 19 pm](https://cloud.githubusercontent.com/assets/5216502/13614389/73be0b82-e52d-11e5-9f12-3d8554b60858.png)

**Comment by dducrest** [comment]
That would be helpful too. No one can remember the "favorite" beer, either.
I have personally have a hard time choosing.

On Tue, Mar 8, 2016 at 2:58 PM, geoffhumphrey <notifications@github.com>
wrote:

> As an additional measure and/or quick look up, I'll add the ability for
> admins to "look up" the question/answer combination for any participant,
> accessed via the Admin > Participants view. If the admin clicks on the
> question mark icon that's part of any record, a modal will display the
> user's secret question/answer combination:
>
> [image: screen shot 2016-03-08 at 12 53 19 pm]
> <https://cloud.githubusercontent.com/assets/5216502/13614389/73be0b82-e52d-11e5-9f12-3d8554b60858.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/553#issuecomment-193942776>
> .
>



-- 
David Ducrest
dducrest@gmail.com

**Comment by geoffhumphrey** [comment]
Here's what I've done to address this issue for 2.1.0. Both are accessed via the Entries and Participants > Manage Participants screen:
- Added Admin access to "secret questions and answers" for all participants, accessible by clicking the question mark icon on each participants line item (see below for icon, above for what the modal will look like)
- Added a function to give Top-Level Admins the ability to change any participant's password. This is accessed by clicking on the key icon on each participant line item (see below)

![screen shot 2016-03-10 at 8 46 35 am](https://cloud.githubusercontent.com/assets/5216502/13675171/a97be3fe-e69d-11e5-96dc-453fb40c1883.png)

The change password function will look like this:

![screen shot 2016-03-10 at 8 55 54 am](https://cloud.githubusercontent.com/assets/5216502/13675332/4ea0a3a6-e69e-11e5-9d33-35ecb39193f1.png)

...and will trigger a warning modal:

![screen shot 2016-03-10 at 8 56 10 am](https://cloud.githubusercontent.com/assets/5216502/13675345/5b87a4e8-e69e-11e5-9e41-9fbb1edbb314.png)

**Comment by dducrest** [comment]
Looks great guys, thanks!
