### ISSUE TITLE
PayPal "mark as paid" function fails if names do not match

### ISSUE THREAD

**Issue by dducrest** [geoffhumphrey/brewcompetitiononlineentry#556]
I think ...

That the automatic "mark as paid" feature fails if the Paypal accounts "owners name" doesn't make the user's first/last name.

I've seen it fail when people use nick names in the site or their spouses paypal account.

**Comment by geoffhumphrey** [comment]
The PayPal mark as paid has always been hit or miss. It's purely dependent upon the user to click the "return to..." on PayPal after paying. I've built in a modal warning (see below); however, that's about as much as can be done on the app end.

![screen shot 2016-03-10 at 7 32 58 am](https://cloud.githubusercontent.com/assets/5216502/13672570/a9df3e32-e692-11e5-9358-543fe5e08651.png)

It's always a crap shoot when you depend upon user action on an external site...

**Comment by dducrest** [comment]
Gotcha. Thanks!
I've been able to keep up with the status more or less.

On Thu, Mar 10, 2016 at 9:35 AM, geoffhumphrey <notifications@github.com>
wrote:

> The PayPal mark as paid has always been hit or miss. It's purely dependent
> upon the user to click the "return to..." on PayPal after paying. I've
> built in a modal warning (see below); however, that's about as much as can
> be done on the app end.
>
> [image: screen shot 2016-03-10 at 7 32 58 am]
> <https://cloud.githubusercontent.com/assets/5216502/13672570/a9df3e32-e692-11e5-9358-543fe5e08651.png>
>
> It's always a crap shoot when you depend upon user action on an external
> site...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/556#issuecomment-194874305>
> .
>



-- 
David Ducrest
dducrest@gmail.com
