### ISSUE TITLE
No input field for sponsor description

### ISSUE THREAD

**Issue by simchuck** [geoffhumphrey/brewcompetitiononlineentry#557]
There is no input field for the description when adding or editing a sponsor.  

Latest version 2.0.0, recent install.

**Comment by anigeluk** [comment]
The input box is there on 2.0.1 but if you use Ad Block Plus then ABP for some unknown reason decides to hide that input box. My solution was just to disable ABP on my competition site.

**Comment by simchuck** [comment]
Thanks for that.  No need for blocking ads on my own site!

I also asked another question regarding entering the BJCP competition ID.
There is an input box and I can enter the number, but it doesn't seem to
store, even with ABP disabled.  I suspect this will be necessary when
finally reporting scores to the BJCP.  Any ideas?

Chuck

**Comment by anigeluk** [comment]
I've no idea on that one sorry, I'm not involved in the project, just happened to see your issue and knew the answer

**Comment by geoffhumphrey** [comment]
This issue came up for another user last week. Not sure of the culprit, but display of the field varied from browser to browser on different platforms. There's nothing in the code that is unusual. Need to dig further... In the meantime, if you change the HTML on the form to a text area instead of a text box, it may work.

**Comment by simchuck** [comment]
I don't know if you were copied on the below reply, but it worked for me...

​
---------- Forwarded message ----------

**Comment by geoffhumphrey** [comment]
Thanks for your report. A fix for this issue will be in the next release.
