### ISSUE TITLE
Duplicate judging numbers -scorpion.brewcompetition.com

### ISSUE THREAD

**Issue by huibertsp** [geoffhumphrey/brewcompetitiononlineentry#559]
When labeling bottles we noticed duplicate judge numbers:
+ Entry 18-002 Entry # 7 and # 25. 
+ Entry 29-001 Entry # 26 and # 39.

Anren't these intended to be uniq and unknown to judges that have entries?

**Comment by huibertsp** [comment]
Maybe also add a button to check for duplicate entry and judge numbers as a verification that there is no dupe?

**Comment by geoffhumphrey** [comment]
There is a way to "regenerate" judging numbers via Admin > Entry Sorting. I'll noodle over how to prevent judging numbers from being duplicated - could be as easy as a check of the DB before assigning one. Stay tuned...

**Comment by huibertsp** [comment]
That checking feature would be greatly appreciated. We were a small comp
but found our error mid-way through the labeling process. At that point
some printed labels attached by the entrants were already removed.

I think at the time of judge entry number is assignment, you can run a
query that verifies whether the one you prepare to assign (i.e. reserved)
is not already taken. I understand that is an extra trip to the DB.
Alternately, you can create a new sequence number w/o the impression of
categories (nn-xxx)  that is incremental but not known to entrants to keep
it blind. Another method is to pick a random number from a range (say
2500-3500) and verify that it has not been applied before at the time of
assignment. I understand the challenge and it takes a little verification
to ensure uniqueness.

**Comment by geoffhumphrey** [comment]
For 2.1.0, the entire judging number schema will be reworked to assign a completely random, unique 6 digit judging number for each entry (a DB check will verify if the generated number has been used prior). If a comp is using the [barcode entry method](http://brewcompetition.com/barcode-check-in) to assign judging numbers, the random number will, of course, be overridden by the scanned judging number. 

This new methodology will also help to keep some anonymity for scanned judging scoresheets with the planned integration of that functionality. See issue #193.
