### ISSUE TITLE
Entries not showing on pull sheets - http://scorpion.brewcompetition.com/

### ISSUE THREAD

**Issue by huibertsp** [geoffhumphrey/brewcompetitiononlineentry#560]
I have 2 entries not showing in my Pull sheets by Table for Judge numbers

+ Table 1 entry 29-001 (29a Fruit beer)
+ Table 2 entry 09-002 (9C Doppelbock)

why was the pull sheet incorrect?

**Comment by geoffhumphrey** [comment]
All entries have to be marked as both paid and received to show on pullsheets. Is this the case?

**Comment by huibertsp** [comment]
that was the case, correct. The situation has not changed on the website,
so you can review it yourself. Would you like me to make you an Admin?

**Comment by geoffhumphrey** [comment]
@huibertsp, This has to do with the judging number assignment issue you reported in #559 - the resolution proposed there should take care of any problems with duplicate judging numbers, thus allowing all entries to be showing on pullsheets...
