### ISSUE TITLE
Include open graph tags for social media

### ISSUE THREAD

**Issue by anigeluk** [geoffhumphrey/brewcompetitiononlineentry#561]
With social media becoming more and more important to homebrewers and competitions, it would be useful if open graph tags were included, potentially with the option under website preferences or somewhere else, to select a different image, title and description for when competitions are shared on social media.

I'm happy to take this on and put in a pull request if you are cool with that.

**Comment by geoffhumphrey** [comment]
Absolutely! Any help and contributions are very much appreciated @anigeluk!

**Comment by anigeluk** [comment]
Closing issue as resolved by merged PR #575
