### ISSUE TITLE
Missing Participants and Entries

### ISSUE THREAD

**Issue by dducrest** [geoffhumphrey/brewcompetitiononlineentry#563]
My SAS site is missing an participant and his two entries.
He was able to pay and print labels, but I see no record of him in the system.

I haven't deleted any of the participants outside of a test acccount that I created in December. 
I have created a new partcipant with the same email as his previous account and filed two new entries.

I can't reproduce the bug and I'm a little scared to at the minute since I'm 6 days out from my competition. So I'm just reporting in the hope that you can find a trend in other bug reports.

Cheers.

**Comment by huibertsp** [comment]
I was missing entry #9 at http://scorpion.brewcompetition.com/ where the entrant had printed a label that said entry #9. I wondered whether the entrant created the entry earlier, printed the label, and then deleted the entry but forgot about or something...

**Comment by dducrest** [comment]
Just to clarify, both my participant and his entries disappeared. I don't think participants are able to delete themselves.

**Comment by geoffhumphrey** [comment]
@dducrest, any further issues?
