### ISSUE TITLE
Category 9A requires special ingredients

### ISSUE THREAD

**Issue by oshc** [geoffhumphrey/brewcompetitiononlineentry#565]
I have an entrant trying to enter a beer into category 9A. It says it requires specifications to be listed but no fields come up to enter them into. This results in the entry being unconfirmed. Because it is a standard category It cannot be edited.

**Comment by geoffhumphrey** [comment]
@oshc, I confirmed that the special ingredients does not "take" when first adding a 9A entry. It will take if editing, however. When accessing the entry for editing, I also confirmed that the special ingredients field does not appear after the page loads. However, if you select another style and then reselect 9A, the field will appear. 

I'll get this in the queue for a bug fix. Thanks for reporting.
