### ISSUE TITLE
Program halts if email entered has no dot

### ISSUE THREAD

**Issue by rmsrosa** [geoffhumphrey/brewcompetitiononlineentry#566]
Just to make sure, this concerns version 2.0.1.

I am adapting the code to my own needs and I was going crazy that the program will halt with a blank page when I was testing registering new users. I couldn't find any error in what I changed in the code. I eventually found that the bug is in the original code. The reason for the problem is that I was typing emails without any dots, like <john@doe>, instead of say <john@doe.com> (I just testing and wanted to enter the least amount of information I could). I tried this in the original 2.0.1 version and had the same problem.

The registration form checks whether there is "@" in the email, but not ".". That shouldn't be a problem if it weren't for line 145 in includes/process/process_users_register.inc.php: 

      if ((strstr($username,'@')) && (strstr($username,'.'))) {

Since there is no dot in the email, the code would just halt.

The code in includes/ajax_functions.inc.php should check whether there is a dot in the email or line 145 should avoid the possibility of not having a dot

Ricardo

**Comment by geoffhumphrey** [comment]
@rmsrosa, thanks for reporting this. The code you suggest will be integrated into the next version.

**Comment by rmsrosa** [comment]
Great! Thanks! I am glad to help!

**Comment by XeonNAS** [comment]
Instead of attempting to code validation should something using the validation filters be used? Not used this function myself, but it looks like it might be pretty useful for email validation.
 https://secure.php.net/manual/en/filter.filters.validate.php

**Comment by rmsrosa** [comment]
I looked at the link provided by XeonNAS and it seems there is some purpose in allowing email addresses without a dot. So my solution was to change all the instances of the conditional

	if ((strstr($username,'@')) && (strstr($username,'.'))) {

in "includes/process/process_users_setup.inc.php", "includes/process/process_users_register.inc.php", and "includes/process/process_users.inc.php" by just
	if (strstr($username,'@')) {

It seems to work fine.

**Comment by geoffhumphrey** [comment]
Thanks for your report. A fix for this issue will be in the next release.
