### ISSUE TITLE
Name labels not printing

### ISSUE THREAD

**Issue by HillbillySasquatch** [geoffhumphrey/brewcompetitiononlineentry#568]
The link under the namebadge print function redirects to the admin dashboard. It does not offer a print function.

Link points to here on my site:
http://thirstyorangebrewoff.brewcomp.com/index.php?section=admin#

**Comment by geoffhumphrey** [comment]
Verified. Since your installation is hosted, the fix has been implemented and is working correctly.

Thanks for your report. A fix for this issue will be in the next release.
