### ISSUE TITLE
Limit of entries per entrant not enforced

### ISSUE THREAD

**Issue by rmsrosa** [geoffhumphrey/brewcompetitiononlineentry#569]
I am using version 2.0.1. For a test, I set the limit per entrant to 2 (the limit per style is 1 and the total limit of entries was set to 8).

When I reach two entries for a given entrant, the sidebar message "You have reached the limit of two (2) entries per participant in this competition." appears, but the icon "+Add an Entry" still shows. I click the icon, add the entry and the systems accepts it. I keep doing it until I reach 8 total entries and then the "+Add an Entry" icon is not visible anymore.

I debugged the code, especially the file includes/process/process_brewing.inc.php, and the conditional in line 30 is met and the lines of code inside the conditional are executed, but then the script continues after the conditional and the entry is finally included. My fix was to add an "exit();" line at the end of the lines inside the conditional:

				if ($row_brews['count'] >= $row_limits['prefsUserEntryLimit']) {
					$insertGoTo = $base_url."index.php?section=list&msg=8";
					$pattern = array('\'', '"');
					$insertGoTo = str_replace($pattern, "", $insertGoTo); 
					header(sprintf("Location: %s", stripslashes($insertGoTo)));
					exit();
				}

I don't known whether this is the best solution. The best actually would be for the icon "+Add an Entry" not to be visible and the limit of entries for a given entrant is met. I will look into that, if I have the time (the competition registration perior starts soon).

**Comment by mccarltone** [comment]
We're having this issue as well over at http://waze.brewcompetition.com/.

**Comment by rmsrosa** [comment]
Well, the fix I found is not good. With the exit() at the end of the conditional, the entrant is not able to edit an entry if it has reached the limit of entries. I need to find another way around.

**Comment by rmsrosa** [comment]
I changed the condition to check whether the actions is to "add" an entry or not, and so far it is working as it should. Hopefully I didn't mess up with anything else:

				if (($row_brews['count'] >= $row_limits['prefsUserEntryLimit']) && ($action == "add")) {
					$insertGoTo = $base_url."index.php?section=list&msg=8";
					$pattern = array('\'', '"');
					$insertGoTo = str_replace($pattern, "", $insertGoTo); 
					header(sprintf("Location: %s", stripslashes($insertGoTo)));
					exit();
				}

**Comment by geoffhumphrey** [comment]
A fix for this issue will be in 2.1.0.
