### ISSUE TITLE
No locations preferences available for judges...can't assign judges!

### ISSUE THREAD

**Issue by SaltCityBrew** [geoffhumphrey/brewcompetitiononlineentry#571]
Same issue as:

https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/490

Sorry to post again, just hoping to find a resolution ASAP since our event is in the morning and I don't want to have to do all of the judge assignments by hand. We reloaded a fresh download of 1.3.2 and still can't designate a location for judges, and all judges show up as "no availability defined".

**Comment by SaltCityBrew** [comment]
OK, I added a second location name, and now they are both populating on the personal info pages...so that appears to be the fix.

**Comment by geoffhumphrey** [comment]
Please see my comment on issue #490 for an update. Bottom line, 2.1.0 will have a fix this issue...
