### ISSUE TITLE
Mead/Cider Strength, Carb, Sweetness Missing from Pullsheets

### ISSUE THREAD

**Issue by geoffhumphrey** [geoffhumphrey/brewcompetitiononlineentry#572]
Required information is missing from pullsheets for mead and cider entries. A bug was introduced in the 2.0.0 programming that precluded this information from being populated.

A fix has been implemented in the /output/pullsheets.output.php file, contained in the latest commit.

**Comment by BrewDrinkRepeat** [comment]
I'm a little confused by the tags: does this bug exist in 2.0.1?

**Comment by geoffhumphrey** [comment]
Yes, this was reported after 2.0.1's release.
