### ISSUE TITLE
Participants Lost Passwords

### ISSUE THREAD

**Issue by oshc** [geoffhumphrey/brewcompetitiononlineentry#576]
Hi Geoff,

I have had a few participants lose their passwords. When I try to edit their record there is no place to reset their password. The only way I have found to do this is to delete their account and force them to recreate it. This is not a good thing when they have multiple entries that have already been checked in and marked paid. Is there a way you can add the ability to edit the participants password to the edit participant record screen?

Thanks.

Joshua Fogg

**Comment by geoffhumphrey** [comment]
2.1.0 will have a feature that will allow Admins to reset entrant account passwords. The present version does not have such a feature as of yet. See Issue #553. Unfortunately, at present, it's a matter of accessing the DB manually, locating the appropriate record in the "users" table, and sending the user their recovery question and answer. Not the most optimal of processes.

For hosted accounts, I'm able to do this; I would not delete any user accounts...

**Comment by joeleaux** [comment]
i need to recover lost passwords as well ... i'm hosting my own registration system.

Bayou Beer Fest

**Comment by geoffhumphrey** [comment]
Versions 2.1.0, 2.1.1 and the latest commit provide admins with the ability to change user passwords.

**Comment by joeleaux** [comment]
OK, upgraded and now i'm greeted with:


Notice: Use of undefined constant â€œbrewdatâ€ - assumed 'â€œbrewdatâ€' in /home/content/36/10504636/html/bayoubeerfest/brewdat/site/config.php on line 45

Warning: mysqli::mysqli() [mysqli.mysqli]: (42000/1044): Access denied for user 'brewdat'@'%' to database 'â€œbrewdatâ€' in /home/content/36/10504636/html/bayoubeerfest/brewdat/site/config.php on line 51

Notice: Use of undefined constant â€œ - assumed 'â€œ' in /home/content/36/10504636/html/bayoubeerfest/brewdat/site/config.php on line 148

Notice: Use of undefined constant brewdatâ€œ - assumed 'brewdatâ€œ' in /home/content/36/10504636/html/bayoubeerfest/brewdat/site/config.php on line 148

Warning: Division by zero in /home/content/36/10504636/html/bayoubeerfest/brewdat/site/config.php on line 148

Notice: Use of undefined constant â€œbrewdatâ€ - assumed 'â€œbrewdatâ€' in /home/content/36/10504636/html/bayoubeerfest/brewdat/site/config.php on line 45

Warning: mysqli::mysqli() [mysqli.mysqli]: (42000/1044): Access denied for user 'brewdat'@'%' to database 'â€œbrewdatâ€' in /home/content/36/10504636/html/bayoubeerfest/brewdat/site/config.php on line 51

Notice: Use of undefined constant â€œ - assumed 'â€œ' in /home/content/36/10504636/html/bayoubeerfest/brewdat/site/config.php on line 148

Notice: Use of undefined constant brewdatâ€œ - assumed 'brewdatâ€œ' in /home/content/36/10504636/html/bayoubeerfest/brewdat/site/config.php on line 148

Warning: Division by zero in /home/content/36/10504636/html/bayoubeerfest/brewdat/site/config.php on line 148

Warning: mysqli_select_db() [function.mysqli-select-db]: Couldn't fetch mysqli in /home/content/36/10504636/html/bayoubeerfest/brewdat/lib/preflight.lib.php on line 5

Warning: mysqli_query() [function.mysqli-query]: Couldn't fetch mysqli in /home/content/36/10504636/html/bayoubeerfest/brewdat/lib/preflight.lib.php on line 8

Warning: mysqli_error() [function.mysqli-error]: Couldn't fetch mysqli in /home/content/36/10504636/html/bayoubeerfest/brewdat/lib/preflight.lib.php on line 8

**Comment by joeleaux** [comment]
Please help, i had this running and then i announce it's live for registration, i update it so i can email people their passwords and now it doesn't work!

**Comment by joeleaux** [comment]
Now i am at this stage:

 The update script cannot run. The version.inc.php file does not exist in the /includes/ directory of your BCOE&M installation.
BCOE&M 2.1.1 Update
Currently your installation's base URL is . If this is incorrect, you will need to edit the $base_url variable in the config.php file, located in your installation's /sites/ directory.

Make sure the version.inc.php file from your previous installation is in your current installation's /includes/ directory. The update script utilizes this file to determine which database tables to update and install.

If you do not have the version.inc.php file from your previous version, create a new document locally, name it version.inc.php and copy/paste the following single line of code into the new document. Don't forget to change the version number!

<?php $version = "1.2.0.4"; ?>
Save the file, upload to your installation's /includes/ directory, and run this script again.

**Comment by geoffhumphrey** [comment]
@joeleaux, my advice for now is to back out the update for the interim until I can track down where the issue is with the update script. If that's not an option, you can do this:
* Keep the 2.1.1 code intact
* Backup your current database.
* Install the basic DB structure with dummy data by importing the /sql/bcoem_baseline_2.1.X.sql file 
    * Be sure to read the instructions at the top of the file first
    * Change the *baseline_* prefix throughout the document to the prefix used in your old DB or eliminate it altogether if no prefix used in the old DB - for example:
```
DROP TABLE IF EXISTS `baseline_archive`;
CREATE TABLE IF NOT EXISTS `baseline_archive` (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `archiveUserTableName` varchar(255) DEFAULT NULL,
  `archiveBrewerTableName` varchar(255) DEFAULT NULL,
  `archiveBrewingTableName` varchar(255) DEFAULT NULL,
  `archiveSuffix` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

Would become...

DROP TABLE IF EXISTS `newprefix_archive`;
CREATE TABLE IF NOT EXISTS `newprefix_archive` (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `archiveUserTableName` varchar(255) DEFAULT NULL,
  `archiveBrewerTableName` varchar(255) DEFAULT NULL,
  `archiveBrewingTableName` varchar(255) DEFAULT NULL,
  `archiveSuffix` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
```
* Copy over the data in these tables from your backed up DB to the new DB:
    * brewer
    * contest_info
    * drop_off
    * special_best_info
    * sponsors
    * users
* Edit the paths.php file and comment out line 42 and "uncomment" line 41:
```
//Error reporting
error_reporting(0);	// comment out to debug
//error_reporting(E_ALL); // uncomment to debug 
```

**Comment by joeleaux** [comment]
i’m at a loss here … i copied the new contents from the update to my server, so all the old files are overwritten. My database is still intact. Help!


Joel Ohmer  |  Bayou Beer Society





www.bayoubeersociety.org <http://www.bayoubeersociety.org/>
www.facebook.com/BayouBeerSociety <http://www.facebook.com/BayouBeerSociety>
985.438.0169
info@bayoubeersociety.org <mailto:info@bayoubeersociety.org>

**Comment by geoffhumphrey** [comment]
You can "backout" by:
* Restoring your DB to its previous state from a backup - your webhost should have this ability and probably took a snapshot of your DB recently. Check their help files. If this isn't an option, then you'll need to start with a fresh database.
* [Downloading 2.0.1](https://github.com/geoffhumphrey/brewcompetitiononlineentry/releases/tag/v2.0.1), configuring the config.php file for your environment, and re-uploading to your server.
