### ISSUE TITLE
password recovery failure

### ISSUE THREAD

**Issue by huibertsp** [geoffhumphrey/brewcompetitiononlineentry#578]
I had a user that had an account from previous year. That person remembered the email/username correctly but could not remember password. When that user tried to reset the password it failed the answers to the security questions were invalid. 

As an admin, I haven't tried the password reset through Security questions but I was looking to push a temp password as an Admin but could not find that option. This would be a good feature to have as Admin or Staff as users can be clumsy.

**Comment by geoffhumphrey** [comment]
2.1.0 will have a feature that will allow Admins to reset entrant account passwords. The present version does not have such a feature as of yet. See Issue #553. Unfortunately, at present, it's a matter of accessing the DB manually, locating the appropriate record in the "users" table, and sending the user their recovery question and answer. Not the most optimal of processes
