### ISSUE TITLE
Saving website preferences results in failure.

### ISSUE THREAD

**Issue by kstec** [geoffhumphrey/brewcompetitiononlineentry#579]
![image](https://cloud.githubusercontent.com/assets/216067/14442704/c423f440-0000-11e6-8ad1-5e218e0b19d4.png)

Making no changes to the form and clicking Update results in the following error:

`Incorrect integer value: 'on' for column 'prefsWinnerMethod' at row 1`

I was able to get it working by manually adding a `value="1"` attribute to the radio button I wanted to pick using the webkit dev tools.

I am using the latest packaged release (2.0.1)

**Comment by geoffhumphrey** [comment]
Thanks for reporting. This will be included in the 2.1.0 release, slated for later this month.
