### ISSUE TITLE
Entry for custom categories is confusing and poorly designed

### ISSUE THREAD

**Issue by kstec** [geoffhumphrey/brewcompetitiononlineentry#580]
![image](https://cloud.githubusercontent.com/assets/216067/14442893/c8f47a0c-0001-11e6-8ab1-2840e43c68a1.png)

Since we already know the style that is being entered (35A in this case), why require another click to display the custom style attributes and requirements? We also already know what specific requirements are required, as well as the style applicable, so why list them all?

Additionally, having `<input type="text" />` is inadequate for most applications of this I can think of. I suggest using `<textarea />`. A 50 character limit is pretty low IMO.

## Here is my suggestion:

Assuming this is the style:
![image](https://cloud.githubusercontent.com/assets/216067/14443061/7fbe6b62-0002-11e6-9150-07f691d963a1.png)

This is roughly how I would design it:

![image](https://cloud.githubusercontent.com/assets/216067/14443517/6277ea80-0005-11e6-84fd-043a0dc335ad.png)

You could also have three separate sections of the form to really stress what the fields are for and avoid all of the red warnings everywhere reiterating what the section is for. Perhaps using bootstrap's `page-header` css class?

**Comment by kstec** [comment]
That "Judges will not know the name of your entry" bit could be put up with the entry name for further de-cluttering.

**Comment by geoffhumphrey** [comment]
A bit of clean-up will be incorporated into 2.1.0. It's all about finding a balance of communicating the right information to entrants so that organizers have necessary data to facilitate effective judging of entries.

**Comment by geoffhumphrey** [comment]
The character limit of special ingredients data entry is set via preferences.

**Comment by kstec** [comment]
>A bit of clean-up will be incorporated into 2.1.0. It's all about finding a balance of communicating the right information to entrants so that organizers have necessary, and more importantly, correct, data to facilitate effective judging of entries.

Completely agree. However, I am more talking about information that will never be relevant to anyone. Why show a link for 07C requirements in a popup when I already picked 35A as the style I am entering? Why use the popup at all when we could just display requirements inline? Why display mead stuff here when my competition doesn't even have a mead category available? I hope you see what I am getting at.

>The character limit of special ingredients data entry is set via preferences.

Ah, I missed that. Thanks. I still feel that field should be a `<textarea>` though so better formatting is allowed.

**Comment by geoffhumphrey** [comment]
Working on a better solution now. Will be in place for next release.

**Comment by geoffhumphrey** [comment]
Been giving this a go recently and have it worked out to provide the necessary entry requirement information dynamically based upon the style chosen from the dropdown. Essentially it was a complete re-work of the backend code and implementation of jQuery html replacing functions to populate the entry requirements information for the chosen style from the dropdown. 

Here's a screenshot of the work in progress:
![screen shot 2016-04-15 at 3 03 46 pm](https://cloud.githubusercontent.com/assets/5216502/14574962/e67ead3c-031b-11e6-8bfb-eeb239cb22e4.png)

Note that the new dynamic text features a clickable link for more style information. This will bring up a modal for the more diligent entrants...
![screen shot 2016-04-15 at 3 04 08 pm](https://cloud.githubusercontent.com/assets/5216502/14574987/12dedbea-031c-11e6-8a03-c223fb00c3a6.png)

**Comment by kstec** [comment]
Excellent. I really appreciate the time and attention to this. It will make running customized competitions much easier!

**Comment by geoffhumphrey** [comment]
Examples of finalized version are below.

**Kellerbier (does not require special ingredients, but does require color):**
![screen shot 2016-04-22 at 10 04 00 am](https://cloud.githubusercontent.com/assets/5216502/14749225/8c9fe7e4-087b-11e6-8e67-2968c301da9c.png)

**Specialty IPA (requires a type to be specified, strength):**
![screen shot 2016-04-22 at 10 04 52 am](https://cloud.githubusercontent.com/assets/5216502/14749295/ef0961e4-087b-11e6-89ad-e28fa274d9ee.png)

**Saison (requires strength and color only):**
![screen shot 2016-04-22 at 10 05 32 am](https://cloud.githubusercontent.com/assets/5216502/14749310/09ee31ec-087c-11e6-9e29-35596daf4a7a.png)

**Beer with special ingredients required:**
![screen shot 2016-04-22 at 10 06 29 am](https://cloud.githubusercontent.com/assets/5216502/14749318/14c22c7c-087c-11e6-9aa3-84c2d946fafb.png)

**General cider (no special ingredients required):**
![screen shot 2016-04-22 at 11 22 10 am](https://cloud.githubusercontent.com/assets/5216502/14749423/7c11aa4c-087c-11e6-8d63-399858466bd7.png)

**Cider with special ingredients required:**
![screen shot 2016-04-22 at 11 23 07 am](https://cloud.githubusercontent.com/assets/5216502/14749443/9f2ed70c-087c-11e6-8d4d-be18d53b9b2f.png)

**General mead (no special ingredients required):**
![screen shot 2016-04-22 at 11 24 41 am](https://cloud.githubusercontent.com/assets/5216502/14749471/d521fa56-087c-11e6-914a-980c7c2661fc.png)

**Mead with special ingredients required**
![screen shot 2016-04-22 at 11 26 38 am](https://cloud.githubusercontent.com/assets/5216502/14749523/1ad0f4da-087d-11e6-9367-42d674895b7f.png)

With modern browsers, both mobile and desktop, users will not be able to submit the form without entering the required information:
![screen shot 2016-04-22 at 11 25 49 am](https://cloud.githubusercontent.com/assets/5216502/14749498/fb74268e-087c-11e6-8fac-15aa9f1fa194.png)
