### ISSUE TITLE
NHC Edition: Score Entry page does not match the pullsheet order

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#581]
This is an old issue (previously reported) that persists in the current NHC version of BCOEMS. When going to enter scores into the system, the order of the entries on-screen cannot be made to match the order on the pullsheet. This significantly increases the amount of time it takes to enter all the scores, as I cannot simply type-tab-type-tab-type-tab without constantly looking up at the screen and double-checking that I'm entering the score in the correct place.

Now here's the crazy part: out of 31 tables, two of them DID appear in the same order as on the pullsheet. But the rest did not; I had to sort them numerically by judging number and then manually skip around the list to enter the scores. Very cumbersome.

**Comment by geoffhumphrey** [comment]
@BrewDrinkRepeat, the NHC codebase has been significantly altered by the folks at the AHA for their own purposes. It's based on code that is at least three releases back. Thus, it's not supported here...

My best advice is to forward your issues to the AHA directly or to post the problems you encounter to the AHA forum area set up for NHC staff.

**Comment by BrewDrinkRepeat** [comment]
Ahhh, I see... I knew it was based on an older version, didn't realize they did all of the customization on their end. I'll forward this along to them for next year (as I will be one of the organizers for the Philadelphia judging center again).

In the meantime, we're going to use the 2.0.1 for the first time next month. Does the score entry screen now match the pullsheets in that version?

**Comment by ercousin** [comment]
I'm seeing something similar.

The pullsheets that were printed aren't in any order specifically, other than lower number styles first.

For example I see the following order for specialty cider table.

(Judging Number / Entry Number / Style)
39-006 / 30 / C2B
39-002 / 5 / C2B
39-004 / 11 / C2B
39-008 / 52 / C2B

Running 2.0.1

**Comment by geoffhumphrey** [comment]
For 2.1.0, the judging numbers that are generated by the system will be standardized to six digits and completely randomized (for a variety of reasons, most important among them is to make sure no duplicates are presents, but also for reasons such as the OP's). 

Comps using the barcode and new QR code (2.1.0) check-in systems can override this random judging number by scanning/entering a new one in during the check-in process (see http://brewcompetition.com/barcode-check-in for more).

The sort order for both pullsheets and the score input screen will be style/substyle then judging number.

Pullsheet:
![screen shot 2016-04-28 at 2 33 43 pm](https://cloud.githubusercontent.com/assets/5216502/14900559/55daf870-0d4e-11e6-8f31-b23d49250cbf.png)

Score Entry Screen:
![screen shot 2016-04-28 at 2 33 16 pm](https://cloud.githubusercontent.com/assets/5216502/14900563/5a9054dc-0d4e-11e6-857b-f329a8b5c580.png)
