### ISSUE TITLE
NHC Edition: Participant Summary Cards Do Not Print In Alphabetical Order

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#582]
So, once you print out several hundred of them, you then have to manually alphabetize them before you can proceed to stuffing envelopes, etc.

**Comment by geoffhumphrey** [comment]
The NHC codebase has been significantly altered by the folks at the AHA for their own purposes. It's based on code that is at least three releases back. Thus, it's not supported here...

My best advice is to forward your issues to the AHA directly or to post the problems you encounter to the AHA forum area set up for NHC staff.
