### ISSUE TITLE
SQLite Instead of MySQL?

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#583]
Just a though for a future version: have you considered switching to using SQLite for the database instead of MySQL? I'm not sure how many people have web hosting that doesn't include MySQL support or how many emails you get from folks having problems getting MySQL set up to run BCOEMS, but it would eliminate the need for that and bring the database into a simple single file.

**Comment by csaunders** [comment]
Still requires having sqlite installed on the server, being able to write to the file from a web server process, and dealing with concurrent updates.

This application does a fair amount of concurrent writing and this can cause some serious issues when using SQLite. I love SQLite, but it's an inappropriate tool for this kind of application.
