### ISSUE TITLE
Best Of Show

### ISSUE THREAD

**Issue by oshc** [geoffhumphrey/brewcompetitiononlineentry#584]
Hi Geoff,

We are having an issue giving places to Best of Show winners.

In competition preferences, manage styles, when I select the BOS method, 1st, 2nd, & 3rd placse It pulls in all the first second and third places from each category instead of allowing me to give first second and third place awards. No matter which method I choose I can still only award first place. It seems like you should be able to select both options, which entries from each category to pull in and how many place awards you want to give.

**Comment by geoffhumphrey** [comment]
I just checked your competition organization preferences (Admin > Preferences > Competition Organization) and you've specified only 1 place for all for all style types. I changed that value to 3...
![screen shot 2016-04-12 at 10 53 49 am](https://cloud.githubusercontent.com/assets/5216502/14468498/1db99c52-009d-11e6-93db-1ffc67a408d5.png)

Now you're able to put in 1st, 2nd, and 3rd place for the BOS eligible entries.
![screen shot 2016-04-12 at 10 54 18 am](https://cloud.githubusercontent.com/assets/5216502/14468511/2616b5a6-009d-11e6-8fa6-c72c86e0973e.png)

**Comment by oshc** [comment]
OK thanks, my bad for not looking!

Cheers!

Josh
Rhode Island Brewing Society
https://ribrewingsociety.com
