### ISSUE TITLE
Participants page suddenly not working?

### ISSUE THREAD

**Issue by PeterSteinberg** [geoffhumphrey/brewcompetitiononlineentry#585]
I tried to look at participants on my competition and just get a blank page.
    http://mhtg.brewcompetition.com/index.php?section=admin&go=participants

Similarly with the filter for judges & stewards.

The dashboard shows 34 participants.

It's happening in both Chrome and Firefox.

**Comment by geoffhumphrey** [comment]
@PeterSteinberg, not sure what happened there, but I copied the code fresh to your hosting account. All are working now. May have been an include that was corrupt or missing...
