### ISSUE TITLE
Competition preferences not being modified.

### ISSUE THREAD

**Issue by aresx130** [geoffhumphrey/brewcompetitiononlineentry#586]
I am using a fresh install of 2.0.1 with a fresh mySQL database and I have noticed that my changes on the competition preferences page are not being pushed to the database. I know the software can see the database as the setup went flawless and managed to initialize the database with no problem.

**Comment by geoffhumphrey** [comment]
@aresx130, is this still an issue for you?

**Comment by aresx130** [comment]
Fresh reinstall fixed it, not sure what was causing the issue the first time.
