### ISSUE TITLE
login problems and forgot password says user answer does not match

### ISSUE THREAD

**Issue by tmccammon** [geoffhumphrey/brewcompetitiononlineentry#587]
Hello, I have installed and setup the database and user accounts are being created in the DB. I believe that the password is check is succeeding because it gives a different message if I use the wrong password. Forgot my password just says user answer does not match even though it is correct and matches what is in the DB.

http://bcoem_2_0_1.brewmaui.com/

I tried to reset up everything again using a prefix for the second attempt and this has the same results.

**Comment by geoffhumphrey** [comment]
Hello @tmccammon. Thanks for reporting. 

There have been some issues with this reported... I would suggest downloading and installing the latest 2.0.1 commit from GitHub here: https://github.com/geoffhumphrey/brewcompetitiononlineentry/archive/master.zip 

It may help...

**Comment by geoffhumphrey** [comment]
The next version will feature the ability for Top-Level Admins to reset user account passwords. That version is slated for release in the upcoming week after testing. Upgrading will not compromise any data in the DB since you are now in the midst of accepting accounts and entries.

**Comment by tmccammon** [comment]
This error is happening for all accounts I can't access the site with admin
or regular users.

On Sun, Apr 17, 2016 at 10:17 AM, geoffhumphrey <notifications@github.com>
wrote:

> The next version will feature the ability for Top-Level Admins to reset
> user account passwords. That version is slated for release in the upcoming
> week after testing. Upgrading will not compromise any data in the DB since
> you are now in the midst of accepting accounts and entries.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/587#issuecomment-211107304>
>



-- 
808-283-9453
tmccammon@gmail.com

**Comment by tmccammon** [comment]
If I try with an admin user this is the error. "You must log in and have
admin privileges to access the Brew Maui 2016 administration functions."

With a regular user I am getting "Please log in to access your account."

I downloaded the -master version and it still gives the same error. I was
already using 2.0.1 from the main site not the -master.zip link you
provided. Anyway I d/l'd the latest and same results.

Thanks!!! Really appreciate it.

Accounts are in the DB I can see them just can't sign in using them.



On Sun, Apr 17, 2016 at 10:36 AM, Thor Mccammon <tmccammon@gmail.com> wrote:

> This error is happening for all accounts I can't access the site with
> admin or regular users.
>
> On Sun, Apr 17, 2016 at 10:17 AM, geoffhumphrey <notifications@github.com>
> wrote:
>
>> The next version will feature the ability for Top-Level Admins to reset
>> user account passwords. That version is slated for release in the upcoming
>> week after testing. Upgrading will not compromise any data in the DB since
>> you are now in the midst of accepting accounts and entries.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/587#issuecomment-211107304>
>>
>
>
>
> --
> 808-283-9453
> tmccammon@gmail.com
>



-- 
808-283-9453
tmccammon@gmail.com

**Comment by tmccammon** [comment]
here is my config file


$hostname = "thorman.fatcowmysql.com";
$username = "brewmaui";
$password = "Ilike2drinkhoppybeer";
$database = "bcoem_2_0_1";
$connection = mysql_connect($hostname, $username, $password) or
trigger_error(mysql_error());
$brewing = $connection;
$images_dir = dirname( __FILE__ );

$prefix = "comp2016_";
//also tried $prefix = "";

$setup_free_access = FALSE;
$sub_directory = "";
//also tried $sub_directory = "/bcoem_2_0_1"; and edited the .htaccess file
at the same time

$base_url = "http://".$_SERVER['SERVER_NAME'].$sub_directory."/";
$server_root = $_SERVER['DOCUMENT_ROOT'];
//$server_root = $_SERVER['SUBDOMAIN_DOCUMENT_ROOT'];

?>

On Sun, Apr 17, 2016 at 10:54 AM, Thor Mccammon <tmccammon@gmail.com> wrote:

> If I try with an admin user this is the error. "You must log in and have
> admin privileges to access the Brew Maui 2016 administration functions."
>
> With a regular user I am getting "Please log in to access your account."
>
> I downloaded the -master version and it still gives the same error. I was
> already using 2.0.1 from the main site not the -master.zip link you
> provided. Anyway I d/l'd the latest and same results.
>
> Thanks!!! Really appreciate it.
>
> Accounts are in the DB I can see them just can't sign in using them.
>
>
>
> On Sun, Apr 17, 2016 at 10:36 AM, Thor Mccammon <tmccammon@gmail.com>
> wrote:
>
>> This error is happening for all accounts I can't access the site with
>> admin or regular users.
>>
>> On Sun, Apr 17, 2016 at 10:17 AM, geoffhumphrey <notifications@github.com
>> > wrote:
>>
>>> The next version will feature the ability for Top-Level Admins to reset
>>> user account passwords. That version is slated for release in the upcoming
>>> week after testing. Upgrading will not compromise any data in the DB since
>>> you are now in the midst of accepting accounts and entries.
>>>
>>> —
>>> You are receiving this because you were mentioned.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/587#issuecomment-211107304>
>>>
>>
>>
>>
>> --
>> 808-283-9453
>> tmccammon@gmail.com
>>
>
>
>
> --
> 808-283-9453
> tmccammon@gmail.com
>



-- 
808-283-9453
tmccammon@gmail.com

**Comment by geoffhumphrey** [comment]
Thor,

From what you're describing and what I experienced trying to establish an account, my suspicion is that there's an environment issue that is preventing access to the DB for some reason. If possible, please  post your server log error file from the site root folder and the /process/ directory. Maybe those will shed some light on the source of the issue. 

Cheers,

Geoff

**Comment by tmccammon** [comment]
I do see the accounts getting created in the DB. I looked everywhere and
can't find the error log file. I will keep looking for it.

[image: Inline image 1]



On Mon, Apr 18, 2016 at 2:58 AM, geoffhumphrey <notifications@github.com>
wrote:

> Thor,
>
> From what you're describing and what I experienced trying to establish an
> account, my suspicion is that there's an environment issue that is
> preventing access to the DB for some reason. If possible, please post your
> server log error file from the site root folder and the /process/
> directory. Maybe those will shed some light on the source of the issue.
>
> Cheers,
>
> Geoff
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/587#issuecomment-211370063>
>



-- 
808-283-9453
tmccammon@gmail.com

**Comment by tmccammon** [comment]
I just noticed that the email user question function is not working. I am
not getting an email when I request one be sent.

On Mon, Apr 18, 2016 at 8:56 AM, Thor Mccammon <tmccammon@gmail.com> wrote:

> I do see the accounts getting created in the DB. I looked everywhere and
> can't find the error log file. I will keep looking for it.
>
> [image: Inline image 1]
>
>
>
> On Mon, Apr 18, 2016 at 2:58 AM, geoffhumphrey <notifications@github.com>
> wrote:
>
>> Thor,
>>
>> From what you're describing and what I experienced trying to establish an
>> account, my suspicion is that there's an environment issue that is
>> preventing access to the DB for some reason. If possible, please post your
>> server log error file from the site root folder and the /process/
>> directory. Maybe those will shed some light on the source of the issue.
>>
>> Cheers,
>>
>> Geoff
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/587#issuecomment-211370063>
>>
>
>
>
> --
> 808-283-9453
> tmccammon@gmail.com
>



-- 
808-283-9453
tmccammon@gmail.com

**Comment by tmccammon** [comment]
It is generating a session ID cookie

[image: Inline image 1]

On Mon, Apr 18, 2016 at 9:42 AM, Thor Mccammon <tmccammon@gmail.com> wrote:

> I just noticed that the email user question function is not working. I am
> not getting an email when I request one be sent.
>
> On Mon, Apr 18, 2016 at 8:56 AM, Thor Mccammon <tmccammon@gmail.com>
> wrote:
>
>> I do see the accounts getting created in the DB. I looked everywhere and
>> can't find the error log file. I will keep looking for it.
>>
>> [image: Inline image 1]
>>
>>
>>
>> On Mon, Apr 18, 2016 at 2:58 AM, geoffhumphrey <notifications@github.com>
>> wrote:
>>
>>> Thor,
>>>
>>> From what you're describing and what I experienced trying to establish
>>> an account, my suspicion is that there's an environment issue that is
>>> preventing access to the DB for some reason. If possible, please post your
>>> server log error file from the site root folder and the /process/
>>> directory. Maybe those will shed some light on the source of the issue.
>>>
>>> Cheers,
>>>
>>> Geoff
>>>
>>> —
>>> You are receiving this because you were mentioned.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/587#issuecomment-211370063>
>>>
>>
>>
>>
>> --
>> 808-283-9453
>> tmccammon@gmail.com
>>
>
>
>
> --
> 808-283-9453
> tmccammon@gmail.com
>



-- 
808-283-9453
tmccammon@gmail.com
