### ISSUE TITLE
7C Kellerbier: Specific Type Field Not Showing to Admin and Not Printing on Special Ingredients Labels

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#589]
When editing a 7C Kellerbier entry as admin (to see any specialty description given) the field doesn't show up for certain styles. If I press the pencil icon on a 7C Kellerbier entry I cannot see any special description field, even though it is required for that style. If I go to see the entry label for that entry I can see the specialty description given.

Side note, is there a better way to see specialty description easier from the entries page rather than click on the edit button?

This may also be the case with 9A, 10C, etc.. Though I do have a 24C entered and I do see the field for that one.

Another issue, and the reason I noticed this is that when printing specialty labels, 7C doesn't print. I had to write this label manually...

![image](https://cloud.githubusercontent.com/assets/1551339/14805786/2bfe424a-0b3d-11e6-9926-c419df66b5c3.png)

**Comment by geoffhumphrey** [comment]
This will be fixed in 2.1.0. Please see #580.

**Comment by ercousin** [comment]
What about the lack of specifics label printed when printing specialty labels?

**Comment by geoffhumphrey** [comment]
Yes, that will be fixed as well.
