### ISSUE TITLE
Brewers Specifics Still Needs Tuning

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#590]
Following on from: https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/522

I've found that the red text isn't enough since it still says that the judges will get the information from this field. However I haven't found a way to print labels that contain this info....

I would like to propose:
- an option be added to disable this feature completely

AND
- a function be added in the Entry Sorting section to print bottle labels that contain the information from the Brewer's Specifics field (just like we print the bottle labels from the specialty field)

Right now entrants are being given the impression that the information in this field will be given to entrants when that is impossible for us to do as organizers other than manually transcribing it...

**Comment by geoffhumphrey** [comment]
Thanks for the suggestions. At present, the brewer's specifics info is only reported on pullsheets. A report and/or labels are easy additions. The option to disable involves a bit more work.

The add/edit entry function has been totally overhauled for 2.1.0 to be more user-friendly while making sure to get the right data out of the entrant as possible. This includes the Brewers Specifics field.

**Comment by ercousin** [comment]
I'm still seeing a lot of confusion over this new field even after the update to the required info.

It would really help cut down on the amount of confusion and support emails if we could just disable that "Brewers Specifics" field.
