### ISSUE TITLE
drop-off locations

### ISSUE THREAD

**Issue by PeterSteinberg** [geoffhumphrey/brewcompetitiononlineentry#591]
I've got multiple drop-off locations defined, but only one of them shows up on the user page:
  http://mhtg.brewcompetition.com/index.php?section=entry#drop

**Comment by geoffhumphrey** [comment]
Not sure what happened to prevent them all from showing. Just in case, I replaced files in your installation and things are looking OK now...

**Comment by PeterSteinberg** [comment]
Thanks!
