### ISSUE TITLE
Glitch in Dislikes List?

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#592]
I was assigning to judges to tables and saw that a judge showed up as red (for a table containing cats 1, 2, 3, 5, 7), however when I went to check their dislike list, it was empty...

This judge was quick added by me, so I wasn't expecting a dislike list to appear. I don't think they would have recovered their password and added dislikes...

![image](https://cloud.githubusercontent.com/assets/1551339/14831354/68af3380-0bc3-11e6-92d2-b20f338dca5b.png)

![image](https://cloud.githubusercontent.com/assets/1551339/14831368/752de106-0bc3-11e6-9b84-8895c8eefd36.png)

**Comment by geoffhumphrey** [comment]
@ercousin, I recreated your steps outlined above, and went through some other scenarios as well. Unfortunately, I couldn't recreate this issue. One thing good about the dislikes is that you can still assign someone to the table even though a sub-style is on their dislikes list, especially for those styles that would not pose a health threat to a judge (e.g., if they're allergic to something or other, don't assign them to specialty, etc...).

**Comment by ercousin** [comment]
I did end up overriding the dislike, since I remembered quick adding the judge, and that style was their strength. Still strange that dislikes were showing up when they weren't added in the profile...
