### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by Beakerboy** [geoffhumphrey/brewcompetitiononlineentry#594]
A user complained that he was unable to use the password reset feature in version 2.0.0. I looked in the database to verify that my security answer is what I expected it to be, and entered it in the correct input box. BCOEM retured the error, "Your verification question does not match what is in the database. Please try again."

I upgraded to 2.0.1 and the problem persists.

**Comment by geoffhumphrey** [comment]
Hello @Beakerboy, I've confirmed the issue and will investigate a fix. Thanks for reporting!

**Comment by geoffhumphrey** [comment]
The issue has been fixed in the latest commit; specifically in the following two files:

- /includes/forgot_password.inc.php
- /sections/login.sec.php

Thanks for your report. A fix for this issue will be in the next release.

**Comment by PeterSteinberg** [comment]
I'm getting similar reports from some of my users also.

Is there a way to get this fixed on my hosted site, or do I have to delete the users and have them recreate themselves?

**Comment by geoffhumphrey** [comment]
@PeterSteinberg, the latest commit code has been applied to all hosted sites as of this morning...

**Comment by PeterSteinberg** [comment]
Thanks; the last report was from 11:40 last night, so hopefully it’s working for him this morning.

Peter

**Comment by ercousin** [comment]
Is there anything special we need to do to get password recovery emails working? I've tried a few test accounts and reset password emails never go through...

**Comment by rgiaquinta** [comment]
I am having the same issue... password reset does not work.  We are using a self-hosted installation of 2.0.1.  Please advise... we're deep into the registration period.

I also noticed that, as an admin, if I look at the table of participants and click "change email address", the new window that opens contains the name/email of a different user than the one I clicked on.

**Comment by geoffhumphrey** [comment]
@ercousin - The recovery emails depend upon php_mail() - you will need to check your server environment to make sure that emails generated by PHP are able to be sent.

@rgiaquinta - version 2.1.3 features the ability for admins to reset passwords for users. 2.0.1 does not. The same issue applies for 2.0.1 that I mentioned above to @ercousin for your environment as well.

**Comment by rgiaquinta** [comment]
We upgraded to 2.1.3 and the two glitches are now fixed.  Thanks!
