### ISSUE TITLE
Users cannot edit entries

### ISSUE THREAD

**Issue by jodygrenert** [geoffhumphrey/brewcompetitiononlineentry#596]
- On my registration site at www.obw.brewcomp.com, users who have put in entries (including me) are not able to log in later and edit those entries. This happens on Chrome, Firefox and IE. The "Action"  column is showing, but the pencil and trash icons are not showing up there. 

- I'm able to change entries in my admin view, but I don't want to have to manually change beers for entrants -- this would be time-consuming

- FYI, I switched from the 2008 guidelines to 2015 guidelines after several entries had already come in. Can't remember if this issue was there before I switched.
-

**Comment by geoffhumphrey** [comment]
Jody, I've been digging through the code to find a reason for this, but I cannot find it. I'll keep looking. Apologies...

**Comment by jodygrenert** [comment]
Thanks for digging. I was considering archiving what's there (only a few entries so far) and doing the setup over again to see if that corrected it. What do you think?

**Comment by geoffhumphrey** [comment]
Jody, I just figured it out. Your judging date is set in the past (July 11, 2015). Those icons in the actions column will not appear if the system detects that the first judging date has passed. I changed the date to July 9, 2016 and things are normal now.

**Comment by jodygrenert** [comment]
Doh! My bad. You're the man. Thanks.

On Thu, May 5, 2016 at 4:17 PM, geoffhumphrey <notifications@github.com>
wrote:

> Jody, I just figured it out. Your judging date is set in the past (July
> 11, 2015). Those icons in the actions column will not appear if the system
> detects that the first judging date has passed. I changed the date to July
> 9, 2016 and things are normal now.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/596#issuecomment-217265928>
>



-- 
_________________

Jody Grenert
30 Briarwood Drive
Athens, OH 45701
740.591.5692
