### ISSUE TITLE
Cannot update judging numbers or box locations

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#597]
v2.0.1 (with the commit you emailed to me earlier this evening)

On the Admin: Entries page, there seems to be no way to manually edit the judging numbers or box locations for any entry. The data in the table is static, and the Edit Entry (pencil) icon only lets us edit the info the brewer entered (beer name, style category, special ingredients, cider & mead attributes, etc.).

**Comment by geoffhumphrey** [comment]
For the boxes to be enabled, you must specify a bottle label that features a barcode from Admin > Preferences > Website Preferences. This will be changed in the next version to be enabled by default.

**Comment by BrewDrinkRepeat** [comment]
We did use the bottle label w/ barcode option for this comp:

![screen shot 2016-05-06 at 11 32 am edt](https://cloud.githubusercontent.com/assets/18423016/15077822/4202365c-137e-11e6-821b-e4dd0b55b802.png)

**Comment by geoffhumphrey** [comment]
The latest commit updates the code to allow for updating judging numbers and box number from the Admin Entries list. Specifically, these two files should be replaced:
/admin/entries.admin.php
/includes/process/process_brewing.inc.php

https://github.com/geoffhumphrey/brewcompetitiononlineentry/archive/master.zip

**Comment by BrewDrinkRepeat** [comment]
Worked perfectly, thank you so much!!!

Brian
