### ISSUE TITLE
Limit printing of bottle labels

### ISSUE THREAD

**Issue by PeterSteinberg** [geoffhumphrey/brewcompetitiononlineentry#600]
I'd like an option that combines the normal "print bottle labels" and the "print bottle labels with special ingredients" options so I just get 1 label per bottle.

Currently I have to print them out both ways and through away a pile of labels.

**Comment by geoffhumphrey** [comment]
Hey Peter, in the next version (releasing VERY soon), there will be an option to print Avery 5160 or Avery 3422 address size labels - one entry per label - with required info printed for those subcategories that necessitate it. You'll will have a choice to print from 1 to 6 labels per entry. 

View from the Admin Dashboard > Entry Sorting section:

![screen shot 2016-05-10 at 1 38 48 pm](https://cloud.githubusercontent.com/assets/5216502/15159968/99d17b2a-16b4-11e6-9773-14fa41b5dcdf.png)

See the attached PDFs...entries with required info start on page 10 in each.
- [Judging Numbers - Avery 3422](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/257932/2016_Test_Homebrew_Competition_Bottle_Labels_Judging_Numbers_Req_Info_Mead-Cider_Avery3422.pdf)
- [Entry Numbers - Avery 3422](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/257935/2016_Test_Homebrew_Competition_Bottle_Labels_Entry_Numbers_Req_Info_Mead-Cider_Avery3422.pdf)
- [Judging Numbers - Avery 5160](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/257933/2016_Test_Homebrew_Competition_Bottle_Labels_Judging_Numbers_Req_Info_Mead-Cider_Avery5160.pdf)
- [Entry Numbers - Avery 5160](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/257934/2016_Test_Homebrew_Competition_Bottle_Labels_Entry_Numbers_Req_Info_Mead-Cider_Avery5160.pdf)

**Comment by PeterSteinberg** [comment]
Thanks!
