### ISSUE TITLE
Blocker: "You have an error in your SQL syntax";  's Lager.', ''),(3, 'C', 'Premium American Lager', 'Light Lager', '1.046', '1.056' at line 1

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#603]
I installed a fresh install of the latest release 2.1.0 and when I try to install DB tables I get an error.

First Error is:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's Lager.', ''),(3, 'C', 'Premium American Lager', 'Light Lager', '1.046', '1.056' at line 1

When I go back and press the button again I get:
Table 'judging_assignments' already exists

Is this a known issue? Are we doing something wrong?

Thanks,
Eric

**Comment by geoffhumphrey** [comment]
The latest commit fixes this issue. Will be releasing 2.1.1 later today that will incorporate it.
