### ISSUE TITLE
Getting "Could not open socket" when trying to add judge

### ISSUE THREAD

**Issue by Zvish** [geoffhumphrey/brewcompetitiononlineentry#605]
When a judge is trying registered and fill the form, he push register but get a screen that tell "Could not open socket"

**Comment by geoffhumphrey** [comment]
Zvi, upon research, this may have to do with the reCAPTCHA function on the registration page - I could not reproduce the issue in any of my test environments. Here's a couple of articles to help out in trying to resolve the problem:

- http://www.tipsandtricks-hq.com/forum/topic/registration-form-can-not-open-socket
- http://stackoverflow.com/questions/19055472/recaptcha-could-not-open-socket
- http://stackoverflow.com/questions/3232639/could-not-open-socket

**Comment by Zvish** [comment]
10x a lot!!! I will review the docs

**Comment by Zvish** [comment]
The hosting site I used (host-ed) block this communication.
The resolution was to move to other hosting system
