### ISSUE TITLE
Unable to create administrators without manually manipulating database entries

### ISSUE THREAD

**Issue by csaunders** [geoffhumphrey/brewcompetitiononlineentry#606]
Giving users `Staff` status does not grant them access to the Admin dashboard. Instead what has to be done is the relevant records need to be manually updated via a SQL command.

`update users set userLevel=0 where id in (range, of, ids, you, care, about);`

It should be possible to set other users as administrators in order to make managing these competitions easier. This would just need to be another assign roles page in the admin.

**Comment by geoffhumphrey** [comment]
It is possible to grant users Admin access via Admin > Entries and Participants > Manage Paticipants section. Click the lock icon and you can grant admin access to any individual as a Top Level Admin or a Mid Level Admin. See http://brewcompetition.com/features for a description of each.

**Comment by csaunders** [comment]
You should use words instead of icons or at least make the icons bigger. They are way too small to read and difficult click targets.

- Chris Saunders / sndrs.ca
