### ISSUE TITLE
Errors on print pullsheet/special ingredients requirements

### ISSUE THREAD

**Issue by kubiakw** [geoffhumphrey/brewcompetitiononlineentry#607]
Updated 2.0.1 to 2.1.0 to 2.1.1

When I try to print a pullsheet, it looks like this for each entry:

> Notice: Uninitialized string offset: 5 in /srv/users/serverpilot/apps/bcoem/public/output/pullsheets.output.php on line 318
> 
> Notice: Uninitialized string offset: 6 in /srv/users/serverpilot/apps/bcoem/public/output/pullsheets.output.php on line 319
> 
> Notice: Uninitialized string offset: 7 in /srv/users/serverpilot/apps/bcoem/public/output/pullsheets.output.php on line 320
> 01C Cream Ale
> Standard American Beer
> Notice: Undefined variable: style_convert in /srv/users/serverpilot/apps/bcoem/public/lib/common.lib.php on line 1695

When I go to the entry, it shows that it requires special ingredients and loads the form with checkboxes even though it doesn't show it in the select list or in the style management as being one that has requirements:

This style requires that you provide specific information for entry. Instructions are below.

Entry info goes here.

**Comment by geoffhumphrey** [comment]
@kubiakw, thanks for your report. For the first issue involving the pullsheets, it looks like you've got error reporting turned on for php notices. The notices do not impede the processing of the scripts, but can be annoying when displayed on the resulting page. To turn off error reporting, edit the paths.php file. Comment out line 42 and "uncomment" line 41:
```
//Error reporting
error_reporting(0);	// comment out to debug
//error_reporting(E_ALL); // uncomment to debug 
```

I tracked down the second issue (on the entry screen) to some characters that were not escaping when being pulled from the DB for custom styles. These non-escaped characters were breaking the javascript code that controls whether the showing/hiding of the Entry Requirements fields. This is definitely a more serious issue that will affect those who upgraded to 2.1.1 recently. To fix this, check to see if you have any single or double quotes in any custom styles and remove them. A fix for this will be in the next release. If you don't have custom styles, I'll do some more digging.
