### ISSUE TITLE
Cannot enable sponsor logo via the admin menu

### ISSUE THREAD

**Issue by Zvish** [geoffhumphrey/brewcompetitiononlineentry#609]
Hello,
I configured the Sponsor logo during installation to be false and now I am trying to enable it under:
Preferences -> Website -> Display sponsor logos -> change to yes and then push "Set website preferences" 
After that I get into this page again and I see that it was not changed, I also do not see the logo on the homepage.
Another thing I saw is under the info menu (home page) the section "Packing and Shipping" is shown twice.
Thanks,
Zvi

**Comment by geoffhumphrey** [comment]
Zvi, thanks for reporting this. I've confirmed the problem and have corrected it in the latest commit. It will be part of the next release.

**Comment by Zvish** [comment]
Hi,
Both issues?
I saw other issues as well, should I report them on git?
Thanks,
Zvi

**Comment by geoffhumphrey** [comment]
Oops. Forgot to say that I couldn't confirm the second issue. Could you post a screenshot? 

And yes, please post issues here. It will help to report if anyone else encounters the same issue...
