### ISSUE TITLE
Alert for open entry registration dependant on registration period not on entry registration period

### ISSUE THREAD

**Issue by rmsrosa** [geoffhumphrey/brewcompetitiononlineentry#610]
Hi,

It seems that the alert for "open entry registration" is showed based on the wrong period. In my case, the entry period had ended but the alert for open entry registration period was still showing because the registration period was still open. 

The problem seems to be in line 201 of alerts.sec.php. The condition
    <?php if (($registration_open == 1) && ...
should probably be
    <?php if (($entry_window_open == 1) && ...

This fix worked for me. 

A similar issue happens for the alert for "Entry limit nearly reached", in line 209. 

I had this issue in version 2.0.1 but I see that it is still present in 2.1.1. The line numbers above are for version 2.1.1. Those for 2.0.1 are 219 and 227, respectively.

Best,
Ricardo

**Comment by geoffhumphrey** [comment]
@rmsrosa, thank you for reporting the issue and providing a solution. I'll make sure it's updated in the next commit.
