### ISSUE TITLE
Typo in name of style 3B

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#611]
Style 3B showing as: 3B Czech Premimum Pale Lager

There is an extra m.

**Comment by geoffhumphrey** [comment]
Ah! Typos. Ugh. Thanks for reporting, @ercousin. I'll get it fixed for the next commit and release. In the meantime, folks can change the name in their DBs by running the following mySQL command in phpMyAdmin or shell access (replace XXX_ with your DB prefix or remove it if no prefix):

```
UPDATE XXX_styles SET brewStyle = 'Czech Premium Pale Lager' WHERE id = 107;
```
