### ISSUE TITLE
Under info tab the "Packing and Shipping" exist twice

### ISSUE THREAD

**Issue by Zvish** [geoffhumphrey/brewcompetitiononlineentry#612]
![packing](https://cloud.githubusercontent.com/assets/19358323/15348933/546653d4-1cd7-11e6-90f5-4eb50f9e91b1.png)

The "Packing and Shipping" area appear twice in the page

**Comment by geoffhumphrey** [comment]
Zvi, I'm not able to reproduce this in any of my test environments running version 2.1.1 - [see here](http://test.brewcomp.com/entry).

There's only one instance in the code where the shipping info exists, in the /sections/entry_info.sec.php script. The variables that holds the info is built on beginning on line 244 through 257 and then displayed to the browser on lines 351 and 352. 

From your screenshot, it looks like the first instance may be part to the Entry Acceptance Rules. Check what you've got entered in that field by going to Admin > Preparing > Edit Competition Info. Is the shipping info text there?

In any case, I recommend updating to 2.1.1 to see if that will take care of things.
