### ISSUE TITLE
Cannot see the beer style list in the website after a user registration

### ISSUE THREAD

**Issue by Zvish** [geoffhumphrey/brewcompetitiononlineentry#613]
Hi,
One of my friend registered to the site as a judge and after that I cannot see the beer style list on the user and admin profiles.
I also get an error on the top of the site that say:
Notice: Undefined variable: currency_code in /home/bhomebre/public_html/lib/common.lib.php on line 580
Notice: Undefined offset: 1 in /home/bhomebre/public_html/includes/constants.inc.php on line 52
Please advise,
Zvi

**Comment by geoffhumphrey** [comment]
Zvi, to troubleshoot the first issue, I need a bit more information. What beer style list are you referring to? I'm assuming the likes/dislikes lists but want to make sure. Please provide a URL and a screenshot so I can pinpoint where this is happening.

As far as the notices, it looks like you've got error reporting turned on. The notices do not impede the processing of the scripts, but can be annoying when displayed on the resulting page. To turn off error reporting, edit the paths.php file. Comment out line 42 and "uncomment" line 41:
```
//Error reporting
error_reporting(0);	// comment out to debug
//error_reporting(E_ALL); // uncomment to debug 
```

**Comment by Zvish** [comment]
Hi,
My website is (will be sent privately)
Sorry for the late response, I refer to the "Categories Accepted" regarding the beer style, on the admin user under "Competition Preperation -> Manage Style Accepted" I also do not see the styles list.
![styles](https://cloud.githubusercontent.com/assets/19358323/15449140/cbd2035c-1f7d-11e6-924d-63036bd0373f.GIF)

When I click "Update Accepted Style Categories" I am getting the following messages:
Notice: Undefined index: id in /home/bhomebre/public_html/includes/process/process_styles.inc.php on line 13

Warning: Invalid argument supplied for foreach() in /home/bhomebre/public_html/includes/process/process_styles.inc.php on line 13

Notice: Undefined variable: result in /home/bhomebre/public_html/includes/process/process_styles.inc.php on line 55

Thanks,
Zvi

**Comment by Zvish** [comment]
Hi,
The issue was resolved by removing ' char from several fields under the Participants table.
Zvi
