### ISSUE TITLE
If i get the install directory correct, the update won't work

### ISSUE THREAD

**Issue by joeleaux** [geoffhumphrey/brewcompetitiononlineentry#614]
If i set the config.php where the install sees the correct "includes" directory, then the install points to the wrong directory.

**Comment by geoffhumphrey** [comment]
@joeleaux, I'm not sure what you mean. The /sites/config.php file only houses configuration for DB connections and URL globals. The paths.php file houses the directory paths for all folders and subfolders utilized throughout the code. 

Could you explain a bit further?

**Comment by joeleaux** [comment]
i’m not sure … i’m not a php or sql expert, i knew enough to get the original up and running, but i need baby step by step instructions.

Can i give you the login and ftp info and have you look at it? I switched to your software at the request of my judges, but this is costing us time.



Joel Ohmer  |  Marketing

Cannata's Family Markets

6289 West Park Avenue Suite 5
Houma, Louisiana  70364
C 985.438.0169  |  O 985.873.9185
joel@cannatas.com <mailto:joel@cannatas.com>


 Fan us on Facebook <http://www.facebook.com/cannatas>  <http://www.facebook.com/cannatas>

**Comment by joeleaux** [comment]
http://bayoubeerfest.com/brewdat/update.php


Joel Ohmer  |  Marketing

Cannata's Family Markets

6289 West Park Avenue Suite 5
Houma, Louisiana  70364
C 985.438.0169  |  O 985.873.9185
joel@cannatas.com <mailto:joel@cannatas.com>


 Fan us on Facebook <http://www.facebook.com/cannatas>  <http://www.facebook.com/cannatas>

**Comment by geoffhumphrey** [comment]
Yes, I'll be happy to look at it if you're OK with giving me the login to your webserver's control panel. Email that info directly to me at prost@brewcompetition.com.

**Comment by joeleaux** [comment]
ftp is ftp.bayoubeersociety.org
user: joeleaux
pass: Slush@123


Joel Ohmer  |  Bayou Beer Society





www.bayoubeersociety.org <http://www.bayoubeersociety.org/>
www.facebook.com/BayouBeerSociety <http://www.facebook.com/BayouBeerSociety>
985.438.0169
info@bayoubeersociety.org <mailto:info@bayoubeersociety.org>
