### ISSUE TITLE
undefined variable being referenced on entry confirmation page.

### ISSUE THREAD

**Issue by phillipwhelan** [geoffhumphrey/brewcompetitiononlineentry#615]
When I add an entry I receive the following notices on the page i am redirected too.

Notice: Undefined variable: judgeLikesModals in /home/whelanp/public_html/sections/brewer_info.sec.php on line 551

Notice: Undefined variable: judgeDislikesModals in /home/whelanp/public_html/sections/brewer_info.sec.php on line 552

**Comment by joeleaux** [comment]
NO idea what the hell that means … shit, the previous version was running fine.



Joel Ohmer  |  Bayou Beer Society





www.bayoubeersociety.org <http://www.bayoubeersociety.org/>
www.facebook.com/BayouBeerSociety <http://www.facebook.com/BayouBeerSociety>
985.438.0169
info@bayoubeersociety.org <mailto:info@bayoubeersociety.org>

**Comment by joeleaux** [comment]
i can guide you to the mySQL settings if you give me a call

or

Login to GoDaddy

Click on Joel at the top, then MY PRODUCTS

in the WEB HOSTING section (second from top), click the “Manage” button on the right

under bayoubeersociety.org, click on MANAGE

on the HOSTING DETAILS page, click on DATABASES on the left

The database is second to last, named brew dat

login is user: brewdat   pass: Slush@123




Joel Ohmer  |  Marketing

Cannata's Family Markets

6289 West Park Avenue Suite 5
Houma, Louisiana  70364
C 985.438.0169  |  O 985.873.9185
joel@cannatas.com <mailto:joel@cannatas.com>


 Fan us on Facebook <http://www.facebook.com/cannatas>  <http://www.facebook.com/cannatas>

**Comment by geoffhumphrey** [comment]
I'm trying to track down the issues reported and figure out the causes. I've backed out the 2.1.1 release and am *trying* to help out as much as possible. Obviously, there was an issue with updating that didn't surface during testing before release.

For the OP, it looks like you've got error reporting turned on for php notices. The notices do not impede the processing of the scripts, but can be annoying when displayed on the resulting page. To turn off error reporting, edit the paths.php file. Comment out line 42 and "uncomment" line 41:
```
//Error reporting
error_reporting(0);	// comment out to debug
//error_reporting(E_ALL); // uncomment to debug 
```
Please keep in mind, it's free software that I try to support mostly on my own. There was an issue introduced in 2.1.1 that I was unaware of and am taking time away from my work day today to try to track it down.

@joeleaux, please check your email for a message entitled "BCOE&M Update" from prost@brewcompetition.com and reply directly to that with your webserver login credentials. Please do not post them here!

**Comment by phillipwhelan** [comment]
Thanks geoff, I appreciate the time and effort your putting into this.
