### ISSUE TITLE
Entry names with an apostrophe don't appear on bottle labels

### ISSUE THREAD

**Issue by wvbrewed** [geoffhumphrey/brewcompetitiononlineentry#619]
I recently submitted five entries to a competition page.  Only three of the five showed the entry names on the bottle labels; those entries didn't have apostrophes in the name.  The other two entries that did have an apostrophe in their name didn't show an entry name on the bottle label.

**Comment by geoffhumphrey** [comment]
Hello and thanks for reporting. A couple of questions: 
- Which version of the software were you using at the time?
- What did the bottle label look like (if possible, print out again from Chrome and use the "save as PDF" function)? Please post it here...
- Are you a user or an administrator of the installation?

In my initial testing with the latest version, I was not able to replicate the issue.

**Comment by wvbrewed** [comment]
Geoff,

1.)  The site is http://kotm.lmhba.org and it appears to use 2.0.0.
2.)  The bottle label looked relatively normal but it just didn't have the "Entry Name" field between the "Email" and "Cat/Sub" fields.  I have attached an image comparing the two resulting bottle labels.  On the left is a screenshot from the label of an entry without an apostrophe in the name that shows the "Entry Name" field; on the right side is a picture I took from a printout of one that did have an apostrophe in the name which resulted in no "Entry Name" field.
![bottle_label](https://cloud.githubusercontent.com/assets/19742359/15827765/886c53d8-2bda-11e6-8ba3-e959b48bda09.png)

3.)  I'm a user of it.

**Comment by geoffhumphrey** [comment]
Gotcha. I have confirmed the problem having to do with apostrophes in entry names on the BJCP Official bottle labels (both regular and with barcodes). The latest master commit has code that fixes the issue and it will be incorporated into the next release.

**Comment by wvbrewed** [comment]
Wow.  Nice work and turn around time.  Keep up the great work on this project.  I know those of us that have hands both in the IT field as well as homebrewing greatly appreciate what you're doing with this project.
