### ISSUE TITLE
Editing entries after paying reverts entry to unpaid state

### ISSUE THREAD

**Issue by csaunders** [geoffhumphrey/brewcompetitiononlineentry#621]
Replication steps:

- Create an entry
- Get the entry into a paid state (via paypal or whatever)
- Edit the entry (change category)
- Note that entry is no longer marked as paid

Either the app should warn the user that they are going to invalidate their entry, or the entry should remain paid.

**Comment by geoffhumphrey** [comment]
What version are you using? This may have some relation to issue #608 - a fix for which was implemented in 2.1.2.

**Comment by csaunders** [comment]
It was on the hosted version which is apparently running 2.1.3

**Comment by geoffhumphrey** [comment]
OK, cool. Which URL?

**Comment by csaunders** [comment]
http://becausebeercompetition.brewcompetition.com

**Comment by geoffhumphrey** [comment]
Confirmed. The latest commit fixes the issue and I've pushed the code to all hosted installations.
