### ISSUE TITLE
BCOEM directory permissions issue.

### ISSUE THREAD

**Issue by Beakerboy** [geoffhumphrey/brewcompetitiononlineentry#623]
BCOEM 2.1.2
A user was trying to upload a sponsor logo and received the following:
"Change permission of user_images to 755 has failed".
The directory is currently at 775 with me being the owner and www-data as the group.

This error irks me. In order to allow www-data to change permissions on user_images, I need to grant it write privs on the root directory, which is a little dangerous. www-data should only have write access to directories in which it needs to write a file. It shoudn't be changing directory permissions, unless it's a subfolder in a directory region which is considered web-writeable.

**Comment by hmmunro** [comment]
Also experiencing this directory permissions issue with user_images.
BCOEM 2.1.3 and user_images directory is at 755.

**Comment by geoffhumphrey** [comment]
This may be a server environment issue. All of my test sites and hosted sites have the user_images folder permission set to 755 and are able to upload images successfully. The containing folder (installation root) folder has permissions set to 555.

With regard to the "Change permission of user_images to 755 has failed" message, I agree - it shouldn't be attempting to change permissions. I'll take that function out.
