### ISSUE TITLE
Options to disable shipping entries and drop-off entries

### ISSUE THREAD

**Issue by elronalds** [geoffhumphrey/brewcompetitiononlineentry#624]
It would be nice to have some options to completely remove the shipping entries option and the drop-off locations for a competition.

For example, we might run a competition that doesn't accept shipped entries. Having this option show on the competition page is confusing even if you set this up with an invalid date.  It would be nice to have the option for these to be completely removed.

**Comment by geoffhumphrey** [comment]
Doh! I meant to add this to the 2.1.5 release. I'll get into the queue the ability to show/hide shipping and drop-off locations via Site Preferences.
