### ISSUE TITLE
Upgrade frm 1.3.1.0 to 2.1.3.0 duplicate column name

### ISSUE THREAD

**Issue by vortexofhate** [geoffhumphrey/brewcompetitiononlineentry#628]
Whenever I try to update the software to the latest and greatest, during the update process I get the message "Duplicate column name 'prefsStyleSet'"

**Comment by geoffhumphrey** [comment]
The best advice I can give here is to go into your present DB and delete the prefsStyleSet column in the preferences table and re-run the update. I'll look for a solution to this for an upcoming release...

**Comment by geoffhumphrey** [comment]
The latest commit package and next version have a fix for this. Specifically, the /update/1.3.2.0_update.php file.
