### ISSUE TITLE
Site name incorrect

### ISSUE THREAD

**Issue by tpklieb** [geoffhumphrey/brewcompetitiononlineentry#629]
The heading that lists the name of the competition it's cut short and only lists "for what it's" and leaves off"wort". Please update so that it reads "for what it's wort"

**Comment by tpklieb** [comment]
Still haven't heard back on this. Here is a SS of what I'm talking about:
![image](https://cloud.githubusercontent.com/assets/8492957/16404056/f6d9a1d0-3cc0-11e6-9d73-4d43e0c4f7d2.png)

**Comment by geoffhumphrey** [comment]
Not sure what's happening to cause this. I was able to change the name via Admin > Competition Preparation > Edit Competition Info on your hosted site. I'll investigate; but for now, it's fixed.
