### ISSUE TITLE
If we choose anonymouse bottle labels, boilerplate "bottle acceptance text" should update

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#632]
Right now the boilerplate reads "Entry forms should be attached to bottles with a rubber band only; **glue and/or tape are unacceptable.**"

 But if we choose the anonymous bottle label option (thanks BTW!) the labels instruct the entrant to use clear packing tape to apply their bottle labels. This could lead to confusion if the competition doesn't notice this and modify the text.

**Comment by geoffhumphrey** [comment]
The "Entry Acceptance Rules" are a freeform field that Admins can update with custom text at their discretion via the Competition Preparation > Edit Competition Info function. For future releases, I'll simply take out the part about rubber-banding and not taping bottle labels in favor of something more generic like "Entry forms should be attached to bottle labels by the method specified on the bottle label."

**Comment by BrewDrinkRepeat** [comment]
I think that's a good idea; I always customize all the boilerplate text, but some folks don't and/or will miss that part.
