### ISSUE TITLE
v2.1.3 -- Cannot Modify Style List

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#633]
I'm setting up for a "summer beers" competition so I'm unchecking all dark beers, high-gravity beers, etc. These changes are not being stored in the database, unfortunately, and all styles remain selectable when adding an entry.

**Comment by geoffhumphrey** [comment]
The [latest commit package](https://github.com/geoffhumphrey/brewcompetitiononlineentry/archive/master.zip) fixes this issue - see Issue #622.

**Comment by BrewDrinkRepeat** [comment]
Thanks! Sorry I missed the original report...

Upload all the new files (except Site > Config.php)?

Brian

**Comment by BrewDrinkRepeat** [comment]
Actually scratch that, I think I see on the original issue page that it's just the one file (process_styles.inc.php):

**Comment by geoffhumphrey** [comment]
Yes, if you are upgrading from 2.1.0 or later. Otherwise, you'll need to re-enter your config variables due to the upgrade from mysql to mysqli protocols introduced in 2.1.0.

**Comment by BrewDrinkRepeat** [comment]
I'm running the latest (2.1.3) for this comp.

**Comment by geoffhumphrey** [comment]
I would upgrade to 2.1.4 copying all files except the config.php file...

**Comment by BrewDrinkRepeat** [comment]
OK, will do!

Thanks, as always, for your help and responsiveness! Wish I was smarter at this kind of thing so I could help out!
