### ISSUE TITLE
Mead strength is not being accepted for entry

### ISSUE THREAD

**Issue by tpklieb** [geoffhumphrey/brewcompetitiononlineentry#634]
![mead problem](https://cloud.githubusercontent.com/assets/8492957/16404034/b24f8494-3cc0-11e6-8a2b-d8ff3e9d38ed.png)

**Comment by geoffhumphrey** [comment]
Confirmed. This actually has to do with an error checking function. The data is being passed and stored in the DB for "Strength"; however, the error checking function is marking the entry as "unconfirmed" for some reason. To get around this, Admins can verify that the affected entries have the required information by hovering over the speech bubble icon by the entry name via the Admin > Entries and Participants > Entries screen (see below).

![screen shot 2016-06-28 at 7 26 00 am](https://cloud.githubusercontent.com/assets/5216502/16417008/d87f4924-3d01-11e6-9bbd-ab2ece5ad7ec.png)

To confirm entries, Admins can then use the "Confirm All Entries" function in the Admin Actions dropdown:

![screen shot 2016-06-28 at 7 26 26 am](https://cloud.githubusercontent.com/assets/5216502/16417092/fad6ba8e-3d01-11e6-91a4-d0c762965ca6.png)

I'll be investigating the issue and post a commit when it is resolved.
