### ISSUE TITLE
handle.php doesn't correctly use document root.

### ISSUE THREAD

**Issue by markalston** [geoffhumphrey/brewcompetitiononlineentry#636]
The following code in handle.php is broken when the software is run in a subdirectory of the document root.
The $storeFolder needs to have the document root and the $subdirectory added to it. I am in a rush so I just commented out the check for write permissions but if I get to it I'll fix it more properly.
```
$ds = DIRECTORY_SEPARATOR; // Directory separator
        if (($action == "default") || ($action == "html")) $storeFolder = "user_images";
        if (($action == "docs") || ($action == "html_docs")) $storeFolder = "user_docs";
        $backlist = array('php', 'php3', 'php4', 'phtml', 'exe'); // Restrict file extensions
        $valid_chars_regex = "A-Za-z0-9_-\s "; // Characters allowed in the file name (in a Regular Expression format)

/*      // Change chmod permission if needed
        chmod($storeFolder, 0755);

```

**Comment by geoffhumphrey** [comment]
This was an oversight. Absolute paths to both upload folders are set up already in the paths.php file, which is included at the top of the handle.php file. To make things work for a subfolder installation, change these lines of code in handle.php to the following:

Lines 26 and 27:
```
if (($action == "default") || ($action == "html")) $storeFolder = USER_IMAGES;
if (($action == "docs") || ($action == "html_docs")) $storeFolder = USER_DOCS;
```
Line 35:
```
if (!chmod($storeFolder,0755)) {
```
Line 70:
```
$targetPath = $storeFolder;
```
