### ISSUE TITLE
Mixed content when using https

### ISSUE THREAD

**Issue by markalston** [geoffhumphrey/brewcompetitiononlineentry#637]
There are some http: urls which break the site on https.

```
index.php:      <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/plug-ins/1.10.10/integration/font-awesome/dataTables.fontAwesome.css" />
setup.php:              <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/plug-ins/1.10.10/integration/font-awesome/dataTables.fontAwesome.css" />
default.css:@import url(http://fonts.googleapis.com/css?family=Raleway:300,500,800|Source+Sans+Pro:300,400,600,700);
default.min.css:@charset "UTF-8";@import url(http://fonts.googleapis.com/css?family=Raleway:300,500,800|Source+Sans+Pro:300,400,600,700);
```
Ideally all the href="http://...." and href="https://..." should be replaced with just href="//..." to make then protocol agnostic.  I don't think that will work with the @import url lines though.

**Comment by geoffhumphrey** [comment]
Agreed. For the next release, all the href="http://...." and href="https://..." will be replaced with href="//..."

For the @import urls in CSS files, simply changing to https:// will work for all themes.
