### ISSUE TITLE
Custom style added causes incorrect display and handling of all styles' required information on entry addition/edit.

### ISSUE THREAD

**Issue by beerrat** [geoffhumphrey/brewcompetitiononlineentry#638]
When adding entries - users sees all the items required for any style, not  ones specific for a style, .  See screen shot:
![bug_entryinfo](https://cloud.githubusercontent.com/assets/20248693/16534329/ef0cb2aa-3fac-11e6-8c7a-4847f0eb2aa6.jpg)

**Comment by beerrat** [comment]
I have determine it only occurs when there is a custom style category defined.  We add a new style that needs Required Info. Once that is added, all other style show the above screen shot.  Even with he custom style disabled, it still exhibited the incorrect behavior.  I deleted the custom style, and all works.

**Comment by geoffhumphrey** [comment]
@beerrat, I'm not able to replicate this issue in my test environments running 2.1.4 just yet, both local and on a webserver, root domain and sub-folder installations. Perhaps you could post more about your environment and/or a link to your installation so I could create a user and see the bug in action?

**Comment by beerrat** [comment]
I narrowed it down to when I copy/pasted the Entry Info when creating a custom style.  When I typed in the text and used the tools built- in formatting, all is ok.... when I copied the text that included a bulleted list, it would cause the behavior.  Here is URL: http://crystallhbc.com/test/

**Comment by geoffhumphrey** [comment]
Confirmed. Not sure why bulleted and numbered html lists break the javascript. Breaks even if not copying/pasting a list. I'm investigating a solution, but for the meantime, removing any lists from any style entry instruction and description will bring the functionality back as expected. Weirdness.

**Comment by jimmyorkin** [comment]
I just found this bug in the v2.1.8 release. I added a second paragraph to the Entry Info field. That broke all the styles. This might not be completely fixed yet.
