### ISSUE TITLE
Unable to assign judges to tables

### ISSUE THREAD

**Issue by jodygrenert** [geoffhumphrey/brewcompetitiononlineentry#643]
I'm unable to assign judges to tables. There is no radio button next to their name labeled "assign judge to table," as the directions indicate. I'm guessing there's a setup or preference issue that I messed up, but I can't find it. See the screenshot to see what I'm seeing.

My site's URL is www.obw.brewcomp.com

![competition table issue](https://cloud.githubusercontent.com/assets/18756031/16808082/0263aed6-48e9-11e6-9d2e-ba2fb108f3fe.JPG)

**Comment by geoffhumphrey** [comment]
@jodygrenert - thanks for reporting. I'm investigating now and it appears this only affects the AM session judging location. Frankly, I cannot think of a reason why this is happening for one judging location and not the other. I'll post when I find a fix or workaround.

**Comment by jodygrenert** [comment]
I tried fiddling with the competition preferences -- number of flights, rounds, etc. Nothing seemed to fix it. I have a hunch the glitch is in there.

**Comment by jodygrenert** [comment]
By the way, the app version this year is AWESOME. Just a few buggies here and there.

**Comment by jodygrenert** [comment]
This may be a clue. I added the PM session just yesterday, after registration had closed. So when judges originally signed up, there was only an AM session. Now I'm having to go into each judge/steward's info and click "yes" to their availability for PM session, since by default the program selects "No."

**Comment by geoffhumphrey** [comment]
Looks like this has to do with the way that individual entries were being flagged by the system as being part of a flight. The new methodology employed in the latest commit (and v2.1.5 when it is released) to address issues #644 and #645 should take care of this issue. Further testing is planned.
