### ISSUE TITLE
Blank Page when Creating Tables

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#644]
In 2.1.3 when I try to create a table for stout & porter with 13B, 13C, 15B, 15C, 20A, 20B, I get a blank page...

Please help, this means I need to do table creation outside the software this time... :(

![image](https://cloud.githubusercontent.com/assets/1551339/16892100/bf39ed0c-4ad5-11e6-93c0-a65627d0166f.png)

**Comment by ercousin** [comment]
More info. I was able to create tables 1 and 2, but then failed when I went to create 3.

Between 2 and 3, I went back and removed 2 styles from table 2 to add to 3. After doing that I am not longer to create tables. Even after deleting them all, I can't even create 1 or 2 again.

**Comment by ercousin** [comment]
I don't know exactly what I did to fix it but here's what I tried...

Manually created a table in the sql database by looking up styleid in styles table.
Tried assigning it to a round and got error said it hadn't been assigned to flight (queued judging)
Looked at judging_flight object in sql and saw there were already 4 (so I took the risk and deleted them all)
Changed website to flight judging
Tried assigning flight to table, got error about value not matching col1
Changed website back to queued judging

Was able to add styles to tables again, and add tables.

Perhaps there was some kind of bug in the judging_flights? Not sure...

**Comment by ercousin** [comment]
I had all 10 tables added, but wanted to switch one style to another table and it happened again.

Perhaps there is an issue with judging_flights being updated when you remove a style from a table?

**Comment by ercousin** [comment]
I was able to fix it easier this time.

Deleted all entries corresponding to those two styles from judging_flights
Deleted the styleid from the array of styles for those two tables
Used BCOEM to add those two styles to the correct tables

I think this is perhaps a bug with the queued judging feature?

**Comment by ercousin** [comment]
Also, non-consequential typo in the spelling of stewards.

![image](https://cloud.githubusercontent.com/assets/1551339/16892961/23deaaea-4af4-11e6-808c-ca7a57a6cc13.png)

**Comment by geoffhumphrey** [comment]
Tracked the problem to errant records left in the judging_flights table when editing a table's styles. These records did not have an association with a judging table in the judging_tables DB table and were breaking the script. Working on a solution.
