### ISSUE TITLE
Unable to add more tables!

### ISSUE THREAD

**Issue by tpklieb** [geoffhumphrey/brewcompetitiononlineentry#645]
I was able to create three judging tables and when I went to create my fourth table, it took me to a blank white page:
http://www.forwhatitswort.brewcomp.com/includes/process.inc.php?section=admin&action=add&dbTable=fwiw_judging_tables&go=judging_tables

**Comment by ercousin** [comment]
You should always look for similar issues before creating a new one. This sounds the exact same as the issue I reported on Friday.

https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/644

**Comment by tpklieb** [comment]
I realize that, but I wanted to make sure you would see I was having the
same issue. Has it been resolved? I haven't been able to fix it myself and
given the SQL solution, I don't have access to fix it.

Sorry for the double

Tim

**Comment by geoffhumphrey** [comment]
Tim, I'm working out a solution and will most likely have one in place on all hosted installations by the end of the day today. Apologies for the issue.

For now, deleting all tables and starting fresh is a possibility, especially if you're in a time crunch.

**Comment by tpklieb** [comment]
If it's finished by the end of the day and fixed that would be fine for my
purposes.
I used to work in IT, you understand that there will be issues from time to
time.

**Comment by tpklieb** [comment]
Any update on this? I'm still not able to create tables. I might need you
to delete the tables

**Comment by geoffhumphrey** [comment]
Apologies, Tim. I haven't been able to update hosted sites as of yet. I'm on my lunch brewk now and should have yours updated within the hour.

**Comment by nealabram** [comment]
Hi Geoff -- I'm having the same problem with http://bellinghambrewers.com/bestofthebay. I've got about 20 tables created, but when I try to create a new table I get a blank page. Help?

**Comment by geoffhumphrey** [comment]
@nealabram, if you download and install the latest committed code, this issue should be resolved. Go to https://github.com/geoffhumphrey/brewcompetitiononlineentry/archive/master.zip to download. Customize the /sites/config.php file to your environment, and upload the code to your webserver.
