### ISSUE TITLE
invalid number specifications in common.lib.php

### ISSUE THREAD

**Issue by tommck** [geoffhumphrey/brewcompetitiononlineentry#648]
these lines (line 2207/8):

   	elseif ($srm >= 07 && $srm < 08) $return = "#cdaa37";
	elseif ($srm >= 08 && $srm < 09) $return = "#c1963c";

The "08" and "09" are invalid octal numbers. 

To run in newer PHP versions, these need to be "8" and "9"

**Comment by geoffhumphrey** [comment]
Noted; I'll remove the leading zeros from lines 2202 through 2208. Thanks for reporting!
