### ISSUE TITLE
SQL Syntax errors

### ISSUE THREAD

**Issue by tommck** [geoffhumphrey/brewcompetitiononlineentry#649]
New installation of 2.1.4 on latest apache2 and mysql 5.7.*
Trying to "manage entries" or "manage participants" comes back with:

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

**Comment by geoffhumphrey** [comment]
See issue #650 for a list of compatible versions...
