### ISSUE TITLE
What versions of dependencies?

### ISSUE THREAD

**Issue by tommck** [geoffhumphrey/brewcompetitiononlineentry#650]
It would be nice to see a list of the versions of dependencies like PHP, MySQL, etc that this has been tested with, or at least what you know is stable.

Grabbing latest of everything results in code that won't run.

**Comment by geoffhumphrey** [comment]
Here are the versions of the dependencies that the current version has been tested with (as of today):
- PHP 5.6.23
- MySQL 5.5.42
- jQuery 2.2.4
- jQuery Easing 1.3.0
- jQuery Mousewheel 3.1.13
- Bootstrap 3.3.6
- DataTables 1.10.12
- Fancybox 2.1.5
- Bootstrap DateTime Picker 4.17.37
- Jasney Bootstrap 3.1.3
- Dropzone 4.2.0
- Bootstrap Validator 0.9.0
- Boostrap Select 1.9.3
- Font Awesome 4.5.0
- JS Moment 2.11.1

I just tested on a local environments (Mac OS, Windows) using Xampp 5.6.23. 

Have not tested with PHP 7 yet.
