### ISSUE TITLE
New feature to download pdf of scoresheets

### ISSUE THREAD

**Issue by rmsrosa** [geoffhumphrey/brewcompetitiononlineentry#652]
Hi, Geoff,

I have forked version 2.0.1 to develop a Brazilian version of the code. Mostly translations but also some particular stuff we need here. But one of the features I added was the ability for the entrants to download a pdf of their scoresheets, if available. It is an action link that appears after scores are available and if the respective scoresheets pdf exists. It only changes about 4 files, including .htaccess (to restrict direct access to the pdfs), and adds a folder with two subfolders, one containing the pdfs and the other, with write-enabled access, where temporary pdfs with randomly-generated keys appended are created, with the temporary pdfs.

If it is of interest, I  can make a pull-request, after I learn how to do the pull-request. Let me know.

Best,
Ricardo

**Comment by geoffhumphrey** [comment]
Hi @rmsrosa,

Thanks for helping out with adding some features! I don't know if you are aware of this or not (probably not since you are running 2.0.1), but the ability for admins to upload and for participants to download scanned PDF scoresheets was integrated into version 2.1.0 that was released on May 12. 

In any case, I would still like to check out your methodology. So please, by all means, make a pull request!

Saúde!

Geoff

**Comment by rmsrosa** [comment]
Great, I didn't know about this feature in 2.1.0! I should have searched the issues for that or looked more carefully into the latest code.

Ok, I doubt my solution is better because it is the first time I am programming with php and web stuff, it is quite a different world. Anyway, I will be happy to make a pull request. Trouble is I don't quite know how to approach this. I guess the best would be to start from you master branch of the latest release, change the relevant files, and make a pull request, but I already forked 2.0.1 and made several other changes, I think it would be a mess to make a pull request from that. I will look into this, but if you can direct me to the correct way of doing this, it would be easier.

Saúde!

Ricardo

**Comment by rmsrosa** [comment]
I think I know a way to do it. I make a branch off of my main repository, change it and commit to make it equal to your master branch, make the changes for the new feature, and then make  a pull-request. Will do it!

**Comment by jodygrenert** [comment]
Geoff,
I'm not sure what version I'm on, but I've just uploaded the judging scoresheets (in the correct 4-digit format) and am now trying to figure out how to instruct participants on how they can download them. Can you enlighten me so I can enlighten them? Thanks.

Jody

**Comment by geoffhumphrey** [comment]
Jody, the scoresheets should be named using the 6-digit judging number (e.g., 123456.pdf) and uploaded to the "user_docs" folder. Code on the user's entry list searches the user_docs forlder for a matching document with a judging number for each of their entries. If there's a match a gavel icon will show in the Actions column of that entry, like this:
![screen shot 2016-08-01 at 8 37 07 am](https://cloud.githubusercontent.com/assets/5216502/17297493/31dd3860-57c3-11e6-93e4-68289edee458.png)
Clicking the icon will force a download (browser viewing is disabled for anonymity reasons). Hope that helps!
