### ISSUE TITLE
Orphan row in brewing table

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#654]
We are using v1.3.2. We will upgrade after this year's competition.

We had a row show up in the brewing table with a unique id and a valid brewUpdated column. All the other columns were null except two true/false columns.

I could not find any issues related to an orphaned row. Is this a know problem?

Thanks,

Jimmy

**Comment by geoffhumphrey** [comment]
I did see the "orphan" row phenomenon with versions prior to 2.0.0 although I could never truly figure out how it was happening. I have not observed any orphan rows in any version since 2.0.0.

**Comment by rmsrosa** [comment]
I saw this issue happen a few times in our competition, with a modified version based on 2.0.1. I didn't find the problem but I believe it might have occurred in some specific platforms that didn't enforce the requirement of naming the beer.

**Comment by rmsrosa** [comment]
I saw these orphan rows after some entrants complain that one of their entries disappeared after they tried to edit its name
