### ISSUE TITLE
Quick Add Judge/Steward Should Include More

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#656]
I've found that when I quick add a judge, I immediately have to go back and edit their profile.

When adding a judge I have to:
"Manually select NO for available to Steward"
"Manually go back and select available only for their indicated sessions"

Can you add more to the quick add page to allow us to specify if we are adding a judge or a steward and also what sessions they are available for?

**Comment by ercousin** [comment]
I just saw that you enhanced this functionality in the latest commit. That's great, I can't wait to try it out.

Any timeline for v2.1.5 release?

I'm running a 400+ entry comp in late Sept and would love to update before entries start entering the system.

**Comment by geoffhumphrey** [comment]
I'm targeting the end of the month for 2.1.5. Currently doing some behind the scenes work to make internationalization easier.
