### ISSUE TITLE
Add Advanced Cicerone Designation

### ISSUE THREAD

**Issue by mezzoblue** [geoffhumphrey/brewcompetitiononlineentry#658]
In the Designations section on the Edit Account screen, the listed options include Professional Brewer, Certified Cicerone, Master Cicerone, and Judge with Sensory Training.

As of April 2016 the Cicerone Certification program began granting a new level, the Advanced Cicerone, which should be offered as an option in addition to the existing list.

**Comment by geoffhumphrey** [comment]
Thanks for the heads up. The designation will be added to the list for the next version.
