### ISSUE TITLE
Choice of time zone not enforced during initial set up of the competition

### ISSUE THREAD

**Issue by rmsrosa** [geoffhumphrey/brewcompetitiononlineentry#660]
I had this issue in version 2.0.1 and again with the current master. During the setup of the competition, after choosing the time zone for the competition ("localization" section of the web form), the next page is for defining the dates for user registration, entry registration, dropoff and so on. The problem is that the dates given at this point are assumed to be GMT while I was expecting the system to understand it should already be in the time zone I chose in the previous setup page. I had to, after finishing the setup, log in as administrator and edit the Competition Info to fix the times to the proper times in the chosen time zone. By then, apparently the system assimilated the new time zone and properly registered the desired times.

**Comment by geoffhumphrey** [comment]
Confirmed. I'll check into the code to see why the chosen time zone is not enforced. My suspicion is that some session coding isn't being invoked.
