### ISSUE TITLE
Display winners

### ISSUE THREAD

**Issue by JoePostma** [geoffhumphrey/brewcompetitiononlineentry#661]
I have winner display set to "Yes" and winner delay display set to "0", but the winners are not showing up on the webpage. Is there some other setting I should use to display?

**Comment by rmsrosa** [comment]
The less obvious requirements are that the brewer and judge registration windows need to be closed (of course, entry window and all judging date need to be over as well).

**Comment by JoePostma** [comment]
That worked! The judge registration was incorrectly set to the end of the month. Thanks for your help.
