### ISSUE TITLE
Edit Account button on My Account Screen 404

### ISSUE THREAD

**Issue by buergermeister75** [geoffhumphrey/brewcompetitiononlineentry#662]
Getting a 404 error when clicking on the Edit Account button on the My Account screen. The URL it goes to is http://<domain>/brewer/account/edit/1. Should go to http://<domain>/brewer/account/edit.

**Comment by geoffhumphrey** [comment]
This probably has to do with the site utilizing the search engine friendly URL option that's available via Site Preferences. Some environments don't do well with the way BCOE&M does SEF urls. My advice would be to ask a site admin to disable the feature.

**Comment by buergermeister75** [comment]
Okay. I'll discuss it with myself and test it. ;)

**Comment by geoffhumphrey** [comment]
Hope it's not a long conversation.

**Comment by buergermeister75** [comment]
I've never experienced this level of bureaucracy due to so many voices. 😜

**Comment by buergermeister75** [comment]
Disabling SEF did the trick. Will leave off going forward.
