### ISSUE TITLE
Make "Brewers Specifics" field opt-in and optional

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#664]
Could we just make the "Brewer's Specifics" field opt-in?

I think this is screwing up a lot of entrants/competitions, and a majority of organizers who actually notice it's there would rather it not be there since it is optional information.

I would like to see only the "Required Info" field plus radio buttons by default. I've had a lot of entrants get confused and enter half of their required info in each text box. I instruct my stewards to verbally announce the brewers specifics, but I imagine there are a lot of comps out there that don't and then info doesn't get given to the judges. I know you added some red text to try and mitigate this, but have an option to get rid of it completely would help the most.

**Comment by geoffhumphrey** [comment]
Seems reasonable. I'll put it in the queue for the next DB-related update.
