### ISSUE TITLE
scoresheet labels printing for people who can't judge.

### ISSUE THREAD

**Issue by markalston** [geoffhumphrey/brewcompetitiononlineentry#665]
Having a weird issue with judges and scoresheets.  The judges have been set to unavailable in their participant profile but still show up in the scoresheet label printout.  I added the following to  output_labels.db.php which solved the problem but I suspect that there is something else going on.

> if (($action == "judging_labels") && ($id == "default")) {
....  AND b.staff_judge='1' and a.brewerJudge = 'Y'  ORDER BY a.brewerLastName ASC";

**Comment by geoffhumphrey** [comment]
Noted. Logic has been added that will ship with the next release to "unassign" any judge or steward that changes their availability via their My Account settings.

Added ```AND a.brewerJudge='Y'``` to the query on line 76 to weed out unavailable judges. Just in case. Couldn't hurt, right?
