### ISSUE TITLE
Add a "Mini BOS" checkbox to pullsheets

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#667]
We always use one of the pullsheets from each table as the Master Score List for the organizer/registrar. We ask the judges to mark which beers went to a mini-BOS by putting a checkmark or star next to each entry, but a printed checkbox for this would be more consistent plus a reminder to the judges to mark those entries (they often forget!).

**Comment by geoffhumphrey** [comment]
Seems easy enough. However, with this addition and the request to separate the Required Info and Brewer's Specifics that will allow the pullsheet order to align with the order on the Scoring screens (see Issue #646), the pullsheet will probably need to be printed in landscape.

Portrait:
![screen shot 2016-08-25 at 9 03 38 am](https://cloud.githubusercontent.com/assets/5216502/17974314/d6d976fc-6aa2-11e6-8212-fc4a69d2f1df.png)

Landscape:
![screen shot 2016-08-25 at 9 03 20 am](https://cloud.githubusercontent.com/assets/5216502/17974326/e08d3922-6aa2-11e6-86aa-4235b06e241c.png)

**Comment by BrewDrinkRepeat** [comment]
Not that printing them in landscape is a terrible thing, but perhaps eliminate the Round column? 

(Not sure what that is for, do a lot of competitions split a table across multiple rounds? And even if so, does that need to be on the pullsheet? Occasionally we will have the same pair of judges to a larger flight, split between AM and PM, rather than have four judges in one session and a miniBOS, but whether a beer was judged in the AM or PM wouldn't need to be noted on the pullsheet... well, speaking only for myself I wouldn't need to know that.)

And for the MiniBOS column, I'm thinking just a small checkbox for the person entering the scores after judging is over. Doesn't have to be as big as the other boxes, just a small checkbox.

**Comment by geoffhumphrey** [comment]
OK. Reworked based upon your suggestions. You're right, no need to have separate column for Round. All entries in a certain flight are in the same round. Moved that info to be with the flight number.

![screen shot 2016-08-25 at 10 12 51 am](https://cloud.githubusercontent.com/assets/5216502/17976860/8080bb8a-6aac-11e6-9d7a-5612cde9e42a.png)

**Comment by BrewDrinkRepeat** [comment]
Looks great! 

Thanks so much (as always) for all the work you've done and continue to do for this!
