### ISSUE TITLE
Quick Judge Email generator

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#668]
It would be great to have a one-click generator for all the assigned judges that could be copy/pasted into an email. All the emails, separated by commas, as most email programs want them to be.

For example, a popup with copyable text like:
name@email.com, name2@email2.com, name3@email3.org, 

Or just automatically post the text to the clipboard.

The current export to CSV includes a bunch of extra data that needs to be parsed and formatted for use in an email.

**Comment by geoffhumphrey** [comment]
The next version will have a button on the Admin > Assign Judges or Admin > Assign Stewards screens that will trigger a modal with the emails of assigned judges/stewards listed in a textbox like the OP described...

**Comment by BrewDrinkRepeat** [comment]
Fantastic, thanks so much! As always, mega-kudos to all the work you do to make this the best competition software available!
