### ISSUE TITLE
Radio button label for "petillant" is missing

### ISSUE THREAD

**Issue by tehchriso** [geoffhumphrey/brewcompetitiononlineentry#673]
When adding a new Mead entry, the radio button label Petillant is missing, and the radio button appears out of line.

Screenshot: http://imgur.com/a/bbDIs
Page URL: `[my-site.com]/index.php?section=brew&go=entry&action=add#`
Version: 2.1.5 - just upgraded from 2.1.4 today

**Comment by geoffhumphrey** [comment]
There was a misspelling of the php variable in /lang/en/en.lang.php. Change line 108 to:

``` $label_petillant = "Petillant"; ```

This will correct the missing label and alignment issues.

![screen shot 2016-09-02 at 9 31 13 am](https://cloud.githubusercontent.com/assets/5216502/18209223/0ea1241a-70f0-11e6-87d8-15c3a063d8ac.png)

**Comment by tehchriso** [comment]
Magnificent, thank you!

I checked in phpMyAdmin, and did some searching in the directory, but I hadn't stumbled upon the language files. Very helpful!

**Comment by geoffhumphrey** [comment]
Re-opening to include in 2.1.6... and just in case others need the solution in the interim.

**Comment by joeleaux** [comment]
Geoff

How do i stop receiving these emails … i keep muting threads but i get every single email


Joel Ohmer  |  Marketing

Cannata's Family Markets

6289 West Park Avenue Suite 5
Houma, Louisiana  70364
C 985.438.0169  |  O 985.873.9185
joel@cannatas.com <mailto:joel@cannatas.com>


 Fan us on Facebook <http://www.facebook.com/cannatas>  <http://www.facebook.com/cannatas>

**Comment by geoffhumphrey** [comment]
Joel, I really can't tell you beyond "unwatching" and/or "unstarring" the repo on GitHub.

**Comment by joeleaux** [comment]
thanks!

Joel Ohmer  |  Marketing

Cannata's Family Markets

6289 West Park Avenue Suite 5
Houma, Louisiana  70364
C 985.438.0169  |  O 985.873.9185
joel@cannatas.com <mailto:joel@cannatas.com>


 Fan us on Facebook <http://www.facebook.com/cannatas>  <http://www.facebook.com/cannatas>
