### ISSUE TITLE
Regenerate Judging Numbers on Admin: Entries Screen Results in NULL

### ISSUE THREAD

**Issue by geoffhumphrey** [geoffhumphrey/brewcompetitiononlineentry#677]
The "Regenerate Judging Numbers" link, accessed via the _Admin Actions_ dropdown on the Admin: Entries screen results in all judging numbers to be nullified (blank).

If you wish to regenerate judging numbers, use one of the links on the Administration Dashboard under the Entry Storing heading.

A fix will be in the next commit and the next release.

EDIT: first reported in Issue #674

**Comment by dogunter** [comment]
You beat me to it! I was just playing around with it again this morning and noticed that the other method (from the admin panel page, non-dropdown action) worked.
