### ISSUE TITLE
Contact form not working in v2.1.6

### ISSUE THREAD

**Issue by dogunter** [geoffhumphrey/brewcompetitiononlineentry#678]
I have configured our competition site to use the contact page to send email to the organizers. During the configuration, the test email works fine (from the option to allow the contact page, clicking the button sends a test email that arrives as it should).

However, no email sent from the contact page ever arrives. Moreover, the website never returns from the submission but remains stuck on a blank page with the URL showing
"http://<host url>/includes/process.inc.php?dbTable=contacts&action=email"

Can you think of any obvious things to check as to why this isn't working?

-david

**Comment by geoffhumphrey** [comment]
Confirmed. I'm investigating, but my suspicion is that it's a programming error and not a server thing. I'll post a fix as soon as I track down the issue.

**Comment by geoffhumphrey** [comment]
On or around line 242 in the /includes/process.inc.php file, change the following line:
```
elseif ($action == "email") {
```
To
```
elseif (($action == "email") && ($dbTable == "default")) {
```
This will route the call to the correct include file.

**Comment by michaeltrego** [comment]
We have a currently active competition on hosted v2.1.6 experiencing this issue.  Will we see this corrected in the hosted version?

**Comment by geoffhumphrey** [comment]
All hosted sites have been updated with the latest committed code as of today. Good to go!

**Comment by dogunter** [comment]
Thanks for the quick fix on this!

**Comment by michaeltrego** [comment]
Thanks Geoff!
