### ISSUE TITLE
BCOE&M v 2.1.6: Stewards are asked if they're willing to judge

### ISSUE THREAD

**Issue by dogunter** [geoffhumphrey/brewcompetitiononlineentry#681]
In sections/register.sec.php around line628, $brewer_text_006 is used a second time for a section on stewarding. It should be $brewer_text_015, "Are you willing to serve as a steward in this competition?".

**Comment by geoffhumphrey** [comment]
Confirmed. Changing line 609 to read:
```
<p><?php echo $brewer_text_015; ?></p>
```
...will fix this error.

Thanks for reporting!
