### ISSUE TITLE
Disable Judging and Stewarding under new user registration

### ISSUE THREAD

**Issue by vstoms** [geoffhumphrey/brewcompetitiononlineentry#686]
Is there any options to disable judge and steward when an user is creating an new account?

**Comment by geoffhumphrey** [comment]
Yes, but in a roundabout way. If you no longer wish to have users register as judges and/or stewards, go to Admin > Preferences > Competition Organization Preferences and set the Judge Limit and/or Steward Limit to a number below your current count of each.

This applies to 2.1.0 and later versions only...

**Comment by geoffhumphrey** [comment]
Version 2.1.8 and 2.1.9 separated the registration process, forcing users to choose between three roles: Entrant, Judge, a Steward. If you no longer wish to accept judge and/or steward accounts, follow the procedure above and it will only be possible to accept entrant only accounts.
