### ISSUE TITLE
assigning tables to rounds does not persist changes

### ISSUE THREAD

**Issue by kenhohl** [geoffhumphrey/brewcompetitiononlineentry#687]
We've been using BCOEM for our competition for 4 years and have had the problem the entire time.  We upgraded to the latest version (2.1.4) a few months ago.  When we assign tables to rounds (we have 2 rounds) the change does not persist even if we repeatedly assign a table to a round.  I have gotten around the issue by manually entering the desired round for each table directly in the database.  Surprised others are not having the same issue because I did not see an existing issue for it.

**Comment by geoffhumphrey** [comment]
Confirmed. We'll get it into the bugfix queue.

Thanks for reporting!

**Comment by kenhohl** [comment]
Can you possibly tell me the files and versions of them that were changed for this fix?  That would be greatly appreciated.  We are using a highly customized version of BCOEM and it's too difficult to upgrade to the latest version of BCOEM that includes this fix and merge all our enhancements back into it.  Thank you!

**Comment by geoffhumphrey** [comment]
Check the following files:
- /includes/process/process_judging_flights.inc.php
- /includes/process/process_judging_flight_check.inc.php
- /includes/process/process_judging_tables.inc.php
