### ISSUE TITLE
Judge registered entries but did not drop them off, is still listed as having entries on those tables.

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#688]
We have a judge who registered a bunch of entries across multiple categories, but never actually dropped off his entries and didn't remove them from the system. (In my experience pretty much no one ever goes in and removes entries they are no longer entering... :o(   )

During judge assigning he is still listed as having entries in these categories, even though those bottles are not marked as paid or received.

Not sure if this is a bug report, or a feature request to modify how judge entries are reported during judge assigning, or maybe just a heads-up to a quirk that needs to be considered during assigning.

Cheers!

**Comment by geoffhumphrey** [comment]
Confirmed. Luckily, it's easily fixed... on line 942 (version 2.1.7) of /lib/admin.lib.php add `AND brewReceived = '1' ` to the MySQL query. It should look like this after adding:
```
$query_entries = sprintf("SELECT COUNT(*) as 'count' FROM %s WHERE brewBrewerID='%s' AND brewCategorySort='%s' AND brewSubCategory='%s' AND brewReceived='1'", $prefix."brewing", $bid, $row_style['brewStyleGroup'],$row_style['brewStyleNum']);
```
Re-upload the file and you'll be good to go.
