### ISSUE TITLE
Ability to hide Brewer's Specifics

### ISSUE THREAD

**Issue by buergermeister75** [geoffhumphrey/brewcompetitiononlineentry#689]
We'd like the ability to turn off the Brewer's Specifics box on the Add and Edit Entry screens. It's confusing some of our entrants and our judges will never see it since we don't include it on our judging labels.

**Comment by ercousin** [comment]
That functionality was added in 2.1.5 I think

**Comment by geoffhumphrey** [comment]
Yes, this was incorporated into version 2.1.5, released on August 31, 2016.

**Comment by buergermeister75** [comment]
Okay. We're running 2.1.4. Will check on my next competition install.
