### ISSUE TITLE
Installing Database Tables Error

### ISSUE THREAD

**Issue by davespring71** [geoffhumphrey/brewcompetitiononlineentry#691]
When I go to install my database tables, this comes up and stops me from continuing. 

Incorrect string value: '\xF8 port...' for column 'brewStyleComEx' at row 1

**Comment by bforrest** [comment]
I just got the same error.

**Comment by bforrest** [comment]
![screenshot from 2016-11-24 22-39-02](https://cloud.githubusercontent.com/assets/275559/20614675/0989b026-b297-11e6-804a-9261c8a9397d.png)
![screenshot from 2016-11-24 22-39-27](https://cloud.githubusercontent.com/assets/275559/20614676/0b6a79b6-b297-11e6-9eb1-e6275508a012.png)

**Comment by bforrest** [comment]
The default MySQL database creates a db with a Latin-1 character-set, not utf-8. I updated the character set of my database, but that wasn't the final fix. Once I saved the install_db_setup.php file "with utf endcoding" I was able to successfully get the database configured and installed. Is there a place where I can submit a pull request to update the installation instructions?
