### ISSUE TITLE
Winner's Lists (Report) Do Not Include BOS Places

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#692]
At the end of the judging, there are options under Reports to print out the list of winners (with or without scores) for reading during the awards ceremony, but these do not include the BOS winners.

I don't recall if the v1.x.x version of the software printed the BOS winners or not, I'm thinking it did?

The BOS winners do print out on the award labels. They are not included in the HTML or PDF downloads.

**Comment by geoffhumphrey** [comment]
Confirmed. There was a separate report for BOS in the pre-2.0.0 Admin Dashboard code that didn't make it into the converted codebase. This is fixed in the latest commit and can be found on the Admin Dashboard under Reports > After Judging.
