### ISSUE TITLE
XML Organizers Report doesn't include Staff points

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#693]
I submitted the XML to the BJCP; Dave Houseman replied asking to confirm that I didn't assign any staff points. I did (one point each to two different people), and this shows up on the printed report but not in the XML -- those two people were listed as "Judge" with 1 point, as opposed to "Staff + Judge" and 2 points.

**Comment by BrewDrinkRepeat** [comment]
Update: I'm told that spaces are required in the XML file for the JudgeRole field. For example, it should say:
<JudgeRole>Judge + BOS</JudgeRole>

but the current BCOEMS-generated XML says:
<JudgeRole>Judge+BOS</JudgeRole>

The full Organizers Report XML spec is here:
http://www.bjcp.org/it/docs/BJCP%20Database%20XML%20Interface%20Spec%202.1.pdf

**Comment by geoffhumphrey** [comment]
Confirmed. There is some legacy scripting that prevents those assigned as staff from being output on the XML and PDF BJCP Point report exports. 

The correct JudgeRole syntax will also be incorporated.

The files will be updated in the next commit and the next release.
