### ISSUE TITLE
Clicking Judge does not change the default in Steward

### ISSUE THREAD

**Issue by johnhaven** [geoffhumphrey/brewcompetitiononlineentry#696]
When folks click "yes" on Judge, the default for Steward remains a "yes". Most judges do not continue after clicking "yes" for judging, so my Steward list contains most of my judges. I can fix this by editing the judge info, but that's a lot of work. Please make the steward default change to "no" when the judge is a "yes".

**Comment by BrewDrinkRepeat** [comment]
+1. I'd say 25 - 35% of my judges do not de-select Steward, so until I go through and compare the two lists I think I have more stewards signed up than I really do.
