### ISSUE TITLE
Enhancement: We need a category for Staff

### ISSUE THREAD

**Issue by johnhaven** [geoffhumphrey/brewcompetitiononlineentry#697]
I have Judges, Stewards and Staff members, but they can only sign-up as a Judge or Steward. Please add a Staff category, so the folks that are not judges or stewards can also sign-up. This can also be important when doing the organizer's report.  Thanks

**Comment by geoffhumphrey** [comment]
For the next version, 2.1.9, users will be able to designate whether they wish to be considered to be a staff member. Admins will still need to assign users from the pool as staff members for BJCP points to be allotted.
