### ISSUE TITLE
Brewer of the Year

### ISSUE THREAD

**Issue by michaeltrego** [geoffhumphrey/brewcompetitiononlineentry#699]
Is there a way to create a custom award category for Brewer of the Year (and Cidermaker and Meadmaker)?  It appears as though Custom Categories allows you to place an entry as a winner in that custom category, but I would like to be able to place an entrant as the winner of a category.  Possible?

If not, perhaps consider it as an enhancement request.  Thanks.

**Comment by geoffhumphrey** [comment]
I'm evaluating for inclusion code authored by our friend in Brazil, Ricardo Rosa (@rmrosa) that may be able to be adapted to do what you're requesting. Take a look - https://github.com/geoffhumphrey/brewcompetitiononlineentry/pull/669.

**Comment by michaeltrego** [comment]
That appears to be a very close match to what we are doing manually.  I think it would be a great addition.  Thanks!

**Comment by geoffhumphrey** [comment]
Best Brewer and Best Club functionality/display will be incorporated in the next release.
