### ISSUE TITLE
Error when opening Entrant-Participant

### ISSUE THREAD

**Issue by glienhard** [geoffhumphrey/brewcompetitiononlineentry#701]
I did the browser install and all seemed to go fine.  But when I try to manage either of the Entries and Participants links I get the following error: 

/index.php?section=admin&go=participants
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

Everything else seems to be working fine.

**Comment by geoffhumphrey** [comment]
@glienhard, are you still receiving this error? I'm not able to recreate it in any of my test environments.

**Comment by glienhard** [comment]
@geoffhumphrey, yes I am.  I ended up installing a separate instance of 1.3.0.3 and it is working just fine.  I did notice that I was able to manually entry a participant in v2.1.7.  It does show me on the home page that there are two registered participants but when I go to the admin pages to manage them I get the error above.

**Comment by glienhard** [comment]
Update: I believe I figured out what caused the issue.  During the initial competition setup screens I nav'd away from the setup.  This was causing the error I reported.  I setup a new instance and went all the way through the setup and did not have any further problems.
