### ISSUE TITLE
UX: Custom Category parameters

### ISSUE THREAD

**Issue by kstec** [geoffhumphrey/brewcompetitiononlineentry#703]
Custom category parameters and description should be viewable/accessible from the Info page without the brewer having to start filling out an entry form.

**Comment by geoffhumphrey** [comment]
The names of the accepted sub-styles that have entry requirements (including custom categories) will be clickable links on the Info page. Clicks will result in a modal that feature the sub-category's description and its required entry parameters. See http://test.brewcomp.com/entry for a demo.
