### ISSUE TITLE
Missing Set Website Preferences button

### ISSUE THREAD

**Issue by julien-gibson** [geoffhumphrey/brewcompetitiononlineentry#705]
The Set Website Preferences button is not being displayed at the bottom of the Administration: Website Preferences page.

Looking at the page source and comparing it to the page source of the Competition Organization Preferences page (where the equivalent button displays just fine), I can't see any problems.  I get the same result in IE, Firefox and Chrome.

V2.1.7
PHP 5.4.45
mysqli 5.6.33

**Comment by julien-gibson** [comment]
More info:
Apart from the button not being displayed, which is I think due to no theme being loaded, the preferences on this page are not being saved when I hit enter from a text field.

**Comment by geoffhumphrey** [comment]
I'm investigating why the preferences are not being saved on setup. In the meantime, adding a record in the preferences DB table with an id of 1 will allow you to then edit your site preferences to your liking via Admin.

Another option would be to copy and run the SQL command in the /sql/bcoem_baseline_2.1.X.sql (lines 785-786).
