### ISSUE TITLE
In Registration: Question about Stewarding asks about Judging

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#706]
This is v2.1.7.

In register.sec.php, the prompting question about Stewarding "Are you willing to serve..." is the question about judging. A new string is needed to ask a question about willing to "steward". Line 609 is the line that needs to reference the new string.

**Comment by geoffhumphrey** [comment]
Confirmed. Fixed in the latest commit.
