### ISSUE TITLE
Link for "pay your entry fees" in "My Account" does not work.

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#707]
The sentence that says "Take a moment to review your entries or **_pay your entry fees_**." in the Your Account page has two links in the sentence. The link for "**_pay your entry fees_**" does not work.

This is v2.1.7.

**Comment by geoffhumphrey** [comment]
Same as Issue #676 - fix will be incorporated into the next release. 2.1.8.
