### ISSUE TITLE
No Submit Button on Judge/Steward Register Page

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#711]
Entrant page seems to work fine but there is no submit button on the judge/steward register pages....

2.1.8

![image](https://cloud.githubusercontent.com/assets/1551339/21275978/5a52b6b2-c39d-11e6-92e8-d6c5184adb80.png)

**Comment by geoffhumphrey** [comment]
Unfortunately, I'm not able to replicate this issue on any 2.1.8 installation that I've accessed. Do you have a limit in place for the number of judges and/or stewards to register? The fields that are missing are the ones associated with judging/stewarding preferences. Also missing, but should not be, is the CAPTCHA field. 

Here are the examples I viewed:
- http://brewoff.brewcomp.com/register/judge
- http://brewoff.brewcomp.com/register/steward
- http://bierederock.com/register/judge
- http://bierederock.com/register/steward
- http://oshc.brewcomp.com/index.php?section=register&go=judge
- http://oshc.brewcomp.com/index.php?section=register&go=steward

Are you OK with providing a URL so I can do more troubleshooting? Also, if you have access to server error logs for the root of your installation, those would be helpful too.

**Comment by ercousin** [comment]
Seasonal.gtabrews.ca

**Comment by geoffhumphrey** [comment]
I see the issue. There's some scripting that is screwing up the DOM (a `<div>` was not closed). The attached file will fix this issue. Download, unzip, and upload it to your /sections/ directory.
[register.sec.php.zip](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/658438/register.sec.php.zip)
