### ISSUE TITLE
Enhancement: Include Table Name in title of all pages in Pullsheet report

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#714]
I am requesting the inclusion of the table name at the top of all the pages in a pullsheet report.

Currently the first page of the first flight has the table name at the top like this "Table 1: PALE LAGER".

The second and third flight pages only have a title something like this: "Table 1, Flight 2, Round 2". I would like to see "Table 1 _: PALE LAGER_ , Flight 2, Round 2" in the 2nd flight and higher flights.

This is v2.1.8.

Thanks.

**Comment by geoffhumphrey** [comment]
No problem. To do this, in the /output/pullsheets.output.php file, change line 45 AND line 161 to:
```
<h4><?php echo sprintf("%s %s: %s - %s %s, %s %s",$label_table,$row_tables['tableNumber'],$row_tables['tableName'],$label_flight,$i,$label_round,$row_round_check['flightRound']); ?></h4>
```
