### ISSUE TITLE
Designation "Experienced Judge" for None/Novice

### ISSUE THREAD

**Issue by westerman** [geoffhumphrey/brewcompetitiononlineentry#717]
I believe that this is a bug instead of what you want.  A Novice/None judge will receive the designation "Experienced Judge".   This arises from the switch statement in common.lib.php around line 2115 in method 2 of designations function.  After case "Novice" I believe you are missing a 

return = "";
break;

**Comment by geoffhumphrey** [comment]
For the next version, line 2116 will return a more benign (and in all cases of non-certified judges, more accurate) "Non-BJCP Judge" instead of "Experienced Judge."
