### ISSUE TITLE
Datetime picker does not work when using local libraries

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#719]
Using v 2.1.8. The picker does not come up using local libraries.

**Comment by jimmyorkin** [comment]
I found a problem in the steps to load the libraries locally. In the steps to load tinymce, the set says "Rename the folder to tincymce". It should not have the "c" in the new name.

Also, there is a difference in the "load_cdn_libraries.inc.php" vs "load_local_libraries.inc.php" file for "moment-with-locales.js" reference. The CDN include has a .min. in the name. the local does not have .min. in the name.

The step to load the "moment-with-locales.min.js" file should say load it into the "js" directory.

**Comment by geoffhumphrey** [comment]
@jimmyorkin - thanks for reporting. I've noted that and will review and update the code and accompanying instructions for the next release.

**Comment by geoffhumphrey** [comment]
Instructions have been updated: http://brewcompetition.com/local-load.

**Comment by jimmyorkin** [comment]
One more fix. In the instructions the line under "Bootstrap 3 Date/Time Picker", 5. Access the Moment With Locales file, The link to the file should be to: http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.1/moment-with-locales.min.js. It needs the file with the .min. in the name.
