### ISSUE TITLE
All grid views showing no records

### ISSUE THREAD

**Issue by whenyeastattack** [geoffhumphrey/brewcompetitiononlineentry#720]
Using 2.1.8.  Every screen that shows a grid view of data records is failing to render any of the rows within the grid view.  For example, I have added three contacts to the system and contacts page looks as if there are no contacts.  

![image](https://cloud.githubusercontent.com/assets/14093069/21742153/b3de3f88-d4b6-11e6-8106-2384416c056e.png)

The same goes for the participants list, sponsors list, etc.  They all appear to have no data when there is in fact data in the system.  A category with no data does not render a grid view at all, but rather prints "No entries have been added to the database yet" to the screen.  Those that do have entries render an empty grid view.

**Comment by whenyeastattack** [comment]
I deleted my database and went through initial setup again and now the data is showing up in the grid views.  Something must have failed during my first attempt at initial setup.  No errors were displayed at any point, though.

**Comment by jimmyorkin** [comment]
I did see a problem when I was going through the initial setup process on 2.1.7 I believe. I clicked on something to get an explanation and the setup went awry. I deleted the database and walked back through the setup and it worked ok,

**Comment by geoffhumphrey** [comment]
The setup process will be fully reviewed for any such potential problems. If such problems do come up in the meantime, there is always the [fallback installation procedure](http://brewcompetition.com/install-instructions#fallback).
