### ISSUE TITLE
Wrong timezone locale displayed

### ISSUE THREAD

**Issue by elronalds** [geoffhumphrey/brewcompetitiononlineentry#721]
Is it possible to disable the timezone from being displayed for the dates in BCOE&M 2.1.8?  I have my timezone set to GMT +10 for Brisbane time, but the time zone is showing as ChST which isn't what our locale uses.

Where in the PHP code can I disable this from being shown or can I display this as GMT+10 instead?

**Comment by geoffhumphrey** [comment]
@elronalds, the time zone displayed utilizes php's native ```date()``` function based upon what you've defined in preferences. 

If you don't want to display the time zone, you'll need to alter the getTimeZoneDateTime function in the /lib/date_time.lib.php file to eliminate all ```date('T',$timezone)``` calls. This is the easiest and most expedient way to not show the time zone abbreviation.
