### ISSUE TITLE
2.1.8: 21B and 27A Entries Do Not Save as BJCP "Example" Style

### ISSUE THREAD

**Issue by schyzac** [geoffhumphrey/brewcompetitiononlineentry#722]
01D: American Wheat Beer - doesn't keep saved information (text) - Required Info
13A: Dark Mild - doesn't keep saved information (text) - Required Info
21B: Black IPA - doesn't keep saved information (text) - Required Info - change it to "Black IPA;"
27A: Gose - doesn't keep saved information (text) - Required Info and everytime entry is Unconfirmed
29A: Fruit Beer - OK

**Comment by geoffhumphrey** [comment]
Thanks for reporting. Regarding what you wrote, I'm assuming you're using version 2.1.8. If not please advise on the version you are using.

1D and 13A do not require any additional information and the Required Info box should be hidden. Is it showing on your installation?

For the Black IPA (21B) and Gose (27A) there is a confirmed issue that has to do with the limit of characters of a row in the MySQL DB. To be compatible with BCOE&M's schema, the examples provided by the BJCP needed to be entered as sub-categories (even though they aren't expressly classified as such by the BJCP). Hence why Black IPA in BCOEM is 21B2 and Gose 27A1. The extra character is the issue when the program is trying to save the info into the DB.

To fix the problem, access your DB via phpMyAdmin or other means and run the following command (be sure to add your installation's prefix before _brewing_ in the table name if you are using one):
```
ALTER TABLE `brewing` CHANGE `brewCategory` `brewCategory` VARCHAR(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL, 
CHANGE `brewCategorySort` `brewCategorySort` VARCHAR(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL, 
CHANGE `brewSubCategory` `brewSubCategory` VARCHAR(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL;
```
This will alleviate the issues encountered with 21B and 27A entries.

Code will be included in the next release to address this issue.

**Comment by schyzac** [comment]
Yes, I'm using 2.1.8
Required Info box is not hidden for all categories. But I want to use it for additional / optional infornation for entries such Plato or OG. But these information are automatically removed.

I'll try to update DB with provided command. Black IPA and Gose are selected as subcategories.

**Comment by geoffhumphrey** [comment]
If you wish to collect further information for subcategories that do not require additional information, be sure to enable the "Brewer's Specifics" field and encourage your entrants to utilize it to enter the information you are seeking.

**Comment by schyzac** [comment]
Thanks a lot for your help.
Can you navigate me where I can enable the "Brewer's Specifics" field (Required Info box) for 01D: American Wheat Beer as example?

**Comment by geoffhumphrey** [comment]
Certainly. Log in as an admin. Then go to the Admin Dashboard > Preferences > Website. In the "Entries" section of the website preferences page, choose "No" for the "Hide Brewer's Specifics Field" item.

Please note that the application will not "force" users to enter information into the Brewer's Specifics field. You'll need to do some follow up with entrants that do not provide the information your particular competition is looking for.

**Comment by schyzac** [comment]
Thank you very much.
