### ISSUE TITLE
brewSubCategory length too short

### ISSUE THREAD

**Issue by madcameron** [geoffhumphrey/brewcompetitiononlineentry#724]
The brewSubCategory datatype in the brewing table is too short, needs to be char(2) to work with the Speciality IPA sub categories (though I guess it really should be varchar(3) to match the brewStyleNum column in the styles table)

**Comment by geoffhumphrey** [comment]
Yes. Thanks for reporting. Please see Issue #722 for a fix. Also, this is addressed in the latest commit and will be in the next release.
