### ISSUE TITLE
User Can't make a payment

### ISSUE THREAD

**Issue by rrbrew2010** [geoffhumphrey/brewcompetitiononlineentry#726]
User added an entry, then when he goes to pay he's taken back to the home page.   He tried this on IE, Edge, Chrome and Firefox, latest versions.   Every time he clicks on pay it goes to the home page.

**Comment by geoffhumphrey** [comment]
This may be a symptom of the search-engine friendly URLs option that can be turned on or off via Admin > Preferences > Website Preferences. Make sure that is turned off.

In any case, please provide a URL so I can do some troubleshooting.

**Comment by rrbrew2010** [comment]
That fixed the issue for us Geoff!

 

Thanks!!

Pete
