### ISSUE TITLE
Users unable to log into the system

### ISSUE THREAD

**Issue by buergermeister75** [geoffhumphrey/brewcompetitiononlineentry#727]
I've been getting some sporadic complaints from users not being able to log in. I remedied the issue by logging in as admin and reset their passwords. 

Unfortunately now I'm unable to login as an admin myself. I'm getting the following error message:
"You must log in and have admin privileges to access the 2017 Midwinter administration functions."
Regular users are getting "Please log in to access your account."

I've checked my error logs and nothing is out there. I've attempted to reset my password and that is not working either. 

Looks like this was reported earlier by someone but I'm not seeing a resolution out there. I'm running v2.1.8.  Please help!

**Comment by geoffhumphrey** [comment]
Bruce, are you able to log in or are you completely locked out? If you're able to log in, but not an admin, to get you back going again, access your DB directly, find your record in the users table and change your user_level to 0. Or, restore the users table from a backup.

If that doesn't work, add the "fallback" admin user from the /sql/bcoem_baseline_2.1.X.sql file. 

In the users table run the following query:
```
INSERT INTO `baseline_users` (`id`, `user_name`, `password`, `userLevel`, `userQuestion`, `userQuestionAnswer`, `userCreated`) VALUES
(NULL, 'user.baseline@brewcompetition.com', '$2a$08$2qgODWiSaYfLTVhu.2qVSer30aG7cLQZX0To01CqinyFyUbwdO64C', '0', 'What is your favorite all-time beer to drink?', 'pabst', '2016-09-01 01:00:01');
```
Once that is inserted, make note of the id of the new record. That will be the uid of the corresponding record in the brewer table. Then, run this query in the brewer table, replacing X with the id from the user table:
```
INSERT INTO `baseline_brewer` (`id`, `uid`, `brewerFirstName`, `brewerLastName`, `brewerAddress`, `brewerCity`, `brewerState`, `brewerZip`, `brewerCountry`, `brewerPhone1`, `brewerPhone2`, `brewerClubs`, `brewerEmail`, `brewerStaff`, `brewerSteward`, `brewerJudge`, `brewerJudgeID`, `brewerJudgeMead`, `brewerJudgeRank`, `brewerJudgeLikes`, `brewerJudgeDislikes`, `brewerJudgeLocation`, `brewerStewardLocation`, `brewerJudgeExp`, `brewerJudgeNotes`, `brewerAssignment`, `brewerJudgeWaiver`, `brewerAHA`, `brewerDiscount`, `brewerJudgeBOS`, `brewerDropOff`) VALUES
(NULL, X, 'Default', 'Admin', '1234 Main Street', 'Anytown', 'CO', '80001', 'United States', '123.456.7890', NULL, NULL, 'user.baseline@brewcompetition.com', 'N', 'N', 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
```
Log in as the new Admin user (see the /sql/bcoem_baseline_2.1.X.sql file for details) and go from there.

I'll dig into the code to figure out why your account, as an admin, was suddenly locked out due to changing another user's password on their behalf. Codewise, they're apples and oranges. Fun.

**Comment by buergermeister75** [comment]
Hi Geoff,

It's sporadic now and very similar to this thread -
https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/587

I played with the database as you suggested and it didn't help. It's like
the person stated in the thread, it looks like it's logging in and can tell
that I'm using the correct password, but then it says that I don't have the
proper credentials. The error message changes if I use a correct password
vs an incorrect one. It also changes if I change the value in the
user_level field to 2, 0 and even 1 using a correct password vs an
incorrect one.

Nothing is showing up in the error log pertaining to this. I suspect that
there is a global variable or something getting cached on the server
somewhere that is conflicting between an older session and a new one that's
attempting to log in.

Email me directly if you'd like me to send you our cPanel or PHP_info file.

Thanks - Bruce

**Comment by geoffhumphrey** [comment]
Yes, that does sound like it could be a factor. Just spit-balling here for now. Try adding the following code to the /includes/db/common.db.php file (this file defines session data):
```
// Check for last activity session variable and determine if it's over 24 minutes (php default)
// If so, reset the session
if (isset($_SESSION['last_activity']) && (time() - $_SESSION['last_activity'] > 1440)) {
    session_unset();
    session_destroy();
}

// Store the time this script ran
$_SESSION['last_activity'] = time();

// Define when the user started their browsing
if (!isset($_SESSION['created'])) $_SESSION['created'] = time();

// Check whether the created session variable is more that 24 minutes ago
// If so, regenerate the created session variable
elseif (time() - $_SESSION['created'] > 1440) {
    session_regenerate_id(true);
    $_SESSION['created'] = time();
}
```
In addition to this, advise those with this issue to clear their local cache and cookies as well.

**Comment by jimmyorkin** [comment]
I don't know if it is relevant but we has a case where PHP seemed to be a current version but was not and caused some login problems related the session. You might check you PHP version.

**Comment by geoffhumphrey** [comment]
In any case, the php code in my previous post will be incorporated into the next version. I'll keep digging though.

**Comment by buergermeister75** [comment]
Looks like the code update has done the trick. I haven't experienced any
new issues and none have been reported to me. The final deadline is Feb 4th
so I'm sure crunch time will further test this.

**Comment by buergermeister75** [comment]
Thank you very much for the quick turn around time and attention on this
one!
