### ISSUE TITLE
Paid Column with a STAR next to the Paid checkbox

### ISSUE THREAD

**Issue by rrbrew2010** [geoffhumphrey/brewcompetitiononlineentry#729]
When I sort on Entries, I see several entries with an empty Star next to the Paid checkbox.   What does this Star mean?

**Comment by geoffhumphrey** [comment]
Those stars indicate that the "owner" of that particular entry paid a discounted fee for that entry. For the next version, I'll add some tooltip text on hover explaining that (which I should have done in the first place).

**Comment by rrbrew2010** [comment]
right on, thanks for that info.


Sent from my Samsung device

-------- Original message --------
