### ISSUE TITLE
As Brewer-Participant cannot edit entry

### ISSUE THREAD

**Issue by dducrest** [geoffhumphrey/brewcompetitiononlineentry#734]
Hey guys,

In the Action cell of the entry list, I cannot edit or delete entry information.

![screen shot 2017-02-15 at 11 05 26 pm](https://cloud.githubusercontent.com/assets/2745258/23007019/68d1a00c-f3d3-11e6-96c6-aaf5743b136a.png)

Reference URL: http://homebrewclassic.brewcompetition.com/list#entries
Site Version: BCOE&M 2.1.9

As admin, do I have to enable something to make this action possible for my participants?

**Comment by geoffhumphrey** [comment]
David, take a look at your judging location date(s). If any one date/time has past, the program will hide the edit and delete links.

**Comment by dducrest** [comment]
Yup that was it. Thanks!
