### ISSUE TITLE
2.1.9 Clean Installation

### ISSUE THREAD

**Issue by vortexofhate** [geoffhumphrey/brewcompetitiononlineentry#737]
MySQL 5.7, PHP 5.6

When I attempt a clean installation, I get the following error:

>  Incorrect string value: '\xF8 port...' for column 'brewStyleComEx' at row 1

**Comment by geoffhumphrey** [comment]
I believe this has to do with the default character set of your DB. 

For 2.1.9, the default character set for all tables was established to be utf8mb4 - the setup script alters your DB to utilize that character set and sets the collation to utf8mb4_unicode_ci automatically. 

For other versions, you'll need to manually make sure the DB's default character set is utf8mb4 and its collation is set to utf8mb4_unicode_ci or utf8mb4_unicode_520_ci. Here's the MySQL command to do that:

``ALTER DATABASE `database_name` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci``

**Comment by geoffhumphrey** [comment]
Also, there is a known issue with a 2.1.9 installation. See Issue #732.

**Comment by Zvish** [comment]
I also encountered this issue and the WA didn't worked for me.
Still getting the error:
_Notice: Undefined variable: entry_closed in /home/X/public_html/X/lang/en/en-US.lang.php on line 608
Incorrect string value: '\xF8 port...' for column 'brewStyleComEx' at row 1_

**Comment by geoffhumphrey** [comment]
That particular character that is throwing the error is ø - which there is an instance of on line 1101 in the install_db.setup.php file (v2.1.9). Changing that character to the HTML equivalent (`&oslash;`) might be a solution.

I couldn't replicate the error in my environment, so if you would, please try this solution out and report back whether it worked for you.

**Comment by Zvish** [comment]
Hi,
There where several bad chars on the file, I fixed all of them and the database installation passed
Attaching the fixed file here.

[install_db.setup.php.txt](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/818064/install_db.setup.php.txt)
Thanks
Zvi
