### ISSUE TITLE
Many notifications about en-US.lan.php

### ISSUE THREAD

**Issue by Zvish** [geoffhumphrey/brewcompetitiononlineentry#739]
Hi,
I am getting many notifications on participants screen, is it ok?

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 147

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 446

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 480

Notice: Undefined variable: go in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 483

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 570

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 602

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 603

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 605

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 607

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 610

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 613

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 615

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 617

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 622

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 627

Notice: Undefined variable: j_s_text in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 627

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 629

Notice: Undefined variable: j_s_text in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 629

Notice: Undefined variable: judge_closed in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 629

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 664

Notice: Undefined variable: php_version in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 664

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 677

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 709

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 709

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 709

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 709

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 709

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 739

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 750

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 816

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 874

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 874

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 912

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 918

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 955

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 991

Notice: Undefined variable: action in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 991

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 1128

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 147

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 446

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 480

Notice: Undefined variable: go in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 483

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 570

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 602

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 603

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 605

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 607

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 610

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 613

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 615

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 617

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 622

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 627

Notice: Undefined variable: j_s_text in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 627

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 629

Notice: Undefined variable: j_s_text in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 629

Notice: Undefined variable: judge_closed in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 629

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 664

Notice: Undefined variable: php_version in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 664

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 677

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 709

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 709

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 709

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 709

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 709

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 739

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 750

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 816

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 874

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 874

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 912

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 918

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 955

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 991

Notice: Undefined variable: action in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 991

Notice: Undefined variable: section in /home/bhomebre/public_html/mevashlim/lang/en/en-US.lang.php on line 1128

Thanks,
Zvi

**Comment by geoffhumphrey** [comment]
Zvi, thanks for reporting... Which version are you running? In the current version, this should not be happening as the url_variables.inc.php file is included prior to the language.lang.php file in bootstrap.php file (which is called on every page load).

In any case, these aren't critical errors - you can turn off the notices by commenting out ``error_reporting(E_ALL)`` and un-commenting ``error_reporting(0)`` in the paths.php file. So, it should look like this:
```
error_reporting(0);	// comment out to debug
//error_reporting(E_ALL); // uncomment to debug 
```
If that doesn't work, you will need to update your php.ini file on the server and set ``display_errors`` to 0.

**Comment by Zvish** [comment]
That's what I did
Thanks
