### ISSUE TITLE
Address labels w/ entry numbers

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#741]
It would tremendously useful to have the option to print address labels (5160 template, as usual) that also includes the entrant's entry and/or judging numbers (whichever were used for the judging) on the stickers, to ease in scoresheet sorting and mailing.

For example:

<img width="620" alt="screen shot 2017-03-09 at 4 00 47 am" src="https://cloud.githubusercontent.com/assets/18423016/23742998/0662c60c-047d-11e7-98c1-01be796861ee.png">

**Comment by jimmyorkin** [comment]
A different take for I assume the the same problem.

We are using BCOEM for the Bluebonnet which has 1312 entries this year. We have over 300 brewers in the competition this year.

We use the Brewer ID to file all the brewer's scoresheets. I wrote a webpage that queries the DB with the Judging number and returns the Brewer ID number. We write the brewer ID number on the top of the scoresheets and file the scoresheets in hanging folders with the brewer number on them.

I wrote a query to get the brewer ID, count of entries and address information and used that data in Word to create the address labels.

This is another way that might satisfy the requirement. It would be good to get something in that would help with filing and mailing the scoresheets.

**Comment by geoffhumphrey** [comment]
My memory is foggy on this, but I seem to remember that this was a feature in a version prior to 2.0.0 (the conversion). I will investigate further...

**Comment by geoffhumphrey** [comment]
Adding entry or judging numbers after the address is certainly possible. Due to space limitations, the entry or judging numbers listed on the label will be limited to the first 20 in the U.S. and 15 elsewhere.

This will be available in the next version.
