### ISSUE TITLE
When editing, brewCarbonationNotes field is populated by brewWaterNotes value

### ISSUE THREAD

**Issue by mbdriscoll** [geoffhumphrey/brewcompetitiononlineentry#742]
When editing a beer entry in version 2.1.9, the `brewCarbonationNotes` field seems to be populated by the `brewWaterNotes` value. A cursory grep reveals both those keys at [brew.sec.php:1136](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/e7b7661d69b8f18713be307a9f033d64bf415c32/sections/brew.sec.php#L1136) . The backend seems to work fine.

**Comment by geoffhumphrey** [comment]
This will be corrected in the next version.
