### ISSUE TITLE
Unable to sign in when using Safari

### ISSUE THREAD

**Issue by schmidtkvn** [geoffhumphrey/brewcompetitiononlineentry#743]
After typing in the correct username and password I see the following in Safari. Works fine in Chrome. This has been reported by 2 participants of my competition and reproduced on my own machine.

<img width="1291" alt="screen shot 2017-03-11 at 11 35 31 am" src="https://cloud.githubusercontent.com/assets/13227820/23826319/09caf7aa-064f-11e7-9b1a-099c125264ff.png">

**Comment by schmidtkvn** [comment]
FWIW I've received more than a dozen complaints about this issue. And that is just the people that bother to email me. I'm worried that there are others who just give up :-(

**Comment by geoffhumphrey** [comment]
Verified - **but ONLY for the domain in your screenshot**. 

Apparently, a user-specific session isn't being created and/or accepted by the Safari Browser on Mac. When I tested, it appears that users are able to register (their registration information, username, and password are accepted and an account is created for them), but they aren't able to log in. 

I was able to create user accounts on three other sites using the same Mac running Safari, so this appears to be an issue specific to your web server regarding PHP sessions. You may need to call your hosting company. The JS reference error in your screenshot does not have anything to do with the issue - the same error was present when I was able to successfully log into other sites using Safari.

A work around at this time is to advise Mac users to utilize Chrome or Firefox (see screens below).
Firefox:
![screen shot 2017-04-14 at 11 51 21 am](https://cloud.githubusercontent.com/assets/5216502/25051247/ec819fe4-2108-11e7-95ca-9a1afa549ba4.png)

Chrome:
![screen shot 2017-04-14 at 11 51 34 am](https://cloud.githubusercontent.com/assets/5216502/25051248/ec881964-2108-11e7-9ff6-93cb8ac7097f.png)

**Comment by schmidtkvn** [comment]
Hmm . . .you are right. I think it has something to do with cookies and the domain vs IP address. For example if you look at network traffic when navigating to the login page it is actually going to 146.148.36.4/index.php?section=login rather than competition.cascadebrewersguild.com/index.php?section=login. So perhaps I have a misconfiguration somewhere?

I've tried to set apache's ServerName, update the hosts file, and $base_url in config.php (the last made things worse so I reverted my change). Any suggestions?

**Comment by geoffhumphrey** [comment]
Unfortunately, I don't have any suggestions beyond what you've tried - except for contacting your hosting provider and working directly with them. Probably a long-shot, though. I searched StackOverflow, etc. and came up with nothing relevant or even related. In other words, I'm stumped. I'll keep looking.
