### ISSUE TITLE
Need staff member to have access to administrator dashboard

### ISSUE THREAD

**Issue by jodygrenert** [geoffhumphrey/brewcompetitiononlineentry#744]
Geoff,
This may be a feature request, but I'd like to 3 of my competition staff members to have access to the admin dashboard, as I do as competition organizer. Is there a way to do this?

Jody

**Comment by geoffhumphrey** [comment]
Hey Jody, yes, you can "promote" any registered user to an admin role. There are three distinct roles for all users: Participants, Admin, and Top-Level Admins.

To change a registered user's user level, access the Admin > Entries and Participants > Participants list. There are a series of icons on the right for each of your participants - click the lock icon. This will provide you the opportunity to change that account holder's user level.

![2017-03-14_10-12-50](https://cloud.githubusercontent.com/assets/5216502/23910471/7289c81e-089f-11e7-8e54-6924df6c57fc.jpg)

Note the definitions for each user level. My suggestion would be to choose "Admin" for those staff members you wish to have access to the Admin Dashboard.

![2017-03-14_10-14-29](https://cloud.githubusercontent.com/assets/5216502/23910526/aab49dfe-089f-11e7-8fa9-b360d30f5e47.jpg)

**Comment by jodygrenert** [comment]
Many thanks for the info, Geoff. Your software gets better every year. Wanna come judge with us on July 15? I'll comp your room!
