### ISSUE TITLE
Unwanted Stewerd at table eventhough he is unassigned

### ISSUE THREAD

**Issue by huibertsp** [geoffhumphrey/brewcompetitiononlineentry#745]
at http://scorpion.brewcompetition.com on table 1 I have a Steward Kooistra. He is no longer assigned to this table and I don't see his name in the selection page. Yet on the Assigned Stewards CSV document his name appears. Can this be corrected please?

**Comment by huibertsp** [comment]
I fixed it by making the Steward available to the pool and than manually remove him before removing him from the round all together.

**Comment by geoffhumphrey** [comment]
That would be the method I would suggest to remove him/her from the list.
