### ISSUE TITLE
Export Data csv creation of all participants causes a Mysql Syntax error

### ISSUE THREAD

**Issue by torreyj** [geoffhumphrey/brewcompetitiononlineentry#748]
Hi there, within the Data Export section, and clicking on 'Emails (CSVs)', and all participants. I get the following error attached. Looks to be a syntax error.  Thanks

<img width="1262" alt="screen shot 2017-03-18 at 5 21 54 pm" src="https://cloud.githubusercontent.com/assets/6643464/24076480/c6640554-0bff-11e7-8868-70ddc486f36d.png">

**Comment by geoffhumphrey** [comment]
This is a known problem for versions prior to 2.1.8. Upgrading to 2.1.9 will correct the bug...please see Issue #716.
