### ISSUE TITLE
Multiple file upload fails

### ISSUE THREAD

**Issue by huibertsp** [geoffhumphrey/brewcompetitiononlineentry#750]
trying to upload the scanned scoresheets via multifile upload tool. Naming <jury#>.pdf as instructed but it fails without a real error. 

website: http://scorpion.brewcompetition.com/
browser: latest Chrome, Edge, or latest FF. Not even 1 or 2 files. 

Such a shame. The rest of the software is really great!

**Comment by geoffhumphrey** [comment]
It looks like you were able to upload scoresheets. Was it using the multiple upload feature or the single file upload feature?

I just confirmed that the multiple upload feature works for your installation. Perhaps it was due to a slower internet connection?

**Comment by geoffhumphrey** [comment]
Looking at your file sizes for your PDFs, they are all quite large (north of 3 MB each). File size and connection speed will definitely affect performance of the multiple upload function. You will definitely timeout if you try to upload a lot of 3 MB files at the same time. 

I would suggest that you adjust your scanner settings - scaning your scoresheets at 300 dpi black and white will result in dramatically smaller file sizes than 600 dpi color (see this [article](http://blogs.adobe.com/acrolaw/2009/08/reducing-the-file-size-of-scanned-pdfs/) for some tips). If that's not possible, you can optimize your PDFs using Adobe Acrobat (which can get expensive) or a myriad of free or low-cost optimizer software packages out there.

**Comment by huibertsp** [comment]
I uploaded them via the single file mode. Using the multifile upload would
have been quite nice.

The connection is a descent cable modem connection from Comcast in the DC
area. Did my activity generate some back-end logs? I got nothing in any of
the browsers.

Thanks for your help

**Comment by caheath** [comment]
I had problems with the multiple upload function as well.  Any files that had 3 scoresheets and a cover sheet were too large (over 2MB) and wouldn't upload.  All the ones with 2 scoresheets and a cover sheet would.  It didn't work to compress files and then upload.  Eventually I was able to get them to load via the single upload function, even though they were the same file size.
