### ISSUE TITLE
Participant email addresses

### ISSUE THREAD

**Issue by elronalds** [geoffhumphrey/brewcompetitiononlineentry#752]
It would be nice to have a feature similar to on the assigning judge screen to get a list of the participant email addresses for the following:

- paid entrants
- unpaid entrants
- all entrants

I can then send out an email to remind entrants that they haven't paid for their entries online a few days before the competition closes.  I can't find anywhere that this is possible.

**Comment by geoffhumphrey** [comment]
Currently, although not as convenient as the methodology on the assign judges/stewards screen, you can get the email addresses of paid, unpaid, and all entrants by going to Admin > Data Exports >Entries (CSV) > All Entries or Paid Entries or Non-Paid Entries. Each of these downloads has the associated email address of the entrant for affected entries.

**Comment by elronalds** [comment]
Thanks @geoffhumphrey  That works for what we need, it would be nice to have this setup like the judges/stewards screen in a future update.
