### ISSUE TITLE
Competition setting to set # of bottles required

### ISSUE THREAD

**Issue by elronalds** [geoffhumphrey/brewcompetitiononlineentry#755]
I think it would be good to have a competition setting to configure the bottle quantity of bottles that is required.  The printing of the bottle labels should then only print that number of labels for each bottle.

For example, we might only require 1 bottle entry for a competition and the system will print 4 bottles labels which 3 aren't needed and are a waste.

Ideally, this could also work with issue #754 as we can print more labels on the one sheet.

**Comment by geoffhumphrey** [comment]
Will be incorporated into version 2.1.14. See issue #857.
