### ISSUE TITLE
Attempting Add Entery However I Get A Not Available Page After Hitting The Submit Button

### ISSUE THREAD

**Issue by huibertsp** [geoffhumphrey/brewcompetitiononlineentry#760]
http://bob.brewcomp.com/

A user reported around 9.28pm EDT 20170331, I am having difficulty adding an entry. I enter the data and hit the submit button and get a blank web page with "not available" on the page. Are they any issues with the servers? I will try Mozilla Web browser next. Any recommendations?

**Comment by geoffhumphrey** [comment]
@huibertsp, thanks for reporting.

This most likely has to do with the user timing out. If there's not activity after 15 minutes, the user's session expires, effectively logging them out. I was able to add an entry without encountering this problem a few minutes ago.
