### ISSUE TITLE
Allow entrants to see if bottles marked as received

### ISSUE THREAD

**Issue by elronalds** [geoffhumphrey/brewcompetitiononlineentry#761]
It would be nice to have a feature once the competition entries close that entrants can see if bottles were marked as received.

Save entrants asking if their bottles were received okay, especially for shipped entries.

**Comment by anigeluk** [comment]
I had already added this to our competition site, however it does raise questions from people as they expect it to be updated when the beer arrives at a shipping or drop off point but in practise it gets updated when I collect them from the shipping location and process then entry, which can be a week after they were delivered to the shipping location.

**Comment by kstec** [comment]
Nothing a little tooltip on hover wouldn't solve.

**Comment by anigeluk** [comment]
True.

I seem to recall hover actions can have issues on mobile, but I could be wrong or things could have changed, as it's been many years since I really did any front end development. Not a show stopper by any means just something to consider

**Comment by kstec** [comment]
With many frameworks (including bootstrap, which is being used here), the hover event is handled by click on mobile unless it's an anchor tag.

**Comment by anigeluk** [comment]
That's nice to know. Thanks.  
> _Every day is a school day_

**Comment by geoffhumphrey** [comment]
Good points here. Bootstrap has a feature called [popovers](http://getbootstrap.com/javascript/#popovers) that would be useful in this instance. Here's a screenshot of a what implementation of this request could look like:
![2017-06-12_13-59-44](https://user-images.githubusercontent.com/5216502/27052622-7e41b882-4f77-11e7-9712-d09cf99d395f.jpg)

The popover will be displayed upon hover on desktops and upon tap on mobile devices/touchscreens.
