### ISSUE TITLE
Nothing displayed for Manage Locations, Contacts, Entries, Participants...

### ISSUE THREAD

**Issue by SKBcompet** [geoffhumphrey/brewcompetitiononlineentry#762]
Unable to manage locations, contacts, entries, participants, judges, etc. When "manage" is clicked for any of the above, the tables displayed are empty and the only option is to Add new. 

When adding a new entry to any of the above sections, the information is captured (as evidenced by the fact that the judging locations are displayed on the home page), but I am unable to view or edit  via the "manage" function. As such, I cannot delete added locations, contacts, entries, etc.

![screenshot 2017-04-10 12 47 33](https://cloud.githubusercontent.com/assets/27230703/24874940/f676c4a4-1deb-11e7-8ceb-37f3f4c1f87c.png)

**Comment by SKBcompet** [comment]
Is there any additional information I can provide to facilitate the resolution of this issue? Please let me know!

**Comment by geoffhumphrey** [comment]
This came up before. However, I searched for it and haven't found the specific work-around (yet), but it sticks out in my mind that this had to do with CDN load of various libraries such as jQuery, Bootstrap, tinyMCE, etc. There is a way to not switch to load these libraries locally directions are here: 

http://brewcompetition.com/local-load

Perhaps try that while I look for other causes.

**Comment by geoffhumphrey** [comment]
Found something - there may have been something awry with your setup. I recall investigating, but wasn't able to replicate the issue nor find a root cause. See Issue #720.
