### ISSUE TITLE
Error exporting winners to CSV

### ISSUE THREAD

**Issue by elronalds** [geoffhumphrey/brewcompetitiononlineentry#764]
I'm unable to export winners to a CSV, the request `/output/export.output.php?section=entries&go=csv&filter=winners` results in the following error:

`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ORDER BY tableNumber ASC' at line 1`

Is there a patch available for this as I can't seem to locate one?

**Comment by geoffhumphrey** [comment]
@elronalds, I'm not able to replicate this issue in the current version (2.1.9). I was able to download the winners CSV without issues.

**Comment by elronalds** [comment]
@geoffhumphrey Was this patched recently or in an update?  I couldn't locate a pull request or any changes related to this.  

What is the correct SQL that should be executing here so I can manually pull out the winners?

**Comment by elronalds** [comment]
@geoffhumphrey I upgraded to 2.1.9 and this issue fixed itself.  Seems it was something wrong within my installation or something that fixed itself in 2.1.9.
