### ISSUE TITLE
Changing entry numbers in label links exposes data from other entry

### ISSUE THREAD

**Issue by deetwenty** [geoffhumphrey/brewcompetitiononlineentry#765]
If you manually copy the link to a set of labels with pre-filled brewer/entry information, and then change the entry number in that URL (nothing else), you get a label that's partially filled with information about the entry with the altered number.  You can't see brewer names (those seem to be loaded from your own "brewer" id number, which cannot be changed without generating a permissions error), but you can view style, entry names, co-brewers, and some other minor things that you probably shouldn't be able to as an entrant.

**Comment by geoffhumphrey** [comment]
Hello @deetwenty, thanks for reporting. Would you clarify which labels you are accessing and whether you are accessing as an Admin or not? I'm having trouble figuring out just what you did to do some troubleshooting.

**Comment by deetwenty** [comment]
I'm not accessing as an admin, but as an entrant.  After entering bottles for an upcoming competition, I'm offered links at the bottom of the "My Info and Entries" page with printable bottle labels containing pre-filled data about my entries.  The URL behind these links is something like:

https://register.beercompetition.com/output/entry.php?id=123&bid=777

This link appears to work as intended.  However, if "id" is changed to "124", I am presented with labels containing information about competition entry 124 even though it is not my entry.  Co-brewer, style. and entry name info for 124 are filled in on the labels, meaning as long as I have a valid "bid", I can deanonymize the other entries by viewing these labels.

**Comment by geoffhumphrey** [comment]
Ah, I see. In a previous version, a simple check was added to verify if the person viewing the page "owns" the id of the entry. Unfortunately, that check, as currently written, doesn't work. The code will be updated in the next version to something like (near the top of /output/entry.output.php):

```
// Check access restrictions
$restricted = FALSE;
if (($_SESSION['user_id'] != $brewing_info['brewBrewerID']) && ($_SESSION['userLevel'] > 1)) $restricted = TRUE;

if ($restricted) { 
  	echo "<html><head><title>Error</title></head><body>";
  	echo "<p>You do not have sufficient access privileges to view this page.</p>";
  	echo "</body>";
  	exit();
}
```

**Comment by kstec** [comment]
Why would you default to unrestricted?

**Comment by geoffhumphrey** [comment]
Simply an oversight from legacy code.

**Comment by kstec** [comment]
I was referring to the code change you posted above.

**Comment by geoffhumphrey** [comment]
Just the way I wrote it, but it serves the same purpose. The labels will not print if the condition was true. Could easily be the other way around, thusly:
```
// Check access restrictions
$restricted =  TRUE;
if (($_SESSION['user_id'] != $brewing_info['brewBrewerID']) && ($_SESSION['userLevel'] > 1)) $restricted = FALSE;

if ($restricted) { 
  	echo "<html><head><title>Error</title></head><body>";
  	echo "<p>You do not have sufficient access privileges to view this page.</p>";
  	echo "</body>";
  	exit();
}
```
Serves the same end...
