### ISSUE TITLE
Participants don't have a option of printing labels

### ISSUE THREAD

**Issue by Jaskolskimichal** [geoffhumphrey/brewcompetitiononlineentry#767]
When participants are log on, and they are watching they list of entry they dont see a option of printing a labels (to put on bottle).

**Comment by kstec** [comment]
Check the "Pay to Print" option on the Website Preferences:
![image](https://cloud.githubusercontent.com/assets/216067/25340670/1a175fb4-28cc-11e7-9d09-1e2330edec2b.png)

If this is enabled, entrants have to be marked as "paid" before they can print their bottle labels. Disable it to let them print as soon as they enter.

**Comment by Jaskolskimichal** [comment]
Yep, we change that already, but it still dont work :/

**Comment by Jaskolskimichal** [comment]
even when they have paid mark on entries it doesnt work...

**Comment by geoffhumphrey** [comment]
Generally, this has to do with dates entered on the Admin > Preparing > Competition Info screen.
Check the following dates - make sure they are **_not_ in the past**:
1. All judging dates
2. The end date of your entry window
3. The end date of your drop-off window
4. The end d ate of your shipping window
5. The end date of your account registration window

Also, what version are you using?

**Comment by phillipwhelan** [comment]
I am using version 2.19 and I don't have an option to print labels, edit entries or delete entries.  I've checked my dates and nothing seems wrong.

**Comment by phillipwhelan** [comment]
I found the issue, the judging location needs to be added and possibly the drop off location before the print option or any of the entry actions will show up.
