### ISSUE TITLE
Assign individual entries to flights

### ISSUE THREAD

**Issue by simchuck** [geoffhumphrey/brewcompetitiononlineentry#769]
Is there any way to assign an individual entry to a specific table/flight, rather than just relying on the bulk assignment for a BJCP sub-category?  I have a few entries in historical (27) and specialty (34) categories (not enough to judge on their own) that I want to include with appropriate base styles on other tables.  

I tried looking through the issues and all of the help documentation but could not find any help on this.

**Comment by geoffhumphrey** [comment]
The ability to assign specific beers to flights is possible if your competition organization preferences are set to "non-queued" - this is set by going to Admin > Preferences > Competition Organization.

Version 2.1.9 introduced the ability for entries to be classified as one of the cited examples in Category 21B (Specialty IPA) and 27B (Historical). This allows admins to assign to tables specific Specialty IPA and Historical styles to tables - prior versions lumped them all together under their respective subcategory (21B or 27B).

For versions prior to 2.1.8, an entry would only be treated by the system as a "Historical Beer" or "Speciality IPA" and not, say, a Grodzskie or White IPA as it's category (the program does require the entrant to enter specifics).

**Comment by simchuck** [comment]
It looks like we are using an older version (2.0.1 at the bottom of the admin dashboard).  It is too late in the game to upgrade -- can I still do what you suggest?  

I have admin rights, but I don't seem to have sufficient privileges to view the preferences as you suggested.
