### ISSUE TITLE
User's Information Is Not Available

### ISSUE THREAD

**Issue by jeremywickham** [geoffhumphrey/brewcompetitiononlineentry#773]
User contacted me to add a late entry. I manually added the entry, after this, the brewer's user information has disappeared. Looks like one of the other organizers tried to add his name again and associate the entries to that account This user happened to have won BOS therefore it is not displaying any of his wins on the Winners page.

This happened on a hosted site: http://www.boardtownbrewoff.brewcompetition.com/ -

**Comment by richardlbryant** [comment]
Joining this issue. Yes. That is exactly what I did. I tried to add his name again and associate the entry, but that did not work.

**Comment by geoffhumphrey** [comment]
Since this is a hosted site, I'll need a couple pieces of information to fix this issue directly in the database - the name of the individual and the entry numbers of each of his entries.

Please feel free to email the info via http://www.brewcompetition.com/contact if you do not wish to record them here.

**Comment by jeremywickham** [comment]
0049, 0040, 0102, 0074, 0041, 0039, 0075, 0069
Jonathan Harden

I contacted the user, he is able to login, but none of his information is there. See photo -- https://dl.dropboxusercontent.com/u/1539580/unnamed.png 

Looks like the participant with brewerID=(89|90) is the one @richardlbryant tried to create.

**Comment by geoffhumphrey** [comment]
I've associated entries, scores, and bos with the new user ID - please take a look and let me know if everything is correct.

If Jonathan wishes to review his "new" account information, he should a) clear cache and cookies from his browser, and b) log in and change the information that was entered by the Admin.

**Comment by jeremywickham** [comment]
Appreciate it!

Cheers!



Jeremy Wickham
[image: https://]about.me/jwickham
<https://about.me/jwickham?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by geoffhumphrey** [comment]
No worries. Least I could do. Thanks for using the software and being a hosted account subscriber!
