### ISSUE TITLE
Setup step 7 (designate styles) excesive links to BJCP style center

### ISSUE THREAD

**Issue by anigeluk** [geoffhumphrey/brewcompetitiononlineentry#775]
When running through the set up on a fresh install of 2.1.9 step 7 presents the following screen. All links just go to https://bjcp.org/stylecenter.php Would it make sense to remove all those links and replace them with a single link to the stylecentre?

Happy to do this and put a pull request in but wanted to make sure that didn't conflict with your plans for this page first. 

![screenshot-bcoem dev-2017-05-29-15-58-40](https://cloud.githubusercontent.com/assets/2588997/26554444/0263c1a0-4488-11e7-8ef5-4c10f1ee5cfb.png)

**Comment by geoffhumphrey** [comment]
Interesting. Those links should not be across the top as in your screenshot - instead, they should be in the table below on the same <tr> as the style. I'll look into it. Thanks!
