### ISSUE TITLE
Can I set an entry price for a specific category?

### ISSUE THREAD

**Issue by tpklieb** [geoffhumphrey/brewcompetitiononlineentry#777]
The competition I'm running will have a side category that will be judged separately from the rest of the competition. I've already added the special category to the system, but I am wondering if there is a way to set the entry price for this category to be different than the other category entries. Ex: abnormal beer category entry is only 3 dollars while a mead or blonde are 7 dollars.

**Comment by geoffhumphrey** [comment]
Unfortunately, no. The entry fees are global - and depend upon certain conditions if set by an Admin (e.g., a separate fee for those with a password, a discounted fee for every entry beyond a certain number, etc.).
