### ISSUE TITLE
Cannot download any pdf from our website

### ISSUE THREAD

**Issue by Zvish** [geoffhumphrey/brewcompetitiononlineentry#778]
Hi,
I am getting the following issue when trying to download entries PDF, the error is:

Notice: A session had already been started - ignoring session_start() in /home/bhomebre/public_html/mevashlim/output/labels.output.php on line 5

Warning: Cannot modify header information - headers already sent by (output started at /home/bhomebre/public_html/mevashlim/output/labels.output.php:5) in /home/bhomebre/public_html/mevashlim/classes/fpdf/fpdf.php on line 1032
FPDF error: Some data has already been output, can't send PDF file

Please advise if I have a problem with my hosting or it's an issue in fPDF tool.
Thanks,
Zvi

**Comment by anigeluk** [comment]
Try turning off `display_errors` in your php config that should enable you to download the pdf files. 

`display_errors` should not normally be on in a production environment.

**Comment by Zvish** [comment]
Thanks for the help.
It's working now, added php.ini to the cPanel
