### ISSUE TITLE
Participant is unable to edit own entry if only allowed one entry in competition

### ISSUE THREAD

**Issue by graemecoates** [geoffhumphrey/brewcompetitiononlineentry#779]
URL: http://competitions.londonamateurbrewers.co.uk/londonvsleeds
Version of BCOEM: 2.1.9 (freshly reinstalled code from tar.gz)

Competition is setup with only one available entry category which is a custom category (setup as 35A).

Participant is able to register and add an entry as normal. 
However, if they don't have admin/top level admin rights, they are now unable to use the edit link in their own entries table (the pencil icon) to edit the entry. The link is of the form "[server]/[subdir]/index.php?section=brew&action=edit&id=18&view=35-A" and returns a styled page with "Edit Entry" as a page title, but no subsequent form/entry info on the screen. See: 

![image](https://user-images.githubusercontent.com/5789649/26924573-60a7d5ae-4c3e-11e7-88e2-8d6c858fb6ef.png)

**Comment by graemecoates** [comment]
Should also say that at this point, changing the accepted styles to make it a standard one only doesn't help = you still can't edit an entry.

Have other BCOEM instances on the same server than work fine (but have no custom styles in place - I'm not sure if this is the issue or not here...). Happy to provide sanitised DB and code to look at if needed.

**Comment by graemecoates** [comment]
I have been able to reproduce this. Method I used;

1. Setup a new db, install BCOEM, setup admin user, dates etc. Ensure that the dates are such that registration is open.
2. During setup, ensure no standard BJCP2015 categories are open for entry.
3. Complete setup, undo the setup flag in config.php, etc.
4. Add a new style into the db (goes in as 35-A). Set Info and strength as required. Set as only acceptable style for entry.
5. Register a new user as an entrant. Enter a new entry in 35-A.
6. As entrant, try to edit entry -> cannot do it!

Attached is a db for 2.1.9 in this state as a mysql dump file. This should allow the issue to be reproduced. 
[bcoem_test.zip](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/1060771/bcoem_test.zip)

**Comment by geoffhumphrey** [comment]
I wasn't able to recreate this issue on my test installation using Chrome, Firefox, or IE 11 using a conventional setup scenario. Does it work when other styles are available for entry as well?

**Comment by graemecoates** [comment]
I looked at this again, and think I've pinned it down - I think the custom styles is a red herring. The issue is occurring when the participant is limited to one entry only in the competition (which is the case in the original report above, and how I had automatically setup the one above...). 

If I change the limit to 2 in the example above via the Website Preferences, it allows editing again - changing it back to one per participant triggers the issue again and returns a blank edit page. 

(It's not browser - the markup just isn't returned!)

**Comment by geoffhumphrey** [comment]
Confirmed when only 1 entry is allowed. I'll look into it and post a fix as soon as I track down the issue.

**Comment by geoffhumphrey** [comment]
Try this. In /sections/brew.sec.php...

Replace line 63, which reads:
```
if (((!$add_entry_disable) && (!$edit_entry_disable) && ($remaining_entries > 0)) || ($_SESSION['userLevel'] <= 1)) {
```
With:
```
if (((!$add_entry_disable) && ($remaining_entries > 0)) || (!$edit_entry_disable) || (($adminUser) && (!$adminUserAddDisable))) {
```
This will "unbind" the ```$edit_entry_disable``` boolean variable from the ```$add_entry_disable``` and ```$remaining_entries``` variables.
