### ISSUE TITLE
Two sites on same server

### ISSUE THREAD

**Issue by glienhard** [geoffhumphrey/brewcompetitiononlineentry#781]
I have two instances of BCOE&M running at the domain name competitions.hopsclub.com, one is at competitions.hopsclub.com/2017jblm (v2.1.7) and the other is at competitions.hopsclub.com/2017cowlitzfair (v2.1.9).  Both installations use separate db's with completely different user and password.  The problem I'm having is that if you go to one competition then go to the other, many of the things from the first site show up on the second.  I think that my browsers are caching variables that don't reset when going between the two.  Do you have any idea how to fix this?

**Comment by jimmyorkin** [comment]
I have seen this happen in the past also. I am interested in how to avoid it.

**Comment by anigeluk** [comment]
I think I have a solution for this which I will submit for Geoff to decide if he wants to include it in a future release, but for now, there is a work around for this. 
In `paths.php` you will need to specify an installation_id that is different for each competition.

Change the line that says 

```$installation_id = "";```

in one competition to be

```$installation_id = "2017jblm";```

and in the other 

```$installation_id = "cowlitzfair";```

**Comment by glienhard** [comment]
@anigeluk Thank you very much, that worked perfectly!  Never knew that was hiding in the paths.php file.  Basically from what I see, if you change the $sub_directory variable in site/config.php file then you need to make the same change to the $installation_id variable in the paths.php file.

Geoff, I have verified this works in my installation.  Please let me know if you would like me to do any additional testing to help out.

Cheers!

**Comment by geoffhumphrey** [comment]
I will add the code submitted by @anigeluk to the codebase. @glienhard, please post back here if you or your users have any further issues.
