### ISSUE TITLE
How to add requirement for category

### ISSUE THREAD

**Issue by MIBeerCup** [geoffhumphrey/brewcompetitiononlineentry#789]
How do I add the requirement to my categories?

♠ = Specific type, special ingredients, classic style, strength (for beer styles), and/or color are required.

**Comment by geoffhumphrey** [comment]
Hello @MIBeerCup. When you are adding your own custom style, there is an option called "Required Info" - checking "Yes" will this will add the requirement.
![2017-07-18_9-20-27](https://user-images.githubusercontent.com/5216502/28325288-a2106210-6b9a-11e7-9ea3-d9de457d779e.jpg)
