### ISSUE TITLE
BOS Judge assignment

### ISSUE THREAD

**Issue by glienhard** [geoffhumphrey/brewcompetitiononlineentry#790]
I had a few issues with assigning judges to my BOS round.  The first issue is that I was not able to assign someone that has a judge ranking of Recognized.  Next the system was allowing me to assign judges that were any level but were "Certified Cicerone".  I found the issue in line 193 of includes/db/brewer.db.php

``$query_brewer = "SELECT * FROM $brewer_db_table WHERE (brewerJudgeRank LIKE '%Certified%' OR brewerJudgeRank LIKE'%National%' OR brewerJudgeRank LIKE '%Master%')";``

By using the LIKE statement, it is pulling everything in the brewerJudgeRank column of the brewer table and include it in the list.  Changing this statement to wildcard after each option will prevent the cicerone from showing up

``$query_brewer = "SELECT * FROM $brewer_db_table WHERE (brewerJudgeRank LIKE 'Certified%' OR brewerJudgeRank LIKE'National%' OR brewerJudgeRank LIKE 'Master%')";``

There was also the issue of Recognized judges not being allowed on the list so I had to make line 193 look like this

``$query_brewer = "SELECT * FROM $brewer_db_table WHERE (brewerJudgeRank LIKE 'Recognized%' OR brewerJudgeRank LIKE 'Certified%' OR brewerJudgeRank LIKE'National%' OR brewerJudgeRank LIKE 'Master%')";``

I also believe that we should be able to choose what ranks of judges are allowed to judge at BOS.  Putting this in the settings would be a great addition

The last thing is that if a judge has entries in BOS, they still show up in the list and are still able to be assigned as a BOS judge.  I would think that the code should do something similar to table assignments and list the judge in red saying they have entries and not allow assignment.  Probably something to work into the next version though.

Cheers!

**Comment by geoffhumphrey** [comment]
Good points here. It also stands to reason that Certified, Advanced, and Master Cicerones be considered for BOS judge assignment. With that in mind, I changed the query to:

`$query_brewer = "SELECT * FROM $brewer_db_table WHERE (brewerJudgeRank LIKE 'Recognized%' OR brewerJudgeRank LIKE 'Certified%' OR brewerJudgeRank LIKE 'National%' OR brewerJudgeRank LIKE 'Master%'  OR brewerJudgeRank LIKE '%Cicerone')";`

This will allow all three ranks to be displayed on the list.

Additionally, in the next version, any judge that has placing entries will be "flagged" in red.
