### ISSUE TITLE
BOS Placements

### ISSUE THREAD

**Issue by glienhard** [geoffhumphrey/brewcompetitiononlineentry#792]
Having an issue where the HM placement in BOS is not showing up both when you go back into edit the BOS placements and when you view on the homepage list of awards it shows an N/A next to the placement.  I found that in the judging_scores_bos table, the scorePlace column was set to float.  I changed the column type to varchar and now it is all working correctly.

**Comment by geoffhumphrey** [comment]
Changing to varchar in the next version. Thanks for the heads-up!
