### ISSUE TITLE
Register participant does not render anything

### ISSUE THREAD

**Issue by kstec** [geoffhumphrey/brewcompetitiononlineentry#797]
2.1.10-beta upgraded from 2.1.9.

GET /index.php?section=admin&go=entrant&action=register
![image](https://user-images.githubusercontent.com/216067/28833012-bc2ca33e-76a3-11e7-91da-b1b3dc536165.png)

All dates are in the future and I get the same when registering a participant, a judge, or a steward.

**Comment by geoffhumphrey** [comment]
I'm not able to recreate the issue. Are there any errors in your logs? Or, if you would, set the DEBUG global variable in /paths.php to TRUE and try again. This will show any php errors on screen.

**Comment by kstec** [comment]
`Parse error: syntax error, unexpected '}' in sections/register.sec.php on line 866`

I double checked that my version of that file is the same as the one in the beta.

I see this:

`\<?php } // end else ?>`
`\<?php } // end else ?>`

I remove one of those and it works. But I don't think that's the problem.

**Comment by geoffhumphrey** [comment]
Hmm, that second curly brace shouldn't be throwing that error. Try this file - I just went through and confirmed all if/else statements in it and confirmed it works in my test environment.

[register.sec.php.zip](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/1191635/register.sec.php.zip)

**Comment by kstec** [comment]
That file works with no modifications, but looking at the diff I can't see what functionally changed.

All I did to upgrade was:

tar xzvf v2.1.10-beta.tar.gz
mv bcoem-sandbox bcowm-sandbox.bak
mv brewcompetitiononlineentry-2.1.10-beta bcoem-sandbox
cp bcoem-sandbox.bak/site/config.php bcoem-sandbox/site/

Maybe there's something new in the config file that is causing this?

**Comment by geoffhumphrey** [comment]
There were two variables introduced in the config file for the 2.1.10 beta version
`$installation_id` with a null default value and `$session_expire_after` with a default value of 30. Since you copied your config.php file from your old install to the beta install, the absence of the `$session_expire_after` variable may be causing the problem.

**Comment by kstec** [comment]
I will revert to the 2.1.10 register.sec.php file and try the new config.php and get back to you. Pretty sure you can chalk this one up to user error.

**Comment by kstec** [comment]
User error
