### ISSUE TITLE
Scoresheet pdf link case sensitive

### ISSUE THREAD

**Issue by glienhard** [geoffhumphrey/brewcompetitiononlineentry#802]
I have just found out that all scoresheets must be uploaded with pdf and not PDF.  The instructions say in step three that the file can be uploaded as either.  But the php code for the front end is hard coded to lowercase pdf links.  All of my scoresheets were named with it in caps (PDF).  The easiest way I found to fix this was rename the files on the server directly `rename 's/\.PDF$/\.pdf/' *.PDF`

**Comment by geoffhumphrey** [comment]
Hmm. In my environments, an uppercase PDF extension was recognized and able to be downloaded. 

However, to mitigate against the problem in other environments, the names of the uploaded files will be converted to lower-case prior to being stored on in the directory in the next version.

**Comment by glienhard** [comment]
Great, that was going to be my suggestion.  Thanks Geoff!
