### ISSUE TITLE
Upgrade from 2.1.9 to 2.1.10 Beta issues

### ISSUE THREAD

**Issue by markalston** [geoffhumphrey/brewcompetitiononlineentry#804]
Upgrading our site from 2.1.9 to 2.1.10 beta results in the following errors:
On first load we get the error

`Duplicate column name 'prefsSpecific'`

Displayed on the browser.

If we reload we then get the following error:

`Incorrect integer value: 'Y' for column 'prefsProEdition' at row 1`

After another reload we get the main page.

**Comment by geoffhumphrey** [comment]
Confirmed. The latest commit should address this issue.
