### ISSUE TITLE
Can't print pullslips after upgrade to 2.1.10 beta

### ISSUE THREAD

**Issue by markalston** [geoffhumphrey/brewcompetitiononlineentry#806]
Error shown is `Unknown column 'brewInfoOptional' in 'field list'`

**Comment by markalston** [comment]
I fixed this for me by forcing the off_schedule_update.php to run by changing the version_date in system to 2017-08-25.

Clearly something else needs to change though as this should be part of a 2.1.9 to 2.1.10 upgrade path.

**Comment by geoffhumphrey** [comment]
The full version will have a check (exactly as you described) that will compare version dates. If the date in the DB is prior to the version date, it will run the code in the off_schedule_updade.php file.

In the current commit, there is also be a `FORCE_UPDATE` flag in the paths.php file that can be set to `TRUE` to force the code in the off_schedule_updade.php file to run ([diff](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/a819da30e4afc17e3c32ba8ed77d6a3a0595eb49#diff-b0353ec5b310698656090b9d7bb9b540R98)). This was put in place for occasions such as this. 

For performance reasons, `FORCE_UPDATE` should only be set to `TRUE` for a single refresh of the index.php page.
