### ISSUE TITLE
tinymce is not defined

### ISSUE THREAD

**Issue by vortexofhate** [geoffhumphrey/brewcompetitiononlineentry#807]
I recently upgraded to 2.1.10 and in bcoem_custom.min.js I am getting the error uncaught referenceerror: tinymce is not defined.  

I am running on a windows installation backed with a MySQL 5.7.18 database.  I am using PHP 5.6.31.

**Comment by geoffhumphrey** [comment]
Confirmed. The latest commit fixes the issue. At this point, there are only a few functions that require TinyMCE and the loading of it definitions is limited.
