### ISSUE TITLE
geoff@zkdigital account

### ISSUE THREAD

**Issue by vortexofhate** [geoffhumphrey/brewcompetitiononlineentry#808]
The geoff@zkdigital account is constantly added back into the users. I delete, check the DB and its reentered again.  I've tried over 5 times to remove that account and unable to.

bcoem v 2.1.10 beta, php 5.6.3.1 , and MySQL 5.7.18 database on Server 2012 R2

**Comment by geoffhumphrey** [comment]
My fault on this one. There's scripting to keep an admin account in my name for hosted accounts. Easy fix. Just set the HOSTED variable in /paths.php to FALSE. That will prevent the creation of the account.
