### ISSUE TITLE
Custom SMTP Server

### ISSUE THREAD

**Issue by vortexofhate** [geoffhumphrey/brewcompetitiononlineentry#809]
is it possible to enable custom SMTP server settings?

I'm hoping my own server and would like the possibility to send the emails through my mail server.

**Comment by geoffhumphrey** [comment]
At present, no. However, I'm looking into incorporating SMTP into the next major release (2.2.0) that will provide more flexibility than simply relying on php's mail() function to deliver email messages to users.

**Comment by ercousin** [comment]
Hey @geoffhumphrey 

Isn't this one already fixed in: https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/955

**Comment by geoffhumphrey** [comment]
Yep. Sure is.
