### ISSUE TITLE
qr code shows wrong confirmation info

### ISSUE THREAD

**Issue by markalston** [geoffhumphrey/brewcompetitiononlineentry#810]
We are using the qr code scanning but are getting bad confirmation numbers.  The problem is that the language file is loaded before the response view is exploded.  Thus, we always get the entry number shown as the first character in the actual entry number and the judging number as the second character in the entry number.

I did a quick fix by adding `require(LANG.'language.lang.php');` after all the `$view = explode("-",$view);` lines in qr.php to force a reload of the language file to properly set all the qr messages.

**Comment by geoffhumphrey** [comment]
Confirmed. Check the latest commit for a fix (similar to what you did). I'm assuming you're running the 2.1.10 Beta.

**Comment by markalston** [comment]
this is on 2.1.9.  I couldn't get 2.1.10 beta working quickly enough for our comp this weekend.  The show stopper is missing columns breaking generation of pullslips.  If I can fix that tonight then I'll give 2.1.10 beta a shot during our comp.
