### ISSUE TITLE
qr.php broken on https servers 2.1.10 beta

### ISSUE THREAD

**Issue by markalston** [geoffhumphrey/brewcompetitiononlineentry#812]
qr.php no longer works on https systems due to the addition of the line:

`$base_url = "http://".$_SERVER['SERVER_NAME'].$sub_directory."/";`

Not sure why this is added to qr.php as it is set via the config.php require.  

Regardless, removal of this line fixed qr.php for me.

**Comment by geoffhumphrey** [comment]
Noted and confirmed. That variable is legacy code that was inadvertently left in since the 2.1.0 release last year (see Issue #552). It will be removed in the next commit and version.

**Comment by markalston** [comment]
Odd. It wasn't in my 2.1.9 code.

**Comment by geoffhumphrey** [comment]
It's entirely possible I put it back in when I was working on code updates. It's been a long road from 2.1.9 to now...
