### ISSUE TITLE
Databases not fully updated when upgrade to 2.1.10 beta

### ISSUE THREAD

**Issue by markalston** [geoffhumphrey/brewcompetitiononlineentry#813]
I was getting the following error when trying to make website settings changes in 2.1.10 beta
`Unknown column 'prefsProEdition' in 'field list'`

The issue looks like a broken update in off_schedule_update.php.  

You need to first change the value of prefsCompOrg from 'Y' to 1 (or 0) before changing the column to prefsProEdition as that column is set to tiny int.

I manually made the change in my database to get past this error.

**Comment by geoffhumphrey** [comment]
Noted. The value of the field will be set to '0' in the off_schedule_update.php script. The fix will be in place in the next commit and the 2.1.10 full version.
