### ISSUE TITLE
Styles not assigned to tables pulls up first style 2.1.10 beta

### ISSUE THREAD

**Issue by markalston** [geoffhumphrey/brewcompetitiononlineentry#815]
Using the "styles not assigned to tables" function is showing the first category 01 Standard American Ale instead of the actual category which isn't assigned.

In fact, it shows this category as unassigned even when all categories are assigned properly.

**Comment by geoffhumphrey** [comment]
Confirmed. There was an extra parameter being passed to the get_table_info function on line 245 of /admin/judging_tables.admin.php. The line was:

``if (!get_table_info($row_styles['id'],"styles","styles","default","default","default")) {``

It should be:

``if (!get_table_info($row_styles['id'],"styles","default","default","default")){``

This fix and a couple of others that I found will be in the next commit and 2.1.10 full version.

**Comment by geoffhumphrey** [comment]
There was a conflict in the scripting that was preventing the code to be processed correctly. The latest commit fixes the error, however, more testing is needed.
