### ISSUE TITLE
Can't assign judge location preferences 2.1.10

### ISSUE THREAD

**Issue by markalston** [geoffhumphrey/brewcompetitiononlineentry#816]
I have some judges whom I can't assign location preferences for. The following errors show up in the apache log:

`[Sat Aug 26 10:13:01.525621 2017] [proxy_fcgi:error] [pid 31453] [client 216.21.162.30:50852] AH01071: Got error 'PHP message: PHP Warning:  trim() expects parameter 1 to be string, array given in /var/www/brewcompetitiononlineentry-master/lib/common.lib.php on line 3954\nPHP message: PHP Notice:  Undefined variable: totalRows_entry_count in /var/www/brewcompetitiononlineentry-master/includes/constants.inc.php on line 69\nPHP message: PHP Notice:  Undefined variable: totalRows_entry_count in /var/www/brewcompetitiononlineentry-master/includes/constants.inc.php on line 70\nPHP message: PHP Notice:  Undefined variable: totalRows_log in /var/www/brewcompetitiononlineentry-master/includes/constants.inc.php on line 168\nPHP message: PHP Notice:  Undefined variable: totalRows_log_confirmed in /var/www/brewcompetitiononlineentry-master/includes/constants.inc.php on line 168\nPHP message: PHP Warning:  trim() expects parameter 1 to be string, array given in /var/www/brewcompetitiononlineentry-master/lib/common.lib.php on line 3954\nPHP message: PHP Warning:  implode(): Invalid arguments passed in /var/www/brewcompetitiononlineentry-master/includes/process/process_brewer.inc.php on line 581\n', referer: https://www.beernut.com/beercomp/index.php?section=brewer&go=admin&action=edit&filter=488&id=488`

**Comment by geoffhumphrey** [comment]
The errors in the log had partially to do with a portion of the `sterilize` function housed in the lib/common.lib.php file. The code responsible for that has been removed. 

Additionally, some adjustments were needed in the /includes/process/process_brewer.inc.php file that would allow for proper imploding of arrays into strings for use by the system. The improper imploding combined with the `sterilize` function resulted in a NULL value to be stored in the DB for a user's judging and stewarding location preferences. 

The latest commit fixes this issue and will be available in the full version of 2.1.10.
