### ISSUE TITLE
Judges show up in Bull Pen list but not in assignment list

### ISSUE THREAD

**Issue by markalston** [geoffhumphrey/brewcompetitiononlineentry#818]
I had an issue where judges would show up in the Bull Pen list when printing judge assignments but would not show up in the list when I was assigning judges to tables.  I had to manually assign these judges to tables and was never able to add them in the software.

I think it is related to to #816 but not sure yet.

**Comment by geoffhumphrey** [comment]
Yes, it is related to #816. If you're not able to make a judge available at a certain location, or if the judge has indicated that they're not available for that location, you will not be able to assign them to a table that has been assigned to that location. See #816 for a solution.
