### ISSUE TITLE
Competition Info Not Saving (plus other issues edit)

### ISSUE THREAD

**Issue by Rangemaster75** [geoffhumphrey/brewcompetitiononlineentry#825]
Version 2.1.9

New user. Trying to setup for our first competition. I can alter and save Contacts, Styles, Drop Off Locations etc but when I do the basic edit of the competition info I fill it all in, hit update competition info and it takes me to the Home screen and retains nothing (still says the default Baseline Data Installation"). I assume the database is fine since other info is saving. Help??

Edit: Looks to be worse than I thought. Once I exit out of the browser post initial install I basically get locked out. The log in button no longer works. Prior to that I notice neither did any of the top row buttons (Info, Volunteers, Contact) they just recycle to the Home page. Home page displays data for the judging locations, contacts added so some date is saving and being processed onto the Home page. If I start from scratch ( delete the database and re-install all the same symptoms listed above occur.

You can see where I'm at: coldsnap.mcbrewers.ca

Thanks in advance,
Stephen

**Comment by markalston** [comment]
Any info in your webserver logs?

**Comment by geoffhumphrey** [comment]
Hi @Rangemaster75. It looks as if there was a hiccup in your installation process. To correct, there are a couple of ways I can think of that are relatively painless.

The first (fastest) is to wipe your database clean and start over with the installation process again.

The second (almost as fast) is to use the fallback installation method. Included in the package download is a subfolder called “sql” that contains an SQL file called bcoem_baseline_2.1.X.sql. This file contains the complete database structure and dummy data to get you up and running. Complete instructions are at the top of the file. To install the baseline database and dummy data, you will need access to your database via phpMyAdmin or shell access.

The third involves digging into the database to make sure certain items are in place. Reply back if you want to go that route.

**Comment by Rangemaster75** [comment]
Geoff,

I see you closed this ticket which after over a month (and no reply) I
definitely understand why! Sadly I've been really busy and although
I've done suggestion 1 & 2 multiple times I haven't had any luck. In
both cases I still am unable to get it to save to the database. when I
try to edit the info I go to Update and it cycles back to the
Dashboard and nothing has saved (both clean install and your
fallback). Today I noticed you updated to a new version so I wiped
everything and tried both clean installs again and fallback. In both
cases I go to Update or save the info in the case of the install and
get a 403 Access to resource forbidden error. My host is GreenGeeks. I
don't know if anybody has had these problems on their servers or I'm
just really unlucky. Time's running out for me and I'm at my wits end.
I know that it's impossible for you to know server side setups beyond
your own server but any thoughts would be amazing either to fix this
or any other solutions. I bought the space specifically for this and
it is upsetting that its not working out on their end I suspect unless
its just user (me) error. I've attached the error log from the host
folder.

Help!!! And thanks in advance for any time you spend helping me,
Stephen Goodal

**Comment by Rangemaster75** [comment]
Also, Here is my config file - altered for the fallback.

**Comment by leswright** [comment]
Hi.
I'm having a similar issue with version 2.1.11.  The Competition Info page is blank except for the title, nothing displays.  I went into the DB using  phpMyAdmin.  The table contest_info contains the info that I entered during setup.  Any advice on where I might go from here to "switch" it on?
Thanks,
Les

**Comment by geoffhumphrey** [comment]
See issues #855 and #867 for some insight into this problem. Bottom line: the latest commit addresses this issue which has to do with PHP 7+ and its handling of array variables.
