### ISSUE TITLE
Hosted site up and down

### ISSUE THREAD

**Issue by michaeltrego** [geoffhumphrey/brewcompetitiononlineentry#830]
Over the past two days we have had several reports of entrants trying to register for our competition and the website appearing to be down.  http://nerhbc.brewcomp.com/

When it happens it looks like a domain name issue and it reverts to the hosting provider landing page. Any ideas what is going on?

![image](https://user-images.githubusercontent.com/22302281/30505293-be6d3fe8-9a41-11e7-805a-4a6e5a45932b.png)

**Comment by geoffhumphrey** [comment]
This has been an ongoing issue with DNS resolution of subdomains of brewcomp.com. Unfortunately, it seems intermittent and random, and the sites do resolve after a few minutes. 

For anyone fielding questions about this, advise your users to clear their browser cache and/or use another browser after a few minutes of waiting.
