### ISSUE TITLE
Restrict Judging Numbers to Class only

### ISSUE THREAD

**Issue by markpalcare** [geoffhumphrey/brewcompetitiononlineentry#831]
Hi all,

What would be the way to restrict the judging number sequence to Class only?

e.g 1A has 10 entries (1 - 001 --> 1 - 010)

Preferably have the judging number look like (1A - 001)

Class 1B then would restart (1B - 001)

**Comment by geoffhumphrey** [comment]
A variation of this is available to Admins from the Admin > Entries screen under the Admin Actions drop-down. Choose "Regenerate Judging Numbers (with Style Number Prefix)."

It does not go as far as sub-style, only overall style. So, for example, if the overall style is 4 (Pale Malty European Lager), the first three digits will be 004 and the last three digits are incremental until all of the entries in that style are numbered (e.g., 004001, 004002, 004003, etc.). By default, the function keys off of the entry number from lowest to highest. Note: to conform to the six-numeral standard used by the application, the BJCP 2015 mead and cider styles are converted to numerals:

- C1 is 38 (038001, 038002, etc.)
- C2 is 39 (039001, 039002, etc.)
- M1 is 40
- M2 is 41
- M3 is 42
- M4 is 44

It should be noted that this function is intended to be used after your entry window has closed but prior to sorting.
