### ISSUE TITLE
Entry Sorting report issues on 2.1.10

### ISSUE THREAD

**Issue by tehchriso** [geoffhumphrey/brewcompetitiononlineentry#834]
On the Administration -> Manage Entries page, when I run **any** report from the _Print Current View..._ button, it produces a list by Entry Number, ascending sort, only.

On the Administration -> Entry Sorting page, when I run off Sorting Sheets (by Entry or by Judging), it produces a sorting list displayed By Category, descending sort (M4, M3, M2, and so on, ending on 01).  The data within each category's sheet is correctly sorted by Subcategory first, then Entry (or Judging) number.

This is also the case for Cheat Sheet. The sub-category and the entry number do sort correctly, but the category pages are in reverse order. (M4 first, etc.)

I'm currently looking through print.output.php to see if I can figure out the variable names within the URL to work around the issue and trick it into the right output.

I did scan through the commit from 9-20-17 which mentioned changes to output, but I can't really tell if it addresses this problem - or other issues.

I am on ver. 2.1.10 Beta, with the files from the 10-4-2017 Master Commit uploaded on top of it. (Heh, but you knew that already... ;-) )

**Comment by tehchriso** [comment]
Just as a follow-up...

If I go to Administration -> Manage Entries... - and then I sort the view by Entry - or Judging - and I simply hit Ctrl-P instead of running a report... I get a totally useable Cheat Sheet-type output correctly sorted.

That method gets me a good chunk of what I need for unpacking/labeling this week. But wanted to share the observations nonetheless.

**Comment by geoffhumphrey** [comment]
Off the top of my head, this may have to do with the DataTables plug in, since it is used to sort these reports. Might be a good idea to make sure that DataTables is implemented/included/available. I'll dig in the code later to see if that's the case.
