### ISSUE TITLE
Link resolution issue

### ISSUE THREAD

**Issue by michaeltrego** [geoffhumphrey/brewcompetitiononlineentry#835]
In the Competition Info section under Competition Rules, we have a link out to our historical winners page. The resolution of the fully formed link is not formatted correct and results in a 404:

http://nerhbc.brewcomp.com/%22http://www.bfd.org/nerhbc/NERHBC_Winners.html%22

**Comment by geoffhumphrey** [comment]
Confirmed for the 2.1.10 Beta release. The latest commit incorporates a fix to the issue.

@michaeltrego, please let me know if you'd like me to upgrade your hosted installation to the latest codebase. I didn't want to do so without your knowledge because you're getting ready to judge next week.

**Comment by michaeltrego** [comment]
I'd rather not upgrade at this point before the competition. It's not a critical fix. Glad to hear it will be in the next update. Thanks.

**Comment by geoffhumphrey** [comment]
Make sure that all tables have been assigned to rounds. For the affected tables without radio buttons to assign judges, go to the assign tables to rounds screen and change the round to something other than what's listed. Then, change it back to the intended round. This has worked for me in the past as a temporary solution. I'll be investigating the cause.
