### ISSUE TITLE
Judges not showing up to assign to BOS panel

### ISSUE THREAD

**Issue by lynhbrew** [geoffhumphrey/brewcompetitiononlineentry#839]
I cannot get all of my assigned judges to show up on the page where I assign my BOS panel. In particular, none of my grand master judges are visible for selection, while all of them participated on the BOS panel. This means that the BJCP point recod is not accurate and has to be manually updated. Am I missing a step?

**Comment by geoffhumphrey** [comment]
Hi @lynhbrew - this was an issue in 2.1.9 that was reported a couple of months ago. Check Issue #790 for a fix or upgrade to 2.1.10 which was just released on Oct 20.

**Comment by lynhbrew** [comment]
Thanks Geoff, Sorry about that. i searched and did not see the specific issue. I will give it a look. I appreciate the rapid response. 
Lyn
