### ISSUE TITLE
Does not handle special characters like åäö when exporting to csv

### ISSUE THREAD

**Issue by kredor** [geoffhumphrey/brewcompetitiononlineentry#840]
When I tried to export recepies to csv, the Swedish special characters is not exported right. 
Look at brewname in the attached file (i removed all other columns, but similar error there as well).

[Belgoträffen_2018_Entries_All_All_10-22-2017.xlsx](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/1408475/Belgotraffen_2018_Entries_All_All_10-22-2017.xlsx)

**Comment by geoffhumphrey** [comment]
Hi @kredor - there was some essential code missing to "prepare" the CSV export for use in Excel and other programs to when exporting UTF-8 encoded characters. Open the attached zip package and upload the file contained in it to the /output/ directory. This should fix the problem, providing that you are running version 2.1.9 or 2.1.10.

[export.output.php.zip](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/1415574/export.output.php.zip)

This fix will be in the next release.
