### ISSUE TITLE
Add Homebrew Club to Drop Down

### ISSUE THREAD

**Issue by foggdogg001** [geoffhumphrey/brewcompetitiononlineentry#849]
Hi,

Can you add 'East Bay Homebrew Club' to the club drop down list when registering an account?

Thanks,

Joshua Fogg
Ocean State Homebrew Competition

**Comment by johnrm** [comment]
Hi there,
Climbing on the back of this.
We are based in Ireland where none of the club names are relevant.
There is no Add/Edit/Delete for club names.
Is it recommended that we edit the underlying table?
Thanks,
John Mangan
National Homebrew Club (Ireland)

**Comment by johnrm** [comment]
I think the editing is done from the AHA website.
You need to register your club, then wait for the list to populate.
Edits and Deletes are done form AHA too.
https://www.homebrewersassociation.org/community/clubs/club-updates-form/

**Comment by geoffhumphrey** [comment]
Currently, the club names are housed in the $club_array found at or around line 36 in the /includes/constants.inc.php file. This array is updated with each release based upon the AHA's list of clubs. In the future I'll investigate whether the AHA offers an API to their club database.

For now, to add your club to the list, add it to the array (note the format).

**Comment by johnrm** [comment]
Many thanks Geoff!

**Comment by foggdogg001** [comment]
I am unfamiliar with how to get to that line of code. Can you give me some
direction as to how to get in there and add the club?

Thanks,

Joshua Fogg
OSHC
Organizer

**Comment by geoffhumphrey** [comment]
Joshua, since you're installation is hosted, I've updated the code to add your club to the list. Your users should see it in the dropdown immediately.

**Comment by DurrtySteve** [comment]
Hey sorry to add to this closed thread @geoffhumphrey  . In order to add my club to the $club_array, do I first create a branch and a Pull Request? I'm brand new to Github. I've made a commit to the master branch on my computer without creating a branch or pull request but I'm not sure I did this right. Are you able to see it?
