### ISSUE TITLE
Is there a way to pick timezone? It seems as if the time zone defaults to MHT

### ISSUE THREAD

**Issue by joquiroz** [geoffhumphrey/brewcompetitiononlineentry#853]
Trying to find a timezone picker but it isn't picking the club's timezone, the drop off location or any other time zone.

**Comment by quimnut** [comment]
Yeaaa, well I looked in /lib/date_time.lib.php and wondered why there is an array of time zones in there when php does this natively.

http://php.net/manual/en/timezones.php

**Comment by geoffhumphrey** [comment]
Time zones are defined in the UI by going to Admin > Preferences. Date and time displays are based upon the chosen time zone.

**Comment by joquiroz** [comment]
Damn, found it, nevermind...I thought I extensively looked for it
previously.

cheers!

---
Joaquin Quiroz Jr.

"Those who can give up essential liberty to purchase a little temporary
safety deserve neither liberty nor safety." -- Ben Franklin

This e-mail and any attachments thereto are intended only for use by the
addressee(s) named herein and may contain legally privileged and/or
confidential information. If you are not the intended recipient of this
e-mail (or the person responsible for delivering this document to the
intended recipient), you are hereby notified that any dissemination,
distribution, printing or copying of this e-mail, and any attachment
thereto, is strictly prohibited. If you have received this e-mail in error,
please respond to the individual sending the message, and permanently
delete the original and any copy of any e-mail and printout thereof.
