### ISSUE TITLE
Edit Club Name

### ISSUE THREAD

**Issue by TomAguero** [geoffhumphrey/brewcompetitiononlineentry#854]
In the club drop down our club is listed as "Middletown Area Society of Homebrewer's"

How can I change that to "Middletown Area Society of Homebrewers"?

Thanks,
![12-20-2017 10-14-48 am](https://user-images.githubusercontent.com/34716728/34214387-5320debe-e570-11e7-934e-4897c54cc032.png)

**Comment by geoffhumphrey** [comment]
See issue #849 for more info on how to change the name yourself. In the next release, the name will be corrected.
