### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by MarieAnnick** [geoffhumphrey/brewcompetitiononlineentry#856]
Since upgrading the site to SSL, links are broken. "Home" works, as does logging in to the admin dashboard once I upgraded to 2.1.11, (it doesn't work in 2.1.9) but anything requiring a path component beyond the home competition folder, like adding entries, etc. does not. For example, I get "Requested URL not found /competition/entry"

**Comment by geoffhumphrey** [comment]
As a temporary measure, disable the Search Engine Friendly links via Preferences. That may clear things in the interim while I investigate.

**Comment by MarieAnnick** [comment]
Thanks, that appears to have resolved the issue for now.
