### ISSUE TITLE
Call to undefined function Error in off_schedule_update

### ISSUE THREAD

**Issue by jwbradley** [geoffhumphrey/brewcompetitiononlineentry#858]
After all of the setup processes have been completed the website errors with HTTP ERROR 500.

Website error log reports the following message:
PHP Fatal error:  Call to undefined function mime_content_type() in /home/jambra49/mashers.talkhops.com/update/off_schedule_update.php on line 669

![browsererror](https://user-images.githubusercontent.com/3986615/34501637-662842da-efd5-11e7-9121-00ad7c435d49.PNG)
[mashers_CompErrors.zip](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/1598823/mashers_CompErrors.zip)

Changed the code to be the following and the page loads fine:

foreach($files as $file) {

	// $mime = mime_content_type($file->getPathname());

	// if (stripos($mime, "pdf") !== false) {
		$file_name_current = $file->getFilename();
		$file_name_new = strtolower($file->getFilename());
		rename(USER_DOCS.$file_name_current, USER_DOCS.$file_name_new);
	// }

}

**Comment by geoffhumphrey** [comment]
Not entirely sure why this error occurred. The mime_content_type function has been built in to PHP since version 4. A check (see below) to see if the function exists will be added to the files that use the function: 
- /admin/upload_scoresheets.admin.php
- /includes/process.inc.php
- /update/off_schedule_update.php

```
if(function_exists('mime_content_type')) {
     // Code
}
```

**Comment by jwbradley** [comment]
Any thoughts on what would happen to the logic when $mime = "" by using the following in those three files? 

$mime = (function_exists('mime_content_type') ? mime_content_type($file->getPathname()) : "");

**Comment by geoffhumphrey** [comment]
Nothing really. In each of the three instances, returning `$mime = ""` would negate the succeeding lines of code. In all three, it's either searching for a mime type that contains pdf or is in an pre-defined array of mime types. If no match, or blank, nothing will happen.

However, I believe that I'll add a backup option similar to one that is enumerated in the [php documentation for the function](http://php.net/manual/en/function.mime-content-type.php) in the user contributed [notes by svogel](http://php.net/manual/en/function.mime-content-type.php#87856) that specifies a mime_content_type function if the php native one isn't available. A failsafe that's not as robust as the native php function, but one that will serve the purposes intended in this application.

**Comment by jwbradley** [comment]
That is the option I was just going to suggest. I added that function to common.lib.php and all seems to be working.

Thanks!
