### ISSUE TITLE
500 server error after setup completes

### ISSUE THREAD

**Issue by codek** [geoffhumphrey/brewcompetitiononlineentry#859]
Hi,

I successfully setup and ran the site locally and had no problems.

I followed the same on our cpanel server, and now once setup completes, we get 500 internal server error on the index.php

Unfortunately we cannot find anything in the server error log file, which seems strange in itself.

We've removed the .htaccess as described here:
http://help.brewcompetition.com/index.html?installation.html
And the problem persists.

We also tried the manual install using the SQL file and saw exactly the same behaviour

PHP is 5.6.32 so not sure what else we can check.
In the config.php the sub_directory is set, we're not using a prefix of any kind.

Did try putting this in index.php but it didnt change anything:

ini_set('display_errors', '1');

**Comment by codek** [comment]
hang on, the mysqlini is out of date, trying to resolve that first.

**Comment by codek** [comment]
Fixed - caused by a missing module:  mime_magic - probably worth documenting the required modules.

**Comment by geoffhumphrey** [comment]
I agree. Glad you were able to fix the issue.

**Comment by jwbradley** [comment]
This sounds like same issue that I was seeing on my site with issue #858. 
Updated on Forked link: [jwbradley/brewcompetitiononlineentry](https://github.com/jwbradley/brewcompetitiononlineentry/commit/b4b10b716899b9119fc8e7b155884a0fd5d522d3)
