### ISSUE TITLE
receive error when trying to archive site

### ISSUE THREAD

**Issue by huibertsp** [geoffhumphrey/brewcompetitiononlineentry#860]
When I choose option 1 to archive all data, I receive the following error " You do not have sufficient access privileges to perform this action." Please advise

**Comment by geoffhumphrey** [comment]
Only top-level Admins are permitted to initiate any archive actions. I suspect your account is a mid-level Admin, thus why you’re receiving this message.

**Comment by huibertsp** [comment]
understood. I found another way to achieve the same goal
