### ISSUE TITLE
What if I change an entry's category after bottle label is printed?

### ISSUE THREAD

**Issue by medirckx** [geoffhumphrey/brewcompetitiononlineentry#861]
Hypothetical question but very relevant for me because my competition has a custom category that we would like to split (based on strength ie single vs. double) so we can assign to different tables. We would do this by creating another custom category and reassigning the double-strength entries.
This would involve changing several entries' category, some of which may have the labels printed and entries dropped off already.
It's unclear what the impact might be if we do this.
Thanks in advance.

**Comment by geoffhumphrey** [comment]
This will not be a problem in the system because the entry number is still the same. It's more a communication issue between you, any sorting staff, and the entrant.
