### ISSUE TITLE
Cannot change default participant level

### ISSUE THREAD

**Issue by torreyj** [geoffhumphrey/brewcompetitiononlineentry#862]
When people are signing up, they're getting assigned the admin level.  I just want them to be a participant level.  How can I change this globally?

**Comment by geoffhumphrey** [comment]
This is definitely a bug. The default level is "user" and Admin user levels must be assigned by other Admins. A global change would require access to the database directly and executing a command similar to this (assuming that user 1 is the "uber-Admin" that set up the installation):
```
UPDATE users SET userLevel=2 WHERE id > 1
```
If your DB tables have a prefix, make sure you add that before "users"

**Comment by geoffhumphrey** [comment]
Assuming you've installed version 2.1.11, changing the following line will hardcode the default user level to the lowest setting of 2 when entrants register an account. On or about line 162 in /includes/process/process_users_register.inc.php, change this line:
```
GetSQLValueString(sterilize($_POST['userLevel']), "int"),
```
To:
```
GetSQLValueString("2", "int"),
```

**Comment by torreyj** [comment]
Awesome, yes on 2.1.11.  I'll update that code. I'm a Dev/DBA for my day job, I can do that no problem.  Thanks

**Comment by geoffhumphrey** [comment]
I'm thinking that a better option to try before hard coding "2" would be to remove the call to the sterilize function, as such:
```
GetSQLValueString($_POST['userLevel'], "int"),
```
This would allow the code to be utilized by the setup function as well as the general registration while in production.
