### ISSUE TITLE
Require login for judging location addresses

### ISSUE THREAD

**Issue by donutbrew** [geoffhumphrey/brewcompetitiononlineentry#863]
As many judging sessions are held at private homes, it would be nice to have some level of privacy for these addresses. I think minimally, it should require a user to log in to see the addresses. Probably the same for shipping location.

**Comment by geoffhumphrey** [comment]
To hide the addresses from those who do not have an account established, add the boolean variable $logged_in to the /sections/entry_info.sec.php (on or around line 239) and /sections/sidebar.sec.php (on or around line 285) files like so...

```
if (($row_judging['judgingLocation'] != "") && ($logged_in))
```
Be sure to remove the `else` statement immediately following the above if statement in entry_info.sec.php to avoid outputting the name of the location's name twice in your UI.

**Comment by geoffhumphrey** [comment]
Also, do the above on or around line 79 in reg_closed.sec.php.

**Comment by ercousin** [comment]
I think this should be an optional setting.

Many competitions manually add judges to the system using quick add, so those people wouldn't know how to login.
