### ISSUE TITLE
Unknown column 'user_name' in 'field list'

### ISSUE THREAD

**Issue by st3r30t1p** [geoffhumphrey/brewcompetitiononlineentry#864]
I installed is application in wordpress and then i create admin user and get error Unknown column 'user_name' in 'field list'. And this is true since there is no user_name column in the wp_user table. How to fix it?

**Comment by geoffhumphrey** [comment]
BCOE&M installs its own database tables. The user_name column is in the users table. If you provided a prefix in your BCOE&M /site/config.php file, then the table would have the prefix pre-pended to it (e.g., if your prefix is "bcoem_" the table would be named bcoem_users).

Just as an aside, BCOE&M is not configured to integrate with WordPress or any other CMS. It is it's own, salient application; essentially a CMS within itself.
