### ISSUE TITLE
Unpaid entries are being marked as paid

### ISSUE THREAD

**Issue by jodygrenert** [geoffhumphrey/brewcompetitiononlineentry#865]
The program has tagged several entries as "paid" even though they haven't been paid.

This happened with an entry for Mike McCaffrey, the contestant who brought it to my attention. 

I've checked our Paypal records and discovered that only two entrants have paid their fees -- Jody Grenert and George Miles. Yet the program marked 5 others as having paid. I've since clicked "unpaid" on the ones that didn't pay, but I really need this fixed asap. Thanks.

**Comment by geoffhumphrey** [comment]
It looks as though when a user adds an entry, it's automatically marking the entry as paid. I'm investigating.

**Comment by geoffhumphrey** [comment]
After investigation, it seems that this was only happening when an Admin added an entry - either for themselves or for another entrant. I've added a temporary fix to the code to resolve the issue for your hosted installation. I'll post an "official" fix after I do some more digging.

**Comment by jodygrenert** [comment]
No admins have added entries for a contestant so far. I’m wondering if the program is somehow tagging these entrants as admins when they log in

**Comment by ecomeaux** [comment]
I'm having the same problem with our brewcomp site. It seems to have just started happening in the past few days as over 100 entries were put in without this issue, then the latest couple of participants having entered have been auto-marked as paid upon registering entries.

**Comment by geoffhumphrey** [comment]
Another instance has been reported to me just now. Very weird, indeed, why this is suddenly happening. What I believe is the responsible code has been in the codebase for well over 2 years. Hmmm.

As a temporary measure, erasing or commenting out the following lines in /sections/brew.sec.php disables what I believe is the culprit (around line 175).

Copy/paste:

```
/*
// Check to see if the amount the entrant has paid is equal to or exceeds the entry fee cap (if defined)
	if ((isset($_SESSION['contestEntryCap'])) && ($_SESSION['contestEntryCap'] > 0)) {
		// if so, mark this entry as paid
		 if ($total_paid_entry_fees >= $_SESSION['contestEntryCap']) $brewPaid = 1;
	}
*/
```

**Comment by foggdogg001** [comment]
Hi Geoff,

I am also having this problem. Can you correct my hosted version as well?

Thanks
Joshua Fogg
OSHC
oshc.brewcomp.com

**Comment by geoffhumphrey** [comment]
A fix is now in the latest commit.

Joshua and Jody, I've pushed the update your hosted installations. Please keep an eye on them and report back if the problem persists.

**Comment by bwestfall03** [comment]
How can I get this fix pushed to our comp?

**Comment by geoffhumphrey** [comment]
@bwestfall03 - If your comp is hosted, I'll push the fix (apologies, I don't recognize your GitHub username as being associated hosted competition).

**Comment by bwestfall03** [comment]
Yes, sorry I just signed up for it. The comp is the babble brew off.
		
		

		Bill
	




On Fri, Jan 19, 2018 at 1:30 PM -0600, "Geoff Humphrey" <notifications@github.com> wrote:












@bwestfall03 - If your comp is hosted, I'll push the fix (apologies, I don't recognize your GitHub username as being associated hosted competition).

**Comment by geoffhumphrey** [comment]
No problem. Done.
