### ISSUE TITLE
Cannot edit entry after max entries reached

### ISSUE THREAD

**Issue by cbwatkins** [geoffhumphrey/brewcompetitiononlineentry#866]
A participant is not able to edit their entry after the maximum number of entries has been received, even though the entry window is still open.  They can delete their entry, but the edit button is grayed out.  The participant should be able to modify their entries until the close of the entry window (as defined in the administrator's "Competition Info" config page).  

If there are competitions that would not want to allow edits after max entries received, then this should at least be a configurable setting in the Competition Info config page.

**Comment by geoffhumphrey** [comment]
To fix this, change the following in /sections/brewer_entries.sec.php (around line 285):
```
if ($entry_window_open == 1) {
```
To:
```
if (($entry_window_open == 1) || (($entry_window_open != 1) && (time() < $row_contest_dates['contestEntryDeadline']))) {
```

**Comment by cbwatkins** [comment]
Thanks! I will give hat a try!

Regards,
Chris Watkins
