### ISSUE TITLE
Add Entry page simply says "Add Entry," is otherwise blank

### ISSUE THREAD

**Issue by whenyeastattack** [geoffhumphrey/brewcompetitiononlineentry#867]
I just set up a new installation of 2.1.8.  When I try to add an entry, I get a page that says "Add Entry" in title text but nothing else.  How can I figure out what is wrong?

I am not using 2.1.11 because I've tried twice to install and configure it and after completing the last installtion step I get a blank page.  Given this, I just created a new database and copied my installation folder from last year's competition (v2.1.8) and ran through setup again.  After completing setup the site is not blank but the Add Entry page is mostly blank.

I am running:

 mysql --version
mysql  Ver 14.14 Distrib 5.5.58, for debian-linux-gnu (x86_64) using readline 6.3

 php --version
PHP 5.6.31 (cli) (built: Jul 27 2017 01:31:08)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

Session support is enabled

**Comment by geoffhumphrey** [comment]
Add the following to your paths.php file:
```
ini_set('error_reporting', E_ALL ^ E_DEPRECATED);
ini_set('log_errors','On');
ini_set('display_errors','On');
```
This will make sure that any errors encountered will be displayed.

Do your server logs reveal any errors?

**Comment by whenyeastattack** [comment]
Thanks, Geoff.  I was able to get 2.1.8 installation working by dropping the db, re-adding it, and going through the setup three more times.  Eventually it worked.  I couldn't get 2.1.11 to work.  I'm going to stick with the 2.1.8 installation. 

Let me know if you'd like to see the debug output from a 2.1.11 installation and I can run through it again.

Cheers,
  Jack

**Comment by geoffhumphrey** [comment]
Hey Jack, if you would provide the debug output, I'd be interested in seeing what was going on with your install...

Appreciate it!

**Comment by rbrionesr** [comment]
Hi, I got the same problem, the message a get is: 
Add Entry

Fatal error: Uncaught Error: [] operator not supported for strings in /home/cbob6yodrkxp/public_html/includes/db/styles_special.db.php:51 Stack trace: #0 /home/cbob6yodrkxp/public_html/sections/brew.sec.php(10): include() #1 /home/cbob6yodrkxp/public_html/index.php(237): include('/home/cbob6yodr...') #2 {main} thrown in /home/cbob6yodrkxp/public_html/includes/db/styles_special.db.php on line 51

The url of the site is http://chihuahuabeerfest.com

Appreciate any help.

**Comment by geoffhumphrey** [comment]
@rbrionesr, I've corrected this in the latest commit - has to do with php 7+ and the use of "unassigned" array variables (see issue #855).

A couple of avenues to pursue: "downgrade" to PHP 5.6 or replace your installation's current codebase with the ones in the latest commit. 

**Beware, though:** the latest commit has NOT been rigorously tested as of yet, so make sure you make backups of your data prior to using the latest committed code.
