### ISSUE TITLE
Need Improved Manual Entry Options for Received Entries

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#872]
Splitting from #847 

I have some requests to improve the manual entry of received entries.

Some ability to mark large groups of entries as recieved would be very helpful.
Example A. Mark all of category 6 as received.
Example B. Drag select a bunch of entries, mark all as paid

A possible extension to the idea in example A, would be to have it prompt you to mark any "not recieved" entries before performing the action. Then all entries from that category would be marked as "rec'd" except for those you specified.

**Comment by geoffhumphrey** [comment]
While not exactly what you've detailed here, version 2.2.0 will feature auto-save on the Admin: Entries screen. Essentially, you could filter the Entries list by category and then mark all of the applicable entries as paid and/or received.

![image](https://user-images.githubusercontent.com/5216502/102700140-2140d280-4208-11eb-8e8a-a6c8a76c3703.png)

See Issue #1070 for futher details.
