### ISSUE TITLE
Req info still truncated from bottle sticker when less than 50 char

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#876]
Splitting from #847

We had someone use the following description which word counts as 47 chars (with space), but the word Sugr was still turncated from the printed bottle label. Perhaps the new lines screw it up? I don't think req-info field should allow new lines since 50 char is the recommended max...

Base: 24A
Homemade Orange Marmalade
Lt.Brown Sugr

**Comment by ercousin** [comment]
@geoffhumphrey have you had a chance to look at this one? I'm still able to replicate with 2.1.11 when using a style with radio buttons like 21B:

![image](https://user-images.githubusercontent.com/1551339/42983278-d5230790-8bb3-11e8-83c2-422439b17e5c.png)

![image](https://user-images.githubusercontent.com/1551339/42983297-e71cd020-8bb3-11e8-94b1-769628330a2e.png)

**Comment by geoffhumphrey** [comment]
Avery 5160 labels appear to be able to fit about 204 characters total at 9 pt Arial. 6 lines at 34 characters per line. 

So, for each label, the lines breakdown like this for an entry with both Required Info and Optional Info:
```
[Style Number: Style Name] [Entry/Judging Number]
[Required Info]
[Required Info]
[Strength, Sweetness, Carbonation]
[Optional Info]
[Optional Info]
```
If only Required Info is present, the breakdown will be:
```
[Style Number: Style Name] [Entry/Judging Number]
[Required Info]
[Required Info]
[Required Info]
[Required Info]
[Strength, Sweetness, Carbonation]
```
If both are present, Required info and Optional Info will be truncated at 68 characters. If only Required Info is present, it will be truncated to 136 characters.

In your example, the labels will look like this in the next version:
![2018-07-20_10-04-04](https://user-images.githubusercontent.com/5216502/43012809-62954f84-8c04-11e8-8ac0-b3665ba5ac21.jpg)

And others with only Required Info would look like this:
![2018-07-20_10-04-23](https://user-images.githubusercontent.com/5216502/43012893-8804162e-8c04-11e8-8040-19901ee9d2bf.jpg)

**Comment by ercousin** [comment]
Thanks @geoffhumphrey  ! Looking forward to picking this change up
