### ISSUE TITLE
Judging points calculating incorrectly

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#877]
Splitting from #847 

BJCP Definitions:
> Judges earn points at a rate of 0.5 Judge Points per session, but the following limitations apply:
> - Judges earn a minimum of 1.0 Judge Point per competition.
> - Judges earn a maximum of 1.5 Judge Points per day.

> SESSION
> An uninterrupted time period when at least one panel of judges sits to judge one or more flights of entries. Typically, "morning", "afternoon" and "evening" are considered sessions at most competitions.

I think there is a bug where "rounds" are counting as 0.5 pts instead of "sessions". I add a new "judging location" for each sessions (morning, afternoon, evening, etc...), and each session has up to two rounds. During one of the sessions we ended up having one table judge two small flights (round 1 + round 2), but somehow BCOEM is counting these two flights as two sessions (0.5 pts + 0.5 pts), when it should be worth only 0.5 pts because it still only took 1 session.

**Comment by geoffhumphrey** [comment]
It's not necessarily a bug, it's more of an interpretation or limitation of the logic that determines what a "session" constitutes. According to the BJCP, a session is defined as:
> [An] uninterrupted time period when at least one panel of judges sits to judge one or more flights of entries. Typically, 'morning', 'afternoon' and 'evening' are considered sessions at most competitions.

The current logic interprets each location as a session and that's probably where the confusion lies here. 

In an effort to eliminate any confusion, the next release will feature much clearer information as to how sessions are factored into the system - see below - in addition to changing the "Judging Location(s)" label to the more precise "Judging Session(s)."
> To correctly calculate BJCP experience points for program participants, it is suggested that each session you set up here follow that guideline (e.g., Session 1: XXX Location - Early Morning, Session 2: XXX Location - Late Morning, Session 3: XXX Location - Afternoon, etc.). A judging session may consist of one or more flights and one or more rounds.

**Comment by ercousin** [comment]
That's what I did though, I setup each session as a new location as you describe above.

> I add a new "judging location" for each sessions (morning, afternoon, evening, etc...), and each session has up to two rounds. During one of the sessions we ended up having one table judge two small flights (round 1 + round 2), but somehow BCOEM is counting these two flights as two sessions (0.5 pts + 0.5 pts), when it should be worth only 0.5 pts because it still only took 1 session.

Using the current terminology:
It was still calculating the rounds within the same location as 0.5 pts each, when the rounds shouldn't have been considered.
