### ISSUE TITLE
Resolved issue with Rel. 2.1.11.00 not displaying Info page

### ISSUE THREAD

**Issue by leswright** [geoffhumphrey/brewcompetitiononlineentry#878]
Hi Geoff,

I hope this is OK to inform of a resolved error.  I brought up my BCOE&M site yesterday and found that the Info page only printed the title on screen, the rest of the page was blank.  I found the following error in error_log:

[28-Jan-2018 10:22:02 America/New_York] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /home/lescp/public_html/sections/entry_info.sec.php:104
Stack trace:
#0 /home/lescp/public_html/index.php(227): include()
#1 {main}
  thrown in /home/lescp/public_html/sections/entry_info.sec.php on line 104

In sections/entry_info.sec.php line 104 is:
$anchor_links[] = $label_entry_registration;

Up the page I found the declaration: 
$anchor_links = "";

So, I added brackets to the declaration and resolved the problem:
$anchor_links[] = "";

The Competition Info page prints on screen great now.  I don't know if this causes any downline problems, none seen yet, but will defer to the master!

The site is http://www.brewmastersopen.com if you want to test something.  Holler if you need admin access or anything.

Thanks for a excellent competition software system!!!

Regards,
Les

**Comment by geoffhumphrey** [comment]
See issues #855 and #867 are similar issues and can provide more information. Variables such as what you've detailed have been corrected throughout the code in the latest commit and will be incorporated into the next release. Thanks!
