### ISSUE TITLE
Problem with datababase marking entries as paid

### ISSUE THREAD

**Issue by TMSBHH** [geoffhumphrey/brewcompetitiononlineentry#880]
I'm from the Great Northern Brew Ha Ha.  As we were checking in entries for our competition (coming up in 8 days).  We have 65 entries that are marked as paid but for which we did not receive funds.  A couple of people pointed this out, and I attributed it to user error, went into the database, unchecked the paid box which allowed them to submit a PayPal payment.

Now we're faced with a $455 discrepancy.  We are e-mailing entrants to try and recover money right now, sadly an burden we didn't need with the competition so close.

Many people were able to use PayPal successfully, so I don't think it's a set-up problem.

Please advise.

**Comment by geoffhumphrey** [comment]
Apologies for the issues. This is a issue that has surfaced in installations in the past couple of weeks. I've pushed the fix detailed in issue #868.
