### ISSUE TITLE
Purge all of the above fails

### ISSUE THREAD

**Issue by huibertsp** [geoffhumphrey/brewcompetitiononlineentry#883]
Purge all of the above in Data Management fails with the following eroror: "Table 'brewcomp_bcoeshared2.bob_payments' doesn't exist"

website: http://bob.brewcomp.com/

**Comment by geoffhumphrey** [comment]
There was a missing check on whether the payments table existed, thus throwing the error if it wasn't found. I've corrected it in your installation and the purge all function should work now as expected.

The fix will be in the next commit and release version.

**Comment by huibertsp** [comment]
Thank you Geoff. I purged all in separate steps, this way others don't have
to suffer
