### ISSUE TITLE
Request: Simultaneous entry editing

### ISSUE THREAD

**Issue by donutbrew** [geoffhumphrey/brewcompetitiononlineentry#885]
Currently, only one person can edit entries at a time. It would be better if several people could edit entries at once. Currently, if I am the second person editing, and I hit enter, numbers someone else has changes that haven't been updated by me will be reset to the numbers on my screen.

**Comment by geoffhumphrey** [comment]
Assuming that you're speaking of marking entries as "paid," "received," and adding staff/admin notes, on-the-fly updating of entry records was implemented in version 2.2.0.
