### ISSUE TITLE
Required Info

### ISSUE THREAD

**Issue by bwestfall03** [geoffhumphrey/brewcompetitiononlineentry#886]
Participants cannot edit their entries and add the required info for 30C and 34A. I have tried to edit it as well as admin and cannot do so.

http://brewoff.brewcomp.com

**Comment by bombersandtalls** [comment]
Same here for styles 29A and 33B.  Adding from admin also gives the same error.
" More information is required for your entry to be accepted and confirmed. See the area(s) highlighted in RED below. Unconfirmed entries may be deleted from the system without warning. " 

Please advise.  Thanks.

snafu.brewcompetition.com

**Comment by geoffhumphrey** [comment]
I'll look into it ASAP. At the moment, I'm kind of at a loss at a possible cause since the same codebase was used to for a recent comp I helped organized and everything was working as expected. I'll update when I find a cause and have a solution in place later today.

Thanks for your patience.

**Comment by geoffhumphrey** [comment]
The code has been pushed to all hosted installations. Please let me know if the issue persists. Apologies for any inconvenience this has caused.

**Comment by bombersandtalls** [comment]
Confirmed resolved.  Thanks!
