### ISSUE TITLE
Issue entering an entry's required info

### ISSUE THREAD

**Issue by jodygrenert** [geoffhumphrey/brewcompetitiononlineentry#887]
An entrant is reporting errors trying to fill in info in the "required info" field. He types in the info and submits, but the info then disappears and he encounters an error saying that the required info is missing. I reported this error previously and thought it had been fixed.

I tried the adding the entrant's info for entries 0065 and 0067 by using my administrative login, but the software then swapped in my name as "brewer." Please advise on how to fix this.

**Comment by geoffhumphrey** [comment]
Hi @jodygrenert - this was reported late yesterday and I've got a fix in the latest commit. I'll push it to all hosted sites later today.

This appears to be isolated to hosted installations.

**Comment by geoffhumphrey** [comment]
The code has been pushed. Please let me know if the issue persists. Apologies for any inconvenience this has caused.
