### ISSUE TITLE
Entry Drop Off Box Additional Text Request

### ISSUE THREAD

**Issue by buergermeister75** [geoffhumphrey/brewcompetitiononlineentry#889]
So evidently people click on the drop off locations link in the Entry Drop Off box on the main page to find the drop off location they want to go to, but they forget the disclaimer in the drop off location note field that pick up at said location is before the competition registration closes. 

They then say, 'well it said on the main page that entries were accepted at drop off locations until x date'.

Can we get some additional wording added to the Entry Drop Off box on the main screen along the lines of "Note: there could be earlier deadlines for some drop off locations."? This will save us from having to do a custom mod every time we upgrade the competition site.

Thank you - Bruce B.

**Comment by geoffhumphrey** [comment]
Hey Bruce,

What do you think about adding a warning modal to alert users of what's in the note field? When users click on the map link, they would see this warning and have to click "I Understand" to get to the Google Map.

![2018-02-07_15-36-27](https://user-images.githubusercontent.com/5216502/35945314-09954194-0c1d-11e8-8b49-824227a0178e.jpg)

**Comment by buergermeister75** [comment]
That is nice but that's assuming that the entrant will click on the map icon. They may already know where the shop is. My suggestion warns them up front that they need to pay attention in the event there is an early pick up. I've had users cite that box on the main page specifically because they use their mobile device and went no further.

**Comment by geoffhumphrey** [comment]
Ah. Gotcha.

What about this: a bit more generic text directing users to pay attention to any notes for each drop-off location, placed both on the sidebar and on the Info screen.

![2018-02-08_12-26-03](https://user-images.githubusercontent.com/5216502/35995878-f722fdca-0cd1-11e8-8881-5507caefbf1d.jpg)

![2018-02-08_13-11-15](https://user-images.githubusercontent.com/5216502/35995882-fafe7cf8-0cd1-11e8-93eb-ee2229b7ffc5.jpg)

**Comment by buergermeister75** [comment]
I like it. Please make it so.

Thank you, 
Bruce
