### ISSUE TITLE
Error Uploading Scoresheets as Admin

### ISSUE THREAD

**Issue by cbwatkins** [geoffhumphrey/brewcompetitiononlineentry#890]
We were able to successfully upload scoresheets using a Top-Level-Admin account, but had issues uploading using a regular Admin account.  We first attempted to upload multiple files with regular admin account and some got posted to participant accounts, but some did not. We verified the filenames were correct (6 digit entry number PDF file), so that was not the issue.  When we attempt to upload a single file using standard admin account we get error everytime: "You must log in and have admin privileges to access administration functions."

**Comment by RJHeath** [comment]
I appear to be having a similar issue.  Haven't tried top-level Admin account yet, but from my regular Admin account I get the same error on uploading single files, and no evidence that batch uploads work at all.  Tried with judging and 6-digit entry number.  

I have a hosted site:  https://bluffcitybrewers.brewcomp.com/

**Comment by bobwright011** [comment]
I also had a similar issue last week uploading 4 of my 269 score sheets to the database, even using a top level admin account. The rest all uploaded flawlessly.  Would not work for these files using either single or multiple upload function.  Also, rescanned and tried again without any luck.

**Comment by brouse69** [comment]
I am on a hosted site, and don't necessarily get an error - it just doesn't upload the files and says there are no files in the folder. I am a top-level admin too.

**Comment by geoffhumphrey** [comment]
Bob, on your hosted site, I was able to upload a PDF via the multiple uploader option and via the single file option using both the latest versions of Chrome and Firefox. I would advise using one of those two browsers, clearing your cache/cookies, and then trying again.

Also, make sure Scoresheet Upload File Names in your site preferences for naming the PDF files correct. The choices are 6-digit judging number or 6-digit entry number.

See also these issues: #1042, #1014, #1004 for more information.

**Comment by brouse69** [comment]
Seems to be working now - weird...

Thanks for the reply.

**Comment by brouse69** [comment]
Okay - some upload and some don't. I didn't see where a size limit was specified, but it seems that any file >= 11 MB gets an "X" over it in the multi-file upload file drop area, and does not get uploaded.

**Comment by geoffhumphrey** [comment]
Yes, there is a 10 MB limit for each file. I'll make sure to add that piece of info to the upload instructions/parameters.
