### ISSUE TITLE
New Designations

### ISSUE THREAD

**Issue by buergermeister75** [geoffhumphrey/brewcompetitiononlineentry#891]
As head of the BJCP Cider Judge Committee I suggest that the Cider Judge designation be added in the release after this one. Please have it mimic the Mead Judge functionality. 
I'd also like to suggest adding Professional Mead Maker and Professional Cider Maker under the Designations section and that functionality mimic the Professional Brewer designation.

**Comment by geoffhumphrey** [comment]
Sounds reasonable to me! Out of curiosity, when do you expect the cider designations to be "official" - this spring?

**Comment by buergermeister75** [comment]
Hopefully April.
