### ISSUE TITLE
Best of Show winner display problems

### ISSUE THREAD

**Issue by jodygrenert** [geoffhumphrey/brewcompetitiononlineentry#893]
Geoff,

I have 2 issues with the winners display for the site. 

1. Best of Show should display BOS 1, 2, 3 and HM, but it's only displaying BOS 1.
2. All the other custom awards should not have "Best of Show" in the title.

Thanks for looking into this. I've combed through the settings several times and can't correct this.

-- Jody

**Comment by geoffhumphrey** [comment]
One thing to check before I dive into the code - check your BOS settings for each of your Style Types (Admin Dashboard > Competition Preparation > Manage Style Types). Make sure that the BOS Method for the affected style types is 1st through 3rd.

Custom awards do say Best of Show by default - the info text on the Admin > Getting Started > Custom Categories page states:
> Custom categories are useful if your competition features unique “best of show” categories, such as Pro-Am opportunites, Stewards’ Choice, Best Name, etc.

Thanks Jody!

**Comment by jodygrenert** [comment]
Yep, the "1st, 2nd and 3rd places" option is selected.

**Comment by geoffhumphrey** [comment]
OK. I'll dive in. Stay tuned.

**Comment by geoffhumphrey** [comment]
Got it. The DB query to display the BOS winner(s) for each style type had a hard-coded scorePlace variable as '1' only. Line 9 in /includes/db/output_results_download_bos.db.php was thus:
```
$query_bos = sprintf("SELECT a.scorePlace, b.brewName, b.brewCategory, b.brewCategorySort, b.brewSubCategory, b.brewStyle, b.brewCoBrewer, c.brewerLastName, c.brewerFirstName, c.brewerCity, c.brewerState, c.brewerBreweryName, c.brewerClubs FROM %s a, %s b, %s c WHERE a.eid = b.id AND a.scorePlace='1' AND c.uid = b.brewBrewerID AND scoreType='%s' ORDER BY a.scorePlace", $prefix."judging_scores_bos", $prefix."brewing", $prefix."brewer", $type);
```
Note the a.scorePlace='1' in the query. This was incorrect. I corrected it by factoring in the choices that Admins are able to define for each style type - 1 (first place only), 2 (first and second only), and 3 (first, second, third and HM). Thus, the code was rewritten as:

```
if ($row_style_type['styleTypeBOSMethod'] == 1) $scorePlace = "AND a.scorePlace = '1'";
elseif ($row_style_type['styleTypeBOSMethod'] == 2) $scorePlace = "AND (a.scorePlace = '1' OR a.scorePlace='2')";
else $scorePlace = "";

$query_bos = sprintf("SELECT a.scorePlace, b.brewName, b.brewCategory, b.brewCategorySort, b.brewSubCategory, b.brewStyle, b.brewCoBrewer, c.brewerLastName, c.brewerFirstName, c.brewerCity, c.brewerState, c.brewerBreweryName, c.brewerClubs FROM %s a, %s b, %s c WHERE a.eid = b.id %s AND c.uid = b.brewBrewerID AND scoreType='%s' ORDER BY a.scorePlace", $prefix."judging_scores_bos", $prefix."brewing", $prefix."brewer", $scorePlace, $type);
```

This will be in the next commit and release.

Jody, I've updated your hosted installation with the correct code. All BOS places are now displaying.

**Comment by bryanflaherty** [comment]
We had the same issue last night when we tried to print up the BOS results.

**Comment by geoffhumphrey** [comment]
All hosted installations have been updated with the fix.

**Comment by bryanflaherty** [comment]
Thank you Geoff,
Is there a location to make requests for additions to the BCEOM functionality, (e.g. printing labels by entry number vice categories, printing labels with entry number and brewer name for the score coversheets, and printing labels by table number)
Cheers,Bryan
    On Monday, March 12, 2018, 10:38:52 AM EDT, Geoff Humphrey <notifications@github.com> wrote:  
 
 
All hosted installations have been updated with the fix.
