### ISSUE TITLE
Best Club Winner Display issue

### ISSUE THREAD

**Issue by jodygrenert** [geoffhumphrey/brewcompetitiononlineentry#894]
The website is not displaying the correct 2nd place "best club" winners -- which should be a tie between four clubs with 3 medals each. The attached spreadsheet shows the clubs in red text.

[Edit: Attachment removed] ~ Geoff

**Comment by geoffhumphrey** [comment]
Hmm. That is definitely incorrect! Let me take a look at the code for the calculations. For now, my advice would be to disable display of the "best club" via Admin > Site Preferences until I can track down the issue. Apologies!

**Comment by jodygrenert** [comment]
Looks like I can't disable the winners display for best club unless I disable it for all winners. I'll just let it display wrong for now and alert the participants to check again once it's fixed.

**Comment by geoffhumphrey** [comment]
In Admin > Preferences, look for the label Best Club Display? Up to which Position? - select "Do not Display." This will disable display of the best club award only but keep all other winner displays.

**Comment by jodygrenert** [comment]
Got it. It's un-displayed now. Thanks.

**Comment by geoffhumphrey** [comment]
@jodygrenert - I think I've tracked down the bug and have implemented what I believe will fix the display issues for the best club functionality. If you would, go back to your installation and display the best club using the option of your choosing. If the numbers don't jibe with your expectations, please let me know.

Note that the functionality (as intended) does not factor in any custom categories. Only placing entries at tables and BOS.

**Comment by jodygrenert** [comment]
Geoff,
I think it's displaying the "best club" winners correctly, except.....

- Why are there decimals in the totals (see attached screenshot) if I'm allowing no additional points beyond 1st,2nd,3rd? It seems like the database is assigning some small point value to something.
- 
- Can you confirm for me that my settings (see 2nd screenshot) will ALWAYS pick the club with the most medals (including BOS awards)? That's listed as my first tie-breaker, but I really want it to be the determining factor for who wins.

**Comment by geoffhumphrey** [comment]
Hey Jody,

I'm not seeing the screenshots here, but when I look at [your install](http://obw.brewcomp.com), there aren't any decimal places showing. Just round numbers, which is expected given your tiebreaker methodologies and the points that were allocated.

In the case where tiebreakers come into play and the differences are less than 1, decimal numbers will be displayed.

**Comment by geoffhumphrey** [comment]
Here's some screens for a particular scenario where the decimals will play a factor. 

First, the configuration:
![2018-02-20_9-52-03](https://user-images.githubusercontent.com/5216502/36437479-5599b3de-1624-11e8-8fc3-2a389f4be4ec.jpg)

The results:
![2018-02-20_9-46-48](https://user-images.githubusercontent.com/5216502/36437510-6bd33cc4-1624-11e8-9ecb-fff53f734f1c.jpg)

**Comment by geoffhumphrey** [comment]
My apologies, I completely forgot that the decimals places are displayed for **Admins only**. So, as the code stands now, if you're just Joe Brewer and not an admin, you'll only see whole numbers. I'm not entirely sure if that's useful or not.

**Comment by jodygrenert** [comment]
Thanks, Geoff. That clears it up. Attached are the screenshots I meant to send, but I think I'm clear on how it all works now.
![snip20180220_2](https://user-images.githubusercontent.com/18756031/36442189-e9b8f1ec-1642-11e8-84ff-b6c8ce3ba133.png)
![snip20180220_1](https://user-images.githubusercontent.com/18756031/36442190-e9c8269e-1642-11e8-8231-c3366fbf722d.png)
