### ISSUE TITLE
bootstrap-select repository has moved

### ISSUE THREAD

**Issue by caseyjhol** [geoffhumphrey/brewcompetitiononlineentry#895]
I'm the lead developer for the bootstrap-select project. I see that your project is utilizing bootstrap-select and you have been kind enough to include us in your "Many Thanks" section. However, we have recently moved the repo and documentation. The new location for the documentation is: https://developer.snapappointments.com/bootstrap-select. If you could update the link on your website it would be much appreciated. Thanks!

**Comment by geoffhumphrey** [comment]
No problem. Done! Thanks for letting me know...

**Comment by caseyjhol** [comment]
Great - thanks!
