### ISSUE TITLE
Blank Page and Fallback Instructions not working

### ISSUE THREAD

**Issue by editjosh** [geoffhumphrey/brewcompetitiononlineentry#896]
I'm hosted through GoDaddy with MySQL 5.5 and PHP 5.6.27. I followed all the instructions on the webpage and the config.php file, and also did change my .htaccess file since i am hosting in a subfolder on my domain. 

I get the blank page. 

I also tried the Fallback Installation, however I find those instructions a little advanced, since I am not sure how to change the password or security question (not listed in the instructions). I was able to upload the database file via phpMyAdmin, and changed the $prefix variable in the config.php file to include that, but I'm not sure why it's still not working.

When I browse to the config.php file in my browser, I get this:
```
Warning: mysqli::mysqli(): (HY000/2002): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) in /home/content/00/7206600/html/ecb/register/site/config.php on line 58

Warning: mysqli_set_charset(): Couldn't fetch mysqli in /home/content/00/7206600/html/ecb/register/site/config.php on line 59

Warning: mysqli_query(): Couldn't fetch mysqli in /home/content/00/7206600/html/ecb/register/site/config.php on line 60

Warning: mysqli_query(): Couldn't fetch mysqli in /home/content/00/7206600/html/ecb/register/site/config.php on line 61

Warning: mysqli_query(): Couldn't fetch mysqli in /home/content/00/7206600/html/ecb/register/site/config.php on line 62
```

Is there any further troubleshooting steps I could take? My competition is scheduled in a couple of months and I want to get this up to start accepting entries.

Thank you!

**Comment by geoffhumphrey** [comment]
GoDaddy has been notorious for these sort of shenanigans. I have to be able to track down a reason why...

The fallback method has worked in the past for other GoDaddy users. Here's a few things to make sure you've got in line when using that method:
1. Make sure that your /site/config.php file has the correct environment variables in place for `$hostname`, `$username`, `$password`, and `$database` - check the GoDaddy documentation for specifics.
2. You may need to specify something other than _localhost_ as your `$hostname` variable - see [this GoDaddy Help article](https://www.godaddy.com/help/viewing-your-database-details-with-shared-hosting-accounts-39).
3. Make sure that the `$prefix` variable is set to "baseline_" - e.g., `$prefix = "baseline"`.

You'll get a blank page when trying to access your URL until all of the environment details are correct.

If you are able to get things running and the GUI is intact, you'll **definitely** need to change the default user's password after using it to gain access to the installation's administration functions.

Post back if you believe you've got things correct in your config.php file and things aren't working.

**Comment by editjosh** [comment]
Yes, changing the hostname seems to have done it! I went back to the standard install, not even using the Fallback option with the $prefix = "baseline". So I think it should work with the defaults. I'd highly recommend letting people know that if they have GoDaddy hosting accounts to update the $hostname variable as instructed in the Help Article you linked.

**Comment by geoffhumphrey** [comment]
Will do! Glad it was a relatively easy fix for you.

**Comment by editjosh** [comment]
Just as a followup that is probably another GoDaddy issue, I couldn't get a test email to send for the contact form. What are the requirements for that to work?

**Comment by geoffhumphrey** [comment]
@editjosh - in version 2.1.18 that will be releasing soon, another method of sending mail using SMTP can be employed that may allow for emails to be sent via BCOE&M. Once it releases, I would suggest implementing it (see [this issue comment](https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/955#issuecomment-531924016) for more information on how to do that).
