### ISSUE TITLE
Update to 2.1.11 from 2.1.9 & 2.1.10 silently fails

### ISSUE THREAD

**Issue by trekie86** [geoffhumphrey/brewcompetitiononlineentry#897]
I attempted to update to 2.1.11 several times. Each time the update page said it was successful but then when I went to login, there was a generic 500 error. Update looking at the system table, the version still read as the previous version.

**Comment by geoffhumphrey** [comment]
There isn't an "official" update from 2.1.9 to 2.1.11. Any updates are taken care of behind the scenes and not via the update.php script - the necessary ones are made in via scripts in the /updates/off_schedule_update.php file when the index.php file is accessed for the first time after replacing the files on the server.

Not sure why you're getting the 500 error without some server logs. My suggestion would be to do a force update by changing the FORCE_UPDATE variable in paths.php to TRUE, re-uploading it, accessing the index.php file once to make sure the updates to 2.1.11 have been made, and then returning the variable back to FALSE, and uploading it one more time.

The only time users should be routed to the update.php file when they access index.php is when updating from any version prior to 2.1.5 to 2.1.6 on up.

In any case, I'll take a look at implementing some failsafe scripting in update.php.
