### ISSUE TITLE
Required Info boxes do not pop up for adding entries in custom styles with required info specified

### ISSUE THREAD

**Issue by Ravenstein589** [geoffhumphrey/brewcompetitiononlineentry#898]
I've tried as many settings at I can but no good.  The add entry page shows up like a normal entry without required info selected.

**Comment by geoffhumphrey** [comment]
What version of the software are you running? If it's any version prior to 2.1.11, please update the installation and see if the issue persists. See issue #852 for an associated issue and fix when running 2.1.11.

**Comment by Ravenstein589** [comment]
Running 2.1.11 I will give that fix a try.

**Comment by medirckx** [comment]
Also running 2.1.11, recently updated, and having the same issue

**Comment by dmofot** [comment]
Running 2.1.11 and attempted the fix from issue #852 and the issue still remains.  Initially, you can write whatever you need to in the comment box, but it doesn't get saved and you get a `More information is required for your entry to be accepted and confirmed. See the area(s) highlighted in RED below.`, but there is no red area below (no comment box).  For a split second I can see the box, before it disappears.

You can try it here: http://bhc-test.wort.org/ and try to add an entry into 36A: Double-strength New England IPA.

**Comment by dmofot** [comment]
@geoffhumphrey I just upgraded our test site at http://bhc-test.wort.org/ to 2.1.12 and the issue is still appearing.  Specifically, it's only occurring on our category `36A Double-strength New England IPA`.  It does not happen in other categories we created, e.g. `35A New England Style IPA`.  Is it possible there was an issue with the category creation?

**Comment by geoffhumphrey** [comment]
It is entirely possible. Are the two categories essentially identical (e.g., requiring special ingredients, etc.)? If so, my advice, until I can dig into the code, is to delete the 36A category completely and re-enter it.
