### ISSUE TITLE
ptBR package 

### ISSUE THREAD

**Issue by fdotta** [geoffhumphrey/brewcompetitiononlineentry#899]
Will very nice to have BCOE&M in other languages, especially Brazilian Portuguese.

Thanks for the awesome work!!!

**Comment by geoffhumphrey** [comment]
We're working on it! Someone has volunteered to translate the package into Brazilian Portuguese and has reported they are half-way there. Stay tuned!

**Comment by miki95** [comment]
Is someone working in the Spanish translation? It would be nice to have a doc explaining how to translate the package

**Comment by matdias** [comment]
Is the brazilian portuguese translation finished? Is there any link for the package download?

**Comment by geoffhumphrey** [comment]
The Brazilian Portuguese translation has been completed and will be available in the next version, 2.1.19, planned for 10 July  2020.
