### ISSUE TITLE
Entries cannot be edited once max entries has been reached

### ISSUE THREAD

**Issue by schubrew** [geoffhumphrey/brewcompetitiononlineentry#901]
Using version 2.1.11

Our competition filled up in 24 hours but our entry deadline isn't for another 2 months. Now that we hit our max entries - entry registration has closed but entrants cannot edit their entries to change them. I know this has happened for another local competition too.

**Comment by geoffhumphrey** [comment]
Yes, this has been confirmed. Please see Issue #866 for a fix.

**Comment by schubrew** [comment]
sorry didn't see that - Thanks for the quick response - I will implement this today.

**Comment by geoffhumphrey** [comment]
NP! That fix should solve your issue.
