### ISSUE TITLE
Issue with specialty description

### ISSUE THREAD

**Issue by Steveg297** [geoffhumphrey/brewcompetitiononlineentry#902]
A user reported an issue with specialty description character limit.  The limit is set to 50 characters and they wanted to add more description information.  Is this changeable, or are we stuck with that limit?  Is it possible to set it to 200 characters?

Thanks,

SteveG

**Comment by geoffhumphrey** [comment]
The amount of characters is determined via Admin > Preferences > Website Preferences. The default is 50, but Admins can certainly increase that.

**Comment by Steveg297** [comment]
Thanks!

SteveG 
 
  On Wed, Mar 7, 2018 at 11:30 AM, Geoff Humphrey<notifications@github.com> wrote:   
The amount of characters is determined via Admin > Preferences > Website Preferences. The default is 50, but Admins can certainly increase that.
