### ISSUE TITLE
Viewing scoresheets in BCEOM

### ISSUE THREAD

**Issue by bryanflaherty** [geoffhumphrey/brewcompetitiononlineentry#903]
How long after you enter the scores and upload the scoresheets before the participants can view them under their account?

**Comment by geoffhumphrey** [comment]
Currently, scoresheets are available after the last judging date/time has passed, but only if scoresheets have been uploaded.

In the next version, scoresheets will only be available when scores and results are published - after the date/time defined by Admins in Website Preferences.
