### ISSUE TITLE
Localization: DST Broken across the whole site

### ISSUE THREAD

**Issue by FDillon00** [geoffhumphrey/brewcompetitiononlineentry#905]
I had my comp set up to accept entries at 8am CST (Central Time US & Canada) should have DST.  The entry window did not open and I edited the time to allow it to open at 7am CST. Then the window opened and the entries updated shows off by -1 hour from my local CST. (Screen shot with OS time correct)
![entry_window](https://user-images.githubusercontent.com/5970995/37555996-14c1f1ca-29be-11e8-9205-7185000c16fd.png)

I then when to check the admin dashboard and the status time is off my -1 hour (Screenshot with OS time correct)
![admin_dash](https://user-images.githubusercontent.com/5970995/37556048-78d47fb6-29be-11e8-81ad-df81f8c1d1bb.png)

Here's where it gets fun, I manage entries an notice the time stamps on the entries are off by  **_+1_** hour.  (Screenshot with OS time correct)
![entry_manage_dash](https://user-images.githubusercontent.com/5970995/37556065-9e8db768-29be-11e8-8adb-e7be2900cb86.png)

Finally I got to the "Website Preferences" menu to confirm Localization settings. Everything looks correct however I am unable to change the setting. I select a NON-DST time zone, (GMT -6:00) Canada Central Time (No Daylight Savings), and click the "Set Website Preferences" button. The next page says Info saved correctly but I got back to Website Preferences and it still shows CST (Central Time US & Canada).
![sitepref_local](https://user-images.githubusercontent.com/5970995/37556161-f3135f44-29bf-11e8-887d-ee917c5af642.png)

**Comment by geoffhumphrey** [comment]
You are correct. To fix this issue, you'll need to update line 21 (or thereabout) in the /lib/date_time.lib.php file to set to a php supported timezone that does observe DST like America/Chicago - apparently Mexico City does not.

Currently, the line is:

``
'-6.000'=>'America/Mexico_City',
``

It should be:

``
'-6.000'=>'America/Chicago',
``

In the 5+ years that localization has been in place, this issue has never surfaced for the Central timezone. Weird.

Hope that helps.

**Comment by FDillon00** [comment]
Thanks a lot, it got really weird when the "Updated" time in the entry view was +1 hour when everything else was -1 hour. 

Thanks for all your work on this.
