### ISSUE TITLE
There is no email address in the system that matches the one you entered. Try again?

### ISSUE THREAD

**Issue by mavandeh** [geoffhumphrey/brewcompetitiononlineentry#906]
I managed to log in and set up the competition, but I have a few items to change.  I've been able to log in no problem prior to this.

Now I'm getting login errors, and when i try to recover password:
![image](https://user-images.githubusercontent.com/24830482/37788452-7dfdb312-2dcf-11e8-8336-af8e89d621e7.png)

I looked in the database where I think the userlist should be:
![image](https://user-images.githubusercontent.com/24830482/37788623-e783fdf0-2dcf-11e8-8a8f-5294e3f9ee0e.png)

"And I said hey, what's going on?"

http://razecompetition.info

EDIT: More info, I can log in from my phone.  Maybe an issue with my company's IT blocking something?

**Comment by geoffhumphrey** [comment]
If you're able to on your phone (another browser), it most likely has to do with session caching. Try clearing your browser cache and cookies. Then try to log in again.
