### ISSUE TITLE
Entry Fee doesn't update in "Pay" section after update Contest Info

### ISSUE THREAD

**Issue by miki95** [geoffhumphrey/brewcompetitiononlineentry#911]
After updating "Per Entry Fee" in Contest Info, the fee shown in Pay Entry Fees doesn't get updated.

**Comment by geoffhumphrey** [comment]
This has to do with sessions. Try logging out of the site and logging back in. If that doesn't work, clear your browser's cache and cookies. Or, try another browser.

**Comment by miki95** [comment]
Yes, just discovered that, thanks!
