### ISSUE TITLE
Safe to update from 2.0.1 to 2.1.11 while competition is active?

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#914]
I reset my website for this year's competition, and just now realized that I'm still running 2.0.1

Entrants and judges are already registering.

Is it safe to update at this point, or should I wait until this years comp is over?

Thanks!

**Comment by geoffhumphrey** [comment]
It is safe. User account and entry data is not affected by an upgrade.

That said, I would caution you to do a couple of things prior to performing an upgrade:
1. Close your competition's account creation and entry windows.
2. Wait 15-30 minutes or so after closing to make sure anyone who had started the account creation prior can finish up and add their entries.
3. Edit your paths.php file to put your site into maintenance mode (change ``define('MAINT', FALSE);`` to ``define('MAINT', TRUE);``

Then, go through the [update process](http://brewcompetition.com/upgrade-instructions). Once you've finished, return your site back to production mode in paths.php - ``define('MAINT', FALSE);``. Then, open up your entry and account creation windows once again.

**Comment by BrewDrinkRepeat** [comment]
Are there any special upgrade instructions for 2.1.11 to 2.1.12, or just upload the new site files and it’s done?
