### ISSUE TITLE
Report with winners entry numbers and names

### ISSUE THREAD

**Issue by Steveg297** [geoffhumphrey/brewcompetitiononlineentry#915]
Hi,

I would like to be able to set up a report with the winning entry numbers, their places, and the brewers names.  I can print winners with the entry categories, but not with their entry numbers.  This would be helpful because the cover sheets only have the entry numbers and I need to be able to match them up to do the sorting for prize awards.

Thanks,

SteveG

**Comment by Steveg297** [comment]
Ideally, I would like a report that would provide the winners name in large type, each of his entries with their entry number, their places, and BOS information.  This would allow me to pull all of his sheets and I could make prize awards accordingly.  Thanks

**Comment by markalston** [comment]
Did you try the "Summaries -- All Participants with entries" report?  This is the report we use to do exactly what you are suggesting.  It is in the admin dashboard under reports.

**Comment by geoffhumphrey** [comment]
In the next version (2.1.14), BOS places will be added. I can't fathom why they weren't added previously.

**Comment by Steveg297** [comment]
Does the new version address the database inconsistency?

SteveG 
 
  On Tue, Oct 2, 2018 at 1:46 PM, Geoff Humphrey<notifications@github.com> wrote:   
In the next version (2.1.14), BOS places will be added. I can't fathom why they weren't added previously.

**Comment by geoffhumphrey** [comment]
I'm not sure which inconsistency you're referring to. Something in another issue report?

**Comment by Steveg297** [comment]
Hi Geoff,
Can you help me regain access to our Brewoff website?  I must have made a mistake when doing website cleanup and removed my email address from the system.
2018 Annual South Shore Brewoff


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
2018 Annual South Shore Brewoff


 |

 |

 |


Thanks,
SteveGsteveg297@yahoo.com
