### ISSUE TITLE
CAPTCHA version 1 expired, Version 2 still does not work with HTTPS

### ISSUE THREAD

**Issue by MarieAnnick** [geoffhumphrey/brewcompetitiononlineentry#917]
Using reCAPTCHA version 2 does not work. User gets the message " CAPTCHA was not successful. Please try again." even though the box has been clicked.

**Comment by MarieAnnick** [comment]
I should add, I'm using version 2.1.11

**Comment by Jwwilson3** [comment]
Use Version 1 but you still have to type in the error message that appears in version one to get by.

**Comment by MarieAnnick** [comment]
Version 1 is inactive as of March 31st. There is no longer a way to
validate it as it is no longer generating text to decipher.

**Comment by geoffhumphrey** [comment]
Hmmm. V2 implementation has been around for a couple of releases and this the first report of any problem such as this. It may be a simple as clearing cache and cookies.

Beyond that, what would definitely clear the problem would be to [register your domain and obtain your own API keys from Google](https://www.google.com/recaptcha/admin#list) for use in your installation. If you do go that route, you'll need to change the ``$public_captcha_key`` and ``$private_captcha_key`` variables in /paths.php to the ones that are assigned to you.

**Comment by ercousin** [comment]
@geoffhumphrey I don't think most people set up HTTPS on their comp subdomains, so that could be why no one has reported an issue.

CAPTCHA.V2 is working well on seasonal.gtabrews.ca, but it's only using standard HTTP.

**Comment by MarieAnnick** [comment]
I suspect that's the issue since it was working great before we upgraded to
SSL, however since we're taking personal info we're going to start being
flagged in the near future without it. I'll register a key with Google and
see if that fixes the issue and then get back to you.

Cheers.

**Comment by MarieAnnick** [comment]
Yeah, unfortunately, generating my own keys didn't appear to work. For now,
I've just changed the default variable to TRUE so we can get up and
running.

**Comment by MarieAnnick** [comment]
I also implemented the suggestions on StackOverflow here, issue still persists. 
https://stackoverflow.com/questions/12015814/recaptcha-not-working-on-https

**Comment by gene1wood** [comment]
For anyone still running and old version of BCOE&M like 1.3.2.0 here's [a drop in replacement](https://gist.github.com/gene1wood/e56fa1604c4a3eaafe214ed600bae6c1) for `includes/recaptchalib.inc.php` that I made which upgrades to the v2 interface.

To use it, update `includes/recaptchalib.inc.php` to [this new code](https://gist.github.com/gene1wood/e56fa1604c4a3eaafe214ed600bae6c1) and get a new v2 api key from google, saving the public key in `/site/bootstrap.php` and the secret in `/includes/process/process_users_register.inc.php` and `/includes/process/process_contacts.inc.php`

**Comment by geoffhumphrey** [comment]
This also may have to do with @MarieAnnick's server environment and the solutions that were posited in #920.

**Comment by MarieAnnick** [comment]
The competition is running right now, so I'll run some tests on this issue
once it's done next week and update. I suspect it has to do with folder
permissions.

**Comment by lnkbrw** [comment]
I seem to be having the same issue. I am getting the "CAPTCHA was not successful. Please try again. " error message.

This is a new, clean installation of v2.1.12 - it coexists with other past version installs, but each is assigned their own public_html sub-folder, SQL db, SQL user/pass, and Installation ID number. 

The server itself is hosted space from nixihost.com and runs cPanel for management. User Registration is set to open as of the present date/time. The Website Preferences page is set to use v2 reCAPTCHA.

I created a new reCAPTCHA site profile within my google account and generated new Site and Secret keys. I have edited paths.php and pasted my new keys in the six corresponding lines found under v2 `else{` .

After making these changes, I still get the error message when trying to register a new judge, steward, or entrant.

Any suggestions come to mind? I have some time before we need it, our entry registration will begin in mid-August. Thanks!

**Comment by MarieAnnick** [comment]
I ran the test again without success and continue to have issues. The entire folder is owned by 33 (apache) which solved previous issues with uploading, but not with reCAPTCHA. Public and private keys are pasted in the process files and recaptchalib. Changing the initial value to TRUE in the process files continues to be the workaround.

**Comment by lnkbrw** [comment]
**Can you tell me where to change the value to TRUE?** We are still unable to register new participants and need to open up entries now.

What I didn't mention before is that we also have https turned on and an active security cert installed, which sounds like it is related to the root of the issue.

**Comment by lnkbrw** [comment]
Thanks @MarieAnnick !

**Comment by diatonic** [comment]
For what it's worth, we use SSL on our BCOE&M sites and reCAPTCHA V2 is working fine. See https://idbeer.org and https://pro.idbeer.org.

**Comment by mattwwatson** [comment]
I too am having this issue on https://www.innersydneybrewers.org/brew19 - try using the contact form for example. When I don't specify recaptcha keys, the box does not even show up, so i added my own keys for my domain and now the box shows up and you can click it (and/or get the photo grid popup) but I always get the " CAPTCHA was not successful. Please try again." message. It appears to be failing on the server side from looking at the http traffic, is there any way to get more logs turned on or something?

**Comment by mattwwatson** [comment]
> includes/processes/process_users_register_inc.php, line 8
> includes/processes/process_contacts_inc.php, line 7
> 
> Change $captcha_success = FALSE; to $captcha_success = TRUE;

Is this better than or just the same as turning recaptcha off entirely? I guess there is a visual deterrent that might trick spammers...

**Comment by MarieAnnick** [comment]
Like you said, it might work as a visual deterrent for spammers, but most
of the spam emails you'll get are from bots.

I haven't managed to fix this issue myself, unfortunately.

**Comment by MarieAnnick** [comment]
Alright, I managed to get reCAPTCHA v2 working. All it took was nuking the site from orbit. The issue appears to stem from various fixes and workarounds tied to the fact that the site was running on Debian 7 - so far behind that it was impossible to update. reCAPTCHA v2 appears to play nicely on Debian 10.
