### ISSUE TITLE
Payments Not Being Marked Paid

### ISSUE THREAD

**Issue by Jwwilson3** [geoffhumphrey/brewcompetitiononlineentry#918]
THere are several people who have paid via paypal confirmed by bank statements however the system did not mark them as paid.  Is there something I missed during installation or is there a fix?  Any help would be great.

Thanks  NJHOPZ

**Comment by geoffhumphrey** [comment]
Without implementing the PayPal IPN capability, entries getting marked as paid after a user pays via PayPal is entirely dependent upon the user clicking the "Return to..." link on paypal.com after completing their payment. Unfortunately, there really isn't anything programatically that can be done in this situation, thus prompting the PayPal IPN feature to be incorporated into version 2.1.11.
