### ISSUE TITLE
Unable to update competition info-Browser & Fallback install

### ISSUE THREAD

**Issue by shockey8oz** [geoffhumphrey/brewcompetitiononlineentry#922]
Not sure this is the place to attempt to reach the author.  I have uploaded version 2.1.12 to my shared hosting server.  I am able to setup the software to step 4.  I am getting blank page on attempting to update competition info on browser load running:
PHP 7.0.29
mysqli 10.0.34-MariaDB
fileinfo enabled
session enabled
I have performed the Fallback install.  Again, I cannot update the competition information such as names and dates.  I get the page not found error.  I have been able to perform the necessary updates to the database manually, but that was tedious.
Thanks
shockey8oz

**Comment by markalston** [comment]
Same problem here on any updates or changes. For me I am seeing the data changing but I am getting blank pages back on execution.  

 Looks like a problem in process.inc.php but I can't figure it out so far.

**Comment by markalston** [comment]
It appears to be something that changed between 2.1.11 and 2.1.12 as I don't have that issue going to 2.1.10  from 2.1.9 but do get it when I go to 2.1.12

**Comment by markalston** [comment]
So, now it is working.  I think maybe it was an issue with the php-fpm cache.  I restarted php-fpm and it is working.  Perhaps that was a coincidence but it's worth a try.
