### ISSUE TITLE
Feature request: Modify Brewer's Specifics field

### ISSUE THREAD

**Issue by MarsMug** [geoffhumphrey/brewcompetitiononlineentry#923]
In BJCP competitions we generally don't pass on the information in Brewer's Specifics to the judges.  It's useful as a competition organiser for us to make sure the beer is properly entered though.  e.g. making sure that an American Pale Ale with Peach that is entered as a standard APA gets moved to the fruit beer category.

The problem is that the Brewer's Specifics says that you should enter information that you wish the judge to consider, which suggests we are going to pass on the information, or that it can be used to mitigate an entry being incorrectly categorised.  

I realise that this field is perhaps used for some competitions, so could we have the option to modify the instructions around Brewer's Specifics so we can tailor it per competition?

**Comment by ercousin** [comment]
I don't see why you can't just fully disable that field for your competition, then use the info in Req/Op fields to do the same check.

**Comment by MarsMug** [comment]
Yes, I think in retrospect that would be better.  Closed!
