### ISSUE TITLE
Bottle Label Text Duplicated - "All Styles" vs "Only Styles Where Required"

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#924]
Running 2.1.11

I went to print bottle labels for my current competition and noticed that the specialty stickers are messed up:
![image](https://user-images.githubusercontent.com/1551339/39684923-3483c8ac-518d-11e8-9ef7-e3622aba2620.png)

## Problem 1)
For Specialty styles, [StyleID-Style-Judging#] is printed twice when printing "All Styles".
This seems to work if printing "Only Styles Where Required". However for M1A in "Only Required" mode, there is no [StyleID-Style-Judging#] printed:
![image](https://user-images.githubusercontent.com/1551339/39685226-f8abed4e-518e-11e8-9408-b804bfed9de6.png)
vs
![image](https://user-images.githubusercontent.com/1551339/39685229-007a7ff4-518f-11e8-9c49-df558591c1f4.png)

## Problem 2)
For 28A, this is my first time seeing the new"Op:" info. I guess this was the solution to #725 ?

Was the specialty text size shrunk to make this fit? I'm surprised see 5 lines fitting on bottle labels, with what appears to be room for 1-2 lines more. Does this mean the recommended char limit is now longer than 50 char for 5160 labels? Does char limit apply to both Op + Req combined?

**Comment by geoffhumphrey** [comment]
Completely reworked the code of the function to a) get rid of the duplicates, b) allow for customization of the amount of characters allowed via the ``$character_limit`` variable defined at the top of the script (only for non-hosted installations). 

For the label sizes and font/font size used, it appears like the maximum is 6 lines of 34 characters each (for a total of 204). Setting the ``$character_limit`` variable to 68 (two lines) seems to do the trick.

In the old code, the font size was not adjusted, but the character limit was limited to 50 for both required info and optional info to fit if needed. There's new logic that doubles the character limit of either Special Ingredients or Optional Info if only one is present. If both are present, however, the character limit will be enforced.

Download the attached zip, unpack, and upload the file to your /output/ directory. Give it a try, and let me know if it helps.

[labels.output.php.zip](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/1981525/labels.output.php.zip)

**Comment by geoffhumphrey** [comment]
In the zip file, I neglected to force the PDF to download. To do this, comment out ``$pdf->Output();`` and un-comment ``$pdf->Output($filename,'D');``. Thus, lines 224 and 225 should be:

```
//$pdf->Output();
$pdf->Output($filename,'D');
```

**Comment by ercousin** [comment]
@geoffhumphrey : Finally got around to trying out your .zip, it (mostly) seems to work! More info below..

### With Required Info - All Styles (Judging Numbers)
- Styles that have notes, [StyleID-Style-Judging#] is printed only one
![image](https://user-images.githubusercontent.com/1551339/40259748-6dfd6c46-5ac5-11e8-9234-7d5d22b7054c.png)

### With Required Info - Only Styles Where Required (Judging Numbers)
- M1A no longer included
![image](https://user-images.githubusercontent.com/1551339/40259836-cb41c6b8-5ac5-11e8-947c-adc73b275192.png)

## Another Issue
I still see one issue with Req Info from radio buttons not triggering inclusion in "Only Styles Where Required" report. For some reason this only seems to affect M1A, and 25B is included in both reports.

Eg.

### With Required Info - All Styles (Judging Numbers)
![image](https://user-images.githubusercontent.com/1551339/40260130-0b0122d4-5ac7-11e8-8842-581b656729ed.png)


### With Required Info - Only Styles Where Required (Judging Numbers)
![image](https://user-images.githubusercontent.com/1551339/40260113-fc7549b6-5ac6-11e8-84f4-91fdfc70911b.png)

**Comment by ercousin** [comment]
If I had to guess, I'd say that radio buttons for Cider/Mead are treated differently than Beer.

For 25B, I see the radio button info showing up after Req:
![image](https://user-images.githubusercontent.com/1551339/40260188-5dc37d3c-5ac7-11e8-9538-ced01969dc66.png)

For C2F/M1A, the radio button info shows up without Req:
![image](https://user-images.githubusercontent.com/1551339/40260216-723c5612-5ac7-11e8-85a4-3837771da7ce.png)
