### ISSUE TITLE
Front-Home page modifications

### ISSUE THREAD

**Issue by glienhard** [geoffhumphrey/brewcompetitiononlineentry#928]
Two thing with the front or Home page.  It would look much better if the competition logo was centered over the right column.  Then it would also be very beneficial if there was a way to post announcements to the Home page.  There are times when we need visitors to see an update or other important message as soon as they visit the site.

**Comment by geoffhumphrey** [comment]
With regard to the logo, it should be centered. I'll double-check the code.

With regard to announcements, etc., you can certainly utilize the custom module function. I've used a custom module to display announcements for quite a few competitions I've organized in the past. You'll need to activate the functionality via Admin > Preferences > Website Preferences.

_** Note: the Custom Module function is not available on hosted installations_

Once activated, go to Admin > Preferences/Customization > Manage Custom Modules. 

![2018-05-29_8-09-38](https://user-images.githubusercontent.com/5216502/40664492-4798dc4c-6318-11e8-9415-820403648287.jpg)

Make sure to read and follow the guidelines presented:

> Custom modules are useful for competitions that wish to extend BCOE&M's core functions. Provided in the program package are two sample HTML files to get you started, located in the “Mods” sub-folder. All mod files MUST have a .php extension (e.g., name_of_file.php - some servers running PHP are not configured to "include" files with other exensions). For the program to use/display any custom module, its information MUST be added into the database. The corresponding file should be uploaded to the “mods” sub-folder via secure FTP.

You'll need to know/research a bit of HTML code - you can use any Bootstrap 3.3 component and/or CSS style. In particular, I have used [Alerts](https://getbootstrap.com/docs/3.3/components/#alerts) and [Helper Classes](https://getbootstrap.com/docs/3.3/css/#helper-classes) previously, but you could also get fancier and use the [Jumbotron](https://getbootstrap.com/docs/3.3/components/#jumbotron) or even a [Carousel](https://getbootstrap.com/docs/3.3/javascript/#carousel) for a series of images.

**Comment by geoffhumphrey** [comment]
I forgot to mention that when you add a Custom Module, you can specify a number of things - its type, the audience, where it will be displayed, the order, etc:

![2018-05-29_8-19-46](https://user-images.githubusercontent.com/5216502/40664869-1bcfc160-6319-11e8-8465-0604e57de896.jpg)

**Comment by glienhard** [comment]
On the comp logo, I had to add a center tag to the sections/sidebar.sec.php
in order to get the logo to be centered.  Actually, I has not been centered
in several versions.  This is just my first time reporting it.  Sorry I
didn't let you know sooner.

On the announcements, thank you very much!  I will check out the custom
mods and see what I can make them do.  That beats going into the database,
changing the field type and length, just so I can enter a bunch of html
into the host club entry.  (Yes I really did end up doing that to get the
announcement posted :-)  Sounds like the custom mods will work great for
lots of different things.

Cheers!
