### ISSUE TITLE
(2.1.12) Preview 'Best Brewer' results and calculation

### ISSUE THREAD

**Issue by MarsMug** [geoffhumphrey/brewcompetitiononlineentry#929]
The ability to have a best brewer is recently new, but there's no way to see the results without publishing them to the front page of the site.  Makes it difficult to check everything is correct before it gets announced.

**Comment by MarsMug** [comment]
Same for best club calculation too.

**Comment by geoffhumphrey** [comment]
Sound idea. I'll put it in the queue.
