### ISSUE TITLE
(2.1.12) Bug in best brewer calculation

### ISSUE THREAD

**Issue by MarsMug** [geoffhumphrey/brewcompetitiononlineentry#930]
First time we published the best brewer calculation to the front page of the site it calculated everything correctly.  We then took results offline, but when we then republished them later it erroneously awarded additional points for to some competitors (which changed the result).

First time was right, later publishing was incorrect.  

See http://londonandsoutheast.brewcompetition.com/

**Comment by geoffhumphrey** [comment]
If any data point has changed, the calculations will change as well (a score, club name, etc.). That's my suspicion - especially since the calculations were correct one time and not another. The formulas do not change, only user input - so I would check your data as well as your tie-breakers.

**Comment by MarsMug** [comment]
I just figured out what happened - it's including the Best of Show results in the calculation.  So if you got a 1st on a table and then that same beer won BoS you would have 2x1sts counted.

Would it be possible to exclude BoS from the calculation?

**Comment by geoffhumphrey** [comment]
It is certainly possible, but I'm not quite sure why you wouldn't want to. Seems to me the BOS winner should be rewarded for their overall win. After all, like in your situation, they really did win two first places.

Just putting it out there for general discussion...

**Comment by jimmyorkin** [comment]
I should also add, we separate the "beer" brewer of the contest and the "mead and cider" brewer of the contest. I don't expect BCOEM to handle all our special awards but I would expect BoS to be excluded from the calc.

Jimmy

**Comment by MarsMug** [comment]
We've always run Champion Brewer separate from Best of Show.  We limit each brewer to 3 entries and Champion Brewer is judged as the best results across 3 (diverse) beers to show their consistent quality as a brewer.

BoS places already get their reward, and giving them extra credit in Champion Brewer is double dipping as it makes them a near shoo-in for that too.

For example, this year we would have been very close to awarding the Champion Brewer to the BoS winner, despite them only entering 1 beer in the competition.

**Comment by geoffhumphrey** [comment]
In the next version, there will be a yes/no option in preferences that will allow admins to include or exclude BOS places in the Best Brewer or Best Club calcs.

**Comment by elronalds** [comment]
It would be great to have an option for highest scoring beer over all entries, we call this Champion Beer and that gets a separate prize.  

We also run a Champion Brewer like MarsMug with the three highest scoring beers to show they brew consistently high quality beers i.e. three beers that are typically over 40 points each.  It's a pain to calculate this manually but the software could easily do this and show it on the front page.

**Comment by Beer-Ranger** [comment]
Our competition also excludes the BOS winners from the 'Great Pumpkin' award.  We also have a couple of special additional categories and those are also excluded from the Great Pumpkin so I hope that we will be able to exclude specific categories in addition to the BOS winners from the Best Brewer calculation.
