### ISSUE TITLE
Bug with required info on custom category (2.1.12)

### ISSUE THREAD

**Issue by jimpdx** [geoffhumphrey/brewcompetitiononlineentry#931]
We run a small competition with Widmer Bros called "Collaborator" that does not follow any style guidelines. Members of our club submit beers to be scaled up on their commercial system and the only requirement is that the beer is unique and you want to drink more than one.

So we have created a custom style called "Collaborator Entry" which requires the "Required Info" field so the entrant can specify some level of detail about the entry. Unfortunately after you first save the entry and go back to Edit/Verify it, you are immediately given an error message that it is missing information but the Required Info box no longer appears on the page. You can toggle the Style back to "Select" (None) and save then repeat, but then the data disappears on you. Any thoughts/advice?

![image](https://user-images.githubusercontent.com/867051/40335388-25b46da4-5d18-11e8-9d00-5204c4328e23.png)

**Comment by jimpdx** [comment]
@geoffhumphrey also seeing this error when I try to edit an entry (could be related?)

Uncaught ReferenceError: CheckRequiredFields is not defined
    at HTMLFormElement.onsubmit (index.php?section=brew&action=edit&id=25&view=35-A&msg=1-35-A:1747)

**Comment by geoffhumphrey** [comment]
This has to do with the Bootstrap Form Validator (http://1000hz.github.io/bootstrap-validator) - it appears it's not being successfully loaded. If you're using the out-of-the-box configuration, this library is loaded from CDN. If you're still experiencing issues, I would follow [the procedure detailed here](http://brewcompetition.com/local-load) to load all libraries locally.

**Comment by jimpdx** [comment]
Thanks Geoff
