### ISSUE TITLE
Enhancement - Participant Email Addresses

### ISSUE THREAD

**Issue by elronalds** [geoffhumphrey/brewcompetitiononlineentry#935]
It would be nice to add a feature like on the judges and stewards page where I can gather all the participant email addresses and also a list of the participant with entries email addresses.

I can then email customers when scoresheets are ready, as well as letting them know that the competition is running again and they should re-enter the competition.

**Comment by geoffhumphrey** [comment]
I'm sure you've already found this, but the functionality you're asking for does exist. There's a CSV download in Admin > Data Exports > Entries (CSV) > All Entries: Limited Data with Brewer Contact Info (among others):

![2018-06-07_9-21-11](https://user-images.githubusercontent.com/5216502/41109548-7f411358-6a34-11e8-9b74-ecfa11227153.jpg)

**Comment by geoffhumphrey** [comment]
This will be incorporated into the next version (2.1.14). In latest master commit.
