### ISSUE TITLE
Display more BOS winners than just 1st place

### ISSUE THREAD

**Issue by Beakerboy** [geoffhumphrey/brewcompetitiononlineentry#937]
Is it possible to display the 2nd, 3rd, and HM BOS winners?

**Comment by geoffhumphrey** [comment]
Not sure if you found the answer yet, but you can. Go to Admin > Competition Preparation > Manage Style Types and edit the BOS Method for each.

**Comment by Beakerboy** [comment]
That's what I needed. Thanks!
