### ISSUE TITLE
Unable create judging tables

### ISSUE THREAD

**Issue by jodygrenert** [geoffhumphrey/brewcompetitiononlineentry#944]
Geoff,
We're trying to create judging tables and are receive the error message below. In trying to fix the problem, I have deleted the category, 35A. Devil's Paw, and deleted all 6 entries in that category. Still getting the error message and can't create tables.

Here's the error message:
Administration: Tables
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's Paw' AND brewReceived='1'' at line 1

**Comment by jodygrenert** [comment]
Update: I deleted "Devil's Paw" from the list of styles accepted and we can now create tables. It would be nice to be able to use apostrophes in the title of custom categories, but I guess that's a feature request rather than a bug fix.

**Comment by geoffhumphrey** [comment]
No problem -the next version will allow apostrophes as part of custom style's name.
