### ISSUE TITLE
2 enhancement requests regarding club points

### ISSUE THREAD

**Issue by jodygrenert** [geoffhumphrey/brewcompetitiononlineentry#949]
Geoff,
BCOE continues getting better and better with each release. I'd love to see this enhancement in the next version: 

An option in:
Admin Dashboard \ Reports \ After Judging \ Results

...that would print a complete list of all clubs and the points their earned in the competition for their members medals/awards. This list displays on the home page when results are posted, but it would be great to run a report immediately after the competition so winners could be read aloud during the award announcements.

**Comment by geoffhumphrey** [comment]
Thanks @jodygrenert!

In the current version, the "Best Club" and "Best Brewer" results are available prior to publishing on the homepage as part of the Admin Dashboard > Reports > After Judging > Results >BOS Results report.

However, there really isn't a compelling reason in my mind to keep them lumped together. A separate report can easily be created.
