### ISSUE TITLE
Style Entered NOT Accepted

### ISSUE THREAD

**Issue by Noghri1666** [geoffhumphrey/brewcompetitiononlineentry#950]
I have had 3 people report to me that they are seeing "Style Entered NOT Accepted" on their entries. These are pretty standard styles like IPA, International Amber and Czech Lager. I'm on the hosted platform.

**Comment by geoffhumphrey** [comment]
Could you provide which hosted site URL where this is happening? I pushed what I think may be a fix, but I'd like to verify.

**Comment by geoffhumphrey** [comment]
Nevermind. Upon further investigation, I found the bug. A fix is in the latest master commit and will be in the next release.

I will update hosted installations today.

**Comment by Noghri1666** [comment]
Thanks!
