### ISSUE TITLE
2.1.12 Update stuck in a loop

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#952]
I followed the instructions to update to 2.1.12. (Downloaded the new version, updated the paths.php and config.php files, uploaded all the files, etc.)

When I browse to my competition site I get a message asking me to login, so I do.

I then get the message: **This script will update your BCOE&M database from its current version, 2.1.12.0 (Build ), to the latest version, 2.1.12.0 (Build 2018-04-19).**

I click the **Begin The Update** button, which immediately presents me with 
**Update to 2.1.12 Complete!** 

However, under "Updated Are Detailed Below" is blank.

It then prompts me to log in again. I do, and the cycle begins all over again.

Not sure what I did wrong... I updated another competition site and it worked perfectly.

**Comment by geoffhumphrey** [comment]
What is the previous version you are updating from? 2.1.6 was the last one to require the update to be manually triggered via the update.php script.

**Comment by BrewDrinkRepeat** [comment]
I believe it was 2.1.1

**Comment by geoffhumphrey** [comment]
OK. Let me give that a test with the latest release (version 2.1.13 preview version).

**Comment by geoffhumphrey** [comment]
Due to numerous issues, 2.1.1 was backed out after only a week in production from May 12-18, 2016. there was no replacement. Did you download and install that version? You can tell the version of an install by looking at the system table in the DB (via phpMyAdmin, etc.) - that is if you made a backup.

**Comment by BrewDrinkRepeat** [comment]
LOL figures... I did back up both the database (via SQL dump) and the entire contents of the website prior to the attempted upgrade. (So, theoretically I could put the whole thing back the way it was.)

Here's what I found:
```
INSERT INTO `system` (`id`, `version`, `version_date`, `data_check`, `setup`) VALUES
(1, '2.1.4.0', '2016-05-24', '2016-07-10 03:57:02', 1);
```

So I guess I was using 2.1.4.0...

**Comment by BrewDrinkRepeat** [comment]
Hi Geoff, I ended up blowing out the whole thing and reinstalling from scratch, and it seems to be working OK.

I would like to restore the archives of previous comps, if there is an easy way to do that. (I was going to just upload the archive table and the other tables that are obviously from previous years, but I wasn't sure if that was OK to do, or all I would have to do).

Thanks!
