### ISSUE TITLE
2.1.12 - Confirmation/Password Emails Not Sending

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#955]
Using: 2.1.12

I've been using BCOEM for several years now, but I've never been able to get confirmation/contact/password emails working correctly.

I asked my webhost to help investigate and they found errors in the server log that BCOEM is trying to send emails with both php and smtp, and smtp fails because it sees two heading fields.

The server thinks the php emails are sent successfully, but they never show up in the test email's inbox or spam. Is it possible that php emails are also being sent with two subjects so gmail silently rejects them?

![image](https://user-images.githubusercontent.com/1551339/43942016-55161168-9c44-11e8-9202-83ad793faed9.png)

**Comment by geoffhumphrey** [comment]
Let me dig into this a bit more. As I recall, and from reviewing the code, there's no SMTP calls generated. Just a simple call to the [PHP mail()](http://php.net/manual/en/function.mail.php) function. 

To test if it's your web server, I suggest making a [simple test script](https://www.arclab.com/en/kb/php/how-to-test-and-fix-php-mail-function.html) and running it via your browser. If you're getting the same server log messages and the email isn't received, we can try something else.

**Comment by ercousin** [comment]
Thanks @geoffhumphrey !

What directory would I upload that test.php file into to access it at "brewslam2018.gtabrews.ca/test.php"?

![image](https://user-images.githubusercontent.com/1551339/44292555-4b0e1700-a253-11e8-9615-eeb18ea38047.png)

**Comment by ercousin** [comment]
I got the php test to work, and I did receive the email. I guess that means that this isn't a host issue, and is a BOCEM issue? It could either be setup or a bug?

For now I'll guess it's a setup issue?

Received test email:
![image](https://user-images.githubusercontent.com/1551339/44294726-28d3c380-a26a-11e8-93ce-dc8f21065dc8.png)

Software setup:
![image](https://user-images.githubusercontent.com/1551339/44294752-87993d00-a26a-11e8-9523-35db536d429b.png)

Is there any other files I can check? Any of the special setup related php files?

**Comment by geoffhumphrey** [comment]
Still digging into this. Not entirely sure what is happening, but in an effort to alleviate the issues, I'm looking at utilizing the [PHPMailer class](https://github.com/PHPMailer/PHPMailer) that's been kicking around for quite a few years. Stay tuned.

**Comment by ercousin** [comment]
Hi @geoffhumphrey ,

Circling back to this bug, I've found some new information that may help. It seems the issue is actually on Gmail's end, specifically with the lack of authentication in the emails generated via php().

I recently switched from using cpanel forwarding to using POP3 account fetching, and found that a bunch of the test emails generated through BCOEM were blocked by gmail. It appears that they had bounced due to lack of authentication.

For example:
- If I register a new account using my personal gmail address, I never get the confirmation email. 
- If I register a new account using an email account on my gtabrews.ca domain, I do get the confirmation email.

I've gone back and forth with my host trying to figure out if we can add authentication to these php() generated emails, and they suggested that BCOEM use SMTP to send emails.

Would it be possible to add an SMTP option?

Thanks,
Eric

**Comment by julien-gibson** [comment]
Hi Geoff,

I thought I would chime in and say that I can confirm the behaviour that Eric has detailed above, on my system.  I have also run the simple test script that you linked above, and noted that, where the email test function in BCOEM will fail for a certain address, the same email address works with the test script.

Regards
Julien

**Comment by julien-gibson** [comment]
I have further information to add on this. Note that we are now using 2.1.17

After a lot of testing today, I have managed to isolate the inclusion of the "To" field in the email header as the factor that was breaking email functionality.  This is reliably repeatable in our environment at least.  Keen to know if it fixes things for others as well.

Regards
Julien

**Comment by ercousin** [comment]
Hi Julien,

Do you have an example of what you changed to get it working? Or an example
of the email headers that worked vs didn't work?

Cheers,
Eric

**Comment by julien-gibson** [comment]
Hi Eric,
Sure.  In forgot_password.inc.php in the includes folder I commented out lines 57 and 128:

`$headers .= "To: ".$to_recipient. " <".$to_email.">, " . "\r\n";`

I also changed the charset in the line above to UTF-8.  Not sure if this made any difference though.

Cheers
Julien

**Comment by ercousin** [comment]
@julien-gibson Commenting out these lines didn't help for me. Password reset email still didn't make it into gmail.

@geoffhumphrey are things any closer to a new mailer? I saw a merge request that implemented PHPMailer, but no action taken to merge it.

https://github.com/geoffhumphrey/brewcompetitiononlineentry/pull/1065

**Comment by geoffhumphrey** [comment]
@ercousin - the latest commit contains @anthonyvscode's PHPMailer integration code. I encourage you to test it out when you're able. I've tested with success.

To implement, you'll need to:

- Download the latest commit
- Change the ENABLE_MAILER definition to TRUE in the /paths.php file (~line 130)
- Define the appropriate variables in the /site/config.mail.php file for your mail server
- Upload to your server

**Comment by ercousin** [comment]
Tried this and it works! So glad to see password reset emails working with gmail now :)

**Comment by geoffhumphrey** [comment]
@ercousin - in the final stages of testing 2.1.18. Planning on a late September release. Optimistically, the 20th; realistically, the 30th.
