### ISSUE TITLE
Drop Off Locations Won't Delete

### ISSUE THREAD

**Issue by shappy118** [geoffhumphrey/brewcompetitiononlineentry#959]
Version: BCOE&M 2.1.13 

Installation URL: https://nerhbc.brewcomp.com/index.php?section=admin&go=dropoff&msg=5#

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: When I go to remove an existing drop off location, the software notes the info was deleted successfully, but it still shows up in the list. 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
This is a bug that was unintentionally with the 2.1.13 Alpha release. The latest commit and full release corrects the issue. 

Hosted installations will be updated by EOB tomorrow with the latest "full" 2.1.13 release.

Related to Issue #951.

**Comment by shappy118** [comment]
Thanks Geoff!
