### ISSUE TITLE
2.1.13 - Winners report incomplete

### ISSUE THREAD

**Issue by markalston** [geoffhumphrey/brewcompetitiononlineentry#962]
The Report Winners with (or without) scores is incomplete.  

We use that report for our awards ceremony prior to publishing the results online.  The report no longer shows BOS results nor does it show best brewer/club results.

I know you can print the BOS results separately but there isn't anywhere to print the best brewer/club results without publishing them first. 

Fortunately in our case it was obvious who won each.

I changed the results.output.php to now include those sections.  I  would love to add a header with the number of entries and participants (just like the final posting page) but couldn't get that to work by including judge_closed.sec.php.  The numbers would show but something else needs to be included I guess to get the proper text around them.

Here is my results.output.php to get a complete winners report. 
```
<?php

require(DB.'winners.db.php');
require(DB.'output_results.db.php');
require(DB.'score_count.db.php');
if ((isset($_SESSION['loginUsername'])) && ($_SESSION['userLevel'] <= 1)) {
    if (NHC) $base_url = "../";

    if (($go == "judging_scores") && ($action == "print"))  {
// the judge_closed.sec.php needs something else added because I am not getting the text.
        include (SECTIONS.'judge_closed.sec.php');
        include (SECTIONS.'bos.sec.php');
        include (SECTIONS.'bestbrewer.sec.php');

        if ($row_prefs['prefsWinnerMethod'] == "1") include (SECTIONS.'winners_category.sec.php');
        elseif ($row_prefs['prefsWinnerMethod'] == "2") include (SECTIONS.'winners_subcategory.sec.php');
        else include (SECTIONS.'winners.sec.php');

    }
    if (($go == "judging_scores_bos") && ($action == "print")) include (SECTIONS.'bos.sec.php');
}
?>


```

**Comment by geoffhumphrey** [comment]
In the next version (and in the current commit), there will be an option to via the Admin Dashboard > Reports menu to print all results in a single report that contains, in the following order:
1. BOS for all style types
2. Best Brewer and/or Best Club (if applicable)
3. Results (with or without scores; all or winners only)

![2018-08-28_11-27-43](https://user-images.githubusercontent.com/5216502/44739737-e1450700-aab5-11e8-9c17-489fa7ef4bef.jpg)

The report does not have the number of entries or participants. Yet. Keep an eye out for that.

**Comment by markalston** [comment]
Awesome.  BTW, the best brewer/club additions to bcoe are greatly appreciated.  Our entrants were very excited to compete for best brewer.
