### ISSUE TITLE
Enhancement: Add organization / company field

### ISSUE THREAD

**Issue by carloswlkr** [geoffhumphrey/brewcompetitiononlineentry#966]
Would it be possible to add a field to the participants registration to input company or organization name? Also, job title?

**Comment by geoffhumphrey** [comment]
These two fields are available if you enable the Professional Edition.

**Comment by geoffhumphrey** [comment]
@carloswlkr -- apologies, I should have clarified a bit...

In Admin > Preferences > Site Preferences, there is a Competition Type choice. 

![2018-09-05_12-43-12](https://user-images.githubusercontent.com/5216502/45114469-4f1ead80-b10a-11e8-9d6a-dab960579732.jpg)

If you choose Professional, Company Name, TTB, Contact First Name, and Contact Last Name are added when ENTRANTS create an account (registering Judges and Stewards will not have the company name or TTB fields).

Here's what an entrant sees when attempting to create an account:

![2018-09-05_12-45-37](https://user-images.githubusercontent.com/5216502/45114530-737a8a00-b10a-11e8-916f-4e6dbcf8cbef.jpg)

Hope that helps...

**Comment by carloswlkr** [comment]
Ah, OK. great to know. Yes, that's important and key to have. My suggestion was specifically for the judges and stewards, since many of ours work for important breweries and we'd like to register that info.

Great software, by the way!

------ Original Message ------

**Comment by geoffhumphrey** [comment]
Currently, if you'd like to capture extra information (such as the title, brewery, etc.) for judges, you can instruct potential judges to enter it in the Notes to Organizer field that's available to them upon registering and via their account.

![2018-09-05_13-09-43](https://user-images.githubusercontent.com/5216502/45115501-3cf23e80-b10d-11e8-95a0-dd1c2f5f262c.jpg)

**Comment by carloswlkr** [comment]
Will do. Thanks!

------ Original Message ------
