### ISSUE TITLE
2.1.12 - Winner results only showing Cat 10-20

### ISSUE THREAD

**Issue by WASABCOrganiser** [geoffhumphrey/brewcompetitiononlineentry#974]
Version:
2.1.12 

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com?

Description of Issue:
After competition had completed, we went to print the winners (prior to posting publically) and under results it will only show Categories 10-20. The full results and entries can be pulled using the Winners under data exports, so we know that the data is correct and there for the remaining cat 1 to 9. 

- All with Scores (Shows cat 10-20)
- Print all entry results with scores listed (Shows cat 10-20)
- Winners Only with Scores (Shows cat 10-20)
- All without Scores (Shows cat 10-20)
- Winners Only without Scores (Shows cat 10-20)
- PDF (nothing displays)
- HTML (Shows cat 10-20)
 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
I believe this issue was fixed in the latest release (2.1.13). My advice would be to upgrade and see if the issue persists.
