### ISSUE TITLE
2.1.12 - Seperating scoresheets from results

### ISSUE THREAD

**Issue by WASABCOrganiser** [geoffhumphrey/brewcompetitiononlineentry#975]
Version:
21.12

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com?

Description of Issue:

Is there a way to make the scoresheets available to the participants without posting winners on the front page?

We would like to post the winners on a separate site for advertising a sponsor purposes. Also, our categories are not displaying correctly (issue #974) This situation is similar to issue #694 posted back in 2016.

Thanks

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Yes, this is possible - available since 2.1.12, I believe. The issue of display was fixed in 2.1.13.

**Comment by ercousin** [comment]
hey @geoffhumphrey 

Aside from the manual file editing I described in [this comment](https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/694#issuecomment-557852344), was there another way implemented to show scoresheets only using the admin GUI?
