### ISSUE TITLE
2.1.13 - Unable to delete sponsor

### ISSUE THREAD

**Issue by Rlshep** [geoffhumphrey/brewcompetitiononlineentry#976]
Version: 2.1.13

Installation URL: http://beerforboobs.sodz.org

Is your installation hosted on brewcompetition.com or brewcomp.com?
No

Description of Issue:
Unable to delete sponsor. Click trash can, confirm, says "Info deleted successfully." but sponsor still there.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Thanks for reporting @Rlshep. Related to Issue #972 - see it for a resolution.

**Comment by geoffhumphrey** [comment]
Should have mentioned that the workaround is to "hide" the sponsor by toggling the appropriate _Display_ checkbox.
