### ISSUE TITLE
Editing Required Info Section

### ISSUE THREAD

**Issue by oconnorshomebrew** [geoffhumphrey/brewcompetitiononlineentry#978]
Version:
2.1.13 Hosted Amateur Competition Edition

Installation URL:
https://oconnors.brewcompetition.com/
Is your installation hosted on brewcompetition.com or brewcomp.com?
brewcompetition.com

Description of Issue:

We have an entrant who filled out required info for a beer that he was going to enter. He told me that he didn't have any bottles left to enter so he changed the entry to a different style. The problem is that the required info from the original entry (which does not apply to the new beer is still showing up for the entry. Is there a way to delete it on my end?

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
The most expedient way would be to edit the entry, choose a style that requires special ingredients (to reveal the special ingredients text area), delete the contents of the text area, and update the entry. Then, go back and edit the entry, choosing the correct style.

There should be some logic on the backend that does this; however, it doesn't appear to be working. I'll look into it.
