### ISSUE TITLE
2.1.13 - Additional Info Boxes not showing on custom styles

### ISSUE THREAD

**Issue by Beer-Ranger** [geoffhumphrey/brewcompetitiononlineentry#980]
Version: 2.1.13 

Installation URL: http://hoppyhalloween.com/comp/

Is your installation hosted on brewcompetition.com or brewcomp.com?
No

Description of Issue:
Our competition just opened registration and has 2 custom styles and when entering a beer and selecting those styles, the Spade logo indicating that additional info is needed is showing after the style name but the boxes to enter the additional information do not appear like they do on other styles requiring additional info.
Also the beers entered in those styles have the warning triangle ! indicating that they are Unconfirmed Entries so the edit to make sure they have the additional info is still there and checking for it but not finding anything. 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Thanks for reporting @Beer-Ranger.

This one is a bit of a conundrum. I confirmed the issue on your installation, but I cannot recreate it on my test installations. For some reason the proper jQuery code isn't being generated in your installation to "unhide" the required info field for your two custom styles.

Try this: delete the custom styles and re-create them. If the required info field appears when you attempt to add or edit an entry, you're good to go. Otherwise, we'll have to entertain other solutions that may required some custom coding.

**Comment by Beer-Ranger** [comment]
These were custom styles that we had last year and were carried over if that would effect anything.  The description info included the html code with the text if that would indicate anything.

Since we have entries for those styles, I first tried creating a new custom category requiring additional info and when I assigned that style to a beer the boxes again did not show up.
On the beers entered in one of the custom styles, I changed the style to Experimental and then deleted that custom style and then re-created it, and when re-assigning the custom style, still no boxes.

I think there is a work around similar to a prior issue listed, when the style is changed to Experimental, the box shows up and the extra information can be added and then the entry saved.  If that entry is then moved back to the custom style, that extra info is still with it and shows up when you mouse over the talking balloon on the entry.
If they want to add or change the extra info again and change it back to Experimental, all of what was originally entered is lost though and they would have to enter it all again.

It would be nice to avoid that work around so hopefully it can be fixed another way.

**Comment by geoffhumphrey** [comment]
Here's something to try to make sure that the boxes do show up - assuming you have FTP access to your installation's we server. 

Essentially, we're hard-coding two additions to an array that houses the numbers (ids) of the styles that require the special ingredients and their accompanying entry instructions.

1. Open the /includes/form_js.inc.php file in your favorite text editor.
2. Add the following lines to the top of the file (below the `<?php` line).

```
$special_beer_info['35-A'] = "Entry instructions here for Halloween Theme Beer/Mead/Cider.";
$special_beer_info['36-A'] = "Entry instructions here for Fresh Killed Hops Beer.";
```
3. Change the entry instructions between the quotes as appropriate. 
4. Save and re-upload to your installation.

This will get you up and running. I'll continue to try and track down causes.

**Comment by Beer-Ranger** [comment]
I added those lines and the input box is now showing up for those styles.  

Thank you for your prompt attention and quick fix.
