### ISSUE TITLE
2.1.13: entering a beer with custom style fails

### ISSUE THREAD

**Issue by djmitche** [geoffhumphrey/brewcompetitiononlineentry#981]
*Version*: 2.1.13

*Installation URL*: http://thoroughbrews.org/kbotb1/404.php

*Is your installation hosted on brewcompetition.com or brewcomp.com?* no

*Description of Issue:*

We have set up style 35A to "Require Info" and include text in both "Entry Info" and "Description":
![screenshot_2018-10-03 knickerbocker battle of the brews](https://user-images.githubusercontent.com/28673/46425394-8e401e80-c709-11e8-8e08-01a6bf45cbaa.png)

In the list of styles for an entrant, the "spade" symbol appears appropriately, but when they go to enter their specifics, there is no entry-info box, unlike for other styles with a spade icon.  The box that does appear specifically says "DO NOT" enter exactly the information we have asked them to enter.

Additionally, having told the entrant to ignore the "DO NOT" and enter the information anyway, they are unable to submit:

> OK, I added the style, strength, color, and where I sourced my malt and hops in that field. The page still says not to do so, but for now I'll leave it. Also worth noting that every time I submit I get an error message telling me more information is needed, and that the field is highlighted in red. It appears to be something with the title, but that field is filled out. Not sure what the issue is. You can view my entry here: http://thoroughbrews.org/kbotb1/index.php?section=brew&action=edit&id=106&view=35-A&msg=1-35-A. I've also attached a screenshot so you can see both the error message at the top, and the instructions not to add style and strength to the field below.

![screen shot 2018-10-02 at 4 06 02 pm](https://user-images.githubusercontent.com/28673/46425313-4ae5b000-c709-11e8-9852-bd697e1c7afe.png)

I assume the inability to submit is because the necessary entry-info field is not appearing.

**Comment by geoffhumphrey** [comment]
See Issue #980 for a fix. Still tracking down the cause of the issue.

**Comment by geoffhumphrey** [comment]
After further investigation, this seems to have to do with missing data on custom styles carried over from previous competition iterations. 

The query that drives the display of the Required Info box specifies the style set from site preferences (BJCP2008, BJCP2015 or BA). Custom styles carried over were not added as part of a particular style set, and thus, aren't being pulled into the data set that drives the display of the Required Info text box for certain styles. 

The above scripts will work as a temporary fix. Or, run this SQL query in your database to fix globally, substituting [style set] with your defined style set (BJCP2008, BJCP2015, BA - *without spaces*). Make sure to add your DB table prefix, if any:
```
UPDATE styles SET brewStyleVersion='[style set]' WHERE brewStyleOwn='custom';
```

The next version's scripting will check and correct for this.
