### ISSUE TITLE
Upgrade 2.1.12 to 2.1.14 version_date error

### ISSUE THREAD

**Issue by vortexofhate** [geoffhumphrey/brewcompetitiononlineentry#984]
Version: 2.1.12

Is your installation hosted on brewcompetition.com or brewcomp.com?
No

Description of Issue:
I currently have 2.1.12 self hosted and when I go to update it to 2.1.14, when I go to the base URL I get the message: "Incorrect date value: '2018-09-95' for column 'version_date' at row 1"

**Comment by geoffhumphrey** [comment]
Whoops. Looks like a simple typo. Crud!

To fix, you'll need to change the `$current_version_date_display` variable in the /includes/current_version.inc.php file to:

```
$current_version_date_display = "2018-10-05";
```

Next, you'll probably need to update the `version_date` row in the `system` table in your DB to `2018-10-05`.

I'll fix this in the release.
