### ISSUE TITLE
Enhancement - Addition of Irish Homebrew Clubs

### ISSUE THREAD

**Issue by mick02** [geoffhumphrey/brewcompetitiononlineentry#985]
Hey,

Thanks a million for the development of this software we use it regularly.

To this end I was hoping that you could add the Irish Homebrew Clubs to the list so that in future versions they will be included.

I've pasted the list below for your convenience.

Mick

// -------------------------- Clubs List ------------------------------------------------------
// Updated January 14, 2018
$club_array = array("Belfast Homebrew Club|Belfast Homebrew Club","Capital Brewers|Capital Brewers","Erne Homebrew Club|Erne Homebrew Club","Galway Homebrew Club|Galway Homebrew Club","Garden County Homebrew Club|Garden County Homebrew Club","Kerry Brewers|Kerry Brewers","Kilkenny Homebrew Club|Kilkenny Homebrew Club","Lee Valley Homebrew Club|Lee Valley Homebrew Club","Liffey Brewers|Liffey Brewers","Limerick Brewers|Limerick Brewers","Maiden City Brewers|Maiden City Brewers","Midland Brewers|Midland Brewers","North County Brewers|North County Brewers","Rebel Brewers|Rebel Brewers","Royal County Brewers|Royal County Brewers","Sligo Brewers|Sligo Brewers","South Central Brewers|South Central Brewers","South Dublin Brewers|South Dublin Brewers","South Eastern Brewers|South Eastern Brewers","South Kildare Homebrew Club|South Kildare Homebrew Club","Wee County Brewers|Wee County Brewers",);

asort($club_array);

**Comment by geoffhumphrey** [comment]
Hey @mick02...

No problem! Thanks for sending them along. They'll be on list in the next version.
