### ISSUE TITLE
2.1.14 - Judge Session Availability Not Saving

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#987]
Version: 2.1.13

Installation URL: brewslam.gtabrews.ca

Is your installation hosted on brewcompetition.com or brewcomp.com? Self Hosted

Description of Issue:
I'm seeing a strange issue where judge availability isn't saving. I don't think this is user error because even the fields are blank:

![image](https://user-images.githubusercontent.com/1551339/46883014-96414200-ce1e-11e8-867e-529e906b8ebf.png)

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by grmelacz** [comment]
I have the same problem in our installation. I had like 5 judges showing up on the competition without a prior notice - their availability is empty like @ercousin has shown above. Currently version 2.1.14. PHP 7.1.5, MySQL 5.6.12.

The availability is set to No in their profile.

**Comment by geoffhumphrey** [comment]
I'll take a look and troubleshoot. However, I can't seem to recreate the issue in my test installations. Stay tuned.
