### ISSUE TITLE
2.1.14 - Custom Style Extra Info Again

### ISSUE THREAD

**Issue by Beer-Ranger** [geoffhumphrey/brewcompetitiononlineentry#988]
Version: 2.1.14

Installation URL: http://hoppyhalloween.com/comp/

Is your installation hosted on brewcompetition.com or brewcomp.com?
No, self hosted

Description of Issue:
Back in issue #980, I could not add the extra info on the custom styles pulled over from last year's competition.  The fix in that issue worked and extra info could not be added.
I upgraded to 2.1.14 and thought it sounded like this issue was fixed, but the extra info box was not showing up for the custom styles again.  So I made the same coding fix and before and the box is showing up.

But now when you try and save the entry with that info, it is not saved and the error shows on top that you need to add that info and the extra info box is highlighted in red.

Also when I tried to change the beer's style to see if it would save the extra info that way on someone elses entry, it changed that entry so my name is now showing up as the brewer, not who entered it.

My current option is to go back to 2.1.13 when the fix was working in a couple days if no quick solution is found.

**Comment by geoffhumphrey** [comment]
I've been on vacation the past couple of weeks and will begin investigating this issue today. The same fix you used for 2.1.13 should work for 2.1.14 until I can track things down.

**Comment by Beer-Ranger** [comment]
We all need vacations.  I tried the same fix, it gave me the box but it would not save anything entered in the box.  After a few days, it purged entries that were were not valid because they didn't have anything in the extra info.  So I rolled back and re-installed 2.1.13 and got it working again and will finish the competition this weekend with that version.

**Comment by jimmyorkin** [comment]
This is 2.1.14. The workaround in #980 does get the Info Box to appear but when you when you enter information in the Required Info area and save. You get this error: "More information is required for your entry to be accepted and confirmed. See the area(s) highlighted in RED below." The Required Info box is red.

The entry is now an unconfirmed entry in the database. All attempts to enter in the Required Info box fail to save.

**Comment by geoffhumphrey** [comment]
Ah, geez. OK. It looks like I'm going to have to do some deep dive troubleshooting with this one, especially since the information now isn't saving in the DB. Apologies for the issues. I'll post back when I find something.

**Comment by geoffhumphrey** [comment]
Found the issue that was causing all of this and reworked the code. Fix will be implemented in the next release.

**Comment by FDillon00** [comment]
I am noticing this issue with "standard" categories. 
- 29A: Fruit Beer
- 29B: Fruit and Spice Beer
- 30A: Spice, Herb, or Vegetable Beer

But NO issues with 
- 21B: Specialty IPA

https://lawrencebrewers.org/competition
version 2.1.11 
- Not sure I want to try an upgrade as our comp just started taking entries today.  

![screenshot](https://user-images.githubusercontent.com/5970995/54482005-8c2ad180-480a-11e9-97d4-fa7fb94280f5.png)

**Comment by ercousin** [comment]
Looks like your "Required Info" box is missing, did you do something to hide it? I always hide "Brewers Specifics" in my comps to avoid confusion.

![image](https://user-images.githubusercontent.com/1551339/54483477-da030200-4829-11e9-8a84-aef244c194a7.png)

**Comment by FDillon00** [comment]
Don't think so. 
![image](https://user-images.githubusercontent.com/5970995/54483529-8f31bc00-4822-11e9-8d12-eef8c8a3bc4a.png)

**Comment by FDillon00** [comment]
This install worked just fine for last year's comp and the form works correctly for "Specialty IPA" that has the same requirements.
