### ISSUE TITLE
Enhancement - Mini-BoS Pullsheets to not show original flight information

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#990]
Version: 2.1.14

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: We use the Mini-BoS pullsheets for a second judging of the entries that advance from the first judging. I would be better if the Mini-BoS pullsheets did not show information about the first judging flights. Just have all the Mini-BoS entries show as one set of entries and all sorted by style for the Table.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Seems reasonable. In the next version there will be two options for generating MBOS pullsheets via the Admin Dashboard - by table and a "combined" version sorted by style as described by @jimmyorkin above.

**Comment by jimmyorkin** [comment]
@geoffhumphrey Don't get me wrong. We want the MBOS pullsheets by table. The way it is now, the entries are grouped by the flight they came from. We are looking for all the entries in the MBOS to be blended so you cannot deduce which flight an entry came from. Sorting that blend of entries by style, just like the first round pullsheets do. Thanks.

**Comment by geoffhumphrey** [comment]
Oh, no worries @jimmyorkin. I hear ya! 

Take a look at these PDFs. The first is the by table display, current state. The second is the combined one I came up with. However, it sounds like you'd like a combination of the two...

[MBOS_by_Table.pdf](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/2626962/MBOS_by_Table.pdf)
[MBOS_combined.pdf](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/2626963/MBOS_combined.pdf)


Would it suffice to add a column on the "combined" one that displays the table number and name? Then, it could be sorted first by Table, then by style.

**Comment by geoffhumphrey** [comment]
Nevermind. After looking at the code, I believe know exactly what you're requesting. Keep the tables, lose the separation of flights when using non-queued judging. Stay tuned.

**Comment by jimmyorkin** [comment]
Just to make sure we are in sync. Attached is what we have used. I hacked the pullsheet php file to not put each 1st round  flight grouping on a separate page but you can still see by the groupings that there were three first round flights combining into MBOS.

[MBOS-TABLE-1.pdf](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/2627132/MBOS-TABLE-1.pdf)

I like your MBOS_by_table pdf.

Jimmy

**Comment by jimmyorkin** [comment]
I like the Example_MBOS_Pullsheets_By_Table.pdf. It is what I was looking for.

The Example_MBOS_Pullsheet_Single_List.pdf does not have value to Bluebonnet but might for some other competition.

Thanks. Jimmy
