### ISSUE TITLE
Unarchiving and reCaptcha V1 issue

### ISSUE THREAD

**Issue by SMortiL987** [geoffhumphrey/brewcompetitiononlineentry#994]
Version:2.1.1

Installation URL:  www.bayoubeerfest.com/brewdat

Is your installation hosted on brewcompetition.com or brewcomp.com?  No

Description of Issue: Competition was accidently archived is there a way to "unarchive"?  Also, now having an issue with reCatpcha V1 at bottom of sign up page saying it's being shut down.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hey Sal - unfortunately, there is no "unarchiving" via BCOE&M. Once it's done, it's done.  Your web host may have a way for you to restore your DB tables from a backup, which will effectively undo the archive.

For reCAPTCHA, I'd recommend updating your installation to the latest version - 2.1.14. You will need to get a reCAPTCHA key from Google (https://www.google.com/recaptcha/admin).
