### ISSUE TITLE
cannot mark an entry as received

### ISSUE THREAD

**Issue by PeterSteinberg** [geoffhumphrey/brewcompetitiononlineentry#995]
Version:

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com?  yes

Description of Issue:
Got a bottle after the competition started.  Tried to mark it as received, get an error
  You do not have sufficient access privileges to perform this action.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Unfortunately, I'm not able to replicate on your installation or on any of my test installations. Were you able to mark it?

**Comment by PeterSteinberg** [comment]
Sorry for the false report.

It’s somehow failing on the instance of Firefox that I was using on a laptop, but it worked fine on different PC’s and in different browsers.

Yet another strange PC configuration issue that I need to look into.

Peter
