### ISSUE TITLE
Help: Having problems accessing competition website

### ISSUE THREAD

**Issue by Steveg297** [geoffhumphrey/brewcompetitiononlineentry#996]
Version:

Installation URL: ssbc.brewcompetition.com

Is your installation hosted on brewcompetition.com or brewcomp.com?

Description of Issue:  I am unable to log into and manage the competition website.  I must have done an archive and the system removed my email address and password from the system.  Can you help to restore my information?

Thanks,

Steve297@yahoo.com

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi Steve, I've restored your database from a backup.  I would suggest following the Purge Current Data instructions available at https://brewcompetition.com/reset-comp -  when you purge participant account data, all Admin-level accounts are retained. If that's not the case, please let me know. I'm unsure how all participant data was purged including yours, but will look into it.

**Comment by Steveg297** [comment]
Thanks Geoff!

SteveG 
 
  On Mon, Nov 5, 2018 at 9:53 AM, Geoff Humphrey<notifications@github.com> wrote:   
Hi Steve, I've restored your database from a backup. I would suggest following the Purge Current Data instructions available at https://brewcompetition.com/reset-comp - when you purge participant account data, all Admin-level accounts are retained. If that's not the case, please let me know. I'm unsure how all participant data was purged including yours, but will look into it.
