### ISSUE TITLE
2.1.14 - Identical Judging Number Generated for Provisional Category

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#998]
Version: 2.1.14
Installation URL: http://brewslam.gtabrews.ca
Is your installation hosted on brewcompetition.com or brewcomp.com? Self Hosted
Description of Issue:

We had three Catharina Sours entered in our competition, and the assigned judging number was "000001" for two of them, and "0PR001" for the 3rd. Luckily we were able to tell them apart by ReqInfo, but no two entries should be assigned the same judging#.

![image](https://user-images.githubusercontent.com/1551339/48391383-564ad480-e6d4-11e8-821f-1c98da91f216.png)

I would have expected:
0PR001
0PR002
0PR003

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Did this occur when using the "Regenerate Judging Numbers (With Style Number Prefix)" function? Or were these numbers automatically assigned by the system. My suspicion is the former because the automatically assigned judging numbers are not alphanumeric. I'll look into the regenerate functions just in case.

**Comment by ercousin** [comment]
Hi Geoff,

Yes, this occurred when manually regenerating the judging numbers. We use
the "3 digit category number + 3 digit order number" method in our comp.

Thanks,
Eric

**Comment by geoffhumphrey** [comment]
Alright - that's what I suspected. There's a function that converts the alphanumeric characters used in BJCP2015 styles to numbers for use in judging numbers (C1 to 38, M3 to 42, etc). This is somewhat of legacy code, developed when only numerals were allowed for judging numbers. 

So, for an easy fix, we can simply convert the "PR" to a number.

Open /lib/process.lib.php. On or around line 85 there's a switch statement that currently looks like this:
```
// Need to convert mead and cider categories for BJCP2015 to numerals (all contain alphas, which break the script)
switch ($style_cat_num) {
	case "C1": $style_cat_num = "38"; break;
	case "C2": $style_cat_num = "39"; break;
	case "M1": $style_cat_num = "40"; break;
	case "M2": $style_cat_num = "41"; break;
	case "M3": $style_cat_num = "42"; break;
	case "M4": $style_cat_num = "43"; break;
	default: $style_cat_num = $style_cat_num;
}
```
Replace that entire switch statement with this one:
```
// Need to convert mead and cider categories for BJCP2015 to numerals (all contain alphas, which break the script)
switch ($style_cat_num) {
	case "C1": $style_cat_num = "93"; break;
	case "C2": $style_cat_num = "94"; break;
	case "M1": $style_cat_num = "95"; break;
	case "M2": $style_cat_num = "96"; break;
	case "M3": $style_cat_num = "97"; break;
	case "M4": $style_cat_num = "98"; break;
	case "PR": $style_cat_num = "99"; break; // for newly added Provisional Styles
	default: $style_cat_num = $style_cat_num;
}
```
Upon looking at the code, however, it occurred to me that custom styles are not accounted for nearly enough - when using BJCP2015, those start a 36 and move sequentially up from there. Hence the conversion above to numbers in the 90s. Now, PR will be 99.

In a future version, I'll look into keeping the alphanumeric prefixes (M2, PR, C1, etc.). For now, this will help alleviate the issue you're having.

**Comment by ercousin** [comment]
Thanks for following up on this Geoff! We we're able to manually fix it for
this year's competition, but I'm glad to see you explored the issue.

The bigger issue for us was the duplicate judging number, but having one of
them include 0PR00# was also strange.

Thanks,
Eric

**Comment by geoffhumphrey** [comment]
No problem, Eric. In the next version, when regenerating judging numbers with the category prefix, the 2 character prefix will be added followed by a dash, then the actual number (e.g., XX-123). 

For example...

![2018-11-28_15-15-15](https://user-images.githubusercontent.com/5216502/49185988-80310780-f320-11e8-9993-528244dee7df.jpg)

Note: [Provisional styles](http://dev.bjcp.org/provisional-styles/) will have a PR prefix if they're not associated with an overall category (currently those are Catharina Sour and New Zealand Pilsner).
